# Generated by Django 5.0.14 on 2025-12-02 22:18

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                (
                    'tier_type',
                    models.CharField(
                        choices=[
                            ('free', 'Free / Explorer'),
                            ('community_pro', 'Community Pro'),
                            ('pro_learn', 'Pro Learn'),
                            ('creator_mentor', 'Creator / Mentor'),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    'price_quarterly',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Price in USD per quarter',
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                    ),
                ),
                (
                    'stripe_product_id',
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    'stripe_price_id_quarterly',
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    'trial_period_days',
                    models.IntegerField(default=0, help_text='Free trial period in days'),
                ),
                (
                    'monthly_ai_requests',
                    models.IntegerField(default=0, help_text='Monthly AI request limit (0 = unlimited)'),
                ),
                ('has_marketplace_access', models.BooleanField(default=False)),
                ('has_go1_courses', models.BooleanField(default=False)),
                ('has_ai_mentor', models.BooleanField(default=False)),
                ('has_quests', models.BooleanField(default=False)),
                ('has_circles', models.BooleanField(default=False)),
                ('has_projects', models.BooleanField(default=False)),
                ('has_creator_tools', models.BooleanField(default=False)),
                ('has_analytics', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'display_order',
                    models.IntegerField(default=0, help_text='Order to display on pricing page'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Tier',
                'verbose_name_plural': 'Subscription Tiers',
                'ordering': ['display_order', 'price_quarterly'],
                'indexes': [
                    models.Index(fields=['tier_type'], name='billing_sub_tier_ty_d3455d_idx'),
                    models.Index(
                        fields=['is_active', 'display_order'],
                        name='billing_sub_is_acti_8d38df_idx',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='TokenPackage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                (
                    'package_type',
                    models.CharField(
                        choices=[
                            ('starter', 'Starter'),
                            ('booster', 'Booster'),
                            ('power', 'Power'),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    'token_amount',
                    models.IntegerField(
                        help_text='Number of tokens in this package',
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Price in USD',
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
                    ),
                ),
                (
                    'stripe_product_id',
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    'stripe_price_id',
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ('is_active', models.BooleanField(default=True)),
                (
                    'display_order',
                    models.IntegerField(default=0, help_text='Order to display in token shop'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Package',
                'verbose_name_plural': 'Token Packages',
                'ordering': ['display_order', 'price'],
                'indexes': [
                    models.Index(
                        fields=['is_active', 'display_order'],
                        name='billing_tok_is_acti_409b60_idx',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='TokenPurchase',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('token_amount', models.IntegerField(help_text='Tokens purchased')),
                (
                    'price_paid',
                    models.DecimalField(decimal_places=2, help_text='Amount paid in USD', max_digits=10),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                            ('refunded', 'Refunded'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'stripe_payment_intent_id',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'stripe_charge_id',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'package',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='purchases',
                        to='billing.tokenpackage',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='token_purchases',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Token Purchase',
                'verbose_name_plural': 'Token Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'transaction_type',
                    models.CharField(
                        choices=[
                            ('purchase', 'Purchase'),
                            ('usage', 'Usage'),
                            ('refund', 'Refund'),
                            ('bonus', 'Bonus'),
                            ('adjustment', 'Adjustment'),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    'amount',
                    models.IntegerField(help_text='Positive for additions, negative for usage'),
                ),
                (
                    'balance_after',
                    models.IntegerField(help_text='Balance after this transaction'),
                ),
                ('description', models.CharField(blank=True, max_length=255)),
                (
                    'ai_provider',
                    models.CharField(blank=True, help_text='e.g., openai, anthropic', max_length=50),
                ),
                (
                    'ai_model',
                    models.CharField(blank=True, help_text='e.g., gpt-4, claude-3', max_length=100),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'related_purchase',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='transactions',
                        to='billing.tokenpurchase',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='token_transactions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Token Transaction',
                'verbose_name_plural': 'Token Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('trialing', 'Trialing'),
                            ('past_due', 'Past Due'),
                            ('canceled', 'Canceled'),
                            ('unpaid', 'Unpaid'),
                        ],
                        db_index=True,
                        default='active',
                        max_length=20,
                    ),
                ),
                (
                    'stripe_customer_id',
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    'stripe_subscription_id',
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('ai_requests_used_this_month', models.IntegerField(default=0)),
                ('ai_requests_reset_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'tier',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='subscriptions',
                        to='billing.subscriptiontier',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscription',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionChange',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'change_type',
                    models.CharField(
                        choices=[
                            ('created', 'Created'),
                            ('upgraded', 'Upgraded'),
                            ('downgraded', 'Downgraded'),
                            ('canceled', 'Canceled'),
                            ('renewed', 'Renewed'),
                            ('reactivated', 'Reactivated'),
                            ('trial_started', 'Trial Started'),
                            ('trial_converted', 'Trial Converted'),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ('reason', models.TextField(blank=True, help_text='Reason for change')),
                (
                    'metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional metadata (e.g., proration, MRR impact)',
                    ),
                ),
                (
                    'effective_date',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscription_changes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'from_tier',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='changes_from',
                        to='billing.subscriptiontier',
                    ),
                ),
                (
                    'to_tier',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='changes_to',
                        to='billing.subscriptiontier',
                    ),
                ),
                (
                    'subscription',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='change_history',
                        to='billing.usersubscription',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Subscription Change',
                'verbose_name_plural': 'Subscription Changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTokenBalance',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'balance',
                    models.IntegerField(
                        default=0,
                        help_text='Current token balance',
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'total_purchased',
                    models.IntegerField(default=0, help_text='Total tokens ever purchased'),
                ),
                (
                    'total_used',
                    models.IntegerField(default=0, help_text='Total tokens ever used'),
                ),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='token_balance',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'User Token Balance',
                'verbose_name_plural': 'User Token Balances',
            },
        ),
        migrations.AddIndex(
            model_name='tokenpurchase',
            index=models.Index(fields=['user', '-created_at'], name='billing_tok_user_id_621a85_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenpurchase',
            index=models.Index(fields=['status', '-created_at'], name='billing_tok_status_73209d_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenpurchase',
            index=models.Index(
                fields=['stripe_payment_intent_id'],
                name='billing_tok_stripe__ecf7cf_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['user', '-created_at'], name='billing_tok_user_id_1d6198_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(
                fields=['transaction_type', '-created_at'],
                name='billing_tok_transac_2a3754_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(
                fields=['status', 'current_period_end'],
                name='billing_use_status_6e270b_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['stripe_customer_id'], name='billing_use_stripe__059a21_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionchange',
            index=models.Index(fields=['user', '-created_at'], name='billing_sub_user_id_e02f52_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionchange',
            index=models.Index(
                fields=['change_type', '-created_at'],
                name='billing_sub_change__27aea7_idx',
            ),
        ),
    ]
