# Generated by Django 5.0.14 on 2025-12-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0009_populate_monthly_annual_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenpurchase',
            name='stripe_charge_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tokenpurchase',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'stripe_event_id',
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    'event_type',
                    models.CharField(
                        db_index=True,
                        help_text='e.g., payment_intent.succeeded',
                        max_length=100,
                    ),
                ),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                (
                    'processing_completed_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    'processing_error',
                    models.TextField(blank=True, help_text='Error message if processing failed'),
                ),
                (
                    'payload',
                    models.JSONField(default=dict, help_text='Full webhook event payload'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['stripe_event_id', 'processed'],
                        name='billing_web_stripe__f2aeda_idx',
                    ),
                    models.Index(
                        fields=['event_type', '-created_at'],
                        name='billing_web_event_t_2469a0_idx',
                    ),
                    models.Index(
                        fields=['processed', '-created_at'],
                        name='billing_web_process_0311f0_idx',
                    ),
                ],
            },
        ),
    ]
