# Generated by Django 5.1.15 on 2025-12-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0010_add_webhook_event_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(
                default=False, help_text='If True, subscription will cancel at current period end'
            ),
        ),
    ]
