# Generated by Django 5.1.15 on 2025-12-17 01:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0011_add_cancel_at_period_end'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokenbalance',
            name='credit_pack_balance',
            field=models.IntegerField(
                default=0,
                help_text='Credits from active credit pack subscription',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='transaction_type',
            field=models.CharField(
                choices=[
                    ('purchase', 'Purchase'),
                    ('usage', 'Usage'),
                    ('refund', 'Refund'),
                    ('bonus', 'Bonus'),
                    ('adjustment', 'Adjustment'),
                    ('credit_pack_grant', 'Credit Pack Monthly Grant'),
                    ('credit_pack_forfeit', 'Credit Pack Forfeited'),
                    ('credit_pack_usage', 'Credit Pack Usage'),
                    ('credit_pack_usage_tracked', 'Credit Pack Usage Tracked'),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g., "625 credits"', max_length=100)),
                (
                    'credits_per_month',
                    models.IntegerField(
                        help_text='Number of credits granted each billing period',
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    'price_cents',
                    models.IntegerField(
                        help_text='Price in cents (2000 = $20)',
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('stripe_product_id', models.CharField(blank=True, help_text='Stripe Product ID', max_length=255)),
                (
                    'stripe_price_id',
                    models.CharField(blank=True, help_text='Stripe Price ID for monthly recurring', max_length=255),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, help_text='Whether this pack is available for purchase'),
                ),
                (
                    'sort_order',
                    models.IntegerField(default=0, help_text='Order to display in selector (lower = first)'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Pack',
                'verbose_name_plural': 'Credit Packs',
                'ordering': ['sort_order', 'credits_per_month'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='billing_cre_is_acti_30f926_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCreditPackSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'stripe_subscription_id',
                    models.CharField(blank=True, help_text='Stripe Subscription ID', max_length=255),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('past_due', 'Past Due'),
                            ('canceled', 'Canceled'),
                            ('inactive', 'Inactive'),
                        ],
                        db_index=True,
                        default='inactive',
                        max_length=20,
                    ),
                ),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                (
                    'credits_this_period',
                    models.IntegerField(default=0, help_text='Credits granted this billing period'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'credit_pack',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='subscriptions',
                        to='billing.creditpack',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credit_pack_subscription',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'User Credit Pack Subscription',
                'verbose_name_plural': 'User Credit Pack Subscriptions',
                'indexes': [
                    models.Index(fields=['status'], name='billing_use_status_677d1a_idx'),
                    models.Index(fields=['stripe_subscription_id'], name='billing_use_stripe__b10989_idx'),
                ],
            },
        ),
    ]
