# Generated by Django 5.1.15 on 2025-12-18 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('tasks', '0005_taskattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UATCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('color', models.CharField(default='slate', help_text='Tailwind color name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UAT Category',
                'verbose_name_plural': 'UAT Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UATScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Scenario name/title', max_length=255)),
                (
                    'description',
                    models.TextField(blank=True, help_text='Expected failure behavior or test description'),
                ),
                ('date_tested', models.DateField(blank=True, help_text='Date when scenario was tested', null=True)),
                (
                    'result',
                    models.CharField(
                        blank=True,
                        choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')],
                        help_text='Test result: pass/fail/na, or null if not yet tested',
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    'tester_name',
                    models.CharField(blank=True, help_text='Name of person who tested this scenario', max_length=255),
                ),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations from testing')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'assignee',
                    models.ForeignKey(
                        blank=True,
                        help_text='Admin assigned to test this scenario',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='assigned_uat_scenarios',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        help_text='Category for grouping scenarios',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='scenarios',
                        to='uat_scenarios.uatcategory',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_uat_scenarios',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'linked_task',
                    models.ForeignKey(
                        blank=True,
                        help_text='Task created from this failed scenario',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='uat_scenarios',
                        to='tasks.task',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='updated_uat_scenarios',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'UAT Scenario',
                'verbose_name_plural': 'UAT Scenarios',
                'ordering': ['order', '-created_at'],
                'indexes': [
                    models.Index(fields=['order'], name='uat_scenari_order_01da2f_idx'),
                    models.Index(fields=['result'], name='uat_scenari_result_a76b7b_idx'),
                    models.Index(fields=['is_archived', '-created_at'], name='uat_scenari_is_arch_b4fae3_idx'),
                    models.Index(fields=['date_tested'], name='uat_scenari_date_te_ac9bfc_idx'),
                    models.Index(fields=['category', 'order'], name='uat_scenari_categor_be126d_idx'),
                    models.Index(fields=['assignee', 'result'], name='uat_scenari_assigne_cbb1ee_idx'),
                ],
            },
        ),
    ]
