# Generated by Django 5.1.15 on 2025-12-18 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('uat_scenarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uatscenario',
            name='tester_name',
        ),
    ]
