# Generated by Django 5.1.15 on 2025-12-18 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0005_taskattachment'),
        ('uat_scenarios', '0002_remove_tester_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UATTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tested', models.DateField(help_text='Date when the test was run')),
                (
                    'result',
                    models.CharField(
                        choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')],
                        help_text='Test result: pass/fail/na',
                        max_length=10,
                    ),
                ),
                ('notes', models.TextField(blank=True, help_text='Notes or observations from this test run')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UAT Test Run',
                'verbose_name_plural': 'UAT Test Runs',
                'ordering': ['-date_tested', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='uatscenario',
            name='uat_scenari_result_a76b7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='uatscenario',
            name='uat_scenari_date_te_ac9bfc_idx',
        ),
        migrations.RemoveIndex(
            model_name='uatscenario',
            name='uat_scenari_assigne_cbb1ee_idx',
        ),
        migrations.RemoveField(
            model_name='uatscenario',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='uatscenario',
            name='date_tested',
        ),
        migrations.RemoveField(
            model_name='uatscenario',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='uatscenario',
            name='result',
        ),
        migrations.AlterField(
            model_name='uatscenario',
            name='description',
            field=models.TextField(blank=True, help_text='Test steps and expected behavior'),
        ),
        migrations.AlterField(
            model_name='uatscenario',
            name='linked_task',
            field=models.ForeignKey(
                blank=True,
                help_text='Task created from a failed test run',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='uat_scenarios',
                to='tasks.task',
            ),
        ),
        migrations.AddField(
            model_name='uattestrun',
            name='scenario',
            field=models.ForeignKey(
                help_text='The scenario that was tested',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='test_runs',
                to='uat_scenarios.uatscenario',
            ),
        ),
        migrations.AddField(
            model_name='uattestrun',
            name='tested_by',
            field=models.ForeignKey(
                help_text='Admin who ran this test',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='uat_test_runs',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='uattestrun',
            index=models.Index(fields=['scenario', '-date_tested'], name='uat_scenari_scenari_ba3fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='uattestrun',
            index=models.Index(fields=['result'], name='uat_scenari_result_42bed1_idx'),
        ),
        migrations.AddIndex(
            model_name='uattestrun',
            index=models.Index(fields=['tested_by', '-date_tested'], name='uat_scenari_tested__dbf444_idx'),
        ),
        migrations.AddIndex(
            model_name='uattestrun',
            index=models.Index(fields=['-date_tested', '-created_at'], name='uat_scenari_date_te_543b99_idx'),
        ),
    ]
