# Generated by Django 5.1.15 on 2025-12-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('uat_scenarios', '0003_add_test_run_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='uatscenario',
            name='priority',
            field=models.CharField(
                choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')],
                default='medium',
                help_text='Priority level: low, medium, high, critical',
                max_length=10,
            ),
        ),
    ]
