# Generated by Django 5.1.15 on 2025-12-06 07:39

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0037_remove_tool_company_remove_tool_taxonomy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='About the company')),
                ('tagline', models.CharField(blank=True, help_text='Short company tagline', max_length=300)),
                ('logo_url', models.URLField(blank=True, help_text='Company logo')),
                ('banner_url', models.URLField(blank=True, help_text='Company banner image')),
                ('website_url', models.URLField(blank=True)),
                ('careers_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, help_text='e.g., San Francisco, CA', max_length=200)),
                ('company_size', models.CharField(blank=True, help_text='e.g., 100-500 employees', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured companies appear prominently')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                (
                    'tagline',
                    models.CharField(
                        help_text="Short tagline (e.g., 'AI-powered conversational assistant')", max_length=300
                    ),
                ),
                ('description', models.TextField(help_text='Detailed description of what the tool does')),
                (
                    'tool_type',
                    models.CharField(
                        choices=[('ai_tool', 'AI Tool'), ('technology', 'Technology')],
                        db_index=True,
                        default='ai_tool',
                        help_text='Whether this is an AI tool or a technology',
                        max_length=20,
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('chat', 'Chat & Conversational AI'),
                            ('code', 'Code & Development'),
                            ('image', 'Image Generation'),
                            ('video', 'Video Generation & Editing'),
                            ('audio', 'Audio & Music'),
                            ('writing', 'Writing & Content'),
                            ('research', 'Research & Search'),
                            ('productivity', 'Productivity & Workflow'),
                            ('data', 'Data & Analytics'),
                            ('design', 'Design & Creative'),
                            ('language', 'Programming Language'),
                            ('framework', 'Framework & Library'),
                            ('database', 'Database'),
                            ('infrastructure', 'Infrastructure & DevOps'),
                            ('cloud', 'Cloud Platform'),
                            ('testing', 'Testing & QA'),
                            ('other', 'Other'),
                        ],
                        db_index=True,
                        default='other',
                        max_length=20,
                    ),
                ),
                (
                    'tags',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for filtering (e.g., ['NLP', 'GPT', 'OpenAI'])",
                    ),
                ),
                ('logo_url', models.URLField(blank=True, help_text='Primary logo (square)')),
                ('banner_url', models.URLField(blank=True, help_text='Wide banner/hero image')),
                (
                    'screenshot_urls',
                    models.JSONField(
                        blank=True, default=list, help_text='List of screenshot URLs to showcase the tool'
                    ),
                ),
                ('demo_video_url', models.URLField(blank=True, help_text='Demo or promotional video')),
                ('website_url', models.URLField(help_text='Official website URL')),
                ('documentation_url', models.URLField(blank=True)),
                ('pricing_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('discord_url', models.URLField(blank=True)),
                (
                    'pricing_model',
                    models.CharField(
                        choices=[
                            ('free', 'Free'),
                            ('freemium', 'Freemium'),
                            ('subscription', 'Subscription'),
                            ('pay_per_use', 'Pay Per Use'),
                            ('enterprise', 'Enterprise Only'),
                            ('open_source', 'Open Source'),
                        ],
                        default='freemium',
                        max_length=20,
                    ),
                ),
                (
                    'starting_price',
                    models.CharField(
                        blank=True, help_text="E.g., '$20/month', 'Free', '$0.002/1K tokens'", max_length=100
                    ),
                ),
                ('has_free_tier', models.BooleanField(default=False)),
                ('requires_api_key', models.BooleanField(default=False)),
                ('requires_waitlist', models.BooleanField(default=False)),
                (
                    'overview',
                    models.TextField(blank=True, help_text='Long-form overview/introduction (supports Markdown)'),
                ),
                (
                    'key_features',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of key features with descriptions [{title: '', description: ''}]",
                    ),
                ),
                (
                    'use_cases',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Specific use cases with examples [{title: '', description: '', example: ''}]",
                    ),
                ),
                (
                    'usage_tips',
                    models.JSONField(
                        blank=True, default=list, help_text='Practical tips for using the tool effectively'
                    ),
                ),
                (
                    'best_practices',
                    models.JSONField(blank=True, default=list, help_text='Best practices and recommendations'),
                ),
                (
                    'limitations',
                    models.JSONField(blank=True, default=list, help_text='Known limitations or considerations'),
                ),
                (
                    'alternatives',
                    models.JSONField(blank=True, default=list, help_text='List of alternative tool slugs'),
                ),
                (
                    'whats_new',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Recent updates and what's new [{date: '2025-01-15', title: '', description: ''}]",
                    ),
                ),
                (
                    'model_info',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical model information (e.g., {'model': 'GPT-4', 'provider': 'OpenAI'})",
                    ),
                ),
                (
                    'integrations',
                    models.JSONField(blank=True, default=list, help_text='List of integrations/platforms supported'),
                ),
                ('api_available', models.BooleanField(default=False)),
                (
                    'languages_supported',
                    models.JSONField(blank=True, default=list, help_text='Programming/natural languages supported'),
                ),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='SEO keywords')),
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True, default=True, help_text='Whether this tool is visible in the directory'
                    ),
                ),
                (
                    'is_featured',
                    models.BooleanField(db_index=True, default=False, help_text='Featured tools appear at the top'),
                ),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by team (shows badge)')),
                ('view_count', models.IntegerField(default=0)),
                (
                    'popularity_score',
                    models.FloatField(default=0.0, help_text='Calculated popularity score for ranking'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                (
                    'company',
                    models.ForeignKey(
                        blank=True,
                        help_text='Parent company/vendor (e.g., Anthropic for Claude)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='tools',
                        to='tools.company',
                    ),
                ),
                (
                    'taxonomy',
                    models.OneToOneField(
                        blank=True,
                        help_text='Link to taxonomy entry for user personalization/tagging',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='tool_entity',
                        to='core.taxonomy',
                    ),
                ),
            ],
            options={
                'ordering': ['-is_featured', '-popularity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ToolBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about the tool')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'tool',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='tools.tool'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tool_bookmarks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tools', models.ManyToManyField(related_name='comparisons', to='tools.tool')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tool_comparisons',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'rating',
                    models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1-5 star rating'),
                ),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('pros', models.JSONField(blank=True, default=list, help_text='List of pros')),
                ('cons', models.JSONField(blank=True, default=list, help_text='List of cons')),
                ('use_case', models.CharField(blank=True, help_text='What they used it for', max_length=200)),
                ('is_verified_user', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'tool',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tools.tool'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tool_reviews',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['tool_type', 'is_active'], name='tools_tool_tool_ty_76089e_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['tool_type', 'category', 'is_active'], name='tools_tool_tool_ty_578776_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['category', 'is_active'], name='tools_tool_categor_5d181e_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_active', '-popularity_score'], name='tools_tool_is_acti_779f86_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_active', '-created_at'], name='tools_tool_is_acti_25b7d9_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_featured', 'is_active'], name='tools_tool_is_feat_47810a_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='tool_tags_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='tool_keywords_gin_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='toolbookmark',
            unique_together={('user', 'tool')},
        ),
        migrations.AddIndex(
            model_name='toolreview',
            index=models.Index(fields=['tool', '-created_at'], name='tools_toolr_tool_id_21bb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='toolreview',
            index=models.Index(fields=['tool', '-helpful_count'], name='tools_toolr_tool_id_d219ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='toolreview',
            unique_together={('tool', 'user')},
        ),
    ]
