# Generated by Django 5.1.15 on 2025-12-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='game_stats',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Numerical stats for game mechanics: {power, speed, versatility, ease_of_use, value} (1-10 scale)',
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='rarity',
            field=models.CharField(
                choices=[
                    ('common', 'Common'),
                    ('uncommon', 'Uncommon'),
                    ('rare', 'Rare'),
                    ('epic', 'Epic'),
                    ('legendary', 'Legendary'),
                ],
                db_index=True,
                default='common',
                help_text='Tool rarity for game collection mechanics',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='superpowers',
            field=models.JSONField(
                blank=True, default=list, help_text='Array of tool strengths: [{title: str, description: str}]'
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='synergy_tools',
            field=models.JSONField(
                blank=True, default=list, help_text='List of tool slugs that combo well with this tool'
            ),
        ),
    ]
