# Generated by Django 5.1.15 on 2025-12-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0070_add_is_timeless_field'),
        ('tools', '0003_add_weaviate_sync_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tool',
            name='tool_tags_gin_idx',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='tags',
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count_range',
            field=models.CharField(
                blank=True,
                choices=[
                    ('1-10', '1-10'),
                    ('11-50', '11-50'),
                    ('51-200', '51-200'),
                    ('201-500', '201-500'),
                    ('501-1000', '501-1000'),
                    ('1000+', '1000+'),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='company',
            name='funding_stage',
            field=models.CharField(
                blank=True,
                choices=[
                    ('bootstrapped', 'Bootstrapped'),
                    ('seed', 'Seed'),
                    ('series_a', 'Series A'),
                    ('series_b', 'Series B'),
                    ('series_c_plus', 'Series C+'),
                    ('public', 'Public'),
                    ('acquired', 'Acquired'),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='company',
            name='has_gdpr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='has_hipaa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='has_soc2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='total_funding',
            field=models.CharField(blank=True, help_text='e.g., "$50M"', max_length=50),
        ),
        migrations.AddField(
            model_name='tool',
            name='compliance_certs',
            field=models.JSONField(
                blank=True, default=list, help_text='Certifications: ["soc2", "hipaa", "gdpr", "iso27001"]'
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='differentiators',
            field=models.JSONField(
                blank=True, default=list, help_text='Comparison vs competitors: [{vs: slug, pros: [], cons: []}]'
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='hosting_options',
            field=models.JSONField(
                blank=True, default=list, help_text='Deployment options: ["managed_cloud", "self_hosted", "kubernetes"]'
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='ideal_for',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Ideal user profiles: ["startups", "RAG applications", "high-throughput"]',
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='not_ideal_for',
            field=models.JSONField(
                blank=True, default=list, help_text='Use cases where NOT recommended (for Ember to cite)'
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='pricing_tiers',
            field=models.JSONField(
                blank=True, default=list, help_text='Pricing tier breakdown: [{name, price, features, limits}]'
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='sdk_languages',
            field=models.JSONField(blank=True, default=list, help_text='Official SDKs: ["python", "javascript", "go"]'),
        ),
        migrations.AddField(
            model_name='tool',
            name='support_tiers',
            field=models.JSONField(
                blank=True, default=list, help_text='Support options: [{tier, response_time, channels}]'
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='topics',
            field=models.ManyToManyField(
                blank=True,
                help_text='Topics for discovery (e.g., Vector Databases, RAG, Authentication)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'topic'},
                related_name='tools',
                to='core.taxonomy',
            ),
        ),
    ]
