# Generated by Django 5.1.15 on 2025-12-18 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0048_project_contact_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'intro_message',
                    models.TextField(
                        help_text='Brief intro message explaining why you want to connect', max_length=500
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('accepted', 'Accepted'),
                            ('declined', 'Declined'),
                            ('expired', 'Expired'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connection_requests',
                        to='core.project',
                    ),
                ),
                (
                    'recipient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='received_connection_requests',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'requester',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sent_connection_requests',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=100)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'connection_request',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='thread',
                        to='messaging.connectionrequest',
                    ),
                ),
                (
                    'last_message_sender',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'originating_project',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='originated_threads',
                        to='core.project',
                    ),
                ),
                ('participants', models.ManyToManyField(related_name='message_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                (
                    'moderation_status',
                    models.CharField(
                        choices=[
                            ('approved', 'Approved'),
                            ('pending', 'Pending Review'),
                            ('flagged', 'Flagged'),
                            ('removed', 'Removed'),
                        ],
                        db_index=True,
                        default='approved',
                        max_length=20,
                    ),
                ),
                ('moderation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'sender',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sent_direct_messages',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'thread',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to='messaging.directmessagethread',
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'reason',
                    models.CharField(
                        choices=[
                            ('spam', 'Spam'),
                            ('harassment', 'Harassment'),
                            ('inappropriate', 'Inappropriate Content'),
                            ('scam', 'Scam / Fraud'),
                            ('other', 'Other'),
                        ],
                        max_length=20,
                    ),
                ),
                ('description', models.TextField(blank=True, max_length=500)),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Pending Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reports',
                        to='messaging.directmessage',
                    ),
                ),
                (
                    'reporter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='message_reports_filed',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'resolved_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='message_reports_resolved',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'blocked',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='blocked_by',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'blocker',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='blocked_users',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['recipient', 'status', '-created_at'], name='messaging_c_recipie_acbb21_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['requester', '-created_at'], name='messaging_c_request_11e04a_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['project', 'status'], name='messaging_c_project_955e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['expires_at', 'status'], name='messaging_c_expires_3f26a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectionrequest',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'pending')),
                fields=('requester', 'project'),
                name='unique_pending_request_per_project',
            ),
        ),
        migrations.AddConstraint(
            model_name='connectionrequest',
            constraint=models.CheckConstraint(
                condition=models.Q(('requester', models.F('recipient')), _negated=True),
                name='no_self_connection_request',
            ),
        ),
        migrations.AddIndex(
            model_name='directmessagethread',
            index=models.Index(fields=['-last_message_at'], name='messaging_d_last_me_f291be_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['thread', 'created_at'], name='messaging_d_thread__c93b89_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['sender', '-created_at'], name='messaging_d_sender__8190f9_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['thread', 'read_at'], name='messaging_d_thread__3ad501_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['status', '-created_at'], name='messaging_m_status_bad163_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(
                fields=('message', 'reporter'), name='unique_report_per_user_per_message'
            ),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocker'], name='messaging_u_blocker_63dc57_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocked'], name='messaging_u_blocked_14283f_idx'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_user_block'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.CheckConstraint(
                condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='no_self_block'
            ),
        ),
    ]
