"""Management command to seed achievement definitions."""

from django.core.management.base import BaseCommand

from core.achievements.models import Achievement, AchievementCategory, AchievementRarity, CriteriaType


class Command(BaseCommand):
    help = 'Seed the database with initial achievement definitions'

    def handle(self, *args, **kwargs):
        achievements = [
            # ========================================
            # CREATOR (Projects) - 6 achievements
            # ========================================
            {
                'key': 'first_spark',
                'name': 'First Spark',
                'description': 'Started something new',
                'icon': 'faRocket',
                'color_from': 'orange-500',
                'color_to': 'orange-600',
                'category': AchievementCategory.PROJECTS,
                'points': 10,
                'criteria_type': CriteriaType.FIRST_TIME,
                'criteria_value': 1,
                'tracking_field': 'lifetime_projects_created',
                'rarity': AchievementRarity.COMMON,
                'order': 1,
            },
            {
                'key': 'getting_started',
                'name': 'Getting Started',
                'description': 'Building momentum',
                'icon': 'faFire',
                'color_from': 'orange-600',
                'color_to': 'red-500',
                'category': AchievementCategory.PROJECTS,
                'points': 25,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 5,
                'tracking_field': 'lifetime_projects_created',
                'rarity': AchievementRarity.COMMON,
                'order': 2,
            },
            {
                'key': 'on_fire',
                'name': 'On Fire',
                'description': 'Creating consistently',
                'icon': 'faFire',
                'color_from': 'red-500',
                'color_to': 'red-600',
                'category': AchievementCategory.PROJECTS,
                'points': 50,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 10,
                'tracking_field': 'lifetime_projects_created',
                'rarity': AchievementRarity.COMMON,
                'order': 3,
            },
            {
                'key': 'prolific',
                'name': 'Prolific',
                'description': 'A serious creator',
                'icon': 'faFire',
                'color_from': 'red-600',
                'color_to': 'orange-500',
                'category': AchievementCategory.PROJECTS,
                'points': 100,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 25,
                'tracking_field': 'lifetime_projects_created',
                'rarity': AchievementRarity.RARE,
                'order': 4,
            },
            {
                'key': 'unstoppable',
                'name': 'Unstoppable',
                'description': "Can't stop creating",
                'icon': 'faFire',
                'color_from': 'red-700',
                'color_to': 'orange-600',
                'category': AchievementCategory.PROJECTS,
                'points': 250,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 50,
                'tracking_field': 'lifetime_projects_created',
                'rarity': AchievementRarity.EPIC,
                'order': 5,
            },
            {
                'key': 'phoenix',
                'name': 'Phoenix',
                'description': 'Master creator',
                'icon': 'faBird',
                'color_from': 'orange-500',
                'color_to': 'pink-500',
                'category': AchievementCategory.PROJECTS,
                'points': 500,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 100,
                'tracking_field': 'lifetime_projects_created',
                'rarity': AchievementRarity.LEGENDARY,
                'is_secret': True,
                'order': 6,
            },
            # ========================================
            # CHALLENGER (Battles) - 6 achievements
            # ========================================
            {
                'key': 'first_attempt',
                'name': 'First Attempt',
                'description': 'Gave it a shot',
                'icon': 'faBullseye',
                'color_from': 'blue-500',
                'color_to': 'blue-600',
                'category': AchievementCategory.BATTLES,
                'points': 10,
                'criteria_type': CriteriaType.FIRST_TIME,
                'criteria_value': 1,
                'tracking_field': 'lifetime_battles_participated',
                'rarity': AchievementRarity.COMMON,
                'order': 1,
            },
            {
                'key': 'explorer',
                'name': 'Explorer',
                'description': 'Trying different approaches',
                'icon': 'faCompass',
                'color_from': 'purple-500',
                'color_to': 'purple-600',
                'category': AchievementCategory.BATTLES,
                'points': 25,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 5,
                'tracking_field': 'lifetime_battles_participated',
                'rarity': AchievementRarity.COMMON,
                'order': 2,
            },
            {
                'key': 'regular',
                'name': 'Regular',
                'description': 'Making it a habit',
                'icon': 'faCalendarCheck',
                'color_from': 'purple-600',
                'color_to': 'pink-500',
                'category': AchievementCategory.BATTLES,
                'points': 50,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 10,
                'tracking_field': 'lifetime_battles_participated',
                'rarity': AchievementRarity.COMMON,
                'order': 3,
            },
            {
                'key': 'personal_best',
                'name': 'Personal Best',
                'description': 'Beat your old record',
                'icon': 'faTrophy',
                'color_from': 'gold-500',
                'color_to': 'orange-500',
                'category': AchievementCategory.BATTLES,
                'points': 75,
                'criteria_type': CriteriaType.FIRST_TIME,
                'criteria_value': 1,
                'tracking_field': 'battles_personal_best_count',
                'rarity': AchievementRarity.RARE,
                'order': 4,
            },
            {
                'key': 'dedicated',
                'name': 'Dedicated',
                'description': 'Showing up consistently',
                'icon': 'faStar',
                'color_from': 'purple-600',
                'color_to': 'pink-600',
                'category': AchievementCategory.BATTLES,
                'points': 100,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 20,
                'tracking_field': 'lifetime_battles_participated',
                'rarity': AchievementRarity.EPIC,
                'order': 5,
            },
            {
                'key': 'versatile',
                'name': 'Versatile',
                'description': 'Exploring different styles',
                'icon': 'faPalette',
                'color_from': 'pink-500',
                'color_to': 'purple-600',
                'category': AchievementCategory.BATTLES,
                'points': 60,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 3,
                'tracking_field': 'battle_types_tried',  # TODO: Add this field
                'rarity': AchievementRarity.RARE,
                'order': 6,
            },
            # ========================================
            # CONTRIBUTOR (Engagement) - 6 achievements
            # ========================================
            {
                'key': 'first_comment',
                'name': 'First Comment',
                'description': 'Joined the conversation',
                'icon': 'faComment',
                'color_from': 'gray-500',
                'color_to': 'gray-600',
                'category': AchievementCategory.COMMUNITY,
                'points': 5,
                'criteria_type': CriteriaType.FIRST_TIME,
                'criteria_value': 1,
                'tracking_field': 'lifetime_comments_posted',
                'rarity': AchievementRarity.COMMON,
                'order': 1,
            },
            {
                'key': 'helpful',
                'name': 'Helpful',
                'description': 'Giving useful feedback',
                'icon': 'faHandshake',
                'color_from': 'green-500',
                'color_to': 'green-600',
                'category': AchievementCategory.COMMUNITY,
                'points': 15,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 5,
                'tracking_field': 'helpful_votes_received',
                'rarity': AchievementRarity.COMMON,
                'order': 2,
            },
            {
                'key': 'active_member',
                'name': 'Active Member',
                'description': 'Engaging regularly',
                'icon': 'faHeart',
                'color_from': 'green-600',
                'color_to': 'emerald-500',
                'category': AchievementCategory.COMMUNITY,
                'points': 35,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 15,
                'tracking_field': 'unique_projects_commented',
                'rarity': AchievementRarity.COMMON,
                'order': 3,
            },
            {
                'key': 'supporter',
                'name': 'Supporter',
                'description': 'Consistently helpful',
                'icon': 'faStar',
                'color_from': 'emerald-500',
                'color_to': 'teal-500',
                'category': AchievementCategory.COMMUNITY,
                'points': 75,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 50,
                'tracking_field': 'helpful_votes_received',
                'rarity': AchievementRarity.RARE,
                'order': 4,
            },
            {
                'key': 'mentor',
                'name': 'Mentor',
                'description': 'Helping others grow',
                'icon': 'faGraduationCap',
                'color_from': 'pink-500',
                'color_to': 'rose-500',
                'category': AchievementCategory.COMMUNITY,
                'points': 150,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 100,
                'tracking_field': 'helpful_votes_received',
                'rarity': AchievementRarity.EPIC,
                'order': 5,
            },
            {
                'key': 'welcoming',
                'name': 'Welcoming',
                'description': 'Making others feel welcome',
                'icon': 'faHandHoldingHeart',
                'color_from': 'blue-400',
                'color_to': 'green-400',
                'category': AchievementCategory.COMMUNITY,
                'points': 40,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 5,
                'tracking_field': 'new_users_welcomed',  # TODO: Add this field
                'rarity': AchievementRarity.RARE,
                'order': 6,
            },
            # ========================================
            # STREAK (Daily Activity) - 6 achievements
            # ========================================
            {
                'key': '3_day_streak',
                'name': '3 Day Streak',
                'description': 'Getting started',
                'icon': 'faFire',
                'color_from': 'orange-400',
                'color_to': 'orange-500',
                'category': AchievementCategory.STREAKS,
                'points': 15,
                'criteria_type': CriteriaType.STREAK,
                'criteria_value': 3,
                'tracking_field': 'current_streak_days',
                'rarity': AchievementRarity.COMMON,
                'order': 1,
            },
            {
                'key': 'week_streak',
                'name': 'Week Streak',
                'description': 'One week strong',
                'icon': 'faFire',
                'color_from': 'orange-500',
                'color_to': 'red-500',
                'category': AchievementCategory.STREAKS,
                'points': 30,
                'criteria_type': CriteriaType.STREAK,
                'criteria_value': 7,
                'tracking_field': 'current_streak_days',
                'rarity': AchievementRarity.COMMON,
                'order': 2,
            },
            {
                'key': 'two_week_streak',
                'name': 'Two Week Streak',
                'description': 'Building a habit',
                'icon': 'faFire',
                'color_from': 'red-500',
                'color_to': 'red-600',
                'category': AchievementCategory.STREAKS,
                'points': 50,
                'criteria_type': CriteriaType.STREAK,
                'criteria_value': 14,
                'tracking_field': 'current_streak_days',
                'rarity': AchievementRarity.COMMON,
                'order': 3,
            },
            {
                'key': 'month_streak',
                'name': 'Month Streak',
                'description': '30 days committed',
                'icon': 'faFire',
                'color_from': 'red-600',
                'color_to': 'orange-600',
                'category': AchievementCategory.STREAKS,
                'points': 100,
                'criteria_type': CriteriaType.STREAK,
                'criteria_value': 30,
                'tracking_field': 'current_streak_days',
                'rarity': AchievementRarity.RARE,
                'order': 4,
            },
            {
                'key': '100_day_streak',
                'name': '100 Day Streak',
                'description': 'Seriously dedicated',
                'icon': 'faFire',
                'color_from': 'orange-600',
                'color_to': 'yellow-500',
                'category': AchievementCategory.STREAKS,
                'points': 300,
                'criteria_type': CriteriaType.STREAK,
                'criteria_value': 100,
                'tracking_field': 'current_streak_days',
                'rarity': AchievementRarity.EPIC,
                'order': 5,
            },
            {
                'key': 'year_streak',
                'name': 'Year Streak',
                'description': 'Unstoppable',
                'icon': 'faFire',
                'color_from': 'orange-600',
                'color_to': 'pink-500',
                'category': AchievementCategory.STREAKS,
                'points': 1000,
                'criteria_type': CriteriaType.STREAK,
                'criteria_value': 365,
                'tracking_field': 'current_streak_days',
                'rarity': AchievementRarity.LEGENDARY,
                'is_secret': True,
                'order': 6,
            },
            # ========================================
            # LEARNER (Quizzes) - 6 achievements
            # ========================================
            {
                'key': 'first_quiz',
                'name': 'First Quiz',
                'description': 'Tried a quiz',
                'icon': 'faLightbulb',
                'color_from': 'blue-400',
                'color_to': 'blue-500',
                'category': AchievementCategory.COMMUNITY,
                'points': 5,
                'criteria_type': CriteriaType.FIRST_TIME,
                'criteria_value': 1,
                'tracking_field': 'lifetime_quizzes_completed',
                'rarity': AchievementRarity.COMMON,
                'order': 7,
            },
            {
                'key': 'quiz_taker',
                'name': 'Quiz Taker',
                'description': 'Testing your knowledge',
                'icon': 'faBook',
                'color_from': 'blue-500',
                'color_to': 'indigo-500',
                'category': AchievementCategory.COMMUNITY,
                'points': 25,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 5,
                'tracking_field': 'lifetime_quizzes_completed',
                'rarity': AchievementRarity.COMMON,
                'order': 8,
            },
            {
                'key': 'quiz_fan',
                'name': 'Quiz Fan',
                'description': 'Really into quizzes',
                'icon': 'faBrain',
                'color_from': 'indigo-500',
                'color_to': 'purple-500',
                'category': AchievementCategory.COMMUNITY,
                'points': 50,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 15,
                'tracking_field': 'lifetime_quizzes_completed',
                'rarity': AchievementRarity.COMMON,
                'order': 9,
            },
            {
                'key': 'perfect_score',
                'name': 'Perfect Score',
                'description': 'Aced it',
                'icon': 'faStar',
                'color_from': 'gold-500',
                'color_to': 'yellow-500',
                'category': AchievementCategory.COMMUNITY,
                'points': 50,
                'criteria_type': CriteriaType.FIRST_TIME,
                'criteria_value': 1,
                'tracking_field': 'perfect_quiz_scores',  # TODO: Add this field
                'rarity': AchievementRarity.RARE,
                'order': 10,
            },
            {
                'key': 'quiz_master',
                'name': 'Quiz Master',
                'description': 'Serious quiz taker',
                'icon': 'faGraduationCap',
                'color_from': 'purple-600',
                'color_to': 'pink-500',
                'category': AchievementCategory.COMMUNITY,
                'points': 150,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 50,
                'tracking_field': 'lifetime_quizzes_completed',
                'rarity': AchievementRarity.EPIC,
                'order': 11,
            },
            {
                'key': 'topic_explorer',
                'name': 'Topic Explorer',
                'description': 'Exploring different areas',
                'icon': 'faCompass',
                'color_from': 'teal-500',
                'color_to': 'blue-500',
                'category': AchievementCategory.COMMUNITY,
                'points': 40,
                'criteria_type': CriteriaType.COUNT,
                'criteria_value': 5,
                'tracking_field': 'topics_explored',
                'rarity': AchievementRarity.RARE,
                'order': 12,
            },
            # ========================================
            # TIER PROGRESS - 5 achievements
            # Note: Using ENGAGEMENT category since there's no PROGRESSION category
            # ========================================
            {
                'key': 'ember_tier',
                'name': 'Ember',
                'description': 'Just getting started',
                'icon': 'faSeedling',
                'color_from': 'gray-500',
                'color_to': 'orange-400',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 5,
                'criteria_type': CriteriaType.FIRST_TIME,
                'criteria_value': 1,
                'tracking_field': 'tier',
                'rarity': AchievementRarity.COMMON,
                'order': 1,
            },
            {
                'key': 'spark_tier',
                'name': 'Spark',
                'description': 'Making progress',
                'icon': 'faBolt',
                'color_from': 'orange-400',
                'color_to': 'yellow-500',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 25,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 500,
                'tracking_field': 'total_points',
                'rarity': AchievementRarity.COMMON,
                'order': 2,
            },
            {
                'key': 'blaze_tier',
                'name': 'Blaze',
                'description': 'Really going now',
                'icon': 'faFire',
                'color_from': 'red-500',
                'color_to': 'orange-500',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 100,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 2000,
                'tracking_field': 'total_points',
                'rarity': AchievementRarity.RARE,
                'order': 3,
            },
            {
                'key': 'beacon_tier',
                'name': 'Beacon',
                'description': 'Serious dedication',
                'icon': 'faLightbulb',
                'color_from': 'blue-500',
                'color_to': 'purple-500',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 250,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 5000,
                'tracking_field': 'total_points',
                'rarity': AchievementRarity.EPIC,
                'order': 4,
            },
            {
                'key': 'phoenix_tier',
                'name': 'Phoenix',
                'description': 'Top tier achieved',
                'icon': 'faBird',
                'color_from': 'purple-500',
                'color_to': 'pink-500',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 500,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 10000,
                'tracking_field': 'total_points',
                'rarity': AchievementRarity.LEGENDARY,
                'order': 5,
            },
            # ========================================
            # MILESTONES (Personal Progress) - 7 achievements
            # ========================================
            {
                'key': '100_xp',
                'name': '100 XP',
                'description': 'First 100 points',
                'icon': 'faChartLine',
                'color_from': 'blue-500',
                'color_to': 'blue-600',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 10,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 100,
                'tracking_field': 'total_points',
                'rarity': AchievementRarity.COMMON,
                'order': 6,
            },
            {
                'key': 'goal_achiever',
                'name': 'Goal Achiever',
                'description': 'Completed a goal',
                'icon': 'faBullseye',
                'color_from': 'purple-500',
                'color_to': 'purple-600',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 20,
                'criteria_type': CriteriaType.FIRST_TIME,
                'criteria_value': 1,
                'tracking_field': 'weekly_goals_completed',  # TODO: Add this field
                'rarity': AchievementRarity.COMMON,
                'order': 7,
            },
            {
                'key': 'hot_week',
                'name': 'Hot Week',
                'description': 'Big week',
                'icon': 'faFire',
                'color_from': 'green-500',
                'color_to': 'emerald-500',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 50,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 500,
                'tracking_field': 'weekly_points_gained',  # TODO: Need to track this
                'rarity': AchievementRarity.RARE,
                'order': 8,
            },
            {
                'key': 'leveled_up',
                'name': 'Leveled Up',
                'description': 'Gaining levels',
                'icon': 'faArrowUp',
                'color_from': 'orange-500',
                'color_to': 'red-500',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 75,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 5,
                'tracking_field': 'level',
                'rarity': AchievementRarity.RARE,
                'order': 9,
            },
            {
                'key': 'streak_breaker',
                'name': 'Streak Breaker',
                'description': 'Beat your record',
                'icon': 'faTrophy',
                'color_from': 'gold-500',
                'color_to': 'orange-500',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 100,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 1,
                'tracking_field': 'broke_streak_record',  # TODO: Track this
                'rarity': AchievementRarity.EPIC,
                'order': 10,
            },
            {
                'key': 'consistent',
                'name': 'Consistent',
                'description': 'Showed up all month',
                'icon': 'faCalendarCheck',
                'color_from': 'blue-600',
                'color_to': 'purple-600',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 80,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 30,
                'tracking_field': 'days_active_this_month',  # TODO: Track this
                'rarity': AchievementRarity.RARE,
                'order': 11,
            },
            {
                'key': 'well_rounded',
                'name': 'Well-Rounded',
                'description': 'Tried everything',
                'icon': 'faStar',
                'color_from': 'purple-500',
                'color_to': 'pink-500',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 150,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 6,
                'tracking_field': 'achievement_categories_earned',  # TODO: Track this
                'rarity': AchievementRarity.LEGENDARY,
                'order': 12,
            },
            # ========================================
            # GROWTH PATH (Tier Milestones) - 5 achievements
            # ========================================
            {
                'key': 'explorer',
                'name': 'Explorer',
                'description': "Discovering what's possible",
                'icon': 'faSeedling',
                'color_from': 'green-400',
                'color_to': 'green-500',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 50,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 1000,
                'tracking_field': 'total_points',
                'rarity': AchievementRarity.COMMON,
                'order': 13,
            },
            {
                'key': 'gardener',
                'name': 'Gardener',
                'description': 'Tending your creative space',
                'icon': 'faSpa',
                'color_from': 'green-500',
                'color_to': 'emerald-500',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 100,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 2500,
                'tracking_field': 'total_points',
                'rarity': AchievementRarity.RARE,
                'order': 14,
            },
            {
                'key': 'cultivator',
                'name': 'Cultivator',
                'description': 'Developing deeper skills',
                'icon': 'faLeaf',
                'color_from': 'emerald-500',
                'color_to': 'teal-500',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 200,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 5000,
                'tracking_field': 'total_points',
                'rarity': AchievementRarity.EPIC,
                'order': 15,
            },
            {
                'key': 'harvest',
                'name': 'Harvest',
                'description': 'Reaping creative rewards',
                'icon': 'faTree',
                'color_from': 'teal-500',
                'color_to': 'cyan-600',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 300,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 10000,
                'tracking_field': 'total_points',
                'rarity': AchievementRarity.EPIC,
                'order': 16,
            },
            {
                'key': 'keeper',
                'name': 'Keeper',
                'description': 'Stewarding the garden, helping others grow',
                'icon': 'faHandHoldingHeart',
                'color_from': 'pink-400',
                'color_to': 'rose-500',
                'category': AchievementCategory.COMMUNITY,
                'points': 500,
                'criteria_type': CriteriaType.THRESHOLD,
                'criteria_value': 50,
                'tracking_field': 'helpful_votes_received',
                'rarity': AchievementRarity.LEGENDARY,
                'order': 17,
            },
            {
                'key': 'prompt_engineer',
                'name': 'Prompt Engineer',
                'description': 'Mastered the art of AI prompting by creating your first avatar',
                'icon': 'faWandMagicSparkles',
                'color_from': 'purple-500',
                'color_to': 'pink-500',
                'category': AchievementCategory.ENGAGEMENT,
                'points': 50,
                'criteria_type': CriteriaType.FIRST_TIME,
                'criteria_value': 1,
                'tracking_field': 'ai_avatars_created',
                'rarity': AchievementRarity.RARE,
                'order': 18,
            },
        ]

        created_count = 0
        updated_count = 0

        for achievement_data in achievements:
            achievement, created = Achievement.objects.update_or_create(
                key=achievement_data['key'], defaults=achievement_data
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'✓ Created: {achievement.name}'))
            else:
                updated_count += 1
                self.stdout.write(self.style.WARNING(f'↻ Updated: {achievement.name}'))

        self.stdout.write(
            self.style.SUCCESS(
                f'\n✓ Successfully seeded {created_count} new and updated {updated_count} existing achievements'
            )
        )
        self.stdout.write(self.style.SUCCESS(f'Total achievements in database: {Achievement.objects.count()}'))
