"""Seed initial challenge types for Prompt Battles."""

from django.core.management.base import BaseCommand

from core.battles.models import ChallengeType
from core.taxonomy.models import Taxonomy

CHALLENGE_TYPES = [
    {
        'key': 'dreamscape',
        'name': 'Dreamscape Design',
        'description': 'Create surreal, dreamlike landscapes and environments using AI image generation.',
        'category_slug': 'images-video',
        'templates': [
            'Design a world where {rule}',
            'Create a dimension that exists inside {location}',
            'What does it look like when {event}?',
            'Design the place you go when {situation}',
        ],
        'variables': {
            'rule': [
                'stairs only go sideways',
                'everyone has to narrate their actions out loud',
                'shadows are 10 seconds ahead of you',
                'you can only turn left',
                'thoughts are visible but lies are louder',
                'nostalgia is a weather pattern',
                'music taste determines social class',
            ],
            'event': [
                'two people reach for the same thing at the grocery store',
                "you wave at someone who wasn't waving at you",
                'autocorrect becomes sentient',
                'your intrusive thoughts win',
                "you finally sneeze after it felt like you wouldn't",
                'every sock finds its pair',
            ],
            'location': [
                'the moment before your alarm goes off',
                'a sneeze that got interrupted',
                'the default wallpaper of every office computer',
                'the hold music when you call customer service',
                "the feeling of forgetting someone's name mid-conversation",
                "a memory you're not sure actually happened",
                'the back of the junk drawer',
            ],
            'situation': [
                'you zone out in a meeting and miss something important',
                'you remember that embarrassing thing from 2013',
                "you're too awake to sleep but too tired to function",
                'you say "you too" when the waiter says enjoy your meal',
                'you pretend to text to avoid someone you know',
            ],
        },
        'judging_criteria': [
            {'name': 'Creativity', 'weight': 30, 'description': 'How original and imaginative is the vision?'},
            {'name': 'Visual Impact', 'weight': 25, 'description': 'How striking and memorable is the image?'},
            {'name': 'Challenge Relevance', 'weight': 25, 'description': 'How well does it address the prompt?'},
            {'name': 'Artistic Cohesion', 'weight': 20, 'description': 'How well do elements work together?'},
        ],
        'default_duration_minutes': 3,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'medium',
    },
    {
        'key': 'movie_poster',
        'name': 'Movie Poster Challenge',
        'description': 'Design compelling movie posters for imaginary films.',
        'category_slug': 'images-video',
        'templates': [
            'Design the poster for "{title}"',
            'Create the movie poster for a film about {concept}',
            'Design a {genre} movie poster with the tagline: "{tagline}"',
        ],
        'variables': {
            'genre': [
                'psychological thriller',
                'romantic comedy',
                'documentary',
                'action',
                'horror',
                'indie drama',
            ],
            'title': [
                'Honey, I Became the HOA President',
                'Fast & Furious 47: Retirement Community',
                'The Notebook 2: She Forgot Again',
                'Jaws but the Shark is Reasonable',
                'Die Hard in a Furniture Warehouse',
                'The Silence of the Hams',
                'Fifty Shades of Beige: A Paint Store Romance',
                "Dude, Where's My Will to Live?",
                "Ocean's Eleven but It's a Potluck",
                'The Godfather but for a Book Club',
            ],
            'concept': [
                'a Roomba that witnessed a crime',
                'a group chat that goes horribly wrong',
                'someone who peaked in middle school',
                'pigeons planning an elaborate heist',
                'a potluck that tears a family apart',
                'an email that was never meant to be sent',
                'the last person on earth who uses Internet Explorer',
            ],
            'tagline': [
                'Some meetings COULD have been emails',
                'In space, everyone can hear you snack',
                'Based on a true story I made up',
                'She came for brunch. She stayed for chaos.',
                'One man. One dream. Zero follow-through.',
                'This summer, the spreadsheet fights back',
            ],
        },
        'judging_criteria': [
            {
                'name': 'Poster Appeal',
                'weight': 30,
                'description': 'Would you want to see this movie based on the poster?',
            },
            {'name': 'Genre Fit', 'weight': 25, 'description': 'Does it capture the genre effectively?'},
            {'name': 'Creativity', 'weight': 25, 'description': 'How original is the design approach?'},
            {'name': 'Technical Quality', 'weight': 20, 'description': 'Is the composition and design well-executed?'},
        ],
        'default_duration_minutes': 4,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'medium',
    },
    {
        'key': 'creature_design',
        'name': 'Creature Design',
        'description': 'Design unique creatures, monsters, or fantastical beings.',
        'category_slug': 'images-video',
        'templates': [
            'Design the creature that lives in {location}',
            'What does {concept} look like as a living thing?',
            'Create the animal that would result if {scenario}',
            'Design a creature that only exists because {reason}',
        ],
        'variables': {
            'reason': [
                'someone wished on a birthday candle wrong',
                'a scientist sneezed during an important experiment',
                'the universe needed something to guard the TV remote',
                'evolution got bored one Tuesday',
                'a child drew something and it became real',
                'someone said "that\'s not my job" one too many times',
            ],
            'concept': [
                'the Sunday Scaries',
                'that feeling when you forget why you walked into a room',
                'the last 5% of phone battery',
                'the audacity of someone who replies-all',
                'the confidence of a seagull stealing fries',
                'the anxiety of an unread email from your boss',
                'deja vu',
            ],
            'location': [
                'the space between couch cushions',
                'that one drawer everyone has but never opens',
                'the back of the fridge where forgotten leftovers go',
                'the void where missing socks disappear to',
                'the 3am corner of your brain',
                'the silence after someone says "we need to talk"',
                'the exact moment before you sneeze',
            ],
            'scenario': [
                'a cat and a loaf of bread loved each other very much',
                'someone left a Roomba and a cactus alone too long',
                'a cloud got really into CrossFit',
                'a potato achieved enlightenment',
                'someone accidentally microwaved their ambition',
                'a moth finally caught the lamp',
            ],
        },
        'judging_criteria': [
            {'name': 'Originality', 'weight': 30, 'description': 'How unique and creative is the design?'},
            {'name': 'Visual Design', 'weight': 25, 'description': 'Is it visually compelling and well-designed?'},
            {'name': 'Concept Clarity', 'weight': 25, 'description': "Is the creature's nature clearly conveyed?"},
            {'name': 'Detail & Coherence', 'weight': 20, 'description': 'Are the details consistent and believable?'},
        ],
        'default_duration_minutes': 4,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'medium',
    },
    {
        'key': 'album_cover',
        'name': 'Album Cover Art',
        'description': 'Design album cover artwork for imaginary music releases.',
        'category_slug': 'images-video',
        'templates': [
            'Album cover for "{title}" by {artist}',
            'Design the cover for a {genre} album about {concept}',
            'Create album art that sounds like {sound}',
        ],
        'variables': {
            'genre': ['ambient', 'lo-fi', 'experimental', 'yacht rock', 'folk punk', 'sad cowboy'],
            'sound': [
                "when you almost sneeze but don't",
                "elevator music but it's having an existential crisis",
                'the 10 seconds after you embarrass yourself',
                'waiting for your food at a restaurant when everyone else got theirs',
                'the specific silence after you say something weird',
            ],
            'title': [
                'Songs to Stare at the Ceiling To',
                'I Peaked in 2007',
                'Unread Emails: The Musical',
                'Crying in the Club (The Club is Target)',
                '3am Wikipedia Spirals',
                'My Therapist Will Hear About This',
            ],
            'artist': [
                'The Regrettable Haircuts',
                'Seasonal Depression feat. Rain',
                'Your Upstairs Neighbor',
                'That Sound Your Fridge Makes',
                'The Group Chat With No Name',
                'Mid-Meeting Panic Attack',
            ],
            'concept': [
                'waiting for someone to text back',
                'the last 15 minutes of work on Friday',
                'being too early to everything',
                'that one intersection everyone hates',
                "food that didn't taste as good as it looked",
                "the friends you made along the way (you didn't)",
            ],
        },
        'judging_criteria': [
            {
                'name': 'Mood & Atmosphere',
                'weight': 30,
                'description': 'Does it evoke the right feeling for the music?',
            },
            {'name': 'Visual Creativity', 'weight': 25, 'description': 'How creative and striking is the design?'},
            {'name': 'Genre Fit', 'weight': 25, 'description': 'Does it fit the musical genre?'},
            {'name': 'Album Cover Quality', 'weight': 20, 'description': 'Would this work as actual album art?'},
        ],
        'default_duration_minutes': 3,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'easy',
    },
    {
        'key': 'future_city',
        'name': 'Future City Vision',
        'description': 'Design cityscapes and urban environments of the future.',
        'category_slug': 'images-video',
        'templates': [
            'Design a city where {rule}',
            'What does {place} look like in a world where {condition}?',
            'Create a utopia designed entirely around {priority}',
        ],
        'variables': {
            'rule': [
                'rent is actually affordable but you have to fight a goose to get your mail',
                'public transit runs on compliments',
                "everyone's inner thoughts appear as weather",
                'the only currency is favors owed',
                'buildings are shaped by collective dreams',
                'traffic lights are replaced by very polite crossing guards',
                'all disputes are settled by rock paper scissors',
            ],
            'place': [
                'a suburb',
                'a downtown',
                'the DMV',
                'an airport',
                'a college campus',
                'a strip mall',
            ],
            'priority': [
                'avoiding awkward elevator conversations',
                'never running into your ex',
                'maximum napability',
                'never having to parallel park',
                'optimal people-watching angles',
                'making small talk physically impossible',
            ],
            'condition': [
                'everyone collectively decided to stop lying',
                'introverts designed everything',
                'dogs are in charge of urban planning',
                'your mom planned the zoning',
                'spite is the main motivator for architecture',
                'everything closes at a reasonable hour',
            ],
        },
        'judging_criteria': [
            {
                'name': 'World-Building',
                'weight': 30,
                'description': 'How believable and detailed is the future vision?',
            },
            {'name': 'Visual Impact', 'weight': 25, 'description': 'How striking is the cityscape?'},
            {'name': 'Creativity', 'weight': 25, 'description': 'How original are the ideas?'},
            {'name': 'Technical Execution', 'weight': 20, 'description': 'How well is it rendered?'},
        ],
        'default_duration_minutes': 4,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'medium',
    },
    {
        'key': 'food_photography',
        'name': 'Food Photography',
        'description': 'Create mouthwatering dishes and culinary presentations that look delicious.',
        'category_slug': 'images-video',
        'templates': [
            'Food photography of {dish} but {twist}',
            "Photograph {dish} as if it's {concept}",
            'Style {dish} for {occasion}',
        ],
        'variables': {
            'dish': [
                'instant ramen',
                'a sad desk lunch',
                'gas station sushi',
                'leftover pizza from last night',
                'a fancy charcuterie board made from convenience store snacks',
                'cereal in a wine glass',
                'questionable leftovers from the back of the fridge',
                'microwave dinner plated like fine dining',
            ],
            'twist': [
                "it's the most expensive meal at a 5-star restaurant",
                "it's evidence in a court case",
                'a food blogger is trying way too hard',
                "it costs $200 and you're at a trendy restaurant",
                'a celebrity chef is about to roast it',
                "it's an ad for a luxury brand",
                'someone is absolutely lying about how good it is',
            ],
            'concept': [
                'worth $500 at a trendy restaurant',
                'a Michelin 3-star dish',
                'the hero shot in a Super Bowl commercial',
                'featured in Bon Appétit magazine',
                "the last meal you'd request",
                'haute cuisine from a celebrity chef',
            ],
            'occasion': [
                "a first date you're trying to sabotage",
                "impressing your partner's parents (and failing)",
                'a photoshoot where the budget was $5',
                'a cookbook titled "Giving Up"',
                "an intervention that's also a dinner party",
            ],
        },
        'judging_criteria': [
            {'name': 'Appetizing Appeal', 'weight': 35, 'description': 'Does it make you hungry?'},
            {'name': 'Presentation', 'weight': 25, 'description': 'How beautiful is the plating and styling?'},
            {'name': 'Creativity', 'weight': 20, 'description': 'How unique and creative is the concept?'},
            {'name': 'Realism', 'weight': 20, 'description': 'Does it look like real, edible food?'},
        ],
        'default_duration_minutes': 3,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'easy',
    },
    {
        'key': 'pet_portraits',
        'name': 'Pet Portraits',
        'description': 'Create adorable, majestic, or hilarious pet photography and portraits.',
        'category_slug': 'images-video',
        'templates': [
            'Portrait of {pet} who just {action}',
            'Paint {pet} in the style of {style}, titled "{title}"',
            'Capture the exact moment {pet} {moment}',
        ],
        'variables': {
            'pet': [
                'a cat',
                'a golden retriever',
                'a very round hamster',
                'an anxious chihuahua',
                'a judgmental parrot',
                'a senior pug',
                'an overly confident corgi',
            ],
            'style': [
                'a Renaissance master, complete with dramatic lighting',
                'a Soviet propaganda poster',
                'a 90s yearbook photo',
                'a wanted poster from the Wild West',
                'a corporate headshot with too much confidence',
                'a baroque oil painting with a gilded frame',
                'an awkward family portrait from the 80s',
            ],
            'title': [
                'I Regret Nothing',
                'This Is My Couch Now',
                'Employee of the Month (Self-Nominated)',
                'The Treat Cometh',
                'I Heard a Can Open',
                'He Looks Sus',
            ],
            'action': [
                'knocked something off a table and feels no remorse',
                'heard a chip bag open from three rooms away',
                'saw their own reflection and chose violence',
                'realized the vet trip was a lie',
                'claimed the warm spot you just left on the couch',
                'pretended not to hear their name being called',
                'stole food and is being too obvious about it',
            ],
            'moment': [
                'realizes the car is going to the vet, not the park',
                'hears the word "walk" in casual conversation',
                'successfully guilt-trips their owner for food',
                'wakes up from a dream where they were running',
                'spots a squirrel through the window',
            ],
        },
        'judging_criteria': [
            {'name': 'Cuteness/Appeal', 'weight': 35, 'description': 'How adorable or appealing is the pet?'},
            {'name': 'Expression & Character', 'weight': 25, 'description': 'Does the pet have personality?'},
            {'name': 'Creativity', 'weight': 20, 'description': 'How creative is the concept?'},
            {'name': 'Technical Quality', 'weight': 20, 'description': 'Is it well-composed and realistic?'},
        ],
        'default_duration_minutes': 3,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'easy',
    },
    {
        'key': 'material_texture',
        'name': 'Material & Texture',
        'description': 'Create stunning material studies and impossible textures.',
        'category_slug': 'images-video',
        'templates': [
            'Create something impossible: a {object} made of {material} that glows with {lighting}',
            'Design an absurd collision between {material} and {material2} - make it weird',
            'What if {object} was secretly made of {material}? Show us the chaos',
            'Create a scene where {material} is melting into {material2} in the most satisfying way possible',
        ],
        'variables': {
            'object': [
                "grandma's favorite chair",
                'a suspicious vending machine',
                'your childhood teddy bear',
                'a very judgmental lamp',
                'the moon (yes, the actual moon)',
                'an overconfident sandwich',
                'a confused escalator',
            ],
            'lighting': [
                'radioactive glow',
                'disco ball chaos',
                'haunted flashlight energy',
                'microwave at 3am vibes',
                'that weird light from the fridge',
                'aggressive neon',
            ],
            'material': [
                'sentient bubblegum',
                'crystallized tears of joy',
                'forbidden Jell-O',
                'weaponized glitter',
                'suspiciously warm aluminum foil',
                'memory foam that actually remembers',
                'emotional support mercury',
                'organic static electricity',
            ],
            'material2': [
                'cosmic dust bunnies',
                'solidified WiFi signals',
                'vintage embarrassment',
                'concentrated chaos',
                'weaponized nostalgia',
                'aggressive sunshine',
                'fermented moonlight',
                'dehydrated sound waves',
            ],
        },
        'judging_criteria': [
            {'name': 'Material Quality', 'weight': 35, 'description': 'How realistic and detailed are the textures?'},
            {'name': 'Visual Impact', 'weight': 25, 'description': 'How visually striking is the result?'},
            {'name': 'Creativity', 'weight': 25, 'description': 'How original is the material concept?'},
            {'name': 'Technical Execution', 'weight': 15, 'description': 'How well are the textures rendered?'},
        ],
        'default_duration_minutes': 3,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'medium',
    },
    {
        'key': 'historical_accuracy',
        'name': 'Historical Accuracy',
        'description': 'Create scenes from history with a twist.',
        'category_slug': 'images-video',
        'templates': [
            'What if {era} had {modern_thing}? Show us the chaos',
            'Create a scene from {era} but everyone is {emotion} about it',
            'Reimagine {era} where {twist}',
            'A day in {era} where {absurdity} is completely normal',
        ],
        'variables': {
            'era': [
                'Ancient Rome',
                'Medieval times',
                'The Renaissance',
                'Victorian England',
                'The 1920s',
                'The 1980s',
            ],
            'twist': [
                'cats are in charge',
                'everyone communicates through memes',
                'formal wear is sweatpants',
                'the economy runs on compliments',
            ],
            'emotion': [
                'way too casual',
                'overdressed',
                'suspiciously enthusiastic',
                'extremely tired',
                'aggressively polite',
            ],
            'absurdity': [
                'consulting your emotional support goat',
                'professional napping',
                'mandatory dance breaks',
                'bringing your plant to work',
            ],
            'modern_thing': [
                'smartphones',
                'coffee culture',
                'influencers',
                'therapy speak',
                'work-from-home culture',
                'brunch',
            ],
        },
        'judging_criteria': [
            {'name': 'Historical Accuracy', 'weight': 35, 'description': 'Are period details correct?'},
            {'name': 'Atmosphere', 'weight': 25, 'description': 'Does it feel authentic to the era?'},
            {'name': 'Detail Richness', 'weight': 25, 'description': 'How detailed is the scene?'},
            {'name': 'Creativity', 'weight': 15, 'description': 'How creative is the interpretation?'},
        ],
        'default_duration_minutes': 4,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'hard',
    },
    {
        'key': 'action_freeze',
        'name': 'Action Freeze',
        'description': 'Capture the perfect moment of action frozen in time.',
        'category_slug': 'images-video',
        'templates': [
            'Freeze the exact moment when {moment}',
            'Capture the split-second of {subject} experiencing {emotion}',
            'High-speed photography of {action} - but make it {style}',
            'The moment right before {anticipation}',
        ],
        'variables': {
            'style': ['elegant', 'chaotic', 'dramatic', 'somehow graceful', 'artfully messy'],
            'action': [
                'a glitter explosion',
                'popping bubble wrap',
                'a perfectly caught frisbee',
                'confetti cannon chaos',
                "the world's best cannonball",
            ],
            'moment': [
                'a cat realizes it miscalculated a jump',
                'someone walks into a glass door',
                'a dog catches the treat mid-air',
                'the last piece of pizza is grabbed',
                'the WiFi finally connects',
                'someone steps on a Lego',
            ],
            'emotion': [
                'immediate regret',
                'pure joy',
                'chaotic triumph',
                'beautiful confusion',
                'dramatic realization',
            ],
            'subject': [
                'a surprised cat',
                'an overconfident seagull',
                'an ambitious squirrel',
                'a determined toddler',
                'an optimistic pigeon',
            ],
            'anticipation': [
                'the sneeze finally happens',
                'the toast pops up',
                'the mic drops',
                'the beat drops',
            ],
        },
        'judging_criteria': [
            {'name': 'Motion Capture', 'weight': 35, 'description': 'Is the movement convincingly frozen?'},
            {'name': 'Dynamic Energy', 'weight': 25, 'description': 'Does it feel energetic and alive?'},
            {'name': 'Technical Execution', 'weight': 25, 'description': 'Is the image sharp and well-composed?'},
            {'name': 'Creativity', 'weight': 15, 'description': 'How creative is the action captured?'},
        ],
        'default_duration_minutes': 3,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'medium',
    },
    {
        'key': 'lighting_master',
        'name': 'Lighting Master',
        'description': 'Create moody, cinematic scenes with creative lighting.',
        'category_slug': 'images-video',
        'templates': [
            'Create a scene lit only by {light_source} and vibes',
            "Capture {subject} in {lighting_type} like they're in a music video",
            'Design a room where the only light is {light_source} - make it aesthetic',
            'Portrait of {subject} lit by {light_source} during their {moment}',
        ],
        'variables': {
            'moment': [
                'third cup of coffee',
                'post-nap awakening',
                'epiphany about life choices',
                'deciding to order takeout again',
            ],
            'subject': [
                'a contemplative cat',
                'someone who just had a realization',
                'a very tired hero',
                'someone vibing alone',
                'a plant having its moment',
            ],
            'light_source': [
                'a single dramatic candle',
                'neon signs that say encouraging things',
                'fairy lights that have seen too much',
                'a very judgmental lamp',
                'the glow of a phone at 3am',
                'the fridge light during a midnight snack raid',
                'those weird lights in gas station bathrooms',
            ],
            'lighting_type': [
                'main character lighting',
                'villain origin story glow',
                'renaissance painting dramatic',
                'indie album cover moody',
                'coming-of-age movie sunset',
            ],
        },
        'judging_criteria': [
            {'name': 'Lighting Quality', 'weight': 40, 'description': 'Is the lighting well-executed?'},
            {'name': 'Mood Creation', 'weight': 25, 'description': 'Does lighting create the right mood?'},
            {'name': 'Technical Skill', 'weight': 20, 'description': 'Shows understanding of light?'},
            {'name': 'Creativity', 'weight': 15, 'description': 'How creative is the lighting choice?'},
        ],
        'default_duration_minutes': 3,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'medium',
    },
    {
        'key': 'street_style',
        'name': 'Street Style Fashion',
        'description': 'Create bold, stylish street fashion looks and outfits.',
        'category_slug': 'images-video',
        'templates': [
            'Style an outfit for someone who {lifestyle}',
            'Create a look that says "{statement}"',
            'Design streetwear for {persona} going to {event}',
            'Fashion a fit that captures {vibe} energy',
        ],
        'variables': {
            'vibe': [
                'cozy goblin',
                'caffeinated chaos',
                'aggressively comfortable',
                'accidentally matching your coffee order',
                'the friend with good music taste',
            ],
            'event': [
                'a casual gallery opening',
                'a first date at a bookstore',
                'accidentally becoming an influencer',
                'a job interview at a startup',
            ],
            'persona': [
                'your cool art teacher',
                'someone who actually reads the books on their shelf',
                'a friendly neighborhood cryptid',
                'a retired superhero',
                'someone who brings their own snacks to the movies',
            ],
            'lifestyle': [
                'just came from brunch and is going to a museum opening',
                'reads in coffee shops professionally',
                "has a podcast but won't tell you about it (they will)",
                'works from home but makes it fashion',
                'has a plant collection with names for each one',
            ],
            'statement': [
                'I woke up like this (lie)',
                "Yes, it's vintage (it's from Target)",
                "I'm running errands but make it editorial",
                'My outfit costs $20 but looks expensive',
                "I'm the main character today",
            ],
        },
        'judging_criteria': [
            {'name': 'Style & Trend', 'weight': 30, 'description': 'How fashionable and on-trend is it?'},
            {'name': 'Outfit Cohesion', 'weight': 25, 'description': 'Do the pieces work well together?'},
            {'name': 'Creativity', 'weight': 25, 'description': 'How unique and creative is the look?'},
            {'name': 'Wearability', 'weight': 20, 'description': 'Would someone actually wear this?'},
        ],
        'default_duration_minutes': 3,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'easy',
    },
    {
        'key': 'meme_generator',
        'name': 'Meme Generator',
        'description': 'Create hilarious, shareable meme images and reaction pics.',
        'category_slug': 'images-video',
        'templates': [
            'Create the meme that perfectly captures {feeling}',
            'Design {subject} reacting to {situation}',
            'Visualize the exact energy of {energy}',
            "Make a meme about {topic} that's painfully accurate",
        ],
        'variables': {
            'topic': [
                'checking your phone with no notifications, then checking again',
                'the audacity of morning people',
                "pretending to stretch when you're really just procrastinating",
                'the specific chaos of working from home',
                'that one friend who responds to texts three weeks later',
            ],
            'energy': [
                'replying "haha" to something that wasn\'t funny',
                'three hours into a project and realizing you did it wrong',
                'the confidence of typing without looking at the screen',
                'waving goodbye to someone walking the same direction as you',
                'saying "let\'s definitely hang out soon" to someone you\'ll never contact',
            ],
            'feeling': [
                'when the group chat goes silent after you sent something',
                'successfully avoiding someone you know at the store',
                'the Sunday evening dread before Monday',
                'when you rehearse an argument in the shower and win',
                "finding out there's a second page to the test",
                'the betrayal of sitting on a warm public toilet seat',
                "when your food arrives at a restaurant but it's for another table",
            ],
            'subject': [
                'a confused Renaissance painting person',
                'a cat who is both the problem and the victim',
                'a stock photo model who knows too much',
                'the last working brain cell',
                'your future self looking back at current you',
            ],
            'situation': [
                'being told "we need to talk" with no context',
                "your song coming on but you're about to leave",
                'the printer working on the first try',
                "finding money in a jacket you haven't worn in months",
                'realizing your camera was on the whole meeting',
            ],
        },
        'judging_criteria': [
            {'name': 'Humor', 'weight': 40, 'description': 'How funny is it?'},
            {'name': 'Relatability', 'weight': 25, 'description': 'Do people connect with it?'},
            {'name': 'Shareability', 'weight': 20, 'description': 'Would people share this?'},
            {'name': 'Creativity', 'weight': 15, 'description': 'How original is the concept?'},
        ],
        'default_duration_minutes': 2,
        'winner_points': 50,
        'participation_points': 10,
        'difficulty': 'easy',
    },
]


class Command(BaseCommand):
    help = 'Seed initial challenge types for Prompt Battles'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Clear existing challenge types before seeding',
        )

    def handle(self, *args, **options):
        if options['clear']:
            count = ChallengeType.objects.count()
            ChallengeType.objects.all().delete()
            self.stdout.write(self.style.WARNING(f'Deleted {count} existing challenge types'))

        created_count = 0
        updated_count = 0

        for data in CHALLENGE_TYPES:
            # Get category if specified
            category = None
            if data.get('category_slug'):
                try:
                    category = Taxonomy.objects.get(
                        slug=data['category_slug'], taxonomy_type='category', is_active=True
                    )
                except Taxonomy.DoesNotExist:
                    self.stdout.write(
                        self.style.WARNING(f"Category '{data['category_slug']}' not found for {data['key']}")
                    )

            challenge_type, created = ChallengeType.objects.update_or_create(
                key=data['key'],
                defaults={
                    'name': data['name'],
                    'description': data['description'],
                    'category': category,
                    'templates': data['templates'],
                    'variables': data['variables'],
                    'judging_criteria': data['judging_criteria'],
                    'default_duration_minutes': data.get('default_duration_minutes', 3),
                    'winner_points': data.get('winner_points', 50),
                    'participation_points': data.get('participation_points', 10),
                    'difficulty': data.get('difficulty', 'medium'),
                    'is_active': True,
                    'order': CHALLENGE_TYPES.index(data),
                },
            )

            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'Created: {challenge_type.name}'))
            else:
                updated_count += 1
                self.stdout.write(self.style.WARNING(f'Updated: {challenge_type.name}'))

        self.stdout.write('')
        self.stdout.write(self.style.SUCCESS(f'Done! Created: {created_count}, Updated: {updated_count}'))
        self.stdout.write(f'Total challenge types: {ChallengeType.objects.count()}')
