# Generated by Django 5.1.15 on 2026-01-04 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0033_add_sms_prompt_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUserSettings',
            fields=[
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='instagram_settings',
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'auto_import_enabled',
                    models.BooleanField(
                        default=False, help_text='Automatically import new Instagram posts as projects'
                    ),
                ),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful media sync', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error message if any')),
            ],
            options={
                'verbose_name': 'Instagram User Settings',
                'verbose_name_plural': 'Instagram User Settings',
            },
        ),
        migrations.CreateModel(
            name='InstagramMediaSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'instagram_media_id',
                    models.CharField(help_text='Unique Instagram media ID', max_length=100, unique=True),
                ),
                (
                    'imported_project_id',
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text='ID of Project created from this post (if imported)',
                        null=True,
                    ),
                ),
                (
                    'media_type',
                    models.CharField(
                        choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('CAROUSEL_ALBUM', 'Carousel Album')],
                        help_text='Type of Instagram media',
                        max_length=20,
                    ),
                ),
                (
                    'media_url',
                    models.URLField(help_text='Direct URL to media (expires after some time)', max_length=2000),
                ),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail URL for videos', max_length=2000)),
                ('permalink', models.URLField(help_text='Permanent Instagram URL', max_length=500)),
                ('caption', models.TextField(blank=True, help_text='Instagram post caption')),
                ('instagram_timestamp', models.DateTimeField(help_text='When the post was created on Instagram')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='When this record was last synced')),
                (
                    'auto_imported',
                    models.BooleanField(
                        default=False, help_text='Whether this was auto-imported (vs manual selection)'
                    ),
                ),
                (
                    'is_imported',
                    models.BooleanField(default=False, help_text='Whether this has been imported as a project'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User who owns this Instagram media',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='instagram_synced_media',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Instagram Media Sync',
                'verbose_name_plural': 'Instagram Media Syncs',
                'ordering': ['-instagram_timestamp'],
                'indexes': [
                    models.Index(fields=['user', 'synced_at'], name='instagram_i_user_id_73dca9_idx'),
                    models.Index(fields=['user', 'is_imported'], name='instagram_i_user_id_cb7642_idx'),
                    models.Index(fields=['instagram_media_id'], name='instagram_i_instagr_97545a_idx'),
                ],
            },
        ),
    ]
