# Generated by Django 5.1.15 on 2025-12-05 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', models.CharField(db_index=True, help_text='Recipient phone number', max_length=20)),
                (
                    'message_type',
                    models.CharField(
                        choices=[
                            ('battle_invitation', 'Battle Invitation'),
                            ('phone_verification', 'Phone Verification'),
                            ('other', 'Other'),
                        ],
                        db_index=True,
                        default='other',
                        max_length=30,
                    ),
                ),
                ('body', models.TextField(help_text='SMS message body')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('sent', 'Sent'),
                            ('delivered', 'Delivered'),
                            ('failed', 'Failed'),
                            ('undelivered', 'Undelivered'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('provider_sid', models.CharField(blank=True, help_text='Twilio message SID', max_length=100)),
                ('error_code', models.CharField(blank=True, help_text='Error code from provider', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details')),
                ('cost_cents', models.IntegerField(blank=True, help_text='Cost in USD cents', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                (
                    'related_object_type',
                    models.CharField(blank=True, help_text='Type of related object', max_length=50),
                ),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object', null=True)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who triggered this SMS',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sms_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['to_phone', '-created_at'], name='sms_smslog_to_phon_b0d53e_idx'),
                    models.Index(fields=['status', '-created_at'], name='sms_smslog_status_31d19e_idx'),
                    models.Index(fields=['message_type', '-created_at'], name='sms_smslog_message_0f26e6_idx'),
                ],
            },
        ),
    ]
