# Generated by Django 5.1.15 on 2026-01-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        # Rename field to preserve existing data
        migrations.RenameField(
            model_name='smslog',
            old_name='provider_sid',
            new_name='provider_message_id',
        ),
        # Update the help_text on the renamed field
        migrations.AlterField(
            model_name='smslog',
            name='provider_message_id',
            field=models.CharField(blank=True, help_text='Provider message ID', max_length=100),
        ),
        # Add new message types
        migrations.AlterField(
            model_name='smslog',
            name='message_type',
            field=models.CharField(
                choices=[
                    ('battle_invitation', 'Battle Invitation'),
                    ('battle_result', 'Battle Result'),
                    ('battle_reminder', 'Battle Reminder'),
                    ('streak_alert', 'Streak Alert'),
                    ('phone_verification', 'Phone Verification'),
                    ('other', 'Other'),
                ],
                db_index=True,
                default='other',
                max_length=30,
            ),
        ),
    ]
