# Generated by Django 5.0.14 on 2025-11-26 01:19

import uuid

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models

import core.referrals.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BattleInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message from the challenger')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('accepted', 'Accepted'),
                            ('declined', 'Declined'),
                            ('expired', 'Expired'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'responded_at',
                    models.DateTimeField(blank=True, help_text='When the invitation was responded to', null=True),
                ),
                (
                    'expires_at',
                    models.DateTimeField(
                        db_index=True, help_text='When the invitation expires (24 hours from creation)'
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(help_text='The prompt created by the user')),
                (
                    'submission_type',
                    models.CharField(
                        choices=[('text', 'Text Generation'), ('image', 'Image Generation')],
                        help_text='Type of submission (text or image prompt)',
                        max_length=20,
                    ),
                ),
                (
                    'generated_output_url',
                    models.URLField(blank=True, help_text='URL to the generated output (if applicable)', null=True),
                ),
                (
                    'generated_output_text',
                    models.TextField(blank=True, help_text='Generated text output (if text submission)'),
                ),
                ('score', models.FloatField(blank=True, help_text='AI-evaluated score (0-100)', null=True)),
                ('evaluation_feedback', models.TextField(blank=True, help_text='AI feedback on the prompt quality')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'evaluated_at',
                    models.DateTimeField(blank=True, help_text='When the submission was evaluated', null=True),
                ),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, db_index=True, help_text='Timestamp when object was soft deleted', null=True
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event')),
                ('start_date', models.DateTimeField(help_text='Event start date and time')),
                ('end_date', models.DateTimeField(help_text='Event end date and time')),
                (
                    'location',
                    models.CharField(blank=True, help_text='Event location (physical or virtual)', max_length=255),
                ),
                ('event_url', models.URLField(blank=True, help_text='URL for event registration or more info')),
                ('is_all_day', models.BooleanField(default=False, help_text='Whether this is an all-day event')),
                (
                    'color',
                    models.CharField(
                        default='#3b82f6',
                        help_text='Hex color code for calendar display (e.g., #3b82f6)',
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Color must be a valid hex code (e.g., #3b82f6)', regex='^#[0-9A-Fa-f]{6}$'
                            )
                        ],
                    ),
                ),
                (
                    'thumbnail',
                    models.URLField(
                        blank=True,
                        help_text='URL to event thumbnail image (must be https)',
                        validators=[django.core.validators.URLValidator(schemes=['https'])],
                    ),
                ),
                (
                    'timezone_name',
                    models.CharField(
                        default='UTC', help_text='Timezone for event (e.g., America/New_York, UTC)', max_length=63
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether event is visible to users')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'role',
                    models.CharField(
                        choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10
                    ),
                ),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('github_repo', 'GitHub Repository'),
                            ('image_collection', 'Image Collection'),
                            ('prompt', 'Prompt / Conversation'),
                            ('other', 'Other'),
                        ],
                        default='other',
                        max_length=32,
                    ),
                ),
                ('is_showcase', models.BooleanField(default=False, help_text='Display in showcase section')),
                (
                    'is_highlighted',
                    models.BooleanField(
                        db_index=True, default=False, help_text='Featured at top of profile (only one per user)'
                    ),
                ),
                (
                    'is_private',
                    models.BooleanField(default=False, help_text='Hidden from public, only visible to owner'),
                ),
                ('is_archived', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True, help_text='Whether project is publicly visible')),
                (
                    'published_at',
                    models.DateTimeField(blank=True, help_text='When project was first published', null=True),
                ),
                ('banner_url', models.CharField(blank=True, default='', help_text='Banner image URL', max_length=500)),
                (
                    'featured_image_url',
                    models.CharField(
                        blank=True, default='', help_text='Featured image for project cards', max_length=500
                    ),
                ),
                (
                    'external_url',
                    models.URLField(
                        blank=True,
                        default='',
                        help_text='External URL for this project (e.g., live demo, GitHub repo)',
                        max_length=500,
                    ),
                ),
                (
                    'user_tags',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text='User-generated tags (moderated for inappropriate content)',
                        size=None,
                    ),
                ),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content')),
                (
                    'moderation_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending Review'),
                            ('approved', 'Approved'),
                            ('rejected', 'Rejected'),
                            ('flagged', 'Flagged for Manual Review'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'moderation_reason',
                    models.TextField(blank=True, default='', help_text='Reason for moderation decision'),
                ),
                (
                    'moderation_data',
                    models.JSONField(blank=True, default=dict, help_text='Full moderation API response data'),
                ),
                (
                    'moderated_at',
                    models.DateTimeField(blank=True, help_text='When moderation was performed', null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_text', models.TextField(help_text='The AI-generated challenge prompt for this battle')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('active', 'Active'),
                            ('completed', 'Completed'),
                            ('expired', 'Expired'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='pending',
                        help_text='Current status of the battle',
                        max_length=20,
                    ),
                ),
                (
                    'battle_type',
                    models.CharField(
                        choices=[
                            ('text_prompt', 'Text Prompt Generation'),
                            ('image_prompt', 'Image Generation Prompt'),
                            ('mixed', 'Mixed Challenge'),
                        ],
                        default='text_prompt',
                        help_text='Type of prompt battle',
                        max_length=20,
                    ),
                ),
                (
                    'duration_minutes',
                    models.IntegerField(default=10, help_text='Duration of battle in minutes (default 10)'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'started_at',
                    models.DateTimeField(
                        blank=True, help_text='When the battle officially started (after acceptance)', null=True
                    ),
                ),
                (
                    'expires_at',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text='When the battle expires (started_at + duration)',
                        null=True,
                    ),
                ),
                (
                    'completed_at',
                    models.DateTimeField(blank=True, help_text='When the battle was completed', null=True),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                (
                    'slug',
                    models.SlugField(
                        blank=True, help_text='URL-friendly version of title', max_length=200, null=True, unique=True
                    ),
                ),
                ('description', models.TextField()),
                ('topic', models.CharField(max_length=100)),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')],
                        default='beginner',
                        max_length=20,
                    ),
                ),
                ('estimated_time', models.IntegerField(help_text='Estimated time in minutes')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'answers',
                    models.JSONField(
                        default=dict,
                        help_text='Store all answers with metadata: {question_id: {answer, correct, timeSpent}}',
                    ),
                ),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('true_false', 'True/False'),
                            ('multiple_choice', 'Multiple Choice'),
                            ('swipe', 'Swipe'),
                        ],
                        default='true_false',
                        max_length=20,
                    ),
                ),
                ('correct_answer', models.JSONField(help_text='String or list of strings for correct answer(s)')),
                ('options', models.JSONField(blank=True, help_text='Options for multiple choice questions', null=True)),
                ('explanation', models.TextField()),
                ('hint', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('completed', 'Completed'),
                            ('rewarded', 'Rewarded'),
                            ('cancelled', 'Cancelled'),
                        ],
                        default='pending',
                        help_text='Current status of the referral',
                        max_length=20,
                    ),
                ),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this referral')),
                (
                    'reward_data',
                    models.JSONField(blank=True, default=dict, help_text='Data about rewards given for this referral'),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'code',
                    models.CharField(
                        default=core.referrals.models.generate_referral_code,
                        help_text='Unique referral code (typically username)',
                        max_length=50,
                        unique=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uses_count', models.IntegerField(default=0, help_text='Number of times this code has been used')),
                (
                    'max_uses',
                    models.IntegerField(blank=True, help_text='Maximum number of uses (null = unlimited)', null=True),
                ),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code can be used')),
                (
                    'expires_at',
                    models.DateTimeField(
                        blank=True, help_text='When this code expires (null = never expires)', null=True
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'provider',
                    models.CharField(
                        choices=[
                            ('github', 'GitHub'),
                            ('gitlab', 'GitLab'),
                            ('linkedin', 'LinkedIn'),
                            ('figma', 'Figma'),
                            ('huggingface', 'Hugging Face'),
                            ('midjourney', 'Midjourney'),
                        ],
                        help_text='OAuth provider name',
                        max_length=20,
                    ),
                ),
                ('provider_user_id', models.CharField(help_text='Unique user ID from the provider', max_length=255)),
                (
                    'provider_username',
                    models.CharField(blank=True, help_text='Username on the provider platform', max_length=255),
                ),
                (
                    'provider_email',
                    models.EmailField(
                        blank=True, help_text='Email from provider (if available)', max_length=254, null=True
                    ),
                ),
                ('access_token_encrypted', models.BinaryField(help_text='Encrypted OAuth access token')),
                (
                    'refresh_token_encrypted',
                    models.BinaryField(blank=True, help_text='Encrypted OAuth refresh token', null=True),
                ),
                (
                    'token_expires_at',
                    models.DateTimeField(blank=True, help_text='When the access token expires', null=True),
                ),
                ('scopes', models.TextField(blank=True, help_text='Comma-separated list of granted OAuth scopes')),
                ('profile_url', models.URLField(blank=True, help_text='Link to user profile on provider')),
                ('avatar_url', models.URLField(blank=True, help_text='Profile picture from provider')),
                (
                    'extra_data',
                    models.JSONField(blank=True, default=dict, help_text='Additional provider-specific data'),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, help_text='Whether this connection is currently active'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'taxonomy_type',
                    models.CharField(
                        choices=[('tool', 'Tool'), ('category', 'Category')],
                        db_index=True,
                        default='tool',
                        max_length=10,
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                (
                    'is_active',
                    models.BooleanField(default=True, help_text='Whether this taxonomy is available for selection'),
                ),
                (
                    'color',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text="Display color for topics (e.g., 'blue', 'teal')",
                        max_length=50,
                    ),
                ),
                ('website_url', models.URLField(blank=True, help_text='Official website URL', null=True)),
                ('logo_url', models.URLField(blank=True, help_text='Logo image URL', null=True)),
                (
                    'usage_tips',
                    models.JSONField(blank=True, default=list, help_text='List of usage tips/bullet points'),
                ),
                (
                    'best_for',
                    models.JSONField(blank=True, default=list, help_text='List of use cases when this tool is best'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Taxonomies',
                'ordering': ['taxonomy_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                (
                    'tagline',
                    models.CharField(
                        help_text="Short tagline (e.g., 'AI-powered conversational assistant')", max_length=300
                    ),
                ),
                ('description', models.TextField(help_text='Detailed description of what the tool does')),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('chat', 'Chat & Conversational AI'),
                            ('code', 'Code & Development'),
                            ('image', 'Image Generation'),
                            ('video', 'Video Generation & Editing'),
                            ('audio', 'Audio & Music'),
                            ('writing', 'Writing & Content'),
                            ('research', 'Research & Search'),
                            ('productivity', 'Productivity & Workflow'),
                            ('data', 'Data & Analytics'),
                            ('design', 'Design & Creative'),
                            ('other', 'Other'),
                        ],
                        db_index=True,
                        default='other',
                        max_length=20,
                    ),
                ),
                (
                    'tags',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for filtering (e.g., ['NLP', 'GPT', 'OpenAI'])",
                    ),
                ),
                ('logo_url', models.URLField(blank=True, help_text='Primary logo (square)')),
                ('banner_url', models.URLField(blank=True, help_text='Wide banner/hero image')),
                (
                    'screenshot_urls',
                    models.JSONField(
                        blank=True, default=list, help_text='List of screenshot URLs to showcase the tool'
                    ),
                ),
                ('demo_video_url', models.URLField(blank=True, help_text='Demo or promotional video')),
                ('website_url', models.URLField(help_text='Official website URL')),
                ('documentation_url', models.URLField(blank=True)),
                ('pricing_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('discord_url', models.URLField(blank=True)),
                (
                    'pricing_model',
                    models.CharField(
                        choices=[
                            ('free', 'Free'),
                            ('freemium', 'Freemium'),
                            ('subscription', 'Subscription'),
                            ('pay_per_use', 'Pay Per Use'),
                            ('enterprise', 'Enterprise Only'),
                            ('open_source', 'Open Source'),
                        ],
                        default='freemium',
                        max_length=20,
                    ),
                ),
                (
                    'starting_price',
                    models.CharField(
                        blank=True, help_text="E.g., '$20/month', 'Free', '$0.002/1K tokens'", max_length=100
                    ),
                ),
                ('has_free_tier', models.BooleanField(default=False)),
                ('requires_api_key', models.BooleanField(default=False)),
                ('requires_waitlist', models.BooleanField(default=False)),
                (
                    'overview',
                    models.TextField(blank=True, help_text='Long-form overview/introduction (supports Markdown)'),
                ),
                (
                    'key_features',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of key features with descriptions [{title: '', description: ''}]",
                    ),
                ),
                (
                    'use_cases',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Specific use cases with examples [{title: '', description: '', example: ''}]",
                    ),
                ),
                (
                    'usage_tips',
                    models.JSONField(
                        blank=True, default=list, help_text='Practical tips for using the tool effectively'
                    ),
                ),
                (
                    'best_practices',
                    models.JSONField(blank=True, default=list, help_text='Best practices and recommendations'),
                ),
                (
                    'limitations',
                    models.JSONField(blank=True, default=list, help_text='Known limitations or considerations'),
                ),
                (
                    'alternatives',
                    models.JSONField(blank=True, default=list, help_text='List of alternative tool slugs'),
                ),
                (
                    'whats_new',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Recent updates and what's new [{date: '2025-01-15', title: '', description: ''}]",
                    ),
                ),
                (
                    'model_info',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical model information (e.g., {'model': 'GPT-4', 'provider': 'OpenAI'})",
                    ),
                ),
                (
                    'integrations',
                    models.JSONField(blank=True, default=list, help_text='List of integrations/platforms supported'),
                ),
                ('api_available', models.BooleanField(default=False)),
                (
                    'languages_supported',
                    models.JSONField(blank=True, default=list, help_text='Programming/natural languages supported'),
                ),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='SEO keywords')),
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True, default=True, help_text='Whether this tool is visible in the directory'
                    ),
                ),
                (
                    'is_featured',
                    models.BooleanField(db_index=True, default=False, help_text='Featured tools appear at the top'),
                ),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by team (shows badge)')),
                ('view_count', models.IntegerField(default=0)),
                (
                    'popularity_score',
                    models.FloatField(default=0.0, help_text='Calculated popularity score for ranking'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_featured', '-popularity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ToolBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about the tool')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'rating',
                    models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1-5 star rating'),
                ),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('pros', models.JSONField(blank=True, default=list, help_text='List of pros')),
                ('cons', models.JSONField(blank=True, default=list, help_text='List of cons')),
                ('use_case', models.CharField(blank=True, help_text='What they used it for', max_length=200)),
                ('is_verified_user', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('login', 'Login'),
                            ('logout', 'Logout'),
                            ('profile_update', 'Profile Update'),
                            ('password_change', 'Password Change'),
                            ('email_change', 'Email Change'),
                            ('role_change', 'Role Change'),
                            ('failed_login', 'Failed Login'),
                            ('account_locked', 'Account Locked'),
                            ('oauth_login', 'OAuth Login'),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Audit Log',
                'verbose_name_plural': 'User Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'interaction_type',
                    models.CharField(
                        choices=[
                            ('project_view', 'Viewed Project'),
                            ('project_create', 'Created Project'),
                            ('conversation', 'Had Conversation'),
                            ('search', 'Searched'),
                            ('content_view', 'Viewed Content'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional context about the interaction (e.g., project_id, search_query, content_type)',
                    ),
                ),
                (
                    'extracted_keywords',
                    models.JSONField(blank=True, default=list, help_text='Keywords extracted from this interaction'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name (can be custom or from taxonomy)', max_length=100)),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('manual', 'Manually Selected'),
                            ('auto_project', 'Auto-generated from Projects'),
                            ('auto_conversation', 'Auto-generated from Conversations'),
                            ('auto_activity', 'Auto-generated from Activity'),
                        ],
                        default='manual',
                        max_length=20,
                    ),
                ),
                (
                    'confidence_score',
                    models.FloatField(default=1.0, help_text='Confidence score for auto-generated tags (0.0-1.0)'),
                ),
                (
                    'interaction_count',
                    models.IntegerField(default=0, help_text='Number of interactions that generated this tag'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-confidence_score', '-interaction_count', 'name'],
            },
        ),
    ]
