# Generated by Django 5.0.14 on 2025-11-26 01:19

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='battleinvitation',
            name='recipient',
            field=models.ForeignKey(
                help_text='User who received the invitation',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='battle_invitations_received',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='battleinvitation',
            name='sender',
            field=models.ForeignKey(
                help_text='User who sent the invitation',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='battle_invitations_sent',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='battlesubmission',
            name='user',
            field=models.ForeignKey(
                help_text='User who made this submission',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='battle_submissions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='conversations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(
                help_text='Admin user who created this event',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_events',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(
                help_text='Last admin user who updated this event',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='updated_events',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.project'
            ),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='project_comments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.projectcomment'
            ),
        ),
        migrations.AddField(
            model_name='projectlike',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.project'
            ),
        ),
        migrations.AddField(
            model_name='projectlike',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='project_likes', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='challenger',
            field=models.ForeignKey(
                help_text='User who initiated the battle',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='battles_initiated',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='opponent',
            field=models.ForeignKey(
                help_text='User who was challenged',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='battles_received',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='winner',
            field=models.ForeignKey(
                blank=True,
                help_text='Winner of the battle (determined by AI scoring)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='battles_won',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='battlesubmission',
            name='battle',
            field=models.ForeignKey(
                help_text='The battle this submission belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='submissions',
                to='core.promptbattle',
            ),
        ),
        migrations.AddField(
            model_name='battleinvitation',
            name='battle',
            field=models.OneToOneField(
                help_text='The battle associated with this invitation',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invitation',
                to='core.promptbattle',
            ),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.quiz'
            ),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz'
            ),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_user',
            field=models.OneToOneField(
                blank=True,
                help_text='User who was referred',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='referred_by',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(
                help_text='User who made the referral',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='referrals_made',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='user',
            field=models.OneToOneField(
                help_text='User who owns this referral code',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='referral_code',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_code',
            field=models.ForeignKey(
                help_text='The referral code that was used',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='referrals',
                to='core.referralcode',
            ),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='social_connections',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='taxonomy',
            index=models.Index(fields=['taxonomy_type', 'is_active'], name='core_taxono_taxonom_60030a_idx'),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(
                blank=True,
                help_text='Categories that organize this project (from predefined Taxonomy)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'category'},
                related_name='projects',
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='tool',
            name='taxonomy',
            field=models.OneToOneField(
                blank=True,
                help_text='Link to taxonomy entry for user personalization/tagging',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tool_entity',
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(
                blank=True, help_text='Tools/technologies used in this project', related_name='projects', to='core.tool'
            ),
        ),
        migrations.AddField(
            model_name='toolbookmark',
            name='tool',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='core.tool'
            ),
        ),
        migrations.AddField(
            model_name='toolbookmark',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='tool_bookmarks', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='toolcomparison',
            name='tools',
            field=models.ManyToManyField(related_name='comparisons', to='core.tool'),
        ),
        migrations.AddField(
            model_name='toolcomparison',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tool_comparisons',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='toolreview',
            name='tool',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.tool'
            ),
        ),
        migrations.AddField(
            model_name='toolreview',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='tool_reviews', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='userauditlog',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='usertag',
            name='taxonomy',
            field=models.ForeignKey(
                blank=True,
                help_text='Link to taxonomy if this is a taxonomy-based tag',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='usertag',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='core_conver_user_id_3e2a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-created_at'], name='core_conver_user_id_d88fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at', 'deleted_at'], name='core_conver_updated_72bec7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'end_date'], name='core_event_start_d_05b9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published'], name='core_event_is_publ_c1332f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='core_messag_convers_d2b392_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'role'], name='core_messag_convers_8de701_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(
                fields=['project', 'moderation_status', '-created_at'], name='core_projec_project_04720c_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['user', '-created_at'], name='core_projec_user_id_c5dc5c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['moderation_status', '-created_at'], name='core_projec_moderat_d4c895_idx'),
        ),
        migrations.AddIndex(
            model_name='commentvote',
            index=models.Index(fields=['comment', 'vote_type'], name='core_commen_comment_a7da45_idx'),
        ),
        migrations.AddIndex(
            model_name='commentvote',
            index=models.Index(fields=['user', '-created_at'], name='core_commen_user_id_7da9cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_comment_vote_per_user'),
        ),
        migrations.AddIndex(
            model_name='projectlike',
            index=models.Index(fields=['project', '-created_at'], name='core_projec_project_d7711f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectlike',
            index=models.Index(fields=['user', '-created_at'], name='core_projec_user_id_e9795b_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectlike',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_project_like_per_user'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['challenger', '-created_at'], name='core_prompt_challen_803316_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['opponent', '-created_at'], name='core_prompt_opponen_d60241_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['status', '-created_at'], name='core_prompt_status_e060b7_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['expires_at'], name='core_prompt_expires_faab10_idx'),
        ),
        migrations.AddIndex(
            model_name='battlesubmission',
            index=models.Index(fields=['battle', 'user'], name='core_battle_battle__9c153a_idx'),
        ),
        migrations.AddIndex(
            model_name='battlesubmission',
            index=models.Index(fields=['user', '-submitted_at'], name='core_battle_user_id_ad63b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='battlesubmission',
            unique_together={('battle', 'user')},
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['recipient', 'status', '-created_at'], name='core_battle_recipie_b6c75a_idx'),
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['sender', '-created_at'], name='core_battle_sender__68f92f_idx'),
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['expires_at'], name='core_battle_expires_8e6706_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['slug'], name='core_quiz_slug_55043c_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['topic', 'difficulty'], name='core_quiz_topic_1f44c9_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_published', '-created_at'], name='core_quiz_is_publ_4a81cf_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-started_at'], name='core_quizat_user_id_41beaa_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', '-started_at'], name='core_quizat_quiz_id_5f5662_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'order')},
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='core_referr_code_bb15e0_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['user', 'is_active'], name='core_referr_user_id_4ba43e_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status'], name='core_referr_referre_c8a5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred_user'], name='core_referr_referre_6bec10_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code', '-created_at'], name='core_referr_referra_eceeee_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconnection',
            index=models.Index(fields=['user', 'provider'], name='core_social_user_id_42d9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconnection',
            index=models.Index(fields=['provider', 'provider_user_id'], name='core_social_provide_5164bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialconnection',
            unique_together={('user', 'provider')},
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['category', 'is_active'], name='core_tool_categor_3a9a83_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_active', '-popularity_score'], name='core_tool_is_acti_b73cab_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_active', '-created_at'], name='core_tool_is_acti_5aaad5_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_featured', 'is_active'], name='core_tool_is_feat_f7c426_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='tool_tags_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='tool_keywords_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'slug'], name='core_projec_user_id_425284_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['is_showcase', 'is_archived', '-created_at'], name='core_projec_is_show_36089d_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-created_at'], name='core_projec_user_id_178de8_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', '-published_at'], name='core_projec_is_publ_a4ac4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_project_slug_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='toolbookmark',
            unique_together={('user', 'tool')},
        ),
        migrations.AddIndex(
            model_name='toolreview',
            index=models.Index(fields=['tool', '-created_at'], name='core_toolre_tool_id_d75f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='toolreview',
            index=models.Index(fields=['tool', '-helpful_count'], name='core_toolre_tool_id_4d746a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='toolreview',
            unique_together={('tool', 'user')},
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='core_userau_user_id_e53bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='core_userau_action_23bd21_idx'),
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['ip_address', '-timestamp'], name='core_userau_ip_addr_fd6952_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', '-created_at'], name='core_userin_user_id_5676cc_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['interaction_type', '-created_at'], name='core_userin_interac_d4c0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='usertag',
            index=models.Index(fields=['user', 'source'], name='core_userta_user_id_83269c_idx'),
        ),
        migrations.AddIndex(
            model_name='usertag',
            index=models.Index(fields=['user', '-confidence_score'], name='core_userta_user_id_11b454_idx'),
        ),
        migrations.AddConstraint(
            model_name='usertag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_tag'),
        ),
    ]
