# Generated by Django 5.0.14 on 2025-11-26 02:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_tags',
        ),
        migrations.AddField(
            model_name='project',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text='User-generated topics (moderated for inappropriate content)',
                size=None,
            ),
        ),
    ]
