# Generated by Django 5.0.14 on 2025-11-16 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_email_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("profile_update", "Profile Update"),
                            ("password_change", "Password Change"),
                            ("email_change", "Email Change"),
                            ("role_change", "Role Change"),
                            ("failed_login", "Failed Login"),
                            ("account_locked", "Account Locked"),
                            ("oauth_login", "OAuth Login"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "User Audit Log",
                "verbose_name_plural": "User Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["user", "slug"], name="core_projec_user_id_425284_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_showcase", "is_archived", "-created_at"], name="core_projec_is_show_36089d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["user", "-created_at"], name="core_projec_user_id_178de8_idx"),
        ),
        migrations.AddField(
            model_name="userauditlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="userauditlog",
            index=models.Index(fields=["user", "-timestamp"], name="core_userau_user_id_e53bc6_idx"),
        ),
        migrations.AddIndex(
            model_name="userauditlog",
            index=models.Index(fields=["action", "-timestamp"], name="core_userau_action_23bd21_idx"),
        ),
        migrations.AddIndex(
            model_name="userauditlog",
            index=models.Index(fields=["ip_address", "-timestamp"], name="core_userau_ip_addr_fd6952_idx"),
        ),
    ]
