# Generated by Django 5.0.14 on 2025-11-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_rename_user_tags_to_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_showcase',
            field=models.BooleanField(default=True, help_text='Display in showcase section'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(
                choices=[
                    ('github_repo', 'GitHub Repository'),
                    ('figma_design', 'Figma Design'),
                    ('image_collection', 'Image Collection'),
                    ('prompt', 'Prompt / Conversation'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=32,
            ),
        ),
    ]
