# Generated by Django 5.0.14 on 2025-11-27 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_change_is_showcase_default_to_true'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'external_url'], name='core_projec_user_id_c3663c_idx'),
        ),
    ]
