# Generated by Django 5.0.14 on 2025-11-27 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_project_core_projec_user_id_c3663c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('external_url__isnull', False),
                    models.Q(('external_url', ''), _negated=True),
                ),
                fields=('user', 'external_url'),
                name='unique_external_url_per_user',
            ),
        ),
    ]
