# Generated by Django 5.0.14 on 2025-11-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_quiz_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['slug'], name='core_quiz_slug_55043c_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['topic', 'difficulty'], name='core_quiz_topic_1f44c9_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_published', '-created_at'], name='core_quiz_is_publ_4a81cf_idx'),
        ),
    ]
