# Generated by Django 5.0.14 on 2025-11-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_taxonomy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=120, unique=True),
        ),
    ]
