# Generated by Django 5.0.14 on 2025-11-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add performance indexes for integration imports.

    These indexes significantly improve query performance for:
    - Duplicate project detection (user + external_url)
    - Project type filtering (user + type)
    """

    dependencies = [
        ('core', '0008_alter_taxonomy_slug'),
    ]

    operations = [
        # Index for duplicate check: check_duplicate_project(user, url)
        # Used by: core.integrations.utils.check_duplicate_project()
        # Query: Project.objects.filter(user=user, external_url=url).first()
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['user', 'external_url'],
                name='project_user_url_idx',
            ),
        ),
        # Index for filtering by project type
        # Used by: Various queries filtering by user and type
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['user', 'type'],
                name='project_user_type_idx',
            ),
        ),
        # Index for published projects (for explore page)
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['is_published', 'created_at'],
                name='project_published_created_idx',
            ),
        ),
    ]
