# Generated by Django 5.0.14 on 2025-11-19 15:32

import core.referral_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_role_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.referral_models.generate_referral_code, help_text='Unique referral code', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uses_count', models.IntegerField(default=0, help_text='Number of times this code has been used')),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of uses (null = unlimited)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code can be used')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this code expires (null = never expires)', null=True)),
                ('user', models.OneToOneField(help_text='User who owns this referral code', on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rewarded', 'Rewarded'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the referral', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this referral')),
                ('reward_data', models.JSONField(blank=True, default=dict, help_text='Data about rewards given for this referral')),
                ('referred_user', models.OneToOneField(blank=True, help_text='User who was referred', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='User who made the referral', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(help_text='The referral code that was used', on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.referralcode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('linkedin', 'LinkedIn'), ('figma', 'Figma'), ('huggingface', 'Hugging Face'), ('midjourney', 'Midjourney')], help_text='OAuth provider name', max_length=20)),
                ('provider_user_id', models.CharField(help_text='Unique user ID from the provider', max_length=255)),
                ('provider_username', models.CharField(blank=True, help_text='Username on the provider platform', max_length=255)),
                ('provider_email', models.EmailField(blank=True, help_text='Email from provider (if available)', max_length=254, null=True)),
                ('access_token_encrypted', models.BinaryField(help_text='Encrypted OAuth access token')),
                ('refresh_token_encrypted', models.BinaryField(blank=True, help_text='Encrypted OAuth refresh token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('scopes', models.TextField(blank=True, help_text='Comma-separated list of granted OAuth scopes')),
                ('profile_url', models.URLField(blank=True, help_text='Link to user profile on provider')),
                ('avatar_url', models.URLField(blank=True, help_text='Profile picture from provider')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific data')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this connection is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='core_referr_code_bb15e0_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['user', 'is_active'], name='core_referr_user_id_4ba43e_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status'], name='core_referr_referre_c8a5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred_user'], name='core_referr_referre_6bec10_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code', '-created_at'], name='core_referr_referra_eceeee_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconnection',
            index=models.Index(fields=['user', 'provider'], name='core_social_user_id_42d9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconnection',
            index=models.Index(fields=['provider', 'provider_user_id'], name='core_social_provide_5164bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialconnection',
            unique_together={('user', 'provider')},
        ),
    ]
