# Generated by Django 5.0.14 on 2025-11-28 07:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_add_project_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='project_user_url_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_user_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_published_created_idx',
        ),
        migrations.AddField(
            model_name='quiz',
            name='categories',
            field=models.ManyToManyField(
                blank=True,
                help_text='Categories that organize this quiz (from predefined Taxonomy)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'category'},
                related_name='quizzes',
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text='Topic tags for this quiz',
                size=None,
            ),
        ),
    ]
