# Generated by Django 5.0.14 on 2025-11-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_remove_project_project_user_url_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='tools',
            field=models.ManyToManyField(
                blank=True,
                help_text='AI tools/technologies covered in this quiz',
                related_name='quizzes',
                to='core.tool',
            ),
        ),
    ]
