# Generated by Django 5.0.14 on 2025-11-19 15:51

from django.db import migrations, models

import core.referrals.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_referralcode_referral_socialconnection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralcode",
            name="code",
            field=models.CharField(
                default=core.referrals.models.generate_referral_code,
                help_text="Unique referral code (typically username)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
