# Generated by Django 5.0.14 on 2025-11-19 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_change_referral_code_to_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("interest", "Interest"),
                            ("skill", "Skill"),
                            ("goal", "Goal"),
                            ("topic", "Topic"),
                            ("industry", "Industry"),
                        ],
                        default="interest",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this taxonomy is available for selection"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Taxonomies",
                "ordering": ["category", "name"],
                "indexes": [models.Index(fields=["category", "is_active"], name="core_taxono_categor_b1ae1f_idx")],
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("project_view", "Viewed Project"),
                            ("project_create", "Created Project"),
                            ("conversation", "Had Conversation"),
                            ("search", "Searched"),
                            ("content_view", "Viewed Content"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the interaction (e.g., project_id, search_query, content_type)",
                    ),
                ),
                (
                    "extracted_keywords",
                    models.JSONField(blank=True, default=list, help_text="Keywords extracted from this interaction"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="core_userin_user_id_5676cc_idx"),
                    models.Index(fields=["interaction_type", "-created_at"], name="core_userin_interac_d4c0b5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Tag name (can be custom or from taxonomy)", max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manually Selected"),
                            ("auto_project", "Auto-generated from Projects"),
                            ("auto_conversation", "Auto-generated from Conversations"),
                            ("auto_activity", "Auto-generated from Activity"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=1.0, help_text="Confidence score for auto-generated tags (0.0-1.0)"),
                ),
                (
                    "interaction_count",
                    models.IntegerField(default=0, help_text="Number of interactions that generated this tag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "taxonomy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to taxonomy if this is a taxonomy-based tag",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.taxonomy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tags", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score", "-interaction_count", "name"],
                "indexes": [
                    models.Index(fields=["user", "source"], name="core_userta_user_id_83269c_idx"),
                    models.Index(fields=["user", "-confidence_score"], name="core_userta_user_id_11b454_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="usertag",
            constraint=models.UniqueConstraint(fields=("user", "name"), name="unique_user_tag"),
        ),
    ]
