# Generated by Django 5.0.14 on 2025-11-28 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_quiz_tools'),
        ('integrations', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content_source',
            field=models.ForeignKey(
                blank=True,
                help_text='Content source that created this project (if auto-synced)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects',
                to='integrations.contentsource',
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(
                choices=[
                    ('github_repo', 'GitHub Repository'),
                    ('figma_design', 'Figma Design'),
                    ('image_collection', 'Image Collection'),
                    ('prompt', 'Prompt / Conversation'),
                    ('video', 'Video'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=32,
            ),
        ),
    ]
