# Generated by Django 5.0.14 on 2025-11-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_project_content_source_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialconnection',
            name='provider',
            field=models.CharField(
                choices=[
                    ('google', 'Google'),
                    ('github', 'GitHub'),
                    ('gitlab', 'GitLab'),
                    ('linkedin', 'LinkedIn'),
                    ('figma', 'Figma'),
                    ('huggingface', 'Hugging Face'),
                    ('midjourney', 'Midjourney'),
                ],
                help_text='OAuth provider name',
                max_length=20,
            ),
        ),
    ]
