# Generated by Django 5.0.14 on 2025-11-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_alter_socialconnection_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(
                choices=[
                    ('github_repo', 'GitHub Repository'),
                    ('figma_design', 'Figma Design'),
                    ('image_collection', 'Image Collection'),
                    ('prompt', 'Prompt / Conversation'),
                    ('video', 'Video'),
                    ('reddit_thread', 'Reddit Thread'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=32,
            ),
        ),
    ]
