# Generated by Django 5.0.14 on 2025-11-19 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_taxonomy_best_for_taxonomy_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL', null=True),
        ),
        migrations.CreateModel(
            name='PromptBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_text', models.TextField(help_text='The AI-generated challenge prompt for this battle')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('active', 'Active'),
                            ('completed', 'Completed'),
                            ('expired', 'Expired'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='pending',
                        help_text='Current status of the battle',
                        max_length=20,
                    ),
                ),
                (
                    'battle_type',
                    models.CharField(
                        choices=[
                            ('text_prompt', 'Text Prompt Generation'),
                            ('image_prompt', 'Image Generation Prompt'),
                            ('mixed', 'Mixed Challenge'),
                        ],
                        default='text_prompt',
                        help_text='Type of prompt battle',
                        max_length=20,
                    ),
                ),
                (
                    'duration_minutes',
                    models.IntegerField(default=10, help_text='Duration of battle in minutes (default 10)'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'started_at',
                    models.DateTimeField(
                        blank=True, help_text='When the battle officially started (after acceptance)', null=True
                    ),
                ),
                (
                    'expires_at',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text='When the battle expires (started_at + duration)',
                        null=True,
                    ),
                ),
                (
                    'completed_at',
                    models.DateTimeField(blank=True, help_text='When the battle was completed', null=True),
                ),
                (
                    'challenger',
                    models.ForeignKey(
                        help_text='User who initiated the battle',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='battles_initiated',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'opponent',
                    models.ForeignKey(
                        help_text='User who was challenged',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='battles_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'winner',
                    models.ForeignKey(
                        blank=True,
                        help_text='Winner of the battle (determined by AI scoring)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='battles_won',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(help_text='The prompt created by the user')),
                (
                    'submission_type',
                    models.CharField(
                        choices=[('text', 'Text Generation'), ('image', 'Image Generation')],
                        help_text='Type of submission (text or image prompt)',
                        max_length=20,
                    ),
                ),
                (
                    'generated_output_url',
                    models.URLField(blank=True, help_text='URL to the generated output (if applicable)', null=True),
                ),
                (
                    'generated_output_text',
                    models.TextField(blank=True, help_text='Generated text output (if text submission)'),
                ),
                ('score', models.FloatField(blank=True, help_text='AI-evaluated score (0-100)', null=True)),
                ('evaluation_feedback', models.TextField(blank=True, help_text='AI feedback on the prompt quality')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'evaluated_at',
                    models.DateTimeField(blank=True, help_text='When the submission was evaluated', null=True),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User who made this submission',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='battle_submissions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'battle',
                    models.ForeignKey(
                        help_text='The battle this submission belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='submissions',
                        to='core.promptbattle',
                    ),
                ),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message from the challenger')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('accepted', 'Accepted'),
                            ('declined', 'Declined'),
                            ('expired', 'Expired'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'responded_at',
                    models.DateTimeField(blank=True, help_text='When the invitation was responded to', null=True),
                ),
                (
                    'expires_at',
                    models.DateTimeField(
                        db_index=True, help_text='When the invitation expires (24 hours from creation)'
                    ),
                ),
                (
                    'recipient',
                    models.ForeignKey(
                        help_text='User who received the invitation',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='battle_invitations_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'sender',
                    models.ForeignKey(
                        help_text='User who sent the invitation',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='battle_invitations_sent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'battle',
                    models.OneToOneField(
                        help_text='The battle associated with this invitation',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invitation',
                        to='core.promptbattle',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                (
                    'tagline',
                    models.CharField(
                        help_text="Short tagline (e.g., 'AI-powered conversational assistant')", max_length=300
                    ),
                ),
                ('description', models.TextField(help_text='Detailed description of what the tool does')),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('chat', 'Chat & Conversational AI'),
                            ('code', 'Code & Development'),
                            ('image', 'Image Generation'),
                            ('video', 'Video Generation & Editing'),
                            ('audio', 'Audio & Music'),
                            ('writing', 'Writing & Content'),
                            ('research', 'Research & Search'),
                            ('productivity', 'Productivity & Workflow'),
                            ('data', 'Data & Analytics'),
                            ('design', 'Design & Creative'),
                            ('other', 'Other'),
                        ],
                        db_index=True,
                        default='other',
                        max_length=20,
                    ),
                ),
                (
                    'tags',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for filtering (e.g., ['NLP', 'GPT', 'OpenAI'])",
                    ),
                ),
                ('logo_url', models.URLField(blank=True, help_text='Primary logo (square)')),
                ('banner_url', models.URLField(blank=True, help_text='Wide banner/hero image')),
                (
                    'screenshot_urls',
                    models.JSONField(
                        blank=True, default=list, help_text='List of screenshot URLs to showcase the tool'
                    ),
                ),
                ('demo_video_url', models.URLField(blank=True, help_text='Demo or promotional video')),
                ('website_url', models.URLField(help_text='Official website URL')),
                ('documentation_url', models.URLField(blank=True)),
                ('pricing_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('discord_url', models.URLField(blank=True)),
                (
                    'pricing_model',
                    models.CharField(
                        choices=[
                            ('free', 'Free'),
                            ('freemium', 'Freemium'),
                            ('subscription', 'Subscription'),
                            ('pay_per_use', 'Pay Per Use'),
                            ('enterprise', 'Enterprise Only'),
                            ('open_source', 'Open Source'),
                        ],
                        default='freemium',
                        max_length=20,
                    ),
                ),
                (
                    'starting_price',
                    models.CharField(
                        blank=True, help_text="E.g., '$20/month', 'Free', '$0.002/1K tokens'", max_length=100
                    ),
                ),
                ('has_free_tier', models.BooleanField(default=False)),
                ('requires_api_key', models.BooleanField(default=False)),
                ('requires_waitlist', models.BooleanField(default=False)),
                (
                    'overview',
                    models.TextField(blank=True, help_text='Long-form overview/introduction (supports Markdown)'),
                ),
                (
                    'key_features',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of key features with descriptions [{title: '', description: ''}]",
                    ),
                ),
                (
                    'use_cases',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Specific use cases with examples [{title: '', description: '', example: ''}]",
                    ),
                ),
                (
                    'usage_tips',
                    models.JSONField(
                        blank=True, default=list, help_text='Practical tips for using the tool effectively'
                    ),
                ),
                (
                    'best_practices',
                    models.JSONField(blank=True, default=list, help_text='Best practices and recommendations'),
                ),
                (
                    'limitations',
                    models.JSONField(blank=True, default=list, help_text='Known limitations or considerations'),
                ),
                (
                    'alternatives',
                    models.JSONField(blank=True, default=list, help_text='List of alternative tool slugs'),
                ),
                (
                    'model_info',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical model information (e.g., {'model': 'GPT-4', 'provider': 'OpenAI'})",
                    ),
                ),
                (
                    'integrations',
                    models.JSONField(blank=True, default=list, help_text='List of integrations/platforms supported'),
                ),
                ('api_available', models.BooleanField(default=False)),
                (
                    'languages_supported',
                    models.JSONField(blank=True, default=list, help_text='Programming/natural languages supported'),
                ),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='SEO keywords')),
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True, default=True, help_text='Whether this tool is visible in the directory'
                    ),
                ),
                (
                    'is_featured',
                    models.BooleanField(db_index=True, default=False, help_text='Featured tools appear at the top'),
                ),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by team (shows badge)')),
                ('view_count', models.IntegerField(default=0)),
                (
                    'popularity_score',
                    models.FloatField(default=0.0, help_text='Calculated popularity score for ranking'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_featured', '-popularity_score', 'name'],
                'indexes': [
                    models.Index(fields=['category', 'is_active'], name='core_tool_categor_3a9a83_idx'),
                    models.Index(fields=['-popularity_score'], name='core_tool_popular_900d29_idx'),
                    models.Index(fields=['-created_at'], name='core_tool_created_b5a846_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ToolBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about the tool')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'tool',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='core.tool'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tool_bookmarks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tools', models.ManyToManyField(related_name='comparisons', to='core.tool')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tool_comparisons',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'rating',
                    models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1-5 star rating'),
                ),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('pros', models.JSONField(blank=True, default=list, help_text='List of pros')),
                ('cons', models.JSONField(blank=True, default=list, help_text='List of cons')),
                ('use_case', models.CharField(blank=True, help_text='What they used it for', max_length=200)),
                ('is_verified_user', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'tool',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.tool'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tool_reviews',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['challenger', '-created_at'], name='core_prompt_challen_803316_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['opponent', '-created_at'], name='core_prompt_opponen_d60241_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['status', '-created_at'], name='core_prompt_status_e060b7_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['expires_at'], name='core_prompt_expires_faab10_idx'),
        ),
        migrations.AddIndex(
            model_name='battlesubmission',
            index=models.Index(fields=['battle', 'user'], name='core_battle_battle__9c153a_idx'),
        ),
        migrations.AddIndex(
            model_name='battlesubmission',
            index=models.Index(fields=['user', '-submitted_at'], name='core_battle_user_id_ad63b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='battlesubmission',
            unique_together={('battle', 'user')},
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['recipient', 'status', '-created_at'], name='core_battle_recipie_b6c75a_idx'),
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['sender', '-created_at'], name='core_battle_sender__68f92f_idx'),
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['expires_at'], name='core_battle_expires_8e6706_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='toolbookmark',
            unique_together={('user', 'tool')},
        ),
        migrations.AddIndex(
            model_name='toolreview',
            index=models.Index(fields=['tool', '-created_at'], name='core_toolre_tool_id_d75f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='toolreview',
            index=models.Index(fields=['tool', '-helpful_count'], name='core_toolre_tool_id_4d746a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='toolreview',
            unique_together={('tool', 'user')},
        ),
    ]
