# Generated by Django 5.0.14 on 2025-12-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_alter_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(
                choices=[('ai_tool', 'AI Tool'), ('technology', 'Technology')],
                db_index=True,
                default='ai_tool',
                help_text='Whether this is an AI tool or a technology',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(
                choices=[
                    ('chat', 'Chat & Conversational AI'),
                    ('code', 'Code & Development'),
                    ('image', 'Image Generation'),
                    ('video', 'Video Generation & Editing'),
                    ('audio', 'Audio & Music'),
                    ('writing', 'Writing & Content'),
                    ('research', 'Research & Search'),
                    ('productivity', 'Productivity & Workflow'),
                    ('data', 'Data & Analytics'),
                    ('design', 'Design & Creative'),
                    ('language', 'Programming Language'),
                    ('framework', 'Framework & Library'),
                    ('database', 'Database'),
                    ('infrastructure', 'Infrastructure & DevOps'),
                    ('cloud', 'Cloud Platform'),
                    ('testing', 'Testing & QA'),
                    ('other', 'Other'),
                ],
                db_index=True,
                default='other',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['tool_type', 'is_active'], name='core_tool_tool_ty_958ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(
                fields=['tool_type', 'category', 'is_active'],
                name='core_tool_tool_ty_7a1e76_idx',
            ),
        ),
    ]
