# Generated by Django 5.0.14 on 2025-11-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_user_github_url_user_instagram_url_user_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='playground_is_public',
            field=models.BooleanField(default=False, help_text='Allow others to view your Playground projects'),
        ),
    ]
