# Generated by Django 5.0.14 on 2025-12-01 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_add_tool_type_and_tech_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                (
                    'description',
                    models.TextField(blank=True, help_text='About the company'),
                ),
                (
                    'tagline',
                    models.CharField(blank=True, help_text='Short company tagline', max_length=300),
                ),
                ('logo_url', models.URLField(blank=True, help_text='Company logo')),
                (
                    'banner_url',
                    models.URLField(blank=True, help_text='Company banner image'),
                ),
                ('website_url', models.URLField(blank=True)),
                ('careers_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'headquarters',
                    models.CharField(blank=True, help_text='e.g., San Francisco, CA', max_length=200),
                ),
                (
                    'company_size',
                    models.CharField(blank=True, help_text='e.g., 100-500 employees', max_length=50),
                ),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                (
                    'is_featured',
                    models.BooleanField(default=False, help_text='Featured companies appear prominently'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='company',
            field=models.ForeignKey(
                blank=True,
                help_text='Parent company/vendor (e.g., Anthropic for Claude)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tools',
                to='core.company',
            ),
        ),
    ]
