# Generated by Django 5.0.14 on 2025-12-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_add_company_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='engagement_velocity',
            field=models.FloatField(
                db_index=True,
                default=0.0,
                help_text='Engagement velocity score for trending algorithm',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='last_velocity_update',
            field=models.DateTimeField(
                blank=True,
                help_text='When engagement velocity was last calculated',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Total view count for analytics'),
        ),
    ]
