# Generated by Django 5.0.14 on 2025-11-19 17:29

from django.db import migrations


def set_playground_public(apps, schema_editor):
    """Set playground_is_public to True for all existing users."""
    User = apps.get_model("core", "User")
    User.objects.all().update(playground_is_public=True)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_user_playground_is_public"),
    ]

    operations = [
        migrations.RunPython(set_playground_public, migrations.RunPython.noop),
    ]
