# Generated by Django 5.0.14 on 2025-12-01 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Simplify project visibility logic:
    - Rename is_showcase -> is_showcased (featured on profile showcase section)
    - Remove is_published (redundant - all non-private projects are public)
    - Remove published_at (no longer needed)
    - is_private is now the ONLY field controlling explore feed visibility
    """

    dependencies = [
        ('core', '0018_add_personalization_indexes'),
        ('integrations', '0003_add_reddit_moderation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove old indexes first
        migrations.RemoveIndex(
            model_name='project',
            name='core_projec_is_show_36089d_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='core_projec_is_publ_a4ac4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_visibility_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_visibility_velocity_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectlike',
            name='projectlike_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectlike',
            name='projectlike_proj_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinteraction',
            name='userinteraction_user_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertag',
            name='usertag_user_taxonomy_idx',
        ),
        # Rename is_showcase to is_showcased (preserves data)
        migrations.RenameField(
            model_name='project',
            old_name='is_showcase',
            new_name='is_showcased',
        ),
        # Remove deprecated fields
        migrations.RemoveField(
            model_name='project',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='project',
            name='published_at',
        ),
        # Update field help text
        migrations.AlterField(
            model_name='project',
            name='is_showcased',
            field=models.BooleanField(default=True, help_text='Featured on user profile showcase section'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft delete - hidden from all views'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(
                default=False,
                help_text='Hidden from explore feed and public views. Only visible to owner.',
            ),
        ),
        # Add new indexes
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['is_private', 'is_archived', '-created_at'],
                name='core_projec_is_priv_4576ac_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['is_showcased', 'is_archived', '-created_at'],
                name='core_projec_is_show_27b56c_idx',
            ),
        ),
    ]
