# Generated by Django 5.0.14 on 2025-11-19 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_user_current_status_user_location_user_pronouns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='taxonomy',
            field=models.OneToOneField(
                blank=True,
                help_text='Link to taxonomy entry for user personalization/tagging',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tool_entity',
                to='core.taxonomy',
            ),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(
                choices=[
                    ('explorer', 'Explorer'),
                    ('expert', 'Expert'),
                    ('mentor', 'Mentor'),
                    ('patron', 'Patron'),
                    ('admin', 'Admin'),
                    ('bot', 'Bot'),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='roleupgraderequest',
            name='current_role',
            field=models.CharField(
                choices=[
                    ('explorer', 'Explorer'),
                    ('expert', 'Expert'),
                    ('mentor', 'Mentor'),
                    ('patron', 'Patron'),
                    ('admin', 'Admin'),
                    ('bot', 'Bot'),
                ],
                help_text='Role at the time of request',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='roleupgraderequest',
            name='requested_role',
            field=models.CharField(
                choices=[
                    ('explorer', 'Explorer'),
                    ('expert', 'Expert'),
                    ('mentor', 'Mentor'),
                    ('patron', 'Patron'),
                    ('admin', 'Admin'),
                    ('bot', 'Bot'),
                ],
                help_text='Role user is requesting',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('explorer', 'Explorer'),
                    ('expert', 'Expert'),
                    ('mentor', 'Mentor'),
                    ('patron', 'Patron'),
                    ('admin', 'Admin'),
                    ('bot', 'Bot'),
                ],
                default='explorer',
                help_text='User role determines access level and permissions',
                max_length=20,
            ),
        ),
    ]
