# Generated by Django 5.0.14 on 2025-11-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_fix_tools_foreignkeys_and_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="thumbnail_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["is_published", "-published_at"], name="core_projec_is_publ_a4ac4c_idx"),
        ),
    ]
