# Generated by Django 5.0.14 on 2025-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_alter_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='difficulty_level',
            field=models.CharField(
                blank=True,
                choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')],
                db_index=True,
                default='',
                help_text='Content difficulty: beginner, intermediate, advanced (for personalization)',
                max_length=20,
            ),
        ),
    ]
