# Generated by Django 5.0.14 on 2025-12-02 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_add_difficulty_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, db_index=True, help_text='Timestamp when object was soft deleted', null=True
                    ),
                ),
                (
                    'conversation_id',
                    models.CharField(
                        db_index=True, help_text='WebSocket conversation ID (e.g., project-123)', max_length=255
                    ),
                ),
                (
                    'final_image_url',
                    models.CharField(blank=True, help_text='URL of the final/selected image', max_length=500),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'project',
                    models.ForeignKey(
                        blank=True,
                        help_text='Project created from this session (if any)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='image_generation_sessions',
                        to='core.project',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='image_generation_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageGenerationIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text="User's prompt for this iteration")),
                ('image_url', models.CharField(help_text='URL of the generated image', max_length=500)),
                (
                    'gemini_response_text',
                    models.TextField(blank=True, help_text="Gemini's text response accompanying the image"),
                ),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this iteration in the session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='iterations',
                        to='core.imagegenerationsession',
                    ),
                ),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='imagegenerationsession',
            index=models.Index(fields=['user', '-created_at'], name='core_imageg_user_id_d65716_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationsession',
            index=models.Index(fields=['conversation_id'], name='core_imageg_convers_371de5_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationiteration',
            index=models.Index(fields=['session', 'order'], name='core_imageg_session_a7a5de_idx'),
        ),
    ]
