# Generated by Django 5.0.14 on 2025-11-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_alter_project_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.IntegerField(default=0, help_text='Current consecutive days login streak'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_date',
            field=models.DateField(blank=True, help_text='Date of last login for streak tracking', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, help_text='User level calculated from points'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_streak',
            field=models.IntegerField(default=0, help_text='Longest login streak achieved'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(default=0, help_text='Total points earned by user'),
        ),
    ]
