# Generated by Django 5.1.15 on 2025-12-04 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0023_imagegenerationsession_imagegenerationiteration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='battlesubmission',
            name='criteria_scores',
            field=models.JSONField(
                blank=True, default=dict, help_text='Breakdown by judging criteria: {"creativity": 85, "relevance": 90}'
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='challenger_connected',
            field=models.BooleanField(default=False, help_text='Is challenger connected via WebSocket'),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='match_source',
            field=models.CharField(
                choices=[('direct', 'Direct Challenge'), ('random', 'Random Match'), ('ai_opponent', 'AI Opponent')],
                default='direct',
                help_text='How this battle match was created',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='opponent_connected',
            field=models.BooleanField(default=False, help_text='Is opponent connected via WebSocket'),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='phase',
            field=models.CharField(
                choices=[
                    ('waiting', 'Waiting for Opponent'),
                    ('countdown', 'Countdown'),
                    ('active', 'Active'),
                    ('generating', 'AI Generating'),
                    ('judging', 'AI Judging'),
                    ('reveal', 'Results Reveal'),
                    ('complete', 'Complete'),
                ],
                db_index=True,
                default='waiting',
                help_text='Current phase of the real-time battle',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='ChallengeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'key',
                    models.CharField(
                        help_text="Unique identifier (e.g., 'dreamscape', 'movie_poster')", max_length=50, unique=True
                    ),
                ),
                ('name', models.CharField(help_text='Display name for the challenge type', max_length=100)),
                ('description', models.TextField(help_text='Description of what this challenge type is about')),
                (
                    'templates',
                    models.JSONField(
                        default=list, help_text='List of challenge templates with {variable} placeholders'
                    ),
                ),
                (
                    'variables',
                    models.JSONField(
                        default=dict,
                        help_text='Variable options for template substitution: {"style": ["surreal", "cosmic"]}',
                    ),
                ),
                (
                    'judging_criteria',
                    models.JSONField(
                        default=list,
                        help_text='List of criteria: [{"name": "creativity", "weight": 30, "description": "..."}]',
                    ),
                ),
                (
                    'ai_judge_prompt',
                    models.TextField(blank=True, help_text='Custom AI judging prompt (uses default if empty)'),
                ),
                (
                    'default_duration_minutes',
                    models.IntegerField(default=3, help_text='Default battle duration in minutes'),
                ),
                (
                    'min_submission_length',
                    models.IntegerField(default=10, help_text='Minimum prompt length in characters'),
                ),
                (
                    'max_submission_length',
                    models.IntegerField(default=2000, help_text='Maximum prompt length in characters'),
                ),
                ('winner_points', models.IntegerField(default=50, help_text='Points awarded to winner')),
                ('participation_points', models.IntegerField(default=10, help_text='Points for participation')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this challenge type is available')),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')],
                        default='medium',
                        max_length=20,
                    ),
                ),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        help_text='Category this challenge type belongs to',
                        limit_choices_to={'taxonomy_type': 'category'},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='challenge_types',
                        to='core.taxonomy',
                    ),
                ),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BattleMatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'match_type',
                    models.CharField(
                        choices=[('random', 'Random Match'), ('ai', 'AI Opponent (Pip)')],
                        default='random',
                        help_text='Type of match requested',
                        max_length=20,
                    ),
                ),
                ('queued_at', models.DateTimeField(auto_now_add=True, help_text='When user joined queue')),
                ('expires_at', models.DateTimeField(help_text='When queue entry expires')),
                (
                    'user',
                    models.OneToOneField(
                        help_text='User waiting in queue',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='matchmaking_queue',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'challenge_type',
                    models.ForeignKey(
                        blank=True,
                        help_text='Preferred challenge type (null = any)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='core.challengetype',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Battle matchmaking queue entries',
            },
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='challenge_type',
            field=models.ForeignKey(
                blank=True,
                help_text='The challenge type configuration used for this battle',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='battles',
                to='core.challengetype',
            ),
        ),
        migrations.CreateModel(
            name='BattleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'vote_source',
                    models.CharField(
                        choices=[('ai', 'AI Judge'), ('community', 'Community Vote'), ('panel', 'Judge Panel')],
                        default='ai',
                        help_text='Source of this vote',
                        max_length=20,
                    ),
                ),
                ('score', models.FloatField(help_text='Score given (0-100)')),
                (
                    'criteria_scores',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Per-criteria breakdown: {"creativity": 85, "relevance": 90}',
                    ),
                ),
                ('feedback', models.TextField(blank=True, help_text='Feedback explaining the vote')),
                ('weight', models.FloatField(default=1.0, help_text='Vote weight for aggregation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'battle',
                    models.ForeignKey(
                        help_text='The battle being voted on',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='votes',
                        to='core.promptbattle',
                    ),
                ),
                (
                    'submission',
                    models.ForeignKey(
                        help_text='The submission being voted on',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='votes',
                        to='core.battlesubmission',
                    ),
                ),
                (
                    'voter',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who voted (null for AI judge)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='battle_votes_cast',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(fields=['battle', 'vote_source'], name='core_battle_battle__290016_idx'),
                    models.Index(fields=['submission', '-created_at'], name='core_battle_submiss_d01f9f_idx'),
                ],
                'unique_together': {('submission', 'voter', 'vote_source')},
            },
        ),
        migrations.AddIndex(
            model_name='challengetype',
            index=models.Index(fields=['is_active', 'order'], name='core_challe_is_acti_7e6d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='challengetype',
            index=models.Index(fields=['category', 'is_active'], name='core_challe_categor_928afc_idx'),
        ),
        migrations.AddIndex(
            model_name='battlematchmakingqueue',
            index=models.Index(fields=['match_type', 'queued_at'], name='core_battle_match_t_ef4726_idx'),
        ),
        migrations.AddIndex(
            model_name='battlematchmakingqueue',
            index=models.Index(fields=['expires_at'], name='core_battle_expires_deb467_idx'),
        ),
    ]
