# Generated by Django 5.0.14 on 2025-11-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0023_user_current_streak_user_last_login_date_user_level_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-total_points'], name='user_points_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['level', '-total_points'], name='user_level_points_idx'),
        ),
    ]
