# Generated by Django 5.0.14 on 2025-11-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0024_user_user_points_idx_user_user_level_points_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(
                blank=True, help_text='Tools/technologies used in this project', related_name='projects', to='core.tool'
            ),
        ),
    ]
