# Generated by Django 5.1.15 on 2025-12-04 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0024_battlesubmission_criteria_scores_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlesubmission',
            name='submission_type',
            field=models.CharField(
                choices=[('text', 'Text Generation'), ('image', 'Image Generation')],
                default='image',
                help_text='Type of submission (text or image prompt)',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['phase', 'status'], name='core_prompt_phase_0b61ac_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['phase', '-created_at'], name='core_prompt_phase_6ae267_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['winner', '-completed_at'], name='core_prompt_winner__069661_idx'),
        ),
    ]
