# Generated by Django 5.1.15 on 2025-12-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_alter_battlesubmission_submission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hide_categories',
            field=models.BooleanField(
                default=False,
                help_text='If True, categories are hidden from public display but still used for filtering',
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(
                choices=[
                    ('github_repo', 'GitHub Repository'),
                    ('figma_design', 'Figma Design'),
                    ('image_collection', 'Image Collection'),
                    ('prompt', 'Prompt / Conversation'),
                    ('video', 'Video'),
                    ('reddit_thread', 'Reddit Thread'),
                    ('rss_article', 'RSS Article'),
                    ('battle', 'Prompt Battle'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=32,
            ),
        ),
    ]
