# Generated by Django 5.0.14 on 2025-11-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_add_tools_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_highlighted',
            field=models.BooleanField(
                db_index=True, default=False, help_text='Featured at top of profile (only one per user)'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Hidden from public, only visible to owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_showcase',
            field=models.BooleanField(default=False, help_text='Display in showcase section'),
        ),
    ]
