# Generated by Django 5.1.15 on 2025-12-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0026_project_hide_categories_alter_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_product',
            field=models.BooleanField(
                db_index=True, default=False, help_text='Whether this project is a sellable digital product'
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(
                choices=[
                    ('github_repo', 'GitHub Repository'),
                    ('figma_design', 'Figma Design'),
                    ('image_collection', 'Image Collection'),
                    ('prompt', 'Prompt / Conversation'),
                    ('video', 'Video'),
                    ('reddit_thread', 'Reddit Thread'),
                    ('rss_article', 'RSS Article'),
                    ('battle', 'Prompt Battle'),
                    ('product', 'Digital Product'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=32,
            ),
        ),
    ]
