# Generated by Django 5.1.15 on 2025-12-05 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0027_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='battleinvitation',
            name='invitation_type',
            field=models.CharField(
                choices=[('platform', 'Platform User'), ('sms', 'SMS'), ('random', 'Random Match')],
                db_index=True,
                default='platform',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='battleinvitation',
            name='invite_token',
            field=models.CharField(
                blank=True, help_text='Unique token for SMS invitation links', max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name='battleinvitation',
            name='recipient_name',
            field=models.CharField(
                blank=True, help_text='Name of SMS recipient (for display purposes)', max_length=100
            ),
        ),
        migrations.AddField(
            model_name='battleinvitation',
            name='recipient_phone',
            field=models.CharField(
                blank=True, db_index=True, help_text='Phone number for SMS invitations (E.164 format)', max_length=20
            ),
        ),
        migrations.AddField(
            model_name='battleinvitation',
            name='sms_log_id',
            field=models.IntegerField(blank=True, help_text='ID of SMSLog record', null=True),
        ),
        migrations.AddField(
            model_name='battleinvitation',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, help_text='When SMS was sent', null=True),
        ),
        migrations.AlterField(
            model_name='battleinvitation',
            name='recipient',
            field=models.ForeignKey(
                blank=True,
                help_text='User who received the invitation (for platform invitations)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='battle_invitations_received',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['recipient_phone', 'status'], name='core_battle_recipie_019643_idx'),
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['invitation_type', 'status'], name='core_battle_invitat_2b60a1_idx'),
        ),
    ]
