# Generated by Django 5.1.15 on 2025-12-05 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0028_battleinvitation_invitation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.CharField(
                        choices=[('going', 'Going'), ('maybe', 'Maybe'), ('not_going', 'Not Going')],
                        default='going',
                        help_text='RSVP status',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'event',
                    models.ForeignKey(
                        help_text="The event being RSVP'd to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rsvps',
                        to='core.event',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text="User who RSVP'd",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_rsvps',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Event RSVP',
                'verbose_name_plural': 'Event RSVPs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['event', 'status'], name='core_eventr_event_i_ca9adf_idx'),
                    models.Index(fields=['user', 'status'], name='core_eventr_user_id_be5040_idx'),
                ],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
