# Generated by Django 5.0.14 on 2025-11-20 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0029_project_featured_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content')),
                (
                    'moderation_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending Review'),
                            ('approved', 'Approved'),
                            ('rejected', 'Rejected'),
                            ('flagged', 'Flagged for Manual Review'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'moderation_reason',
                    models.TextField(blank=True, default='', help_text='Reason for moderation decision'),
                ),
                (
                    'moderation_data',
                    models.JSONField(blank=True, default=dict, help_text='Full moderation API response data'),
                ),
                (
                    'moderated_at',
                    models.DateTimeField(blank=True, help_text='When moderation was performed', null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='projectlike',
            new_name='core_projec_project_d7711f_idx',
            old_name='core_projec_project_idx',
        ),
        migrations.RenameIndex(
            model_name='projectlike',
            new_name='core_projec_user_id_e9795b_idx',
            old_name='core_projec_user_id_idx',
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', help_text='Banner image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.project'
            ),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='project_comments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.projectcomment'
            ),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(
                fields=['project', 'moderation_status', '-created_at'], name='core_projec_project_04720c_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['user', '-created_at'], name='core_projec_user_id_c5dc5c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['moderation_status', '-created_at'], name='core_projec_moderat_d4c895_idx'),
        ),
        migrations.AddIndex(
            model_name='commentvote',
            index=models.Index(fields=['comment', 'vote_type'], name='core_commen_comment_a7da45_idx'),
        ),
        migrations.AddIndex(
            model_name='commentvote',
            index=models.Index(fields=['user', '-created_at'], name='core_commen_user_id_7da9cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_comment_vote_per_user'),
        ),
    ]
