# Generated by Django 5.1.15 on 2025-12-05 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0029_eventrsvp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptbattle',
            name='match_source',
            field=models.CharField(
                choices=[
                    ('direct', 'Direct Challenge'),
                    ('random', 'Random Match'),
                    ('ai_opponent', 'AI Opponent'),
                    ('invitation', 'SMS Invitation'),
                ],
                default='direct',
                help_text='How this battle match was created',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='promptbattle',
            name='opponent',
            field=models.ForeignKey(
                blank=True,
                help_text='User who was challenged (null for SMS invitations until accepted)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='battles_received',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
