# Generated by Django 5.0.14 on 2025-11-20 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0030_add_project_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event')),
                ('start_date', models.DateTimeField(help_text='Event start date and time')),
                ('end_date', models.DateTimeField(help_text='Event end date and time')),
                (
                    'location',
                    models.CharField(blank=True, help_text='Event location (physical or virtual)', max_length=255),
                ),
                ('event_url', models.URLField(blank=True, help_text='URL for event registration or more info')),
                ('is_all_day', models.BooleanField(default=False, help_text='Whether this is an all-day event')),
                (
                    'color',
                    models.CharField(
                        default='#3b82f6', help_text='Hex color code for calendar display (e.g., #3b82f6)', max_length=7
                    ),
                ),
                ('thumbnail', models.URLField(blank=True, help_text='URL to event thumbnail image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether event is visible to users')),
                (
                    'created_by',
                    models.ForeignKey(
                        help_text='Admin user who created this event',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date'],
                'indexes': [
                    models.Index(fields=['start_date', 'end_date'], name='core_event_start_d_05b9cd_idx'),
                    models.Index(fields=['is_published'], name='core_event_is_publ_c1332f_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ProjectRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(help_text='The old slug that now redirects to project', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='core.project'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_redirects',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'old_slug'], name='core_projec_user_id_60e492_idx'),
                    models.Index(fields=['project', '-created_at'], name='core_projec_project_e96985_idx'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='projectredirect',
            constraint=models.UniqueConstraint(fields=('user', 'old_slug'), name='unique_redirect_slug_per_user'),
        ),
    ]
