# Generated by Django 5.1.15 on 2025-12-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0030_alter_promptbattle_match_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_date',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text='Original publication date for external content (e.g., news articles)',
                null=True,
            ),
        ),
    ]
