# Generated by Django 5.1.15 on 2025-12-05 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0031_project_published_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'session_key',
                    models.CharField(
                        blank=True, default='', help_text='Session key for anonymous click tracking', max_length=40
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('explore_for_you', 'Explore: For You'),
                            ('explore_trending', 'Explore: Trending'),
                            ('explore_new', 'Explore: New'),
                            ('explore_news', 'Explore: News'),
                            ('search', 'Search Results'),
                            ('profile', 'Profile Page'),
                            ('related', 'Related Projects'),
                        ],
                        help_text='Feed/context where the click occurred',
                        max_length=20,
                    ),
                ),
                (
                    'position',
                    models.PositiveIntegerField(
                        blank=True, help_text='Position in the feed where project was clicked (0-indexed)', null=True
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='core.project'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who clicked (null for anonymous)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='project_clicks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['project', '-created_at'], name='core_projec_project_c3f88a_idx'),
                    models.Index(fields=['project', 'created_at'], name='core_projec_project_09d510_idx'),
                    models.Index(fields=['source', '-created_at'], name='core_projec_source_1c67e6_idx'),
                    models.Index(fields=['-created_at'], name='core_projec_created_eb9ae2_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ProjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'session_key',
                    models.CharField(
                        blank=True, default='', help_text='Session key for anonymous view deduplication', max_length=40
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('explore', 'Explore Feed'),
                            ('profile', 'Profile Page'),
                            ('direct', 'Direct Link'),
                            ('search', 'Search Results'),
                            ('embed', 'Embedded View'),
                        ],
                        default='direct',
                        help_text='Where the view originated from',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.project'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who viewed (null for anonymous)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='project_views',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['project', '-created_at'], name='core_projec_project_ac062a_idx'),
                    models.Index(fields=['project', 'created_at'], name='core_projec_project_cd6da9_idx'),
                    models.Index(fields=['user', '-created_at'], name='core_projec_user_id_fd8a52_idx'),
                    models.Index(fields=['-created_at'], name='core_projec_created_c17692_idx'),
                ],
            },
        ),
    ]
