# Generated by Django 5.0.14 on 2025-11-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0031_event_projectredirect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether project is publicly visible'),
        ),
    ]
