# Generated by Django 5.0.14 on 2025-12-05 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0032_add_project_view_and_click_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HallucinationMetrics',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                (
                    'feature',
                    models.CharField(
                        db_index=True,
                        help_text='Agent type: project_agent, auth_chat, etc.',
                        max_length=50,
                    ),
                ),
                (
                    'confidence_level',
                    models.CharField(
                        choices=[
                            ('high', 'High (80-100%)'),
                            ('medium', 'Medium (60-79%)'),
                            ('low', 'Low (40-59%)'),
                            ('uncertain', 'Uncertain (0-39%)'),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    'confidence_score',
                    models.FloatField(db_index=True, help_text='0.0-1.0'),
                ),
                (
                    'flags',
                    models.JSONField(
                        default=list,
                        help_text='Issues detected: overconfident, no_tool_citation, etc.',
                    ),
                ),
                (
                    'response_text',
                    models.TextField(help_text='First 1000 chars of LLM response'),
                ),
                (
                    'tool_outputs',
                    models.JSONField(default=list, help_text='Tool results for verification'),
                ),
                (
                    'metadata',
                    models.JSONField(default=dict, help_text='Extra: latency_ms, token_count, etc.'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'agents_hallucination_metrics',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['feature', '-created_at'],
                        name='agents_hall_feature_d90423_idx',
                    ),
                    models.Index(
                        fields=['confidence_level', '-created_at'],
                        name='agents_hall_confide_a083f3_idx',
                    ),
                    models.Index(
                        fields=['confidence_score'],
                        name='agents_hall_confide_fbf9ed_idx',
                    ),
                ],
            },
        ),
    ]
