# Generated by Django 5.0.14 on 2025-11-21 08:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0032_alter_project_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone_name',
            field=models.CharField(
                default='UTC', help_text='Timezone for event (e.g., America/New_York, UTC)', max_length=63
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(
                help_text='Last admin user who updated this event',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='updated_events',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(
                default='#3b82f6',
                help_text='Hex color code for calendar display (e.g., #3b82f6)',
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Color must be a valid hex code (e.g., #3b82f6)', regex='^#[0-9A-Fa-f]{6}$'
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.URLField(
                blank=True,
                help_text='URL to event thumbnail image (must be https)',
                validators=[django.core.validators.URLValidator(schemes=['https'])],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether project is publicly visible'),
        ),
        migrations.DeleteModel(
            name='ProjectRedirect',
        ),
    ]
