# Generated by Django 5.0.14 on 2025-11-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0033_event_timezone_name_event_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('ember', 'Ember'),
                    ('spark', 'Spark'),
                    ('blaze', 'Blaze'),
                    ('beacon', 'Beacon'),
                    ('phoenix', 'Phoenix'),
                ],
                default='ember',
                help_text='User tier based on total points',
            ),
        ),
        # Rename current_streak to current_streak_days for consistency
        migrations.RenameField(
            model_name='user',
            old_name='current_streak',
            new_name='current_streak_days',
        ),
        # Rename max_streak to longest_streak_days for consistency
        migrations.RenameField(
            model_name='user',
            old_name='max_streak',
            new_name='longest_streak_days',
        ),
        # Rename last_login_date to last_activity_date for accuracy
        migrations.RenameField(
            model_name='user',
            old_name='last_login_date',
            new_name='last_activity_date',
        ),
        # Update help text for last_activity_date
        migrations.AlterField(
            model_name='user',
            name='last_activity_date',
            field=models.DateField(
                blank=True, null=True, help_text='Last date user earned points (for streak tracking)'
            ),
        ),
        # Add lifetime stats fields
        migrations.AddField(
            model_name='user',
            name='lifetime_quizzes_completed',
            field=models.IntegerField(default=0, help_text='Total quizzes completed'),
        ),
        migrations.AddField(
            model_name='user',
            name='lifetime_projects_created',
            field=models.IntegerField(default=0, help_text='Total projects created'),
        ),
        migrations.AddField(
            model_name='user',
            name='lifetime_side_quests_completed',
            field=models.IntegerField(default=0, help_text='Total side quests completed'),
        ),
        migrations.AddField(
            model_name='user',
            name='lifetime_comments_posted',
            field=models.IntegerField(default=0, help_text='Total comments posted'),
        ),
        # Update help text for current_streak_days
        migrations.AlterField(
            model_name='user',
            name='current_streak_days',
            field=models.IntegerField(default=0, help_text='Current consecutive day streak'),
        ),
        # Update help text for longest_streak_days
        migrations.AlterField(
            model_name='user',
            name='longest_streak_days',
            field=models.IntegerField(default=0, help_text='Longest streak ever achieved'),
        ),
        # Add tier index
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tier'], name='user_tier_idx'),
        ),
        # Add tier with date_joined index
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tier', '-date_joined'], name='user_tier_recent_idx'),
        ),
        # Add constraint for non-negative points
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(total_points__gte=0), name='user_points_non_negative'),
        ),
    ]
