# Generated by Django 5.1.15 on 2025-12-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0033_hallucinationmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(
                choices=[
                    ('project_view', 'Viewed Project'),
                    ('project_create', 'Created Project'),
                    ('conversation', 'Had Conversation'),
                    ('search', 'Searched'),
                    ('content_view', 'Viewed Content'),
                    ('game_404_start', '404 Game Started'),
                    ('game_404_complete', '404 Game Completed'),
                ],
                max_length=30,
            ),
        ),
    ]
