# Generated by Django 5.0.14 on 2025-11-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0034_add_user_tier_and_gamification_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'ordering': ['name'], 'verbose_name_plural': 'Taxonomies'},
        ),
        migrations.RemoveIndex(
            model_name='taxonomy',
            name='core_taxono_categor_b1ae1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_points_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_level_points_idx',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='category',
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether project is publicly visible'),
        ),
        migrations.AddIndex(
            model_name='taxonomy',
            index=models.Index(fields=['is_active'], name='core_taxono_is_acti_f96c5c_idx'),
        ),
    ]
