# Generated by Django 5.1.15 on 2025-12-05 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0034_add_404_game_interaction_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_promoted',
            field=models.BooleanField(
                db_index=True, default=False, help_text='Admin promoted - appears at top of explore feeds'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='promoted_at',
            field=models.DateTimeField(
                blank=True, help_text='When this project was promoted (for ordering)', null=True
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='promoted_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Admin who promoted this project',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='promoted_projects',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
