# Generated by Django 5.0.14 on 2025-11-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0035_alter_taxonomy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'ordering': ['taxonomy_type', 'name'], 'verbose_name_plural': 'Taxonomies'},
        ),
        migrations.RemoveIndex(
            model_name='taxonomy',
            name='core_taxono_is_acti_f96c5c_idx',
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='color',
            field=models.CharField(
                blank=True, default='', help_text="Display color for topics (e.g., 'blue', 'teal')", max_length=50
            ),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='taxonomy_type',
            field=models.CharField(
                choices=[('tool', 'Tool'), ('topic', 'Topic')], db_index=True, default='tool', max_length=10
            ),
        ),
        migrations.AddIndex(
            model_name='taxonomy',
            index=models.Index(fields=['taxonomy_type', 'is_active'], name='core_taxono_taxonom_60030a_idx'),
        ),
    ]
