# Generated by Django 5.0.14 on 2025-11-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0036_alter_taxonomy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='topics',
            field=models.ManyToManyField(
                blank=True,
                help_text='Topics that categorize this project (from Taxonomy with type=topic)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'topic'},
                related_name='projects',
                to='core.taxonomy',
            ),
        ),
    ]
