# Generated by Django 5.1.15 on 2025-12-06 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0036_alter_project_type'),
    ]

    operations = [
        # Drop indexes that will be re-created by the new tools app
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS tool_tags_gin_idx;',
            reverse_sql='',  # No reverse needed
        ),
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS tool_name_idx;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS tool_category_idx;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS tool_keywords_gin_idx;',
            reverse_sql='',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='toolcomparison',
            name='tools',
        ),
        # Remove unique_together BEFORE removing fields
        migrations.AlterUniqueTogether(
            name='toolbookmark',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='toolreview',
            unique_together=None,
        ),
        # Now remove the fields
        migrations.RemoveField(
            model_name='toolbookmark',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='toolreview',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='toolbookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='toolcomparison',
            name='user',
        ),
        migrations.RemoveField(
            model_name='toolreview',
            name='user',
        ),
    ]
