# Generated by Django 5.1.15 on 2025-12-06 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0036_alter_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='toolcomparison',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='toolbookmark',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='toolreview',
            name='tool',
        ),
        migrations.AlterUniqueTogether(
            name='toolbookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='toolbookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='toolcomparison',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='toolreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='toolreview',
            name='user',
        ),
    ]
