# Generated by Django 5.1.15 on 2025-12-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0037_remove_tool_company_remove_tool_taxonomy_and_more'),
        ('tools', '0001_initial'),
        ('vendors', '0002_alter_toolcompetitorview_tool_a_and_more'),
    ]

    operations = [
        # Clear M2M join tables before altering FK to point to new tools.Tool table
        migrations.RunSQL(
            sql='DELETE FROM core_project_tools;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DELETE FROM core_quiz_tools;',
            reverse_sql='',
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(
                blank=True,
                help_text='Tools/technologies used in this project',
                related_name='projects',
                to='tools.tool',
            ),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='tools',
            field=models.ManyToManyField(
                blank=True,
                help_text='AI tools/technologies covered in this quiz',
                related_name='quizzes',
                to='tools.tool',
            ),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.DeleteModel(
            name='ToolBookmark',
        ),
        migrations.DeleteModel(
            name='ToolComparison',
        ),
        migrations.DeleteModel(
            name='ToolReview',
        ),
    ]
