# Generated by Django 5.1.15 on 2025-12-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0039_remove_battlematchmakingqueue_challenge_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('login', 'Login'),
                    ('logout', 'Logout'),
                    ('profile_update', 'Profile Update'),
                    ('password_change', 'Password Change'),
                    ('email_change', 'Email Change'),
                    ('role_change', 'Role Change'),
                    ('failed_login', 'Failed Login'),
                    ('account_locked', 'Account Locked'),
                    ('oauth_login', 'OAuth Login'),
                    ('guest_created', 'Guest Account Created'),
                    ('guest_converted', 'Guest Converted to Full Account'),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
