# Generated by Django 5.1.15 on 2025-12-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0041_add_clipped_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                (
                    'display_name',
                    models.CharField(help_text='Canonical display name (properly capitalized)', max_length=100),
                ),
                ('description', models.TextField(help_text='AI-generated dictionary-style definition (2-3 sentences)')),
                (
                    'aliases',
                    models.JSONField(
                        blank=True, default=list, help_text='Alternative slugs that map to this definition'
                    ),
                ),
                (
                    'project_count',
                    models.PositiveIntegerField(default=0, help_text='Cached count of projects with this topic'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Topic Definition',
                'verbose_name_plural': 'Topic Definitions',
                'ordering': ['display_name'],
            },
        ),
    ]
