# Generated by Django 5.1.15 on 2025-12-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0042_topicdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tools_order',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Ordered list of tool IDs. First tool appears in project teaser circle.',
            ),
        ),
    ]
