# Generated by Django 5.1.15 on 2025-12-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0043_project_tools_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='decay_factor',
            field=models.FloatField(
                default=1.0,
                help_text='Recency decay factor (0.0-1.0). Auto-generated tags decay over time if not reinforced.',
            ),
        ),
    ]
