# Generated by Django 5.1.15 on 2025-12-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0044_add_decay_factor_to_usertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_promoted',
            field=models.BooleanField(
                db_index=True, default=False, help_text='Admin promoted - weighted higher in explore feeds (not pinned)'
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='promoted_at',
            field=models.DateTimeField(
                blank=True, help_text='When this project was promoted (used for score decay)', null=True
            ),
        ),
    ]
