# Generated by Django 5.1.15 on 2025-12-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0045_alter_project_is_promoted_alter_project_promoted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='taxonomy_type',
            field=models.CharField(
                choices=[
                    ('tool', 'Tool'),
                    ('category', 'Category'),
                    ('topic', 'Topic'),
                    ('goal', 'Goal'),
                    ('industry', 'Industry'),
                    ('interest', 'Interest'),
                    ('skill', 'Skill'),
                ],
                db_index=True,
                default='tool',
                max_length=10,
            ),
        ),
    ]
