# Generated by Django 5.1.15 on 2025-12-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0047_setup_linkedin_oauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(
                default=True, help_text='Hidden from explore feed and public views. Only visible to owner.'
            ),
        ),
    ]
