# Generated by Django 5.1.15 on 2025-12-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0047_setup_linkedin_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_enabled',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Allow visitors to request to contact the project owner about this project',
            ),
        ),
    ]
