# Generated by Django 5.1.15 on 2025-12-19 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0048_change_is_private_default_to_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                help_text='Parent taxonomy for hierarchical structures (e.g., ML -> Neural Networks)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='children',
                to='core.taxonomy',
            ),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='taxonomy_type',
            field=models.CharField(
                choices=[
                    ('tool', 'Tool'),
                    ('category', 'Category'),
                    ('topic', 'Topic'),
                    ('goal', 'Goal'),
                    ('industry', 'Industry'),
                    ('interest', 'Interest'),
                    ('skill', 'Skill'),
                    ('modality', 'Learning Modality'),
                    ('outcome', 'Learning Outcome'),
                ],
                db_index=True,
                default='tool',
                max_length=15,
            ),
        ),
    ]
