# Generated by Django 5.1.15 on 2025-12-19 17:15

from django.db import migrations


def seed_learning_modalities(apps, schema_editor):
    """Seed the 6 learning modalities into the Taxonomy model.

    Note: Slugs are prefixed with 'modality-' to avoid collision with existing
    taxonomies (e.g., there's already a 'video' topic taxonomy).
    """
    Taxonomy = apps.get_model('core', 'Taxonomy')

    modalities = [
        {
            'name': 'Video (Learning)',
            'slug': 'modality-video',
            'description': 'Watch and learn through video content - tutorials, demos, and explanations',
            'taxonomy_type': 'modality',
        },
        {
            'name': 'Long Reads',
            'slug': 'modality-long-reads',
            'description': 'In-depth articles, documentation, and comprehensive written content',
            'taxonomy_type': 'modality',
        },
        {
            'name': 'Microlearning',
            'slug': 'modality-microlearning',
            'description': 'Quick, focused lessons in 5-10 minutes for bite-sized learning',
            'taxonomy_type': 'modality',
        },
        {
            'name': 'Quizzes & Challenges',
            'slug': 'modality-quiz-challenges',
            'description': 'Test your knowledge with interactive quizzes and side quest challenges',
            'taxonomy_type': 'modality',
        },
        {
            'name': 'Games (Learning)',
            'slug': 'modality-games',
            'description': 'Learn through interactive games and gamified experiences',
            'taxonomy_type': 'modality',
        },
        {
            'name': 'Projects (Learning)',
            'slug': 'modality-projects',
            'description': 'Learn from real project examples and hands-on building',
            'taxonomy_type': 'modality',
        },
    ]

    for modality in modalities:
        Taxonomy.objects.get_or_create(
            slug=modality['slug'],
            defaults=modality,
        )


def remove_learning_modalities(apps, schema_editor):
    """Remove the seeded learning modalities."""
    Taxonomy = apps.get_model('core', 'Taxonomy')
    Taxonomy.objects.filter(taxonomy_type='modality').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0049_taxonomy_parent_alter_taxonomy_taxonomy_type'),
    ]

    operations = [
        migrations.RunPython(seed_learning_modalities, remove_learning_modalities),
    ]
