# Generated by Django 5.1.15 on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0053_migrate_topics_to_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='taxonomy_type',
            field=models.CharField(
                choices=[
                    ('tool', 'Tool'),
                    ('category', 'Category'),
                    ('topic', 'Topic'),
                    ('goal', 'Goal'),
                    ('industry', 'Industry'),
                    ('interest', 'Interest'),
                    ('skill', 'Skill'),
                    ('modality', 'Learning Modality'),
                    ('outcome', 'Learning Outcome'),
                    ('content_type', 'Content Type'),
                    ('time_investment', 'Time Investment'),
                    ('difficulty', 'Difficulty'),
                    ('pricing', 'Pricing'),
                    ('personality', 'Personality Type'),
                    ('learning_style', 'Learning Style'),
                    ('role', 'Role'),
                ],
                db_index=True,
                default='tool',
                max_length=20,
            ),
        ),
    ]
