# Generated by Django 5.1.15 on 2025-12-19
"""
Seed new taxonomy types for content discovery and user personalization:
- content_type: Unified content types across the platform
- time_investment: Time required to consume/build
- difficulty: Content difficulty level
- pricing: Free vs paid content
- personality: MBTI personality types
- learning_style: How users learn best
- role: Job function/audience (multi-select)
"""

from django.db import migrations


def seed_new_taxonomies(apps, schema_editor):
    """Seed all new taxonomy types."""
    Taxonomy = apps.get_model('core', 'Taxonomy')

    # =========================================================================
    # CONTENT TYPE - Unified content types across the platform
    # Prefix: content-* for types that could collide with topics
    # =========================================================================
    content_types = [
        {
            'name': 'Code Repository',
            'slug': 'content-code-repo',
            'description': 'Code repositories, GitHub/GitLab projects, and source code',
        },
        {
            'name': 'Article',
            'slug': 'content-article',
            'description': 'Articles, blog posts, tutorials, and written guides',
        },
        {
            'name': 'Website',
            'slug': 'content-website',
            'description': 'Websites, web apps, landing pages, and live demos',
        },
        {
            'name': 'Automation',
            'slug': 'content-automation',
            'description': 'Automation tools, workflows, and integrations',
        },
        {
            'name': 'Chat Prompt',
            'slug': 'content-chat-prompt',
            'description': 'Chat prompts, conversations, and prompt examples',
        },
        {
            'name': 'Image',
            'slug': 'content-image',
            'description': 'Images, designs, artwork, and visual content',
        },
        {
            'name': 'Video',
            'slug': 'content-video',
            'description': 'Video content, tutorials, and walkthroughs',
        },
        {
            'name': 'Course',
            'slug': 'content-course',
            'description': 'Courses, multi-lesson learning content',
        },
        {
            'name': 'Prompt Pack',
            'slug': 'content-prompt-pack',
            'description': 'Prompt packs, prompt collections, and prompt libraries',
        },
        {
            'name': 'Template',
            'slug': 'content-template',
            'description': 'Templates, starters, and boilerplates',
        },
        {
            'name': 'E-Book',
            'slug': 'content-ebook',
            'description': 'E-books, guides, and downloadable documents',
        },
        {
            'name': 'Quiz',
            'slug': 'content-quiz',
            'description': 'Quizzes, assessments, and knowledge checks',
        },
        {
            'name': 'Side Quest',
            'slug': 'content-side-quest',
            'description': 'Side quests, challenges, and hands-on exercises',
        },
        {
            'name': 'Battle',
            'slug': 'content-battle',
            'description': 'Prompt battles and competitive challenges',
        },
    ]

    for item in content_types:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'content_type',
                'is_active': True,
            },
        )

    # =========================================================================
    # TIME INVESTMENT - How long to consume/build
    # Prefix: time-*
    # =========================================================================
    time_investments = [
        {
            'name': 'Quick Win',
            'slug': 'time-quick',
            'description': 'Less than 15 minutes to consume or implement',
        },
        {
            'name': 'Short',
            'slug': 'time-short',
            'description': '15-60 minutes to consume or implement',
        },
        {
            'name': 'Medium',
            'slug': 'time-medium',
            'description': '1-4 hours to consume or implement',
        },
        {
            'name': 'Deep Dive',
            'slug': 'time-deep-dive',
            'description': 'A day or more to fully consume or implement',
        },
    ]

    for item in time_investments:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'time_investment',
                'is_active': True,
            },
        )

    # =========================================================================
    # DIFFICULTY - Content difficulty level
    # Prefix: level-*
    # =========================================================================
    difficulties = [
        {
            'name': 'Beginner',
            'slug': 'level-beginner',
            'description': 'Suitable for beginners with no prior experience',
        },
        {
            'name': 'Intermediate',
            'slug': 'level-intermediate',
            'description': 'Requires some foundational knowledge',
        },
        {
            'name': 'Advanced',
            'slug': 'level-advanced',
            'description': 'For experienced practitioners',
        },
    ]

    for item in difficulties:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'difficulty',
                'is_active': True,
            },
        )

    # =========================================================================
    # PRICING - Free vs paid content
    # Prefix: pricing-*
    # =========================================================================
    pricing_tiers = [
        {
            'name': 'Free',
            'slug': 'pricing-free',
            'description': 'Completely free content with no cost',
        },
        {
            'name': 'Freemium',
            'slug': 'pricing-freemium',
            'description': 'Free with optional paid upgrades or premium features',
        },
        {
            'name': 'Paid',
            'slug': 'pricing-paid',
            'description': 'Paid content requiring purchase',
        },
    ]

    for item in pricing_tiers:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'pricing',
                'is_active': True,
            },
        )

    # =========================================================================
    # PERSONALITY - Myers-Briggs Type Indicator (MBTI) personality types
    # No prefix needed - MBTI codes are unique
    # =========================================================================
    personality_types = [
        # Analysts
        {
            'name': 'INTJ - Architect',
            'slug': 'intj',
            'description': 'Imaginative and strategic thinkers with a plan for everything',
        },
        {
            'name': 'INTP - Logician',
            'slug': 'intp',
            'description': 'Innovative inventors with an unquenchable thirst for knowledge',
        },
        {
            'name': 'ENTJ - Commander',
            'slug': 'entj',
            'description': 'Bold, imaginative and strong-willed leaders who always find a way',
        },
        {
            'name': 'ENTP - Debater',
            'slug': 'entp',
            'description': 'Smart and curious thinkers who love intellectual challenges',
        },
        # Diplomats
        {
            'name': 'INFJ - Advocate',
            'slug': 'infj',
            'description': 'Quiet and mystical idealists who are inspiring and tireless',
        },
        {
            'name': 'INFP - Mediator',
            'slug': 'infp',
            'description': 'Poetic, kind and altruistic people always eager to help a good cause',
        },
        {
            'name': 'ENFJ - Protagonist',
            'slug': 'enfj',
            'description': 'Charismatic and inspiring leaders who mesmerize their listeners',
        },
        {
            'name': 'ENFP - Campaigner',
            'slug': 'enfp',
            'description': 'Enthusiastic, creative and sociable free spirits who find joy everywhere',
        },
        # Sentinels
        {
            'name': 'ISTJ - Logistician',
            'slug': 'istj',
            'description': 'Practical and fact-minded individuals whose reliability cannot be doubted',
        },
        {
            'name': 'ISFJ - Defender',
            'slug': 'isfj',
            'description': 'Very dedicated and warm protectors, always ready to defend their loved ones',
        },
        {
            'name': 'ESTJ - Executive',
            'slug': 'estj',
            'description': 'Excellent administrators, unsurpassed at managing things or people',
        },
        {
            'name': 'ESFJ - Consul',
            'slug': 'esfj',
            'description': 'Extraordinarily caring, social and popular people, always ready to help',
        },
        # Explorers
        {
            'name': 'ISTP - Virtuoso',
            'slug': 'istp',
            'description': 'Bold and practical experimenters, masters of all kinds of tools',
        },
        {
            'name': 'ISFP - Adventurer',
            'slug': 'isfp',
            'description': 'Flexible and charming artists, always ready to explore something new',
        },
        {
            'name': 'ESTP - Entrepreneur',
            'slug': 'estp',
            'description': 'Smart, energetic and perceptive people who truly enjoy living on the edge',
        },
        {
            'name': 'ESFP - Entertainer',
            'slug': 'esfp',
            'description': 'Spontaneous, energetic and enthusiastic entertainers who love life',
        },
    ]

    for item in personality_types:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'personality',
                'is_active': True,
            },
        )

    # =========================================================================
    # LEARNING STYLE - How users learn best
    # Prefix: style-*
    # =========================================================================
    learning_styles = [
        {
            'name': 'Visual',
            'slug': 'style-visual',
            'description': 'Learns best through images, diagrams, charts, and videos',
        },
        {
            'name': 'Reading/Writing',
            'slug': 'style-reading',
            'description': 'Prefers written content, documentation, and text-based learning',
        },
        {
            'name': 'Hands-On',
            'slug': 'style-hands-on',
            'description': 'Learns by doing - projects, exercises, and practical application',
        },
        {
            'name': 'Audio',
            'slug': 'style-audio',
            'description': 'Prefers podcasts, verbal explanations, and audio content',
        },
        {
            'name': 'Social',
            'slug': 'style-social',
            'description': 'Learns through discussion, community interaction, and collaboration',
        },
    ]

    for item in learning_styles:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'learning_style',
                'is_active': True,
            },
        )

    # =========================================================================
    # ROLE - Job function/audience (multi-select)
    # Merged from previous audience + role taxonomies
    # Prefix: role-*
    # =========================================================================
    roles = [
        # Technical roles
        {
            'name': 'Developer',
            'slug': 'role-developer',
            'description': 'Software developer, engineer, or programmer',
        },
        {
            'name': 'Designer',
            'slug': 'role-designer',
            'description': 'UI/UX designer, product designer, or graphic designer',
        },
        {
            'name': 'Data Professional',
            'slug': 'role-data',
            'description': 'Data analyst, data scientist, or analytics professional',
        },
        # Business roles
        {
            'name': 'Product Manager',
            'slug': 'role-product-manager',
            'description': 'Product management and strategy',
        },
        {
            'name': 'Founder/Entrepreneur',
            'slug': 'role-founder',
            'description': 'Founder, CEO, or entrepreneur building a business',
        },
        {
            'name': 'Marketer',
            'slug': 'role-marketer',
            'description': 'Marketing, growth, or content professional',
        },
        # Creator roles
        {
            'name': 'Content Creator',
            'slug': 'role-creator',
            'description': 'Content creators, influencers, and media producers',
        },
        {
            'name': 'No-Code Builder',
            'slug': 'role-no-code',
            'description': 'No-code and low-code builders',
        },
        # Learning roles
        {
            'name': 'Student',
            'slug': 'role-student',
            'description': 'Student or full-time learner',
        },
        {
            'name': 'Hobbyist',
            'slug': 'role-hobbyist',
            'description': 'Personal interest, side projects, or casual exploration',
        },
        # Non-technical
        {
            'name': 'Non-Technical User',
            'slug': 'role-non-technical',
            'description': 'Non-technical users and general audiences',
        },
    ]

    for item in roles:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'role',
                'is_active': True,
            },
        )


def remove_new_taxonomies(apps, schema_editor):
    """Remove the seeded taxonomies (reverse migration)."""
    Taxonomy = apps.get_model('core', 'Taxonomy')
    Taxonomy.objects.filter(
        taxonomy_type__in=[
            'content_type',
            'time_investment',
            'difficulty',
            'pricing',
            'personality',
            'learning_style',
            'role',
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0054_alter_taxonomy_type_add_new_types'),
    ]

    operations = [
        migrations.RunPython(seed_new_taxonomies, remove_new_taxonomies),
    ]
