# Generated by Django 5.1.15 on 2025-12-19 18:28
# Consolidated migration: Removes deprecated topic fields and adds Taxonomy M2M fields

from django.db import migrations, models


def cleanup_deprecated_fields(apps, schema_editor):
    """Clean up deprecated topic fields - idempotent operations."""
    connection = schema_editor.connection
    quote_name = connection.ops.quote_name

    with connection.cursor() as cursor:
        # Remove index if exists
        cursor.execute('SELECT 1 FROM pg_indexes WHERE indexname = %s', ['core_quiz_topic_1f44c9_idx'])
        if cursor.fetchone():
            cursor.execute(f'DROP INDEX IF EXISTS {quote_name("core_quiz_topic_1f44c9_idx")}')

        # Drop old M2M tables if they exist (from topics_taxonomy fields)
        for table_name in ['core_project_topics_taxonomy', 'core_quiz_topics_taxonomy']:
            cursor.execute('SELECT 1 FROM information_schema.tables WHERE table_name = %s', [table_name])
            if cursor.fetchone():
                cursor.execute(f'DROP TABLE IF EXISTS {quote_name(table_name)} CASCADE')

        # Remove quiz.topic column if exists (old CharField)
        cursor.execute(
            'SELECT 1 FROM information_schema.columns WHERE table_name = %s AND column_name = %s',
            ['core_quiz', 'topic'],
        )
        if cursor.fetchone():
            cursor.execute(f'ALTER TABLE {quote_name("core_quiz")} DROP COLUMN IF EXISTS {quote_name("topic")}')


def reverse_cleanup(apps, schema_editor):
    """
    Reverse migration - recreates old fields.
    Note: Data will be lost, this only recreates schema.
    """
    connection = schema_editor.connection
    quote_name = connection.ops.quote_name

    with connection.cursor() as cursor:
        # Recreate quiz.topic CharField if it doesn't exist
        cursor.execute(
            'SELECT 1 FROM information_schema.columns WHERE table_name = %s AND column_name = %s',
            ['core_quiz', 'topic'],
        )
        if not cursor.fetchone():
            cursor.execute(
                f'ALTER TABLE {quote_name("core_quiz")} ' f'ADD COLUMN {quote_name("topic")} varchar(50) DEFAULT %s',
                [''],
            )

        # Recreate index
        cursor.execute('SELECT 1 FROM pg_indexes WHERE indexname = %s', ['core_quiz_topic_1f44c9_idx'])
        if not cursor.fetchone():
            cursor.execute(
                f'CREATE INDEX {quote_name("core_quiz_topic_1f44c9_idx")} '
                f'ON {quote_name("core_quiz")} ({quote_name("topic")})'
            )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0055_seed_new_taxonomy_types'),
    ]

    operations = [
        # Run custom cleanup with proper reverse function
        migrations.RunPython(cleanup_deprecated_fields, reverse_cleanup),
        # Update Django's model state to match database
        # Remove old fields from state, then add new M2M fields
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='project',
                    name='topics_taxonomy',
                ),
                migrations.RemoveField(
                    model_name='quiz',
                    name='topic',
                ),
                migrations.RemoveField(
                    model_name='quiz',
                    name='topics_taxonomy',
                ),
                migrations.RemoveField(
                    model_name='project',
                    name='topics',
                ),
                migrations.RemoveField(
                    model_name='quiz',
                    name='topics',
                ),
                # Also remove the index from state
                migrations.RemoveIndex(
                    model_name='quiz',
                    name='core_quiz_topic_1f44c9_idx',
                ),
            ],
            database_operations=[],
        ),
        # Add the new M2M fields pointing to Taxonomy
        migrations.AddField(
            model_name='project',
            name='topics',
            field=models.ManyToManyField(
                blank=True,
                help_text='Topic taxonomies for this project',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'topic'},
                related_name='topic_projects',
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topics',
            field=models.ManyToManyField(
                blank=True,
                help_text='Topic taxonomies for this quiz',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'topic'},
                related_name='topic_quizzes',
                to='core.taxonomy',
            ),
        ),
    ]
