# Generated by Django 5.1.15 on 2025-12-19

"""
Remove unique constraint from Taxonomy.name field.

This allows the same name to be used across different taxonomy types.
For example, "Audio" can exist as both a topic and a learning_style.
The slug field remains unique as the primary identifier.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0056_cleanup_deprecated_topic_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
