# Generated by Django 5.1.15 on 2025-12-19

"""
Fix taxonomy slugs to have consistent prefixes and add missing taxonomy types.

This migration:
1. Updates existing content_type, time_investment, difficulty, pricing slugs to have prefixes
2. Seeds personality (MBTI types), learning_style, and role taxonomies
"""

from django.db import migrations


def update_and_seed_taxonomies(apps, schema_editor):
    """Update existing slugs and seed missing taxonomies."""
    Taxonomy = apps.get_model('core', 'Taxonomy')

    # =========================================================================
    # UPDATE EXISTING SLUGS - Add prefixes for consistency
    # =========================================================================

    # Content type slug updates
    content_type_renames = [
        ('article', 'content-article'),
        ('battle', 'content-battle'),
        ('chat-prompt', 'content-chat-prompt'),
        ('code-repo', 'content-code-repo'),
        ('course', 'content-course'),
        ('ebook', 'content-ebook'),
        ('image', 'content-image'),
        ('prompt-pack', 'content-prompt-pack'),
        ('quiz', 'content-quiz'),
        ('side-quest', 'content-side-quest'),
        ('template', 'content-template'),
        ('video', 'content-video'),
        ('website', 'content-website'),
        ('automation', 'content-automation'),
    ]

    for old_slug, new_slug in content_type_renames:
        Taxonomy.objects.filter(slug=old_slug, taxonomy_type='content_type').update(slug=new_slug)

    # Time investment slug updates
    time_renames = [
        ('quick', 'time-quick'),
        ('short', 'time-short'),
        ('medium', 'time-medium'),
        ('deep-dive', 'time-deep-dive'),
    ]

    for old_slug, new_slug in time_renames:
        Taxonomy.objects.filter(slug=old_slug, taxonomy_type='time_investment').update(slug=new_slug)

    # Difficulty slug updates
    difficulty_renames = [
        ('beginner', 'level-beginner'),
        ('intermediate', 'level-intermediate'),
        ('advanced', 'level-advanced'),
    ]

    for old_slug, new_slug in difficulty_renames:
        Taxonomy.objects.filter(slug=old_slug, taxonomy_type='difficulty').update(slug=new_slug)

    # Pricing slug updates
    pricing_renames = [
        ('free', 'pricing-free'),
        ('freemium', 'pricing-freemium'),
        ('paid', 'pricing-paid'),
    ]

    for old_slug, new_slug in pricing_renames:
        Taxonomy.objects.filter(slug=old_slug, taxonomy_type='pricing').update(slug=new_slug)

    # =========================================================================
    # PERSONALITY - Myers-Briggs Type Indicator (MBTI) personality types
    # No prefix needed - MBTI codes are unique
    # =========================================================================
    personality_types = [
        # Analysts
        {
            'name': 'INTJ - Architect',
            'slug': 'intj',
            'description': 'Imaginative and strategic thinkers with a plan for everything',
        },
        {
            'name': 'INTP - Logician',
            'slug': 'intp',
            'description': 'Innovative inventors with an unquenchable thirst for knowledge',
        },
        {
            'name': 'ENTJ - Commander',
            'slug': 'entj',
            'description': 'Bold, imaginative and strong-willed leaders who always find a way',
        },
        {
            'name': 'ENTP - Debater',
            'slug': 'entp',
            'description': 'Smart and curious thinkers who love intellectual challenges',
        },
        # Diplomats
        {
            'name': 'INFJ - Advocate',
            'slug': 'infj',
            'description': 'Quiet and mystical idealists who are inspiring and tireless',
        },
        {
            'name': 'INFP - Mediator',
            'slug': 'infp',
            'description': 'Poetic, kind and altruistic people always eager to help a good cause',
        },
        {
            'name': 'ENFJ - Protagonist',
            'slug': 'enfj',
            'description': 'Charismatic and inspiring leaders who mesmerize their listeners',
        },
        {
            'name': 'ENFP - Campaigner',
            'slug': 'enfp',
            'description': 'Enthusiastic, creative and sociable free spirits who find joy everywhere',
        },
        # Sentinels
        {
            'name': 'ISTJ - Logistician',
            'slug': 'istj',
            'description': 'Practical and fact-minded individuals whose reliability cannot be doubted',
        },
        {
            'name': 'ISFJ - Defender',
            'slug': 'isfj',
            'description': 'Very dedicated and warm protectors, always ready to defend their loved ones',
        },
        {
            'name': 'ESTJ - Executive',
            'slug': 'estj',
            'description': 'Excellent administrators, unsurpassed at managing things or people',
        },
        {
            'name': 'ESFJ - Consul',
            'slug': 'esfj',
            'description': 'Extraordinarily caring, social and popular people, always ready to help',
        },
        # Explorers
        {
            'name': 'ISTP - Virtuoso',
            'slug': 'istp',
            'description': 'Bold and practical experimenters, masters of all kinds of tools',
        },
        {
            'name': 'ISFP - Adventurer',
            'slug': 'isfp',
            'description': 'Flexible and charming artists, always ready to explore something new',
        },
        {
            'name': 'ESTP - Entrepreneur',
            'slug': 'estp',
            'description': 'Smart, energetic and perceptive people who truly enjoy living on the edge',
        },
        {
            'name': 'ESFP - Entertainer',
            'slug': 'esfp',
            'description': 'Spontaneous, energetic and enthusiastic entertainers who love life',
        },
    ]

    for item in personality_types:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'personality',
                'is_active': True,
            },
        )

    # =========================================================================
    # LEARNING STYLE - How users learn best
    # Prefix: style-* (slug only, name can be simple since unique=False now)
    # =========================================================================
    learning_styles = [
        {
            'name': 'Visual',
            'slug': 'style-visual',
            'description': 'Learns best through images, diagrams, charts, and videos',
        },
        {
            'name': 'Reading/Writing',
            'slug': 'style-reading',
            'description': 'Prefers written content, documentation, and text-based learning',
        },
        {
            'name': 'Hands-On',
            'slug': 'style-hands-on',
            'description': 'Learns by doing - projects, exercises, and practical application',
        },
        {
            'name': 'Audio',
            'slug': 'style-audio',
            'description': 'Prefers podcasts, verbal explanations, and audio content',
        },
        {
            'name': 'Social',
            'slug': 'style-social',
            'description': 'Learns through discussion, community interaction, and collaboration',
        },
    ]

    for item in learning_styles:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'learning_style',
                'is_active': True,
            },
        )

    # =========================================================================
    # ROLE - Job function/audience (multi-select)
    # Merged from previous audience + role taxonomies
    # Prefix: role-* (slug only, name can be simple since unique=False now)
    # =========================================================================
    roles = [
        # Technical roles
        {
            'name': 'Developer',
            'slug': 'role-developer',
            'description': 'Software developer, engineer, or programmer',
        },
        {
            'name': 'Designer',
            'slug': 'role-designer',
            'description': 'UI/UX designer, product designer, or graphic designer',
        },
        {
            'name': 'Data Professional',
            'slug': 'role-data',
            'description': 'Data analyst, data scientist, or analytics professional',
        },
        # Business roles
        {
            'name': 'Product Manager',
            'slug': 'role-product-manager',
            'description': 'Product management and strategy',
        },
        {
            'name': 'Founder/Entrepreneur',
            'slug': 'role-founder',
            'description': 'Founder, CEO, or entrepreneur building a business',
        },
        {
            'name': 'Marketer',
            'slug': 'role-marketer',
            'description': 'Marketing, growth, or content professional',
        },
        # Creator roles
        {
            'name': 'Content Creator',
            'slug': 'role-creator',
            'description': 'Content creators, influencers, and media producers',
        },
        {
            'name': 'No-Code Builder',
            'slug': 'role-no-code',
            'description': 'No-code and low-code builders',
        },
        # Learning roles
        {
            'name': 'Student',
            'slug': 'role-student',
            'description': 'Student or full-time learner',
        },
        {
            'name': 'Hobbyist',
            'slug': 'role-hobbyist',
            'description': 'Personal interest, side projects, or casual exploration',
        },
        # Non-technical
        {
            'name': 'Non-Technical User',
            'slug': 'role-non-technical',
            'description': 'Non-technical users and general audiences',
        },
    ]

    for item in roles:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'role',
                'is_active': True,
            },
        )


def reverse_updates(apps, schema_editor):
    """Reverse the slug updates and remove new taxonomies."""
    Taxonomy = apps.get_model('core', 'Taxonomy')

    # Reverse content type slugs
    content_type_renames = [
        ('content-article', 'article'),
        ('content-battle', 'battle'),
        ('content-chat-prompt', 'chat-prompt'),
        ('content-code-repo', 'code-repo'),
        ('content-course', 'course'),
        ('content-ebook', 'ebook'),
        ('content-image', 'image'),
        ('content-prompt-pack', 'prompt-pack'),
        ('content-quiz', 'quiz'),
        ('content-side-quest', 'side-quest'),
        ('content-template', 'template'),
        ('content-video', 'video'),
        ('content-website', 'website'),
        ('content-automation', 'automation'),
    ]

    for old_slug, new_slug in content_type_renames:
        Taxonomy.objects.filter(slug=old_slug, taxonomy_type='content_type').update(slug=new_slug)

    # Reverse time investment slugs
    time_renames = [
        ('time-quick', 'quick'),
        ('time-short', 'short'),
        ('time-medium', 'medium'),
        ('time-deep-dive', 'deep-dive'),
    ]

    for old_slug, new_slug in time_renames:
        Taxonomy.objects.filter(slug=old_slug, taxonomy_type='time_investment').update(slug=new_slug)

    # Reverse difficulty slugs
    difficulty_renames = [
        ('level-beginner', 'beginner'),
        ('level-intermediate', 'intermediate'),
        ('level-advanced', 'advanced'),
    ]

    for old_slug, new_slug in difficulty_renames:
        Taxonomy.objects.filter(slug=old_slug, taxonomy_type='difficulty').update(slug=new_slug)

    # Reverse pricing slugs
    pricing_renames = [
        ('pricing-free', 'free'),
        ('pricing-freemium', 'freemium'),
        ('pricing-paid', 'paid'),
    ]

    for old_slug, new_slug in pricing_renames:
        Taxonomy.objects.filter(slug=old_slug, taxonomy_type='pricing').update(slug=new_slug)

    # Remove new taxonomies
    Taxonomy.objects.filter(taxonomy_type__in=['personality', 'learning_style', 'role']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0057_alter_taxonomy_name_remove_unique'),
    ]

    operations = [
        migrations.RunPython(update_and_seed_taxonomies, reverse_updates),
    ]
