# Generated by Django 5.1.15 on 2025-12-20 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0058_update_taxonomy_slugs_and_add_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_tag_metadata',
            field=models.JSONField(
                blank=True, default=dict, help_text='AI-generated tag metadata: {field: {confidence, model, timestamp}}'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='content_type_taxonomy',
            field=models.ForeignKey(
                blank=True,
                help_text='Content format (article, video, code-repo, course, etc.)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'content_type'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects_of_type',
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='difficulty_taxonomy',
            field=models.ForeignKey(
                blank=True,
                help_text='Content difficulty level (beginner, intermediate, advanced)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'difficulty'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects_with_difficulty',
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='pricing_taxonomy',
            field=models.ForeignKey(
                blank=True,
                help_text='Pricing tier (free, freemium, paid)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'pricing'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects_with_pricing',
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='time_investment',
            field=models.ForeignKey(
                blank=True,
                help_text='Time to consume (quick, short, medium, deep-dive)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'time_investment'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects_with_time',
                to='core.taxonomy',
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='difficulty_level',
            field=models.CharField(
                blank=True,
                choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')],
                db_index=True,
                default='',
                help_text='DEPRECATED: Use difficulty_taxonomy. Content difficulty for personalization.',
                max_length=20,
            ),
        ),
    ]
