# Generated by Django 5.1.15 on 2025-12-20
# Drops the legacy topics ArrayField column that was missed in migration 0056

from django.db import migrations


def drop_legacy_topics_columns(apps, schema_editor):
    """
    Drop the legacy 'topics' ArrayField columns from core_project and core_quiz.

    Migration 0056 removed these from Django's model state but didn't actually
    drop the database columns, causing NOT NULL constraint violations when
    creating new projects.
    """
    connection = schema_editor.connection
    quote_name = connection.ops.quote_name

    with connection.cursor() as cursor:
        # Check and drop topics column from core_project
        cursor.execute(
            """
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_name = 'core_project' AND column_name = 'topics'
            """
        )
        result = cursor.fetchone()
        if result and result[1] == 'ARRAY':
            print("Dropping legacy 'topics' ArrayField column from core_project...")
            cursor.execute(f'ALTER TABLE {quote_name("core_project")} DROP COLUMN IF EXISTS {quote_name("topics")}')
            print('Dropped core_project.topics column')

        # Check and drop topics column from core_quiz
        cursor.execute(
            """
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_name = 'core_quiz' AND column_name = 'topics'
            """
        )
        result = cursor.fetchone()
        if result and result[1] == 'ARRAY':
            print("Dropping legacy 'topics' ArrayField column from core_quiz...")
            cursor.execute(f'ALTER TABLE {quote_name("core_quiz")} DROP COLUMN IF EXISTS {quote_name("topics")}')
            print('Dropped core_quiz.topics column')


def recreate_legacy_topics_columns(apps, schema_editor):
    """
    Reverse migration - recreates the legacy topics ArrayField columns.
    Note: This only recreates the schema, data will be empty.
    """
    connection = schema_editor.connection
    quote_name = connection.ops.quote_name

    with connection.cursor() as cursor:
        # Recreate topics column on core_project if it doesn't exist
        cursor.execute(
            """
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'core_project' AND column_name = 'topics'
            """
        )
        if not cursor.fetchone():
            cursor.execute(
                f"""
                ALTER TABLE {quote_name("core_project")}
                ADD COLUMN {quote_name("topics")} varchar(50)[] NOT NULL DEFAULT '{{}}'
                """
            )

        # Recreate topics column on core_quiz if it doesn't exist
        cursor.execute(
            """
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'core_quiz' AND column_name = 'topics'
            """
        )
        if not cursor.fetchone():
            cursor.execute(
                f"""
                ALTER TABLE {quote_name("core_quiz")}
                ADD COLUMN {quote_name("topics")} varchar(50)[] NOT NULL DEFAULT '{{}}'
                """
            )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0063_populate_quiz_difficulty_taxonomy'),
    ]

    operations = [
        migrations.RunPython(drop_legacy_topics_columns, recreate_legacy_topics_columns),
    ]
