# Generated by Django 5.1.15 on 2025-12-20 03:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0064_drop_legacy_topics_array_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_indexed_at',
            field=models.DateTimeField(
                blank=True, db_index=True, help_text='When this content was last indexed in Weaviate', null=True
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='weaviate_uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, help_text='Stable UUID for Weaviate object reference'
            ),
        ),
        migrations.AddField(
            model_name='quiz',
            name='last_indexed_at',
            field=models.DateTimeField(
                blank=True, db_index=True, help_text='When this content was last indexed in Weaviate', null=True
            ),
        ),
        migrations.AddField(
            model_name='quiz',
            name='weaviate_uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, help_text='Stable UUID for Weaviate object reference'
            ),
        ),
    ]
