# Generated by Django 5.1.15 on 2025-12-20
"""
Seed user matching taxonomies for the UserRecommendationService.

These taxonomies enable matching users based on shared:
- goals: What users want to achieve
- interests: Topics users are passionate about
- industries: Professional domains users work in

This migration is required for the find_people_to_connect Ava tool.
"""

from django.db import migrations


def seed_user_matching_taxonomies(apps, schema_editor):
    """Seed goals, interests, and industries for user matching."""
    Taxonomy = apps.get_model('core', 'Taxonomy')

    # =========================================================================
    # GOALS - What users want to achieve
    # Prefix: goal-*
    # =========================================================================
    goals = [
        {
            'name': 'Learn New Skills',
            'slug': 'goal-learn-skills',
            'description': 'Learn new AI tools, techniques, and skills to expand capabilities',
        },
        {
            'name': 'Build Projects',
            'slug': 'goal-build-projects',
            'description': 'Create and ship projects using AI-powered tools',
        },
        {
            'name': 'Start a Business',
            'slug': 'goal-start-business',
            'description': 'Launch a business or side project leveraging AI tools',
        },
        {
            'name': 'Find Collaborators',
            'slug': 'goal-find-collaborators',
            'description': 'Connect with others to collaborate on projects and ideas',
        },
        {
            'name': 'Grow My Career',
            'slug': 'goal-career-growth',
            'description': 'Advance career through AI skills and project portfolio',
        },
        {
            'name': 'Stay Current with AI',
            'slug': 'goal-stay-current',
            'description': 'Keep up with the latest AI tools, trends, and developments',
        },
    ]

    for item in goals:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'goal',
                'is_active': True,
            },
        )

    # =========================================================================
    # INTERESTS - Topics users are passionate about
    # Prefix: interest-*
    # =========================================================================
    interests = [
        {
            'name': 'AI & Machine Learning',
            'slug': 'interest-ai-ml',
            'description': 'Artificial intelligence, machine learning, neural networks, and LLMs',
        },
        {
            'name': 'Web Development',
            'slug': 'interest-web-dev',
            'description': 'Frontend, backend, and full-stack web development',
        },
        {
            'name': 'Design & UX',
            'slug': 'interest-design',
            'description': 'UI/UX design, visual design, and user experience',
        },
        {
            'name': 'Data Science',
            'slug': 'interest-data-science',
            'description': 'Data analysis, visualization, and data-driven decision making',
        },
        {
            'name': 'Automation & Workflows',
            'slug': 'interest-automation',
            'description': 'Process automation, workflow optimization, and integrations',
        },
        {
            'name': 'Mobile Development',
            'slug': 'interest-mobile',
            'description': 'iOS, Android, and cross-platform mobile app development',
        },
        {
            'name': 'Content Creation',
            'slug': 'interest-content-creation',
            'description': 'Writing, video production, and multimedia content',
        },
        {
            'name': 'No-Code Tools',
            'slug': 'interest-no-code',
            'description': 'Building with no-code and low-code platforms',
        },
    ]

    for item in interests:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'interest',
                'is_active': True,
            },
        )

    # =========================================================================
    # INDUSTRIES - Professional domains
    # Prefix: industry-*
    # =========================================================================
    industries = [
        {
            'name': 'Technology',
            'slug': 'industry-technology',
            'description': 'Software, hardware, and tech services',
        },
        {
            'name': 'Healthcare',
            'slug': 'industry-healthcare',
            'description': 'Medical, health tech, and wellness',
        },
        {
            'name': 'Finance',
            'slug': 'industry-finance',
            'description': 'Banking, fintech, and financial services',
        },
        {
            'name': 'Education',
            'slug': 'industry-education',
            'description': 'EdTech, learning, and academic institutions',
        },
        {
            'name': 'Marketing & Advertising',
            'slug': 'industry-marketing',
            'description': 'Digital marketing, advertising, and brand strategy',
        },
        {
            'name': 'E-commerce',
            'slug': 'industry-ecommerce',
            'description': 'Online retail, marketplaces, and D2C brands',
        },
        {
            'name': 'Media & Entertainment',
            'slug': 'industry-media',
            'description': 'Content, streaming, gaming, and entertainment',
        },
    ]

    for item in industries:
        Taxonomy.objects.get_or_create(
            slug=item['slug'],
            defaults={
                **item,
                'taxonomy_type': 'industry',
                'is_active': True,
            },
        )


def remove_user_matching_taxonomies(apps, schema_editor):
    """Remove the seeded taxonomies (reverse migration)."""
    Taxonomy = apps.get_model('core', 'Taxonomy')
    Taxonomy.objects.filter(
        taxonomy_type__in=['goal', 'interest', 'industry'],
        slug__startswith='goal-',
    ).delete()
    Taxonomy.objects.filter(
        taxonomy_type__in=['goal', 'interest', 'industry'],
        slug__startswith='interest-',
    ).delete()
    Taxonomy.objects.filter(
        taxonomy_type__in=['goal', 'interest', 'industry'],
        slug__startswith='industry-',
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0066_add_game_content_type'),
    ]

    operations = [
        migrations.RunPython(seed_user_matching_taxonomies, remove_user_matching_taxonomies),
    ]
