# Generated by Django 5.1.15 on 2025-12-20 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0067_seed_user_matching_taxonomies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(
                choices=[
                    ('github_repo', 'GitHub Repository'),
                    ('gitlab_project', 'GitLab Project'),
                    ('figma_design', 'Figma Design'),
                    ('image_collection', 'Image Collection'),
                    ('prompt', 'Prompt / Conversation'),
                    ('video', 'Video'),
                    ('reddit_thread', 'Reddit Thread'),
                    ('rss_article', 'RSS Article'),
                    ('battle', 'Prompt Battle'),
                    ('product', 'Digital Product'),
                    ('clipped', 'Clipped'),
                    ('game', 'Game'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name='ProjectDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'reason',
                    models.CharField(
                        choices=[
                            ('not_interested', 'Not Interested'),
                            ('seen_before', 'Already Seen'),
                            ('wrong_topic', 'Wrong Topic'),
                            ('too_basic', 'Too Basic'),
                            ('too_advanced', 'Too Advanced'),
                        ],
                        default='not_interested',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='core.project'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='dismissed_projects',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project Dismissal',
                'verbose_name_plural': 'Project Dismissals',
                'indexes': [
                    models.Index(fields=['user', '-created_at'], name='core_projec_user_id_ec4f47_idx'),
                    models.Index(fields=['project'], name='core_projec_project_1d8c74_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project_dismissal')
                ],
            },
        ),
    ]
