# Generated by Django 5.1.15 on 2025-12-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0069_add_ai_lesson_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_timeless',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Timeless content - mixed into feeds regardless of creation date (e.g., games)',
            ),
        ),
    ]
