# Generated by Django 5.1.15 on 2025-12-26 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0070_add_is_timeless_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='WebSocket conversation ID (e.g., ember-home-123, sage-learn-456)',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(
                choices=[
                    ('ember_home', 'Ember Home Chat'),
                    ('ember_chat', 'Ember Sidebar Chat'),
                    ('sage_learn', 'Sage Learning Chat'),
                    ('avatar', 'Avatar Generation'),
                    ('image', 'Image Generation'),
                ],
                db_index=True,
                default='ember_home',
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(
                condition=models.Q(('user__isnull', False), _negated=False) & ~models.Q(('conversation_id', '')),
                fields=('user', 'conversation_id'),
                name='unique_user_conversation_id',
            ),
        ),
    ]
