# Generated by Django 5.1.15 on 2025-12-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0071_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(
                choices=[
                    ('ember_chat', 'Ember Sidebar Chat'),
                    ('ember_learn', 'Ember Learn Chat'),
                    ('ember_explore', 'Ember Explore Chat'),
                    ('learning_path', 'Learning Path Chat'),
                    ('avatar', 'Avatar Generation'),
                    ('image', 'Image Generation'),
                ],
                db_index=True,
                default='ember_home',
                max_length=50,
            ),
        ),
    ]
