# Generated by Django 5.1.15 on 2026-01-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0072_rename_ember_to_ava_conversations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(
                choices=[
                    ('github_repo', 'GitHub Repository'),
                    ('gitlab_project', 'GitLab Project'),
                    ('figma_design', 'Figma Design'),
                    ('image_collection', 'Image Collection'),
                    ('prompt', 'Prompt / Conversation'),
                    ('video', 'Video'),
                    ('reddit_thread', 'Reddit Thread'),
                    ('rss_article', 'RSS Article'),
                    ('battle', 'Prompt Battle'),
                    ('product', 'Digital Product'),
                    ('clipped', 'Clipped'),
                    ('game', 'Game'),
                    ('social_clip', 'Social Clip'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=32,
            ),
        ),
    ]
