import { useState, useCallback, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDownTrayIcon, FolderPlusIcon, XMarkIcon } from '@heroicons/react/24/outline';

interface ProjectCreatedResult {
  projectUrl: string;
  projectTitle: string;
}

interface GeneratedImageMessageProps {
  imageUrl: string;
  filename: string;
  sessionId?: number;
  iterationNumber?: number;
  onCreateProject?: (sessionId: number) => Promise<ProjectCreatedResult>;
}

/**
 * GeneratedImageMessage - Display a generated image in the chat with download and create project options
 *
 * Features:
 * - Display the generated image
 * - Download button to save the image
 * - "Create Project" button to create a project from the image
 */
export function GeneratedImageMessage({
  imageUrl,
  filename,
  sessionId,
  iterationNumber,
  onCreateProject,
}: GeneratedImageMessageProps) {
  const [isCreatingProject, setIsCreatingProject] = useState(false);
  const [projectCreated, setProjectCreated] = useState<ProjectCreatedResult | null>(null);
  const [imageLoaded, setImageLoaded] = useState(false);
  const [imageError, setImageError] = useState(false);
  const [isOverlayOpen, setIsOverlayOpen] = useState(false);

  // Handle escape key to close overlay
  const handleKeyDown = useCallback((e: KeyboardEvent) => {
    if (e.key === 'Escape') {
      setIsOverlayOpen(false);
    }
  }, []);

  useEffect(() => {
    if (isOverlayOpen) {
      document.addEventListener('keydown', handleKeyDown);
      document.body.style.overflow = 'hidden';
      return () => {
        document.removeEventListener('keydown', handleKeyDown);
        document.body.style.overflow = '';
      };
    }
  }, [isOverlayOpen, handleKeyDown]);

  const handleDownload = async () => {
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename || 'nano-banana-image.png';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Failed to download image:', error);
    }
  };

  const handleCreateProject = async () => {
    if (!onCreateProject || !sessionId) return;
    setIsCreatingProject(true);
    try {
      const result = await onCreateProject(sessionId);
      setProjectCreated(result);
    } catch (error) {
      console.error('Failed to create project:', error);
    } finally {
      setIsCreatingProject(false);
    }
  };

  return (
    <>
      <div className="rounded-lg overflow-hidden bg-gray-50 dark:bg-gray-800 p-3 max-w-md">
        {/* Image container with loading state - clickable to open overlay */}
        <button
          type="button"
          onClick={() => imageLoaded && !imageError && setIsOverlayOpen(true)}
          className="relative aspect-video bg-gray-200 dark:bg-gray-700 rounded-lg overflow-hidden w-full cursor-zoom-in focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:ring-offset-2"
          disabled={!imageLoaded || imageError}
        >
          {!imageLoaded && !imageError && (
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="animate-pulse flex flex-col items-center gap-2">
                <div className="w-8 h-8 border-2 border-primary-500 border-t-transparent rounded-full animate-spin" />
                <span className="text-xs text-gray-500">Loading image...</span>
              </div>
            </div>
          )}
          {imageError ? (
            <div className="absolute inset-0 flex items-center justify-center text-gray-500">
              <span className="text-sm">Failed to load image</span>
            </div>
          ) : (
            <img
              src={imageUrl}
              alt="Generated by Nano Banana"
              className={`w-full h-full object-contain transition-opacity duration-300 ${
                imageLoaded ? 'opacity-100' : 'opacity-0'
              }`}
              onLoad={() => setImageLoaded(true)}
              onError={() => setImageError(true)}
            />
          )}
        </button>

      {/* Iteration indicator */}
      {iterationNumber && iterationNumber > 1 && (
        <div className="text-xs text-gray-500 dark:text-gray-400 mt-2 text-center">
          Iteration {iterationNumber}
        </div>
      )}

      {/* Action buttons */}
      <div className="flex flex-wrap gap-2 mt-3">
        <button
          onClick={handleDownload}
          className="flex-1 min-w-[120px] flex items-center justify-center gap-2 px-3 py-2 bg-primary-500 text-white rounded-lg text-sm font-medium hover:bg-primary-600 transition-colors"
        >
          <ArrowDownTrayIcon className="w-4 h-4" />
          Download
        </button>

        {/* Create Project button - only show if session exists and no project created yet */}
        {onCreateProject && sessionId && !projectCreated && (
          <button
            onClick={handleCreateProject}
            disabled={isCreatingProject}
            className="flex-1 min-w-[120px] flex items-center justify-center gap-2 px-3 py-2 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-lg text-sm font-medium hover:from-purple-600 hover:to-pink-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <FolderPlusIcon className="w-4 h-4" />
            {isCreatingProject ? 'Creating...' : 'Create Project'}
          </button>
        )}

        {/* Project created success state */}
        {projectCreated && (
          <Link
            to={projectCreated.projectUrl}
            className="flex-1 min-w-[120px] flex items-center justify-center gap-2 px-3 py-2 bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 rounded-lg text-sm font-medium hover:bg-green-200 dark:hover:bg-green-900/50 transition-colors cursor-pointer"
          >
            <span className="text-green-500">✓</span>
            View Project
          </Link>
        )}
      </div>
    </div>

      {/* Fullscreen overlay */}
      {isOverlayOpen && (
        <div
          className="fixed inset-0 z-[9999] bg-black/90 flex items-center justify-center p-4"
          onClick={() => setIsOverlayOpen(false)}
        >
          {/* Close button */}
          <button
            type="button"
            onClick={() => setIsOverlayOpen(false)}
            className="absolute top-4 right-4 p-2 text-white/70 hover:text-white transition-colors rounded-full hover:bg-white/10"
            aria-label="Close"
          >
            <XMarkIcon className="w-8 h-8" />
          </button>

          {/* Full-size image */}
          <img
            src={imageUrl}
            alt="Generated image (full size)"
            className="max-w-full max-h-full object-contain cursor-zoom-out"
            onClick={(e) => {
              e.stopPropagation();
              setIsOverlayOpen(false);
            }}
          />

          {/* Download button in overlay */}
          <button
            onClick={(e) => {
              e.stopPropagation();
              handleDownload();
            }}
            className="absolute bottom-6 left-1/2 -translate-x-1/2 flex items-center gap-2 px-5 py-2.5 bg-white text-gray-900 rounded-full text-sm font-semibold transition-all hover:bg-gray-100 shadow-lg"
          >
            <ArrowDownTrayIcon className="w-5 h-5" />
            Download
          </button>
        </div>
      )}
    </>
  );
}
