import { useState } from 'react';
import { ArrowDownTrayIcon, PhotoIcon, FolderPlusIcon } from '@heroicons/react/24/outline';

interface ProjectCreatedResult {
  projectUrl: string;
  projectTitle: string;
}

interface GeneratedImageMessageProps {
  imageUrl: string;
  filename: string;
  sessionId?: number;
  iterationNumber?: number;
  onUseAsFeaturedImage?: (imageUrl: string) => Promise<void>;
  onCreateProject?: (sessionId: number) => Promise<ProjectCreatedResult>;
}

/**
 * GeneratedImageMessage - Display a generated image in the chat with download and use options
 *
 * Features:
 * - Display the generated image
 * - Download button to save the image
 * - "Use as Featured" button to set as project's featured image
 */
export function GeneratedImageMessage({
  imageUrl,
  filename,
  sessionId,
  iterationNumber,
  onUseAsFeaturedImage,
  onCreateProject,
}: GeneratedImageMessageProps) {
  const [isSettingFeatured, setIsSettingFeatured] = useState(false);
  const [featuredSuccess, setFeaturedSuccess] = useState(false);
  const [isCreatingProject, setIsCreatingProject] = useState(false);
  const [projectCreated, setProjectCreated] = useState<ProjectCreatedResult | null>(null);
  const [imageLoaded, setImageLoaded] = useState(false);
  const [imageError, setImageError] = useState(false);

  const handleDownload = async () => {
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename || 'nano-banana-image.png';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Failed to download image:', error);
    }
  };

  const handleUseAsFeatured = async () => {
    if (!onUseAsFeaturedImage) return;
    setIsSettingFeatured(true);
    try {
      await onUseAsFeaturedImage(imageUrl);
      setFeaturedSuccess(true);
    } catch (error) {
      console.error('Failed to set as featured image:', error);
    } finally {
      setIsSettingFeatured(false);
    }
  };

  const handleCreateProject = async () => {
    if (!onCreateProject || !sessionId) return;
    setIsCreatingProject(true);
    try {
      const result = await onCreateProject(sessionId);
      setProjectCreated(result);
    } catch (error) {
      console.error('Failed to create project:', error);
    } finally {
      setIsCreatingProject(false);
    }
  };

  return (
    <div className="rounded-lg overflow-hidden bg-gray-50 dark:bg-gray-800 p-3 max-w-md">
      {/* Image container with loading state */}
      <div className="relative aspect-video bg-gray-200 dark:bg-gray-700 rounded-lg overflow-hidden">
        {!imageLoaded && !imageError && (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="animate-pulse flex flex-col items-center gap-2">
              <div className="w-8 h-8 border-2 border-primary-500 border-t-transparent rounded-full animate-spin" />
              <span className="text-xs text-gray-500">Loading image...</span>
            </div>
          </div>
        )}
        {imageError ? (
          <div className="absolute inset-0 flex items-center justify-center text-gray-500">
            <span className="text-sm">Failed to load image</span>
          </div>
        ) : (
          <img
            src={imageUrl}
            alt="Generated by Nano Banana"
            className={`w-full h-full object-contain transition-opacity duration-300 ${
              imageLoaded ? 'opacity-100' : 'opacity-0'
            }`}
            onLoad={() => setImageLoaded(true)}
            onError={() => setImageError(true)}
          />
        )}
      </div>

      {/* Iteration indicator */}
      {iterationNumber && iterationNumber > 1 && (
        <div className="text-xs text-gray-500 dark:text-gray-400 mt-2 text-center">
          Iteration {iterationNumber}
        </div>
      )}

      {/* Action buttons */}
      <div className="flex flex-wrap gap-2 mt-3">
        <button
          onClick={handleDownload}
          className="flex-1 min-w-[120px] flex items-center justify-center gap-2 px-3 py-2 bg-primary-500 text-white rounded-lg text-sm font-medium hover:bg-primary-600 transition-colors"
        >
          <ArrowDownTrayIcon className="w-4 h-4" />
          Download
        </button>

        {onUseAsFeaturedImage && !featuredSuccess && (
          <button
            onClick={handleUseAsFeatured}
            disabled={isSettingFeatured}
            className="flex-1 min-w-[120px] flex items-center justify-center gap-2 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <PhotoIcon className="w-4 h-4" />
            {isSettingFeatured ? 'Setting...' : 'Use as Featured'}
          </button>
        )}

        {featuredSuccess && (
          <div className="flex-1 min-w-[120px] flex items-center justify-center gap-2 px-3 py-2 bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 rounded-lg text-sm font-medium">
            <span className="text-green-500">✓</span>
            Set as Featured
          </div>
        )}

        {/* Create Project button - only show if session exists and no project created yet */}
        {onCreateProject && sessionId && !projectCreated && (
          <button
            onClick={handleCreateProject}
            disabled={isCreatingProject}
            className="flex-1 min-w-[120px] flex items-center justify-center gap-2 px-3 py-2 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-lg text-sm font-medium hover:from-purple-600 hover:to-pink-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <FolderPlusIcon className="w-4 h-4" />
            {isCreatingProject ? 'Creating...' : 'Create Project'}
          </button>
        )}

        {/* Project created success state */}
        {projectCreated && (
          <a
            href={projectCreated.projectUrl}
            className="flex-1 min-w-[120px] flex items-center justify-center gap-2 px-3 py-2 bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 rounded-lg text-sm font-medium hover:bg-green-200 dark:hover:bg-green-900/50 transition-colors"
          >
            <span className="text-green-500">✓</span>
            View Project
          </a>
        )}
      </div>
    </div>
  );
}
