# Generated by Django 5.0.14 on 2025-11-20 17:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'activity_type',
                    models.CharField(
                        choices=[
                            ('quiz_completed', 'Quiz Completed'),
                            ('quiz_perfect_score', 'Quiz Perfect Score'),
                            ('quiz_streak', 'Quiz Streak'),
                            ('project_created', 'Project Created'),
                            ('project_published', 'Project Published'),
                            ('project_milestone', 'Project Milestone'),
                            ('daily_login', 'Daily Login'),
                            ('week_streak', 'Week Streak'),
                            ('month_streak', 'Month Streak'),
                            ('battle_participated', 'Battle Participated'),
                            ('battle_won', 'Battle Won'),
                            ('battle_completed', 'Battle Completed'),
                            ('profile_completed', 'Profile Completed'),
                            ('referral', 'Referral'),
                            ('achievement_earned', 'Achievement Earned'),
                            ('manual_award', 'Manual Award'),
                            ('manual_deduction', 'Manual Deduction'),
                        ],
                        help_text='Type of activity',
                        max_length=50,
                    ),
                ),
                ('points_awarded', models.IntegerField(help_text='Points awarded (can be negative for deductions)')),
                ('description', models.TextField(help_text='Human-readable description of why points were awarded')),
                (
                    'metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional data about the activity (e.g., quiz_id, score, etc.)',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='points_history',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Points History',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', '-created_at'], name='points_poin_user_id_929285_idx'),
                    models.Index(fields=['activity_type', '-created_at'], name='points_poin_activit_a808b1_idx'),
                ],
            },
        ),
    ]
