AWSTemplateFormatVersion: '2010-09-09'
Description: 'AllThrive AI - RDS PostgreSQL Database'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
    Description: Environment name for resource tagging

  DBInstanceClass:
    Type: String
    Default: db.t4g.micro  # Smallest instance for testing (~$12/mo vs $50/mo for medium)
    AllowedValues:
      - db.t4g.micro
      - db.t4g.small
      - db.t4g.medium
      - db.t4g.large
      - db.r6g.large
      - db.r6g.xlarge
    Description: RDS instance class (use db.t4g.medium+ for production)

  DBAllocatedStorage:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 1000
    Description: Allocated storage in GB

  DBMaxAllocatedStorage:
    Type: Number
    Default: 100
    MinValue: 20
    MaxValue: 1000
    Description: Maximum allocated storage for autoscaling (GB)

  DBName:
    Type: String
    Default: allthrive_ai
    Description: Database name

  DBMasterUsername:
    Type: String
    Default: allthrive
    NoEcho: true
    Description: Master username for the database

  MultiAZ:
    Type: String
    Default: 'false'  # Disabled for cost savings during testing (~$40/mo savings)
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable Multi-AZ deployment (enable for production HA)

  BackupRetentionPeriod:
    Type: Number
    Default: 1  # Minimum retention for testing (use 7+ for production)
    MinValue: 1
    MaxValue: 35
    Description: Backup retention period in days

Resources:
  # DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${EnvironmentName}-allthrive-db-subnet-group
      DBSubnetGroupDescription: Subnet group for AllThrive AI RDS
      SubnetIds:
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-PrivateSubnet1Id
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-PrivateSubnet2Id
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-PrivateSubnet3Id
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-db-subnet-group
        - Key: Environment
          Value: !Ref EnvironmentName

  # DB Parameter Group
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      DBParameterGroupName: !Sub ${EnvironmentName}-allthrive-pg18-params
      Description: Custom parameter group for PostgreSQL 18
      Family: postgres18
      Parameters:
        log_statement: all
        log_min_duration_statement: '1000'
        shared_preload_libraries: pg_stat_statements
        pg_stat_statements.track: all
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-pg18-params
        - Key: Environment
          Value: !Ref EnvironmentName

  # RDS Master Password (generated by Secrets Manager)
  DBMasterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/rds/master
      Description: Master credentials for AllThrive AI RDS instance
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBMasterUsername}"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-rds-master-secret
        - Key: Environment
          Value: !Ref EnvironmentName

  # RDS Instance
  DBInstance:
    Type: AWS::RDS::DBInstance
    DependsOn:
      - DBSubnetGroup
      - DBParameterGroup
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub ${EnvironmentName}-allthrive-postgres
      DBInstanceClass: !Ref DBInstanceClass
      Engine: postgres
      EngineVersion: '18.1'
      DBName: !Ref DBName
      MasterUsername: !Sub '{{resolve:secretsmanager:${DBMasterSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBMasterSecret}:SecretString:password}}'
      AllocatedStorage: !Ref DBAllocatedStorage
      MaxAllocatedStorage: !Ref DBMaxAllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      MultiAZ: !Ref MultiAZ
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !Ref DBParameterGroup
      VPCSecurityGroups:
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-RDSSecurityGroupId
      PubliclyAccessible: false
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'sun:04:00-sun:05:00'
      AutoMinorVersionUpgrade: true
      DeletionProtection: true
      # Performance Insights disabled for cost savings during testing
      EnablePerformanceInsights: false
      EnableCloudwatchLogsExports:
        - postgresql
        - upgrade
      CopyTagsToSnapshot: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-postgres
        - Key: Environment
          Value: !Ref EnvironmentName

  # Attach RDS to Secret for rotation
  DBSecretAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DBMasterSecret
      TargetId: !Ref DBInstance
      TargetType: AWS::RDS::DBInstance

  # CloudWatch Alarms
  DBCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-allthrive-rds-high-cpu
      AlarmDescription: CPU utilization is high
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstance

  DBStorageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-allthrive-rds-low-storage
      AlarmDescription: Free storage space is low
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5368709120  # 5 GB in bytes
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstance

  DBConnectionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-allthrive-rds-high-connections
      AlarmDescription: Database connections are high
      MetricName: DatabaseConnections
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstance

Outputs:
  DBInstanceIdentifier:
    Description: RDS Instance Identifier
    Value: !Ref DBInstance
    Export:
      Name: !Sub ${EnvironmentName}-DBInstanceIdentifier

  DBEndpoint:
    Description: RDS Endpoint Address
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub ${EnvironmentName}-DBEndpoint

  DBPort:
    Description: RDS Endpoint Port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub ${EnvironmentName}-DBPort

  DBSecretArn:
    Description: ARN of the RDS Master Secret
    Value: !Ref DBMasterSecret
    Export:
      Name: !Sub ${EnvironmentName}-DBSecretArn

  DatabaseURL:
    Description: PostgreSQL connection URL (without password)
    Value: !Sub
      - 'postgresql://${Username}@${Endpoint}:${Port}/${DBName}'
      - Username: !Ref DBMasterUsername
        Endpoint: !GetAtt DBInstance.Endpoint.Address
        Port: !GetAtt DBInstance.Endpoint.Port
        DBName: !Ref DBName
    Export:
      Name: !Sub ${EnvironmentName}-DatabaseURL
