AWSTemplateFormatVersion: '2010-09-09'
Description: |
  AllThrive AI - Secrets Manager (Secret Containers Only)

  CRITICAL SAFETY MEASURE:
  This stack ONLY creates empty secret containers - it does NOT manage secret values.
  Secret values must be populated and updated manually outside of CloudFormation.

  This design prevents accidental overwrites during stack updates that caused
  production outages (2025-12-29 incident where REPLACE_ME placeholders overwrote
  real API keys).

  To populate secrets:
    aws secretsmanager put-secret-value \
      --secret-id production/allthrive/ai/api-keys \
      --secret-string '{"OPENAI_API_KEY": "sk-...", ...}'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
    Description: Environment name for resource tagging

Resources:
  # Django Secret Key
  DjangoSecretKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/django/secret-key
      Description: Django SECRET_KEY for AllThrive AI
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: secret_key
        PasswordLength: 50
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-django-secret
        - Key: Environment
          Value: !Ref EnvironmentName

  # AI API Keys
  # CRITICAL: No SecretString property - CloudFormation only creates the secret
  # container, it never manages the actual secret values. This prevents accidental
  # overwrites during stack updates.
  #
  # After stack creation, populate manually with:
  #   aws secretsmanager put-secret-value --secret-id production/allthrive/ai/api-keys \
  #     --secret-string '{...}'
  AIApiKeys:
    Type: AWS::SecretsManager::Secret
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/ai/api-keys
      Description: AI provider API keys (OpenAI, Anthropic, Google, Azure) - Managed manually, not by CloudFormation
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-ai-keys
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: ManagedBy
          Value: Manual

  # OAuth Credentials (Managed manually)
  OAuthCredentials:
    Type: AWS::SecretsManager::Secret
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/oauth/credentials
      Description: OAuth provider credentials - Managed manually, not by CloudFormation
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-oauth
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: ManagedBy
          Value: Manual

  # Stripe Credentials (Managed manually)
  StripeCredentials:
    Type: AWS::SecretsManager::Secret
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/stripe/credentials
      Description: Stripe API keys and webhook secret - Managed manually, not by CloudFormation
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-stripe
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: ManagedBy
          Value: Manual

  # Twilio Credentials (Managed manually)
  TwilioCredentials:
    Type: AWS::SecretsManager::Secret
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/twilio/credentials
      Description: Twilio API credentials - Managed manually, not by CloudFormation
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-twilio
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: ManagedBy
          Value: Manual





Outputs:
  DjangoSecretKeyArn:
    Description: Django Secret Key ARN
    Value: !Ref DjangoSecretKey
    Export:
      Name: !Sub ${EnvironmentName}-DjangoSecretKeyArn

  AIApiKeysArn:
    Description: AI API Keys Secret ARN
    Value: !Ref AIApiKeys
    Export:
      Name: !Sub ${EnvironmentName}-AIApiKeysArn

  OAuthCredentialsArn:
    Description: OAuth Credentials Secret ARN
    Value: !Ref OAuthCredentials
    Export:
      Name: !Sub ${EnvironmentName}-OAuthCredentialsArn

  StripeCredentialsArn:
    Description: Stripe Credentials Secret ARN
    Value: !Ref StripeCredentials
    Export:
      Name: !Sub ${EnvironmentName}-StripeCredentialsArn

  TwilioCredentialsArn:
    Description: Twilio Credentials Secret ARN
    Value: !Ref TwilioCredentials
    Export:
      Name: !Sub ${EnvironmentName}-TwilioCredentialsArn

  EmailConfigArn:
    Description: Email Config Secret ARN
    Value: !Ref EmailConfig
    Export:
      Name: !Sub ${EnvironmentName}-EmailConfigArn

  ObservabilityKeysArn:
    Description: Observability Keys Secret ARN
    Value: !Ref ObservabilityKeys
    Export:
      Name: !Sub ${EnvironmentName}-ObservabilityKeysArn

  RecaptchaKeysArn:
    Description: reCAPTCHA Keys Secret ARN
    Value: !Ref RecaptchaKeys
    Export:
      Name: !Sub ${EnvironmentName}-RecaptchaKeysArn

  SmokeTestApiKeyArn:
    Description: Smoke Test API Key Secret ARN
    Value: !Ref SmokeTestApiKey
    Export:
      Name: !Sub ${EnvironmentName}-SmokeTestApiKeyArn
