AWSTemplateFormatVersion: '2010-09-09'
Description: 'AllThrive AI - Secrets Manager'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
    Description: Environment name for resource tagging

Resources:
  # Django Secret Key
  DjangoSecretKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/django/secret-key
      Description: Django SECRET_KEY for AllThrive AI
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: secret_key
        PasswordLength: 50
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-django-secret
        - Key: Environment
          Value: !Ref EnvironmentName

  # AI API Keys (placeholder - values to be set manually)
  AIApiKeys:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/ai/api-keys
      Description: AI provider API keys (OpenAI, Anthropic, Google)
      SecretString: |
        {
          "OPENAI_API_KEY": "REPLACE_ME",
          "ANTHROPIC_API_KEY": "REPLACE_ME",
          "GOOGLE_API_KEY": "REPLACE_ME",
          "DEFAULT_AI_PROVIDER": "openai",
          "FALLBACK_AI_PROVIDER": "openai"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-ai-keys
        - Key: Environment
          Value: !Ref EnvironmentName

  # OAuth Credentials
  OAuthCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/oauth/credentials
      Description: OAuth provider credentials
      SecretString: |
        {
          "GOOGLE_CLIENT_ID": "REPLACE_ME",
          "GOOGLE_CLIENT_SECRET": "REPLACE_ME",
          "GITHUB_CLIENT_ID": "REPLACE_ME",
          "GITHUB_CLIENT_SECRET": "REPLACE_ME",
          "LINKEDIN_OAUTH_CLIENT_ID": "REPLACE_ME",
          "LINKEDIN_OAUTH_CLIENT_SECRET": "REPLACE_ME"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-oauth
        - Key: Environment
          Value: !Ref EnvironmentName

  # Stripe Credentials
  StripeCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/stripe/credentials
      Description: Stripe API keys and webhook secret
      SecretString: |
        {
          "STRIPE_PUBLIC_KEY": "REPLACE_ME",
          "STRIPE_SECRET_KEY": "REPLACE_ME",
          "STRIPE_WEBHOOK_SECRET": "REPLACE_ME"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-stripe
        - Key: Environment
          Value: !Ref EnvironmentName

  # Twilio Credentials
  TwilioCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/twilio/credentials
      Description: Twilio API credentials
      SecretString: |
        {
          "TWILIO_ACCOUNT_SID": "REPLACE_ME",
          "TWILIO_AUTH_TOKEN": "REPLACE_ME",
          "TWILIO_PHONE_NUMBER": "REPLACE_ME"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-twilio
        - Key: Environment
          Value: !Ref EnvironmentName

  # Email Configuration
  EmailConfig:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/email/config
      Description: Email service configuration (SendGrid)
      SecretString: |
        {
          "EMAIL_HOST": "smtp.sendgrid.net",
          "EMAIL_PORT": "587",
          "EMAIL_HOST_USER": "apikey",
          "EMAIL_HOST_PASSWORD": "REPLACE_ME",
          "DEFAULT_FROM_EMAIL": "noreply@allthrive.ai",
          "ADMIN_EMAIL": "admin@allthrive.ai"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-email
        - Key: Environment
          Value: !Ref EnvironmentName

  # Observability Keys (LangSmith, Sentry, PostHog)
  ObservabilityKeys:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/observability/keys
      Description: Observability and monitoring API keys
      SecretString: |
        {
          "LANGSMITH_API_KEY": "REPLACE_ME",
          "LANGSMITH_PROJECT": "allthrive-ai-gateway",
          "SENTRY_DSN": "REPLACE_ME",
          "POSTHOG_API_KEY": "REPLACE_ME"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-observability
        - Key: Environment
          Value: !Ref EnvironmentName

  # reCAPTCHA Keys
  RecaptchaKeys:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/recaptcha/keys
      Description: Google reCAPTCHA v3 keys
      SecretString: |
        {
          "RECAPTCHA_SECRET_KEY": "REPLACE_ME"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-recaptcha
        - Key: Environment
          Value: !Ref EnvironmentName

  # Smoke Test API Key (for production E2E testing)
  SmokeTestApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/allthrive/smoke-test/api-key
      Description: API key for production E2E smoke tests (GitHub Actions)
      SecretString: |
        {
          "SMOKE_TEST_API_KEY": "REPLACE_ME"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-smoke-test
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  DjangoSecretKeyArn:
    Description: Django Secret Key ARN
    Value: !Ref DjangoSecretKey
    Export:
      Name: !Sub ${EnvironmentName}-DjangoSecretKeyArn

  AIApiKeysArn:
    Description: AI API Keys Secret ARN
    Value: !Ref AIApiKeys
    Export:
      Name: !Sub ${EnvironmentName}-AIApiKeysArn

  OAuthCredentialsArn:
    Description: OAuth Credentials Secret ARN
    Value: !Ref OAuthCredentials
    Export:
      Name: !Sub ${EnvironmentName}-OAuthCredentialsArn

  StripeCredentialsArn:
    Description: Stripe Credentials Secret ARN
    Value: !Ref StripeCredentials
    Export:
      Name: !Sub ${EnvironmentName}-StripeCredentialsArn

  TwilioCredentialsArn:
    Description: Twilio Credentials Secret ARN
    Value: !Ref TwilioCredentials
    Export:
      Name: !Sub ${EnvironmentName}-TwilioCredentialsArn

  EmailConfigArn:
    Description: Email Config Secret ARN
    Value: !Ref EmailConfig
    Export:
      Name: !Sub ${EnvironmentName}-EmailConfigArn

  ObservabilityKeysArn:
    Description: Observability Keys Secret ARN
    Value: !Ref ObservabilityKeys
    Export:
      Name: !Sub ${EnvironmentName}-ObservabilityKeysArn

  RecaptchaKeysArn:
    Description: reCAPTCHA Keys Secret ARN
    Value: !Ref RecaptchaKeys
    Export:
      Name: !Sub ${EnvironmentName}-RecaptchaKeysArn

  SmokeTestApiKeyArn:
    Description: Smoke Test API Key Secret ARN
    Value: !Ref SmokeTestApiKey
    Export:
      Name: !Sub ${EnvironmentName}-SmokeTestApiKeyArn
