AWSTemplateFormatVersion: '2010-09-09'
Description: 'AllThrive AI - Application Load Balancer'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
    Description: Environment name for resource tagging

  CertificateArn:
    Type: String
    Default: ''
    Description: ACM Certificate ARN for HTTPS (leave empty for HTTP only)

Conditions:
  HasCertificate: !Not [!Equals [!Ref CertificateArn, '']]

Resources:
  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-allthrive-alb
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      SecurityGroups:
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-ALBSecurityGroupId
      Subnets:
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-PublicSubnet1Id
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-PublicSubnet2Id
      LoadBalancerAttributes:
        # Increased timeout for WebSocket connections and AI streaming
        # WebSockets may be idle during user thinking or AI processing
        - Key: idle_timeout.timeout_seconds
          Value: '300'
        - Key: routing.http2.enabled
          Value: 'true'
        - Key: deletion_protection.enabled
          Value: 'true'
        - Key: access_logs.s3.enabled
          Value: 'false'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-alb
        - Key: Environment
          Value: !Ref EnvironmentName

  # HTTP Listener (redirect to HTTPS if certificate exists)
  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - !If
          - HasCertificate
          - Type: redirect
            RedirectConfig:
              Protocol: HTTPS
              Port: '443'
              StatusCode: HTTP_301
          - Type: forward
            TargetGroupArn: !Ref BackendTargetGroup

  # HTTPS Listener (only if certificate exists)
  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: HasCertificate
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref BackendTargetGroup

  # Backend Target Group (Django)
  BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-allthrive-backend-tg
      Port: 8000
      Protocol: HTTP
      VpcId: !ImportValue
        Fn::Sub: ${EnvironmentName}-VPCId
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /api/v1/health/
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: '200'
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
        - Key: stickiness.enabled
          Value: 'false'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-backend-tg
        - Key: Environment
          Value: !Ref EnvironmentName

  # WebSocket Target Group (for Django Channels)
  WebSocketTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-allthrive-ws-tg
      Port: 8000
      Protocol: HTTP
      VpcId: !ImportValue
        Fn::Sub: ${EnvironmentName}-VPCId
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /api/v1/health/
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: '200'
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
        - Key: stickiness.enabled
          Value: 'true'
        - Key: stickiness.type
          Value: lb_cookie
        - Key: stickiness.lb_cookie.duration_seconds
          Value: '86400'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-ws-tg
        - Key: Environment
          Value: !Ref EnvironmentName

  # Weaviate Target Group
  WeaviateTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-allthrive-weaviate-tg
      Port: 8080
      Protocol: HTTP
      VpcId: !ImportValue
        Fn::Sub: ${EnvironmentName}-VPCId
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /v1/.well-known/ready
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: '200'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allthrive-weaviate-tg
        - Key: Environment
          Value: !Ref EnvironmentName

  # Listener Rule for WebSocket paths (HTTPS)
  # IMPORTANT: This rule routes /ws/* to the WebSocket target group for Django Channels
  # Without this rule, WebSocket connections fail with 403 or route to wrong target group
  WebSocketListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: HasCertificate
    DependsOn: HTTPSListener
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - '/ws/*'
      Actions:
        - Type: forward
          TargetGroupArn: !Ref WebSocketTargetGroup

  # Listener Rule for WebSocket paths (HTTP - for non-HTTPS setup)
  WebSocketListenerRuleHTTP:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - '/ws/*'
      Actions:
        - !If
          - HasCertificate
          - Type: redirect
            RedirectConfig:
              Protocol: HTTPS
              Port: '443'
              StatusCode: HTTP_301
          - Type: forward
            TargetGroupArn: !Ref WebSocketTargetGroup

Outputs:
  ALBArn:
    Description: Application Load Balancer ARN
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub ${EnvironmentName}-ALBArn

  ALBDNSName:
    Description: Application Load Balancer DNS Name
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub ${EnvironmentName}-ALBDNSName

  ALBHostedZoneId:
    Description: Application Load Balancer Hosted Zone ID
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
    Export:
      Name: !Sub ${EnvironmentName}-ALBHostedZoneId

  BackendTargetGroupArn:
    Description: Backend Target Group ARN
    Value: !Ref BackendTargetGroup
    Export:
      Name: !Sub ${EnvironmentName}-BackendTargetGroupArn

  WebSocketTargetGroupArn:
    Description: WebSocket Target Group ARN
    Value: !Ref WebSocketTargetGroup
    Export:
      Name: !Sub ${EnvironmentName}-WebSocketTargetGroupArn

  WeaviateTargetGroupArn:
    Description: Weaviate Target Group ARN
    Value: !Ref WeaviateTargetGroup
    Export:
      Name: !Sub ${EnvironmentName}-WeaviateTargetGroupArn

  HTTPListenerArn:
    Description: HTTP Listener ARN
    Value: !Ref HTTPListener
    Export:
      Name: !Sub ${EnvironmentName}-HTTPListenerArn

  HTTPSListenerArn:
    Description: HTTPS Listener ARN
    Condition: HasCertificate
    Value: !Ref HTTPSListener
    Export:
      Name: !Sub ${EnvironmentName}-HTTPSListenerArn
