# Generated by Django 5.1.15 on 2025-12-07 08:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event')),
                ('start_date', models.DateTimeField(help_text='Event start date and time')),
                ('end_date', models.DateTimeField(help_text='Event end date and time')),
                (
                    'location',
                    models.CharField(blank=True, help_text='Event location (physical or virtual)', max_length=255),
                ),
                ('event_url', models.URLField(blank=True, help_text='URL for event registration or more info')),
                ('is_all_day', models.BooleanField(default=False, help_text='Whether this is an all-day event')),
                (
                    'color',
                    models.CharField(
                        default='#3b82f6',
                        help_text='Hex color code for calendar display (e.g., #3b82f6)',
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Color must be a valid hex code (e.g., #3b82f6)', regex='^#[0-9A-Fa-f]{6}$'
                            )
                        ],
                    ),
                ),
                (
                    'thumbnail',
                    models.URLField(
                        blank=True,
                        help_text='URL to event thumbnail image (must be https)',
                        validators=[django.core.validators.URLValidator(schemes=['https'])],
                    ),
                ),
                (
                    'timezone_name',
                    models.CharField(
                        default='UTC', help_text='Timezone for event (e.g., America/New_York, UTC)', max_length=63
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether event is visible to users')),
                (
                    'created_by',
                    models.ForeignKey(
                        help_text='Admin user who created this event',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        help_text='Last admin user who updated this event',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='updated_events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'core_event',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.CharField(
                        choices=[('going', 'Going'), ('maybe', 'Maybe'), ('not_going', 'Not Going')],
                        default='going',
                        help_text='RSVP status',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'event',
                    models.ForeignKey(
                        help_text="The event being RSVP'd to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rsvps',
                        to='events.event',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text="User who RSVP'd",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_rsvps',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Event RSVP',
                'verbose_name_plural': 'Event RSVPs',
                'db_table': 'core_eventrsvp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'end_date'], name='core_event_start_d_05b9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published'], name='core_event_is_publ_c1332f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['event', 'status'], name='core_eventr_event_i_ca9adf_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['user', 'status'], name='core_eventr_user_id_be5040_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventrsvp',
            unique_together={('event', 'user')},
        ),
    ]
