# Generated by Django 5.1.15 on 2025-12-21 00:39

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('thrive_circle', '0012_cleanup_deprecated_topic_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'content',
                    models.TextField(
                        help_text='Message content (max 4000 chars)',
                        validators=[django.core.validators.MaxLengthValidator(4000)],
                    ),
                ),
                (
                    'message_type',
                    models.CharField(
                        choices=[
                            ('text', 'Text'),
                            ('image', 'Image'),
                            ('file', 'File'),
                            ('embed', 'Embed'),
                            ('system', 'System'),
                            ('deleted', 'Deleted'),
                        ],
                        default='text',
                        max_length=20,
                    ),
                ),
                (
                    'attachments',
                    models.JSONField(
                        blank=True, default=list, help_text='List of attachment objects: [{url, name, size, type}]'
                    ),
                ),
                (
                    'embeds',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of embed objects: [{url, title, description, thumbnail}]',
                    ),
                ),
                ('mentions', models.JSONField(blank=True, default=list, help_text='List of mentioned user IDs')),
                (
                    'reaction_counts',
                    models.JSONField(blank=True, default=dict, help_text='Cached reaction counts: {emoji: count}'),
                ),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for moderation review')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden by moderator')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned message in room')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'author',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='community_messages',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'reply_to',
                    models.ForeignKey(
                        blank=True,
                        help_text='Message this is replying to',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='replies',
                        to='community.message',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Room display name', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Room description')),
                ('emoji', models.CharField(blank=True, default='', help_text='Room emoji icon', max_length=10)),
                (
                    'room_type',
                    models.CharField(
                        choices=[('forum', 'Forum'), ('circle', 'Circle Chat'), ('dm', 'Direct Message')],
                        default='forum',
                        max_length=20,
                    ),
                ),
                (
                    'visibility',
                    models.CharField(
                        choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')],
                        default='public',
                        max_length=20,
                    ),
                ),
                (
                    'auto_thread',
                    models.BooleanField(default=False, help_text='Automatically create threads for each message'),
                ),
                ('position', models.IntegerField(default=0, help_text='Display order')),
                (
                    'is_default',
                    models.BooleanField(default=False, help_text='Is this the default room (e.g., General)'),
                ),
                (
                    'slow_mode_seconds',
                    models.IntegerField(
                        default=0,
                        help_text='Seconds users must wait between messages (0 = disabled)',
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'min_trust_to_join',
                    models.IntegerField(
                        default=0,
                        help_text='Minimum trust level to join (0 = anyone)',
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'min_trust_to_post',
                    models.IntegerField(
                        default=0,
                        help_text='Minimum trust level to post (0 = anyone)',
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ('member_count', models.IntegerField(default=0, help_text='Cached member count')),
                ('message_count', models.IntegerField(default=0, help_text='Cached message count')),
                ('online_count', models.IntegerField(default=0, help_text='Cached online user count')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Last message timestamp', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Archived rooms are read-only')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rooms are hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'circle',
                    models.OneToOneField(
                        blank=True,
                        help_text='Associated circle for circle chat rooms',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chat_room',
                        to='thrive_circle.circle',
                    ),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who created this room (null for system-created)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_rooms',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'action_type',
                    models.CharField(
                        choices=[
                            ('warn', 'Warning'),
                            ('delete', 'Delete Message'),
                            ('mute', 'Mute User'),
                            ('unmute', 'Unmute User'),
                            ('ban', 'Ban User'),
                            ('unban', 'Unban User'),
                            ('hide', 'Hide Message'),
                            ('unhide', 'Unhide Message'),
                            ('lock', 'Lock Thread'),
                            ('unlock', 'Unlock Thread'),
                            ('approve', 'Approve Content'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('ai', 'AI Moderation'),
                            ('community', 'Community Report'),
                            ('admin', 'Admin/Moderator'),
                            ('system', 'Automated System'),
                        ],
                        max_length=20,
                    ),
                ),
                ('reason', models.TextField(blank=True, help_text='Reason for action')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When action expires', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this action still in effect')),
                (
                    'ai_scores',
                    models.JSONField(blank=True, default=dict, help_text='AI moderation scores: {category: score}'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'moderator',
                    models.ForeignKey(
                        blank=True,
                        help_text='Moderator who took action (null for automated)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='moderation_actions_taken',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'target_message',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='moderation_actions',
                        to='community.message',
                    ),
                ),
                (
                    'target_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='moderation_actions_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'target_room',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='moderation_actions',
                        to='community.room',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Moderation Action',
                'verbose_name_plural': 'Moderation Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community.room'
            ),
        ),
        migrations.CreateModel(
            name='DirectMessageThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_group', models.BooleanField(default=False, help_text='True if more than 2 participants')),
                ('name', models.CharField(blank=True, help_text='Group DM name (optional)', max_length=100)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_dm_threads',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'participants',
                    models.ManyToManyField(
                        help_text='Users in this DM thread', related_name='dm_threads', to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'room',
                    models.OneToOneField(
                        blank=True,
                        help_text='Room containing DM messages',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='dm_thread',
                        to='community.room',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Direct Message Thread',
                'verbose_name_plural': 'Direct Message Threads',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('owner', 'Owner'),
                            ('admin', 'Admin'),
                            ('moderator', 'Moderator'),
                            ('trusted', 'Trusted'),
                            ('member', 'Member'),
                            ('muted', 'Muted'),
                            ('banned', 'Banned'),
                        ],
                        default='member',
                        max_length=20,
                    ),
                ),
                ('trust_score', models.IntegerField(default=0, help_text='Room-specific trust score')),
                ('messages_sent', models.IntegerField(default=0, help_text='Messages sent in this room')),
                ('warnings_count', models.IntegerField(default=0, help_text='Number of warnings received')),
                ('notifications_enabled', models.BooleanField(default=True)),
                (
                    'notification_level',
                    models.CharField(
                        choices=[('all', 'All Messages'), ('mentions', 'Mentions Only'), ('none', 'None')],
                        default='mentions',
                        max_length=20,
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('last_read_at', models.DateTimeField(blank=True, help_text='Last message read timestamp', null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'room',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.room'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='room_memberships',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Room Membership',
                'verbose_name_plural': 'Room Memberships',
                'ordering': ['role', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Thread title', max_length=200)),
                (
                    'is_locked',
                    models.BooleanField(default=False, help_text='Locked threads cannot receive new messages'),
                ),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned threads appear at top')),
                ('is_resolved', models.BooleanField(default=False, help_text='Thread marked as resolved')),
                ('message_count', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                (
                    'auto_archive_after_hours',
                    models.IntegerField(blank=True, help_text='Auto-archive after X hours of inactivity', null=True),
                ),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'creator',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_threads',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'parent_message',
                    models.ForeignKey(
                        blank=True,
                        help_text='Message that started this thread',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='child_threads',
                        to='community.message',
                    ),
                ),
                (
                    'room',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='community.room'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Thread',
                'verbose_name_plural': 'Threads',
                'ordering': ['-is_pinned', '-last_message_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(
                blank=True,
                help_text='Thread this message belongs to (null = room-level message)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='messages',
                to='community.thread',
            ),
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'blocked',
                    models.ForeignKey(
                        help_text='User who is blocked',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='blocked_by',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'blocker',
                    models.ForeignKey(
                        help_text='User who blocked',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='blocking',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'User Block',
                'verbose_name_plural': 'User Blocks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(help_text='Emoji character', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.message'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='message_reactions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Message Reaction',
                'verbose_name_plural': 'Message Reactions',
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(fields=['message', 'emoji'], name='community_m_message_c356ee_idx'),
                    models.Index(fields=['user', '-created_at'], name='community_m_user_id_fcdf38_idx'),
                ],
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='ModerationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending Review'),
                            ('approved', 'Approved'),
                            ('rejected', 'Rejected'),
                            ('escalated', 'Escalated'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('ai_flagged', models.BooleanField(default=False)),
                ('ai_scores', models.JSONField(blank=True, default=dict)),
                ('ai_reason', models.TextField(blank=True, help_text='AI explanation for flagging')),
                ('report_count', models.IntegerField(default=0)),
                (
                    'report_reasons',
                    models.JSONField(blank=True, default=list, help_text='List of report reasons from users'),
                ),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='moderation_queue_entries',
                        to='community.message',
                    ),
                ),
                (
                    'reporters',
                    models.ManyToManyField(
                        blank=True, related_name='reported_queue_items', to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reviewed_queue_items',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Moderation Queue Entry',
                'verbose_name_plural': 'Moderation Queue',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', '-created_at'], name='community_m_status_8519e4_idx'),
                    models.Index(fields=['ai_flagged', 'status'], name='community_m_ai_flag_04ed29_idx'),
                    models.Index(fields=['reviewed_by', '-reviewed_at'], name='community_m_reviewe_2888d9_idx'),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type', 'visibility', 'is_active'], name='community_r_room_ty_aec60b_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['slug'], name='community_r_slug_3ad221_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['creator', '-created_at'], name='community_r_creator_19a29b_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['circle'], name='community_r_circle__8aa60e_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_default', 'is_active'], name='community_r_is_defa_988868_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['-last_message_at'], name='community_r_last_me_842d84_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['target_user', '-created_at'], name='community_m_target__0af8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['moderator', '-created_at'], name='community_m_moderat_cc5b93_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action_type', '-created_at'], name='community_m_action__d2c0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['source', '-created_at'], name='community_m_source_d174ed_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['is_active', 'expires_at'], name='community_m_is_acti_b73ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessagethread',
            index=models.Index(fields=['-last_message_at'], name='community_d_last_me_0fb935_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessagethread',
            index=models.Index(fields=['created_by', '-created_at'], name='community_d_created_3afc8c_idx'),
        ),
        migrations.AddIndex(
            model_name='roommembership',
            index=models.Index(fields=['room', 'role', 'is_active'], name='community_r_room_id_3cbb53_idx'),
        ),
        migrations.AddIndex(
            model_name='roommembership',
            index=models.Index(fields=['user', 'is_active'], name='community_r_user_id_850c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='roommembership',
            index=models.Index(fields=['user', 'role'], name='community_r_user_id_31124e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roommembership',
            unique_together={('room', 'user')},
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['room', '-last_message_at'], name='community_t_room_id_069bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['room', 'is_pinned', '-created_at'], name='community_t_room_id_55ead7_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['creator', '-created_at'], name='community_t_creator_e6e693_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['parent_message'], name='community_t_parent__0e98f2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='community_m_room_id_fdcd67_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='community_m_thread__ee75b9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['author', '-created_at'], name='community_m_author__6e94ed_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_flagged', '-created_at'], name='community_m_is_flag_24c419_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_pinned', 'room'], name='community_m_is_pinn_5fe8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at', 'id'], name='community_m_room_id_08749b_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocker'], name='community_u_blocker_83b151_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocked'], name='community_u_blocked_24c5c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together={('blocker', 'blocked')},
        ),
    ]
