# Generated by Django 5.1.15 on 2025-12-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='emoji',
        ),
        migrations.AddField(
            model_name='room',
            name='icon',
            field=models.CharField(
                default='comments', help_text='FontAwesome icon name (e.g., "comments", "robot", "book")', max_length=50
            ),
        ),
    ]
