import { api } from './api';
import type { 
  Taxonomy, 
  UserTag, 
  UserPersonalization,
  InteractionType 
} from '@/types/models';

/**
 * Get all available taxonomies
 */
export async function getTaxonomies(): Promise<Taxonomy[]> {
  const response = await api.get('/taxonomies/');
  return response.data;
}

/**
 * Get taxonomies grouped by category
 */
export async function getTaxonomiesByCategory(): Promise<Record<string, Taxonomy[]>> {
  const response = await api.get('/taxonomies/by_category/');
  return response.data;
}

/**
 * Get user's personalization overview
 */
export async function getUserPersonalization(): Promise<UserPersonalization> {
  const response = await api.get('/me/personalization/');
  return response.data;
}

/**
 * Get user's manual tags
 */
export async function getManualTags(): Promise<UserTag[]> {
  const response = await api.get('/me/tags/manual/');
  return response.data;
}

/**
 * Get user's auto-generated tags
 */
export async function getAutoGeneratedTags(): Promise<UserTag[]> {
  const response = await api.get('/me/tags/auto_generated/');
  return response.data;
}

/**
 * Get all user tags
 */
export async function getAllUserTags(): Promise<UserTag[]> {
  const response = await api.get('/me/tags/');
  return response.data;
}

/**
 * Create a single manual tag
 */
export async function createUserTag(data: {
  taxonomy?: number;
  name?: string;
}): Promise<UserTag> {
  const response = await api.post('/me/tags/', data);
  return response.data;
}

/**
 * Create multiple tags from taxonomy selections
 */
export async function bulkCreateTags(taxonomyIds: number[]): Promise<UserTag[]> {
  const response = await api.post('/me/tags/bulk_create/', {
    taxonomy_ids: taxonomyIds,
  });
  return response.data;
}

/**
 * Delete a single tag
 */
export async function deleteUserTag(tagId: number): Promise<void> {
  await api.delete(`/me/tags/${tagId}/`);
}

/**
 * Delete multiple tags
 */
export async function bulkDeleteTags(tagIds: number[]): Promise<{ deleted: number }> {
  const response = await api.delete('/me/tags/bulk_delete/', {
    data: { tag_ids: tagIds },
  });
  return response.data;
}

/**
 * Track a user interaction
 */
export async function trackInteraction(data: {
  interactionType: InteractionType;
  metadata?: Record<string, any>;
  extractedKeywords?: string[];
}): Promise<void> {
  await api.post('/me/interactions/', {
    interaction_type: data.interactionType,
    metadata: data.metadata || {},
    extracted_keywords: data.extractedKeywords || [],
  });
}
