import { api } from './api';
import type {
  Taxonomy,
  UserTag,
  UserPersonalization,
  InteractionType
} from '@/types/models';

/**
 * Get all available taxonomies
 * Fetches all pages if paginated
 */
export async function getTaxonomies(): Promise<Taxonomy[]> {
  let allTaxonomies: Taxonomy[] = [];
  let nextUrl: string | null = '/taxonomies/';

  // Fetch all pages
  while (nextUrl) {
    const response = await api.get(nextUrl);
    const data = response.data;

    // Handle both paginated and non-paginated responses
    if (data.results) {
      allTaxonomies = allTaxonomies.concat(data.results);
      // Extract relative path from next URL
      if (data.next) {
        const url = new URL(data.next);
        nextUrl = url.pathname + url.search;
        // Remove /api/v1 prefix if present since api base already includes it
        nextUrl = nextUrl.replace('/api/v1', '');
      } else {
        nextUrl = null;
      }
    } else {
      allTaxonomies = data;
      nextUrl = null;
    }
  }

  return allTaxonomies;
}

/**
 * Get taxonomies grouped by category
 */
export async function getTaxonomiesByCategory(): Promise<Record<string, Taxonomy[]>> {
  const response = await api.get('/taxonomies/by_category/');
  return response.data;
}

/**
 * Get user's personalization overview
 */
export async function getUserPersonalization(): Promise<UserPersonalization> {
  const response = await api.get('/me/personalization/');
  return response.data;
}

/**
 * Get user's manual tags
 */
export async function getManualTags(): Promise<UserTag[]> {
  const response = await api.get('/me/tags/manual/');
  return response.data;
}

/**
 * Get user's auto-generated tags
 */
export async function getAutoGeneratedTags(): Promise<UserTag[]> {
  const response = await api.get('/me/tags/auto_generated/');
  return response.data;
}

/**
 * Get all user tags
 */
export async function getAllUserTags(): Promise<UserTag[]> {
  const response = await api.get('/me/tags/');
  return response.data;
}

/**
 * Create a single manual tag
 */
export async function createUserTag(data: {
  taxonomy?: number;
  name?: string;
}): Promise<UserTag> {
  const response = await api.post('/me/tags/', data);
  return response.data;
}

/**
 * Create multiple tags from taxonomy selections
 */
export async function bulkCreateTags(taxonomyIds: number[]): Promise<UserTag[]> {
  const response = await api.post('/me/tags/bulk_create/', {
    taxonomy_ids: taxonomyIds,
  });
  return response.data;
}

/**
 * Delete a single tag
 */
export async function deleteUserTag(tagId: number): Promise<void> {
  await api.delete(`/me/tags/${tagId}/`);
}

/**
 * Delete multiple tags
 */
export async function bulkDeleteTags(tagIds: number[]): Promise<{ deleted: number }> {
  const response = await api.delete('/me/tags/bulk_delete/', {
    data: { tag_ids: tagIds },
  });
  return response.data;
}

/**
 * Track a user interaction
 */
export async function trackInteraction(data: {
  interactionType: InteractionType;
  metadata?: Record<string, any>;
  extractedKeywords?: string[];
}): Promise<void> {
  await api.post('/me/interactions/', {
    interaction_type: data.interactionType,
    metadata: data.metadata || {},
    extracted_keywords: data.extractedKeywords || [],
  });
}
