# Generated by Django 5.1.15 on 2025-12-15 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0043_project_tools_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('view', 'Project View'),
                            ('view_milestone', 'View Milestone (>30s)'),
                            ('scroll_depth', 'Scroll Depth'),
                            ('time_spent', 'Time Spent'),
                            ('like', 'Like'),
                        ],
                        db_index=True,
                        help_text='Type of engagement event',
                        max_length=20,
                    ),
                ),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Event-specific data payload')),
                (
                    'processed',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text='Whether this event has been processed for profile updates',
                    ),
                ),
                (
                    'processed_at',
                    models.DateTimeField(blank=True, help_text='When this event was processed', null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'project',
                    models.ForeignKey(
                        blank=True,
                        help_text='Project the engagement is about (if applicable)',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='engagement_events',
                        to='core.project',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User who triggered the event',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='engagement_events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Engagement Event',
                'verbose_name_plural': 'Engagement Events',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'event_type', '-created_at'], name='engagement__user_id_12e63c_idx'),
                    models.Index(fields=['processed', '-created_at'], name='engagement__process_4f1b9c_idx'),
                    models.Index(fields=['project', '-created_at'], name='engagement__project_e32977_idx'),
                ],
            },
        ),
    ]
