# Generated by Django 5.1.15 on 2025-12-18 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, db_index=True, help_text='Timestamp when object was soft deleted', null=True
                    ),
                ),
                ('image_url', models.URLField(help_text='URL of the avatar image stored in MinIO/S3', max_length=500)),
                (
                    'creation_mode',
                    models.CharField(
                        choices=[
                            ('make_me', 'Make Me (Photo-based)'),
                            ('template', 'Template'),
                            ('scratch', 'Build from Scratch'),
                            ('dicebear', 'DiceBear Preset'),
                            ('legacy', 'Legacy (Pre-existing)'),
                        ],
                        help_text='How this avatar was created',
                        max_length=20,
                    ),
                ),
                (
                    'template_used',
                    models.CharField(
                        blank=True,
                        help_text='Template name if creation_mode is "template" (e.g., wizard, robot)',
                        max_length=50,
                    ),
                ),
                ('original_prompt', models.TextField(blank=True, help_text='The prompt used to generate this avatar')),
                (
                    'is_current',
                    models.BooleanField(
                        db_index=True, default=False, help_text="Whether this is the user's current active avatar"
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'User Avatar',
                'verbose_name_plural': 'User Avatars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvatarGenerationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, db_index=True, help_text='Timestamp when object was soft deleted', null=True
                    ),
                ),
                (
                    'conversation_id',
                    models.CharField(
                        db_index=True,
                        help_text='WebSocket conversation ID (pattern: avatar-{user_id}-{timestamp})',
                        max_length=255,
                    ),
                ),
                (
                    'creation_mode',
                    models.CharField(
                        choices=[
                            ('make_me', 'Make Me (Photo-based)'),
                            ('template', 'Template'),
                            ('scratch', 'Build from Scratch'),
                            ('dicebear', 'DiceBear Preset'),
                            ('legacy', 'Legacy (Pre-existing)'),
                        ],
                        default='scratch',
                        max_length=20,
                    ),
                ),
                (
                    'template_used',
                    models.CharField(blank=True, help_text='Template name if using template mode', max_length=50),
                ),
                (
                    'reference_image_url',
                    models.URLField(
                        blank=True,
                        help_text='Reference photo URL for "Make Me" mode (deleted after 24 hours)',
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('generating', 'Generating'),
                            ('ready', 'Ready for Review'),
                            ('accepted', 'Accepted'),
                            ('abandoned', 'Abandoned'),
                            ('failed', 'Failed'),
                        ],
                        default='generating',
                        max_length=20,
                    ),
                ),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed')),
                (
                    'achievement_awarded',
                    models.BooleanField(
                        default=False, help_text='Whether the Prompt Engineer achievement was awarded for this session'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='avatar_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'saved_avatar',
                    models.OneToOneField(
                        blank=True,
                        help_text='The final saved avatar if session was accepted',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='generation_session',
                        to='avatars.useravatar',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Avatar Generation Session',
                'verbose_name_plural': 'Avatar Generation Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvatarGenerationIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='The prompt used for this iteration')),
                ('image_url', models.URLField(help_text='URL of the generated avatar image', max_length=500)),
                (
                    'order',
                    models.IntegerField(default=0, help_text='Order of this iteration within the session (0-indexed)'),
                ),
                (
                    'is_selected',
                    models.BooleanField(
                        default=False, help_text='Whether this iteration was selected as the final avatar'
                    ),
                ),
                (
                    'generation_time_ms',
                    models.IntegerField(
                        blank=True, help_text='Time taken to generate this image in milliseconds', null=True
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='iterations',
                        to='avatars.avatargenerationsession',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Avatar Generation Iteration',
                'verbose_name_plural': 'Avatar Generation Iterations',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['session', 'order'], name='avatars_ava_session_fd8f36_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='useravatar',
            index=models.Index(fields=['user', 'is_current'], name='avatars_use_user_id_60a0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='useravatar',
            index=models.Index(fields=['user', '-created_at'], name='avatars_use_user_id_bead7f_idx'),
        ),
        migrations.AddIndex(
            model_name='avatargenerationsession',
            index=models.Index(fields=['user', 'status'], name='avatars_ava_user_id_d8f48c_idx'),
        ),
        migrations.AddIndex(
            model_name='avatargenerationsession',
            index=models.Index(fields=['conversation_id'], name='avatars_ava_convers_595c90_idx'),
        ),
        migrations.AddIndex(
            model_name='avatargenerationsession',
            index=models.Index(fields=['-created_at'], name='avatars_ava_created_5205ea_idx'),
        ),
    ]
