# Generated by Django 5.1.15 on 2025-12-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('avatars', '0002_migrate_existing_avatars'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='avatargenerationsession',
            name='avatars_ava_convers_595c90_idx',
        ),
        migrations.AlterField(
            model_name='avatargenerationsession',
            name='conversation_id',
            field=models.CharField(
                help_text='WebSocket conversation ID (pattern: avatar-{user_id}-{timestamp})',
                max_length=255,
                unique=True,
            ),
        ),
    ]
