# Generated by Django 5.1.15 on 2025-12-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('avatars', '0003_add_unique_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatargenerationsession',
            name='reference_image_url',
            field=models.URLField(
                blank=True,
                default='',
                help_text='Reference photo URL for "Make Me" mode (deleted after 24 hours)',
                max_length=500,
            ),
        ),
    ]
