# Generated by Django 5.1.15 on 2025-12-19 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'game',
                    models.CharField(
                        choices=[('context_snake', 'Context Snake'), ('ethics_defender', 'Ethics Defender')],
                        max_length=50,
                    ),
                ),
                ('score', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='game_scores',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [
                    models.Index(fields=['game', '-score'], name='games_games_game_4b6cdc_idx'),
                    models.Index(fields=['user', 'game'], name='games_games_user_id_9432d7_idx'),
                ],
            },
        ),
    ]
