# Generated by Django 5.1.15 on 2025-12-19 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gamescore',
            constraint=models.CheckConstraint(
                condition=models.Q(('score__gte', 0), ('score__lte', 10000)), name='games_gamescore_valid_score_range'
            ),
        ),
    ]
