# Generated by Django 5.0.14 on 2025-11-26 01:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        error_messages={'unique': 'A user with that username already exists.'},
                        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name='username',
                    ),
                ),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text=(
                            'Designates whether this user should be treated as active. '
                            'Unselect this instead of deleting accounts.'
                        ),
                        verbose_name='active',
                    ),
                ),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('explorer', 'Explorer'),
                            ('expert', 'Expert'),
                            ('mentor', 'Mentor'),
                            ('patron', 'Patron'),
                            ('admin', 'Admin'),
                            ('bot', 'Bot'),
                        ],
                        default='explorer',
                        help_text='User role determines access level and permissions',
                        max_length=20,
                    ),
                ),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                (
                    'tagline',
                    models.CharField(blank=True, help_text='Short headline or professional title', max_length=150),
                ),
                ('location', models.CharField(blank=True, help_text='City, state/country or "Remote"', max_length=100)),
                ('pronouns', models.CharField(blank=True, help_text='e.g. she/her, he/him, they/them', max_length=50)),
                (
                    'current_status',
                    models.CharField(
                        blank=True, help_text="Current availability or what you're working on", max_length=200
                    ),
                ),
                ('website_url', models.URLField(blank=True, help_text='Personal website or portfolio URL', null=True)),
                (
                    'calendar_url',
                    models.URLField(blank=True, help_text='Public calendar URL for scheduling', null=True),
                ),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL', null=True)),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL', null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', null=True)),
                (
                    'playground_is_public',
                    models.BooleanField(default=True, help_text='Allow others to view your Playground projects'),
                ),
                ('total_points', models.IntegerField(default=0, help_text='Total points earned by user')),
                ('level', models.IntegerField(default=1, help_text='User level calculated from points')),
                (
                    'tier',
                    models.CharField(
                        choices=[
                            ('ember', 'Ember'),
                            ('spark', 'Spark'),
                            ('blaze', 'Blaze'),
                            ('beacon', 'Beacon'),
                            ('phoenix', 'Phoenix'),
                        ],
                        default='ember',
                        help_text='User tier based on total points',
                        max_length=20,
                    ),
                ),
                ('current_streak_days', models.IntegerField(default=0, help_text='Current consecutive day streak')),
                ('longest_streak_days', models.IntegerField(default=0, help_text='Longest streak ever achieved')),
                (
                    'last_activity_date',
                    models.DateField(
                        blank=True, help_text='Last date user earned points (for streak tracking)', null=True
                    ),
                ),
                ('lifetime_quizzes_completed', models.IntegerField(default=0, help_text='Total quizzes completed')),
                ('lifetime_projects_created', models.IntegerField(default=0, help_text='Total projects created')),
                (
                    'lifetime_side_quests_completed',
                    models.IntegerField(default=0, help_text='Total side quests completed'),
                ),
                ('lifetime_comments_posted', models.IntegerField(default=0, help_text='Total comments posted')),
                (
                    'total_achievements_unlocked',
                    models.IntegerField(default=0, help_text='Total achievements unlocked'),
                ),
                (
                    'last_achievement_earned_at',
                    models.DateTimeField(
                        blank=True, help_text='Timestamp of most recently earned achievement', null=True
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            'The groups this user belongs to. A user will get all '
                            'permissions granted to each of their groups.'
                        ),
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'ordering': ['-date_joined'],
                'indexes': [
                    models.Index(fields=['tier'], name='user_tier_idx'),
                    models.Index(fields=['tier', '-date_joined'], name='user_tier_recent_idx'),
                ],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=models.Q(('total_points__gte', 0)), name='user_points_non_negative'
            ),
        ),
    ]
