# Generated by Django 5.0.14 on 2025-11-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Add tier field
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(
                choices=[
                    ('ember', 'Ember'),
                    ('spark', 'Spark'),
                    ('blaze', 'Blaze'),
                    ('beacon', 'Beacon'),
                    ('phoenix', 'Phoenix'),
                ],
                default='ember',
                help_text='User tier based on total points',
                max_length=20,
            ),
        ),
        # Rename streak fields for consistency
        migrations.RenameField(
            model_name='user',
            old_name='current_streak',
            new_name='current_streak_days',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='max_streak',
            new_name='longest_streak_days',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_login_date',
            new_name='last_activity_date',
        ),
        # Add lifetime stats
        migrations.AddField(
            model_name='user',
            name='lifetime_quizzes_completed',
            field=models.IntegerField(default=0, help_text='Total quizzes completed'),
        ),
        migrations.AddField(
            model_name='user',
            name='lifetime_projects_created',
            field=models.IntegerField(default=0, help_text='Total projects created'),
        ),
        migrations.AddField(
            model_name='user',
            name='lifetime_side_quests_completed',
            field=models.IntegerField(default=0, help_text='Total side quests completed'),
        ),
        migrations.AddField(
            model_name='user',
            name='lifetime_comments_posted',
            field=models.IntegerField(default=0, help_text='Total comments posted'),
        ),
        # Remove old indexes
        migrations.RemoveIndex(
            model_name='user',
            name='user_points_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_level_points_idx',
        ),
        # Add new indexes for tier circles
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tier'], name='user_tier_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tier', '-date_joined'], name='user_tier_recent_idx'),
        ),
        # Add constraint
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=models.Q(total_points__gte=0),
                name='user_points_non_negative',
            ),
        ),
    ]
