# Generated by Django 5.0.14 on 2025-11-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_llm_training',
            field=models.BooleanField(
                default=False, help_text='Allow AI models (like ChatGPT) to use profile data for training'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='gamification_is_public',
            field=models.BooleanField(
                default=True, help_text='Show points, level, tier, and achievements on public profile'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_public',
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text='Allow profile to appear in search engines and sitemaps. Opt-out for privacy.',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('explorer', 'Explorer'),
                    ('learner', 'Learner'),
                    ('expert', 'Expert'),
                    ('creator', 'Creator'),
                    ('mentor', 'Mentor'),
                    ('patron', 'Patron'),
                    ('admin', 'Admin'),
                    ('bot', 'Bot'),
                ],
                default='explorer',
                help_text='User role determines access level and permissions',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(
                choices=[
                    ('seedling', 'Seedling'),
                    ('sprout', 'Sprout'),
                    ('blossom', 'Blossom'),
                    ('bloom', 'Bloom'),
                    ('evergreen', 'Evergreen'),
                ],
                default='seedling',
                help_text='User tier based on total points',
                max_length=20,
            ),
        ),
    ]
