# Generated by Django 5.0.14 on 2025-12-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_migrate_tier_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_similarity_matching',
            field=models.BooleanField(
                default=True,
                help_text=(
                    'Allow your preferences to be used for finding users with similar interests '
                    '(collaborative filtering). Your specific interests are never shared, only used '
                    'anonymously for recommendations.'
                ),
            ),
        ),
    ]
