# Generated by Django 5.0.14 on 2025-12-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_add_similarity_matching_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('explorer', 'Explorer'),
                    ('learner', 'Learner'),
                    ('expert', 'Expert'),
                    ('creator', 'Creator'),
                    ('mentor', 'Mentor'),
                    ('patron', 'Patron'),
                    ('admin', 'Admin'),
                    ('agent', 'Agent'),
                ],
                default='explorer',
                help_text='User role determines access level and permissions',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(
                choices=[
                    ('seedling', 'Seedling'),
                    ('sprout', 'Sprout'),
                    ('blossom', 'Blossom'),
                    ('bloom', 'Bloom'),
                    ('evergreen', 'Evergreen'),
                    ('curation', 'Curation'),
                ],
                default='seedling',
                help_text='User tier based on total points',
                max_length=20,
            ),
        ),
    ]
