# Generated by Django 5.0.14 on 2025-12-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_user_role_alter_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievement_categories_earned',
            field=models.IntegerField(
                default=0, help_text='Number of unique achievement categories with at least one earned achievement'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='battle_types_tried',
            field=models.IntegerField(default=0, help_text='Number of different battle types participated in'),
        ),
        migrations.AddField(
            model_name='user',
            name='broke_streak_record',
            field=models.BooleanField(default=False, help_text='Whether user broke their own streak record'),
        ),
        migrations.AddField(
            model_name='user',
            name='days_active_this_month',
            field=models.IntegerField(default=0, help_text='Number of days active in current month'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_users_welcomed',
            field=models.IntegerField(default=0, help_text='Number of new users welcomed to the community'),
        ),
        migrations.AddField(
            model_name='user',
            name='perfect_quiz_scores',
            field=models.IntegerField(default=0, help_text='Number of quizzes completed with perfect scores'),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_goals_completed',
            field=models.IntegerField(default=0, help_text='Number of weekly goals completed'),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_xp_gained',
            field=models.IntegerField(default=0, help_text='XP gained in the current week'),
        ),
    ]
