# Generated by Django 5.1.15 on 2025-12-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_rename_weekly_xp_to_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weekly_points_gained',
            field=models.IntegerField(default=0, help_text='Points gained in the current week'),
        ),
    ]
