# Generated by Django 5.1.15 on 2025-12-04 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_alter_user_weekly_points_gained'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'email',
                    models.EmailField(
                        help_text='Email address of person requesting invitation', max_length=254, unique=True
                    ),
                ),
                ('name', models.CharField(help_text='Name of person requesting invitation', max_length=100)),
                ('reason', models.TextField(blank=True, help_text='Why they want to join (optional)')),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'ip_address',
                    models.GenericIPAddressField(
                        blank=True, help_text='IP address of requester (for spam prevention)', null=True
                    ),
                ),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent (for spam prevention)')),
                ('review_notes', models.TextField(blank=True, help_text='Internal notes from reviewer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'reviewed_at',
                    models.DateTimeField(blank=True, help_text='When the request was approved/rejected', null=True),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        help_text='Admin who reviewed this request',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reviewed_invitations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Invitation Request',
                'verbose_name_plural': 'Invitation Requests',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', '-created_at'], name='users_invit_status_7e085b_idx'),
                    models.Index(fields=['email'], name='users_invit_email_575647_idx'),
                ],
            },
        ),
    ]
