# Generated by Django 5.1.15 on 2025-12-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0009_invitationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_sms_invitations',
            field=models.BooleanField(default=True, help_text='Allow receiving battle invitations via SMS'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available_for_battles',
            field=models.BooleanField(
                default=True, help_text='User is open to receiving random battle invitations from active users'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(
                blank=True, db_index=True, help_text='Last time user made an API request (for online status)', null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(
                blank=True, db_index=True, help_text='Phone number in E.164 format (e.g., +14155551234)', max_length=20
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Whether phone number has been verified via SMS code'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='When phone number was verified', null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-last_seen_at'], name='user_last_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_available_for_battles', '-last_seen_at'], name='user_battle_available_idx'),
        ),
    ]
