# Generated by Django 5.1.15 on 2025-12-05 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users following this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='following_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users this user follows'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('explorer', 'Explorer'),
                    ('learner', 'Learner'),
                    ('expert', 'Expert'),
                    ('creator', 'Creator'),
                    ('mentor', 'Mentor'),
                    ('patron', 'Patron'),
                    ('admin', 'Admin'),
                    ('agent', 'Agent'),
                    ('vendor', 'Vendor'),
                ],
                default='explorer',
                help_text='User role determines access level and permissions',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'follower',
                    models.ForeignKey(
                        help_text='The user who is following',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='following_set',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'following',
                    models.ForeignKey(
                        help_text='The user being followed',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='followers_set',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['following', '-created_at'], name='userfollow_following_idx'),
                    models.Index(fields=['follower', '-created_at'], name='userfollow_follower_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow'),
                    models.CheckConstraint(
                        condition=models.Q(('follower', models.F('following')), _negated=True), name='no_self_follow'
                    ),
                ],
            },
        ),
    ]
