# Generated by Django 5.1.15 on 2025-12-05 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0012_user_followers_count_user_following_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'use_topic_selections',
                    models.BooleanField(default=True, help_text='Use manually selected topics for recommendations'),
                ),
                ('learn_from_views', models.BooleanField(default=True, help_text='Learn from projects user views')),
                ('learn_from_likes', models.BooleanField(default=True, help_text='Learn from projects user likes')),
                (
                    'consider_skill_level',
                    models.BooleanField(default=True, help_text='Match content difficulty to user skill level'),
                ),
                (
                    'factor_content_difficulty',
                    models.BooleanField(default=True, help_text='Consider content difficulty in recommendations'),
                ),
                (
                    'use_social_signals',
                    models.BooleanField(
                        default=True, help_text='Use following/engagement patterns for recommendations'
                    ),
                ),
                (
                    'discovery_balance',
                    models.IntegerField(
                        default=50, help_text='Balance between familiar content (0) and new discovery (100)'
                    ),
                ),
                (
                    'allow_time_tracking',
                    models.BooleanField(default=True, help_text='Track time spent on pages for better recommendations'),
                ),
                (
                    'allow_scroll_tracking',
                    models.BooleanField(default=True, help_text='Track scroll depth to understand engagement'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        help_text='User these settings belong to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='personalization_settings',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Personalization Settings',
                'verbose_name_plural': 'Personalization Settings',
            },
        ),
    ]
