# Generated by Django 5.1.15 on 2025-12-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0013_add_personalization_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_sections',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=('Ordered list of profile section configurations for the showcase tab'),
            ),
        ),
    ]
