# Generated by Django 5.1.15 on 2025-12-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0014_add_profile_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lifetime_battles_participated',
            field=models.IntegerField(default=0, help_text='Total battles participated in'),
        ),
        migrations.AddField(
            model_name='user',
            name='lifetime_battles_won',
            field=models.IntegerField(default=0, help_text='Total battles won'),
        ),
    ]
