# Generated by Django 5.1.15 on 2025-12-10 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0017_fix_agent_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for impersonation')),
                (
                    'admin_user',
                    models.ForeignKey(
                        help_text='The admin who initiated the impersonation',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='impersonation_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'target_user',
                    models.ForeignKey(
                        help_text='The user being impersonated',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='impersonated_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [
                    models.Index(
                        fields=['admin_user', '-started_at'],
                        name='users_imper_admin_u_0d5432_idx',
                    ),
                    models.Index(
                        fields=['target_user', '-started_at'],
                        name='users_imper_target__1e3114_idx',
                    ),
                ],
            },
        ),
    ]
