# Generated by Django 5.1.15 on 2025-12-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0018_add_impersonation_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_focal_x',
            field=models.FloatField(default=0.5, help_text='Horizontal focal point for avatar crop (0-1, 0.5=center)'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_focal_y',
            field=models.FloatField(default=0.5, help_text='Vertical focal point for avatar crop (0-1, 0.5=center)'),
        ),
    ]
