# Generated by Django 5.1.15 on 2025-12-12 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0019_user_avatar_focal_x_user_avatar_focal_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'old_username',
                    models.CharField(
                        db_index=True, help_text='The previous username before the change', max_length=150
                    ),
                ),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        help_text='The user who changed their username',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='username_history',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Username History',
                'verbose_name_plural': 'Username Histories',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['old_username'], name='username_history_old_idx')],
            },
        ),
    ]
