# Generated by Django 5.1.15 on 2025-12-12 01:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0020_add_username_history'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usernamehistory',
            name='username_history_old_idx',
        ),
    ]
