# Generated by Django 5.1.15 on 2025-12-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0021_remove_redundant_username_history_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationrequest',
            name='desired_integrations',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Integrations user wants for portfolio import (shown if portfolio selected)',
            ),
        ),
        migrations.AddField(
            model_name='invitationrequest',
            name='desired_integrations_other',
            field=models.CharField(blank=True, help_text='Other integration specified by user', max_length=200),
        ),
        migrations.AddField(
            model_name='invitationrequest',
            name='excited_features',
            field=models.JSONField(
                blank=True, default=list, help_text='Features the requester is most excited about (multi-select)'
            ),
        ),
    ]
