# Generated by Django 5.1.15 on 2025-12-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0022_invitationrequest_desired_integrations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizationsettings',
            name='desired_integrations',
            field=models.JSONField(blank=True, default=list, help_text='Integrations user wants for portfolio import'),
        ),
        migrations.AddField(
            model_name='personalizationsettings',
            name='desired_integrations_other',
            field=models.CharField(
                blank=True, default='', help_text='Other integration specified by user', max_length=200
            ),
        ),
        migrations.AddField(
            model_name='personalizationsettings',
            name='excited_features',
            field=models.JSONField(
                blank=True, default=list, help_text='Features the user is most interested in (multi-select)'
            ),
        ),
    ]
