# Generated by Django 5.1.15 on 2025-12-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0023_add_feature_interests_to_personalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationrequest',
            name='approval_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the approval/welcome email was sent', null=True),
        ),
    ]
