# Generated by Django 5.1.15 on 2025-12-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0024_add_approval_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed_at',
            field=models.DateTimeField(
                blank=True, help_text='When the user completed onboarding by selecting a path', null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_path',
            field=models.CharField(
                blank=True,
                choices=[
                    ('battle_pip', 'Prompt Battle'),
                    ('add_project', 'Add Your First Project'),
                    ('explore', 'Explore'),
                ],
                db_index=True,
                help_text='Path selected during onboarding (Prompt Battle, Add Project, or Explore)',
                max_length=20,
            ),
        ),
    ]
