# Generated by Django 5.1.15 on 2025-12-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0025_add_onboarding_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_avatars_created',
            field=models.IntegerField(
                default=0, help_text='Total AI avatars created (for Prompt Engineer achievement)'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='onboarding_path',
            field=models.CharField(
                blank=True,
                choices=[
                    ('battle_pip', 'Prompt Battle'),
                    ('add_project', 'Add Your First Project'),
                    ('explore', 'Explore'),
                    ('personalize', 'Personalize'),
                ],
                db_index=True,
                help_text='Path selected during onboarding (Battle, Project, Explore, or Personalize)',
                max_length=20,
            ),
        ),
    ]
