# Generated by Django 5.1.15 on 2025-12-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0025_add_onboarding_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_contact_requests',
            field=models.BooleanField(
                default=True, help_text='Allow other users to send you contact requests through your projects'
            ),
        ),
    ]
