# Generated by Django 5.1.15 on 2025-12-20 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0058_update_taxonomy_slugs_and_add_missing'),
        ('users', '0026_add_avatar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.ManyToManyField(
                blank=True,
                help_text='User goals (learn new skills, start a business, etc.)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'goal'},
                related_name='users_with_goal',
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='industries',
            field=models.ManyToManyField(
                blank=True,
                help_text='Industry verticals (healthcare, finance, etc.)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'industry'},
                related_name='users_in_industry',
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(
                blank=True,
                help_text='Interest areas (AI & ML, design, automation, etc.)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'interest'},
                related_name='users_with_interest',
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_styles',
            field=models.ManyToManyField(
                blank=True,
                help_text='Preferred learning styles (visual, hands-on, etc.)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'learning_style'},
                related_name='users_with_learning_style',
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='personality',
            field=models.ForeignKey(
                blank=True,
                help_text='MBTI personality type (e.g., INTJ, ENFP)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'personality'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users_with_personality',
                to='core.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(
                blank=True,
                help_text='Professional roles (developer, designer, marketer, etc.)',
                limit_choices_to={'is_active': True, 'taxonomy_type': 'role'},
                related_name='users_with_role',
                to='core.taxonomy',
            ),
        ),
    ]
