# Generated by Django 5.1.15 on 2025-12-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0027_add_taxonomy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_interests',
            field=models.JSONField(
                blank=True, default=list, help_text='Topics this agent is interested in (for agents only)'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='personality_prompt',
            field=models.TextField(
                blank=True, help_text='System prompt defining the agent personality for LLM interactions'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='signature_phrases',
            field=models.JSONField(
                blank=True, default=list, help_text='List of characteristic phrases this agent uses'
            ),
        ),
    ]
