# Generated by Django 5.1.15 on 2025-12-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0028_add_agent_personality_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(
                choices=[
                    ('seedling', 'Seedling'),
                    ('sprout', 'Sprout'),
                    ('blossom', 'Blossom'),
                    ('bloom', 'Bloom'),
                    ('evergreen', 'Evergreen'),
                    ('curation', 'Curation'),
                    ('team', 'All Thrive Team'),
                ],
                default='seedling',
                help_text='User tier based on total points',
                max_length=20,
            ),
        ),
    ]
