# Generated by Django 5.1.15 on 2025-12-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0029_alter_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Free-form admin notes (editable anytime)'),
        ),
    ]
