# Generated by Django 5.1.15 on 2025-12-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0030_invitationrequest_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationrequest',
            name='skill_level',
            field=models.CharField(
                blank=True,
                choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')],
                help_text='Self-reported AI skill level',
                max_length=20,
            ),
        ),
    ]
