# Generated by Django 5.1.15 on 2026-01-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0032_rename_ember_to_ava'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_prompt_dismissed_at',
            field=models.DateTimeField(blank=True, help_text='When user dismissed SMS opt-in prompt', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_prompt_shown_at',
            field=models.DateTimeField(blank=True, help_text='When SMS opt-in prompt was shown to user', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='allow_sms_invitations',
            field=models.BooleanField(
                default=False, help_text='Master switch for receiving SMS notifications (must opt-in)'
            ),
        ),
    ]
