# Generated by Django 5.1.15 on 2026-01-08 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0033_add_sms_prompt_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'name',
                    models.CharField(
                        help_text='Name for this brand voice (e.g., "LinkedIn Professional", "Twitter Casual")',
                        max_length=100,
                    ),
                ),
                (
                    'target_audience',
                    models.TextField(
                        blank=True, help_text='Description of your target audience (e.g., "developers learning AI")'
                    ),
                ),
                (
                    'tone',
                    models.CharField(
                        choices=[
                            ('casual', 'Casual & Friendly'),
                            ('professional', 'Professional'),
                            ('provocative', 'Bold & Provocative'),
                            ('educational', 'Educational'),
                            ('inspirational', 'Inspirational'),
                            ('humorous', 'Humorous'),
                        ],
                        default='professional',
                        help_text='Primary communication tone',
                        max_length=20,
                    ),
                ),
                ('description', models.TextField(blank=True, help_text='Additional notes about your brand voice')),
                (
                    'catchphrases',
                    models.JSONField(
                        blank=True, default=list, help_text='Signature phrases or expressions you like to use'
                    ),
                ),
                (
                    'topics_to_avoid',
                    models.JSONField(blank=True, default=list, help_text='Topics or themes to steer away from'),
                ),
                (
                    'example_hooks',
                    models.JSONField(blank=True, default=list, help_text='Example hooks or openings that worked well'),
                ),
                (
                    'keywords',
                    models.JSONField(
                        blank=True, default=list, help_text='Key terms or jargon relevant to your content'
                    ),
                ),
                (
                    'is_default',
                    models.BooleanField(
                        default=False, help_text='Use this brand voice by default when creating content'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='brand_voices',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
                'indexes': [models.Index(fields=['user', '-is_default'], name='users_brand_user_id_ea7344_idx')],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('is_default', True)),
                        fields=('user',),
                        name='unique_default_brand_voice_per_user',
                    )
                ],
            },
        ),
    ]
