# Generated by Django 5.1.15 on 2025-12-05 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0033_hallucinationmetrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCompetitorView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                (
                    'minutes_between',
                    models.PositiveIntegerField(default=0, help_text='Minutes between viewing tool_a and tool_b'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'tool_a',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='competitor_views_a', to='core.tool'
                    ),
                ),
                (
                    'tool_b',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='competitor_views_b', to='core.tool'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'Tool Competitor View',
                'verbose_name_plural': 'Tool Competitor Views',
                'indexes': [
                    models.Index(fields=['tool_a', '-created_at'], name='vendors_too_tool_a__b55a23_idx'),
                    models.Index(fields=['tool_b', '-created_at'], name='vendors_too_tool_b__d93c09_idx'),
                ],
                'unique_together': {('session_id', 'tool_a', 'tool_b')},
            },
        ),
        migrations.CreateModel(
            name='ToolDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('search_impressions', models.PositiveIntegerField(default=0)),
                ('browse_impressions', models.PositiveIntegerField(default=0)),
                ('recommendation_impressions', models.PositiveIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('external_clicks', models.PositiveIntegerField(default=0)),
                ('docs_clicks', models.PositiveIntegerField(default=0)),
                ('pricing_clicks', models.PositiveIntegerField(default=0)),
                ('github_clicks', models.PositiveIntegerField(default=0)),
                ('bookmarks_added', models.PositiveIntegerField(default=0)),
                ('bookmarks_removed', models.PositiveIntegerField(default=0)),
                ('project_adds', models.PositiveIntegerField(default=0)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0, help_text='Click-through rate: page_views / impressions')),
                (
                    'engagement_rate',
                    models.FloatField(
                        default=0, help_text='Engagement rate: (external_clicks + bookmarks) / page_views'
                    ),
                ),
                ('avg_dwell_time_seconds', models.FloatField(default=0, help_text='Average time on page in seconds')),
                (
                    'top_search_queries',
                    models.JSONField(blank=True, default=list, help_text='Top 10 search queries: [{query, count}]'),
                ),
                (
                    'top_co_viewed_tools',
                    models.JSONField(
                        blank=True, default=list, help_text='Top 10 co-viewed tools: [{tool_id, tool_name, count}]'
                    ),
                ),
                (
                    'user_roles_breakdown',
                    models.JSONField(blank=True, default=dict, help_text='Breakdown by user role: {role: count}'),
                ),
                ('aggregated_at', models.DateTimeField(auto_now=True)),
                (
                    'tool',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='core.tool'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Tool Daily Stats',
                'verbose_name_plural': 'Tool Daily Stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tool', '-date'], name='vendors_too_tool_id_02fe37_idx')],
                'unique_together': {('tool', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ToolEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                (
                    'engagement_type',
                    models.CharField(
                        choices=[
                            ('page_view', 'Viewed Tool Page'),
                            ('external_click', 'Clicked Website'),
                            ('docs_click', 'Clicked Documentation'),
                            ('pricing_click', 'Clicked Pricing'),
                            ('github_click', 'Clicked GitHub'),
                            ('bookmark', 'Bookmarked'),
                            ('unbookmark', 'Removed Bookmark'),
                            ('project_add', 'Added to Project'),
                            ('project_remove', 'Removed from Project'),
                            ('review', 'Left Review'),
                            ('compare_add', 'Added to Comparison'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'dwell_time_seconds',
                    models.PositiveIntegerField(blank=True, help_text='Time spent on page in seconds', null=True),
                ),
                (
                    'scroll_depth_percent',
                    models.PositiveIntegerField(blank=True, help_text='How far user scrolled (0-100)', null=True),
                ),
                ('destination_url', models.URLField(blank=True, help_text='URL clicked (for external clicks)')),
                (
                    'source_context',
                    models.CharField(
                        blank=True, help_text='Where user came from (search, browse, recommendation)', max_length=50
                    ),
                ),
                (
                    'metadata',
                    models.JSONField(blank=True, default=dict, help_text='Additional engagement-specific data'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'tool',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='core.tool'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'Tool Engagement',
                'verbose_name_plural': 'Tool Engagements',
                'indexes': [
                    models.Index(
                        fields=['tool', 'engagement_type', '-created_at'], name='vendors_too_tool_id_036e47_idx'
                    ),
                    models.Index(fields=['tool', '-created_at'], name='vendors_too_tool_id_e77f96_idx'),
                    models.Index(fields=['session_id', '-created_at'], name='vendors_too_session_f07fed_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ToolImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'session_id',
                    models.CharField(db_index=True, help_text='Session ID for anonymous user tracking', max_length=64),
                ),
                (
                    'context',
                    models.CharField(
                        choices=[
                            ('search', 'Search Result'),
                            ('browse', 'Directory Browse'),
                            ('project', 'Project Detail'),
                            ('recommend', 'Recommendation'),
                            ('compare', 'Comparison'),
                            ('profile', 'User Profile'),
                            ('homepage', 'Homepage'),
                            ('tool_detail', 'Tool Detail (Related)'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'position',
                    models.PositiveIntegerField(
                        blank=True, help_text='Position in list (1-indexed) for CTR calculation', null=True
                    ),
                ),
                (
                    'search_query',
                    models.CharField(
                        blank=True, help_text='Search query if impression came from search', max_length=500
                    ),
                ),
                (
                    'referrer_tool_id',
                    models.PositiveIntegerField(
                        blank=True, help_text='Tool ID if impression came from "related tools"', null=True
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'tool',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='core.tool'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        help_text='Authenticated user (null for anonymous)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Tool Impression',
                'verbose_name_plural': 'Tool Impressions',
                'indexes': [
                    models.Index(fields=['tool', '-created_at'], name='vendors_too_tool_id_3a01f3_idx'),
                    models.Index(fields=['session_id', '-created_at'], name='vendors_too_session_6e77b4_idx'),
                    models.Index(fields=['tool', 'context', '-created_at'], name='vendors_too_tool_id_1ab108_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='VendorToolAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_basic', models.BooleanField(default=True, help_text='Can view impressions, views, clicks')),
                ('can_view_competitive', models.BooleanField(default=False, help_text='Can view "also viewed" data')),
                ('can_view_segments', models.BooleanField(default=False, help_text='Can view user segment breakdown')),
                ('can_view_queries', models.BooleanField(default=False, help_text='Can view discovery search queries')),
                ('can_export', models.BooleanField(default=False, help_text='Can export data')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this access grant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'granted_by',
                    models.ForeignKey(
                        blank=True,
                        help_text='Admin who granted this access',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='vendor_access_granted',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'tool',
                    models.ForeignKey(
                        help_text='Tool this vendor has analytics access to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vendor_access',
                        to='core.tool',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='Vendor user who has access to this tool analytics',
                        limit_choices_to={'role': 'vendor'},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vendor_tool_access',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Vendor Tool Access',
                'verbose_name_plural': 'Vendor Tool Access',
                'ordering': ['user__username', 'tool__name'],
                'unique_together': {('user', 'tool')},
            },
        ),
    ]
