# Generated by Django 5.1.15 on 2025-12-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tools', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        # Clear analytics data that references old tool IDs before altering FK
        migrations.RunSQL(
            sql='DELETE FROM vendors_toolcompetitorview;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DELETE FROM vendors_tooldailystats;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DELETE FROM vendors_toolengagement;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DELETE FROM vendors_toolimpression;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DELETE FROM vendors_vendortoolaccess;',
            reverse_sql='',
        ),
        migrations.AlterField(
            model_name='toolcompetitorview',
            name='tool_a',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='competitor_views_a', to='tools.tool'
            ),
        ),
        migrations.AlterField(
            model_name='toolcompetitorview',
            name='tool_b',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='competitor_views_b', to='tools.tool'
            ),
        ),
        migrations.AlterField(
            model_name='tooldailystats',
            name='tool',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='tools.tool'
            ),
        ),
        migrations.AlterField(
            model_name='toolengagement',
            name='tool',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='tools.tool'
            ),
        ),
        migrations.AlterField(
            model_name='toolimpression',
            name='tool',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='tools.tool'
            ),
        ),
        migrations.AlterField(
            model_name='vendortoolaccess',
            name='tool',
            field=models.ForeignKey(
                help_text='Tool this vendor has analytics access to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='vendor_access',
                to='tools.tool',
            ),
        ),
    ]
