# Generated by Django 5.0.14 on 2025-12-03 00:33

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'provider',
                    models.CharField(db_index=True, help_text='e.g., openai, anthropic, cohere', max_length=50),
                ),
                ('model', models.CharField(db_index=True, help_text='e.g., gpt-4, claude-3-opus', max_length=100)),
                (
                    'input_price_per_million',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='USD per 1M input tokens',
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                    ),
                ),
                (
                    'output_price_per_million',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='USD per 1M output tokens',
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                    ),
                ),
                (
                    'effective_date',
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text='When this pricing became effective'
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, help_text='Whether this is the current active pricing'),
                ),
                ('notes', models.TextField(blank=True, help_text='Any notes about this pricing version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Provider Pricing',
                'verbose_name_plural': 'AI Provider Pricing',
                'ordering': ['-effective_date'],
                'indexes': [
                    models.Index(
                        fields=['provider', 'model', '-effective_date'], name='ai_usage_ai_provide_7a500d_idx'
                    ),
                    models.Index(fields=['is_active', '-effective_date'], name='ai_usage_ai_is_acti_bfb311_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'session_id',
                    models.CharField(blank=True, help_text='Session ID for tracking user sessions', max_length=255),
                ),
                (
                    'feature',
                    models.CharField(
                        db_index=True,
                        help_text='Feature that made the request (e.g., chat, project_generation)',
                        max_length=100,
                    ),
                ),
                (
                    'request_type',
                    models.CharField(
                        choices=[
                            ('completion', 'Completion'),
                            ('chat', 'Chat'),
                            ('embedding', 'Embedding'),
                            ('image', 'Image Generation'),
                            ('audio', 'Audio'),
                        ],
                        default='completion',
                        max_length=50,
                    ),
                ),
                (
                    'provider',
                    models.CharField(db_index=True, help_text='AI provider (openai, anthropic, etc.)', max_length=50),
                ),
                (
                    'model',
                    models.CharField(
                        db_index=True, help_text='Model used (gpt-4, claude-3-opus, etc.)', max_length=100
                    ),
                ),
                (
                    'input_tokens',
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    'output_tokens',
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    'total_tokens',
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    'input_cost',
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal('0'),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                    ),
                ),
                (
                    'output_cost',
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal('0'),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                    ),
                ),
                (
                    'total_cost',
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal('0'),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                    ),
                ),
                ('latency_ms', models.IntegerField(blank=True, help_text='Request latency in milliseconds', null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('success', 'Success'),
                            ('error', 'Error'),
                            ('timeout', 'Timeout'),
                            ('rate_limited', 'Rate Limited'),
                        ],
                        db_index=True,
                        default='success',
                        max_length=20,
                    ),
                ),
                ('error_message', models.TextField(blank=True)),
                (
                    'request_metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional request metadata (prompt length, temperature, etc.)',
                    ),
                ),
                (
                    'response_metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional response metadata (finish reason, model version, etc.)',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'pricing_version',
                    models.ForeignKey(
                        blank=True,
                        help_text='Pricing version used for calculation',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='ai_usage.aiproviderpricing',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ai_usage_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', '-created_at'], name='ai_usage_ai_user_id_a167d2_idx'),
                    models.Index(fields=['feature', '-created_at'], name='ai_usage_ai_feature_bd06b8_idx'),
                    models.Index(fields=['provider', 'model', '-created_at'], name='ai_usage_ai_provide_6665e7_idx'),
                    models.Index(fields=['status', '-created_at'], name='ai_usage_ai_status_2ff079_idx'),
                    models.Index(fields=['-created_at', 'total_cost'], name='ai_usage_ai_created_d26d32_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='UserAICostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of this summary')),
                ('total_requests', models.IntegerField(default=0, help_text='Total AI requests made this day')),
                ('total_tokens', models.BigIntegerField(default=0, help_text='Total tokens used this day')),
                (
                    'total_cost',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0'),
                        help_text='Total cost in USD for this day',
                        max_digits=10,
                    ),
                ),
                (
                    'cost_by_feature',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cost breakdown by feature {'chat': 0.50, 'project_gen': 1.20}",
                    ),
                ),
                (
                    'cost_by_provider',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cost breakdown by provider {'openai': 1.20, 'anthropic': 0.50}",
                    ),
                ),
                (
                    'requests_by_feature',
                    models.JSONField(
                        blank=True, default=dict, help_text="Request count by feature {'chat': 10, 'project_gen': 5}"
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ai_cost_summaries',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'User AI Cost Summary',
                'verbose_name_plural': 'User AI Cost Summaries',
                'ordering': ['-date'],
                'indexes': [
                    models.Index(fields=['user', '-date'], name='ai_usage_us_user_id_6f7c88_idx'),
                    models.Index(fields=['date', '-total_cost'], name='ai_usage_us_date_e0d5cd_idx'),
                    models.Index(fields=['-total_cost'], name='ai_usage_us_total_c_b9321e_idx'),
                ],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
