# Generated by Django 5.0.14 on 2025-12-03 01:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ai_usage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiusagelog',
            options={
                'ordering': ['-created_at'],
                'permissions': [
                    ('view_all_usage_logs', 'Can view all AI usage logs'),
                    ('view_usage_details', 'Can view detailed usage information'),
                ],
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
            },
        ),
        migrations.AlterModelOptions(
            name='useraicostsummary',
            options={
                'ordering': ['-date'],
                'permissions': [
                    ('view_all_user_costs', 'Can view all user AI costs'),
                    ('view_cau_metrics', 'Can view CAU analytics'),
                    ('view_pii', 'Can view personally identifiable information'),
                    ('export_usage_data', 'Can export usage data'),
                ],
                'verbose_name': 'User AI Cost Summary',
                'verbose_name_plural': 'User AI Cost Summaries',
            },
        ),
    ]
