# Generated by Django 5.1.15 on 2025-12-05 19:06

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ai_usage', '0002_add_security_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of this summary', unique=True)),
                ('total_users', models.IntegerField(default=0, help_text='Cumulative total users')),
                ('new_users_today', models.IntegerField(default=0, help_text='New signups on this day')),
                (
                    'active_users_today',
                    models.IntegerField(default=0, help_text='Users who logged in or took action today'),
                ),
                ('dau', models.IntegerField(default=0, help_text='Daily Active Users')),
                ('wau', models.IntegerField(default=0, help_text='Weekly Active Users (trailing 7 days)')),
                ('mau', models.IntegerField(default=0, help_text='Monthly Active Users (trailing 30 days)')),
                ('total_ai_requests', models.IntegerField(default=0, help_text='Total AI requests made today')),
                ('total_ai_tokens', models.BigIntegerField(default=0, help_text='Total tokens used today')),
                (
                    'total_ai_cost',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), help_text='Total AI cost today (USD)', max_digits=10
                    ),
                ),
                ('ai_users_today', models.IntegerField(default=0, help_text='Unique users who made AI requests today')),
                (
                    'cau',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0'),
                        help_text='Cost per Active User (total_ai_cost / ai_users_today)',
                        max_digits=10,
                    ),
                ),
                (
                    'ai_by_feature',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="AI usage by feature: {'project_agent': {'requests': 100, 'cost': 1.5}}",
                    ),
                ),
                (
                    'ai_by_provider',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="AI usage by provider: {'openai': {'requests': 50, 'cost': 0.8}}",
                    ),
                ),
                ('total_projects', models.IntegerField(default=0, help_text='Cumulative total projects')),
                ('new_projects_today', models.IntegerField(default=0, help_text='New projects created today')),
                ('total_project_views', models.IntegerField(default=0, help_text='Project page views today')),
                ('total_project_clicks', models.IntegerField(default=0, help_text='Project card clicks today')),
                ('total_comments', models.IntegerField(default=0, help_text='Comments posted today')),
                ('total_quests_completed', models.IntegerField(default=0, help_text='Side quests completed today')),
                ('total_quiz_attempts', models.IntegerField(default=0, help_text='Quiz attempts today')),
                ('total_events_created', models.IntegerField(default=0, help_text='Events created today')),
                ('total_tool_reviews', models.IntegerField(default=0, help_text='Tool reviews posted today')),
                (
                    'revenue_today',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), help_text='Revenue generated today (USD)', max_digits=10
                    ),
                ),
                ('new_subscribers_today', models.IntegerField(default=0, help_text='New paid subscribers today')),
                ('total_subscribers', models.IntegerField(default=0, help_text='Total active subscribers')),
                (
                    'avg_hallucination_score',
                    models.FloatField(
                        blank=True, help_text='Average confidence score from hallucination tracking', null=True
                    ),
                ),
                (
                    'hallucination_flags_count',
                    models.IntegerField(default=0, help_text='Number of hallucination flags today'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Daily Stats',
                'verbose_name_plural': 'Platform Daily Stats',
                'ordering': ['-date'],
                'permissions': [('view_platform_stats', 'Can view platform-wide statistics')],
                'indexes': [
                    models.Index(fields=['-date'], name='ai_usage_pl_date_dfe793_idx'),
                    models.Index(fields=['date', '-total_users'], name='ai_usage_pl_date_7a9c1e_idx'),
                    models.Index(fields=['date', '-total_ai_cost'], name='ai_usage_pl_date_537842_idx'),
                ],
            },
        ),
    ]
