# Generated by Django 5.1.15 on 2025-12-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ai_usage', '0003_platformdailystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of this summary', unique=True)),
                (
                    'hourly_activity',
                    models.JSONField(default=dict, help_text='Activity count by hour: {"0": 10, "1": 5, ...}'),
                ),
                ('day_of_week', models.IntegerField(default=0, help_text='Day of week (0=Monday in Python)')),
                ('total_actions', models.IntegerField(default=0, help_text='Total PointActivity actions this day')),
                ('peak_hour', models.IntegerField(default=0, help_text='Hour with most activity (0-23)')),
                (
                    'feature_usage',
                    models.JSONField(
                        default=dict,
                        help_text='Usage by activity type: {"quiz_complete": {"users": 10, "actions": 50}, ...}',
                    ),
                ),
                ('unique_active_users', models.IntegerField(default=0, help_text='Unique users who took action today')),
                ('signups_today', models.IntegerField(default=0, help_text='New user signups on this day')),
                ('d1_cohort_size', models.IntegerField(default=0, help_text='Users who signed up 1 day ago')),
                ('d1_retained', models.IntegerField(default=0, help_text='D1 cohort users active today')),
                ('d7_cohort_size', models.IntegerField(default=0, help_text='Users who signed up 7 days ago')),
                ('d7_retained', models.IntegerField(default=0, help_text='D7 cohort users active today')),
                ('d30_cohort_size', models.IntegerField(default=0, help_text='Users who signed up 30 days ago')),
                ('d30_retained', models.IntegerField(default=0, help_text='D30 cohort users active today')),
                (
                    'first_action_count',
                    models.IntegerField(default=0, help_text='New users who took their first action today'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Engagement Daily Stats',
                'verbose_name_plural': 'Engagement Daily Stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='ai_usage_en_date_984811_idx')],
            },
        ),
    ]
