# Generated by Django 5.0.14 on 2025-11-26 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('achievements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementprogress',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='achievement_progress',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='achievements.achievement'
            ),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='earned_achievements',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='achievementprogress',
            index=models.Index(fields=['user', 'last_updated'], name='achievement_user_id_44304b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='achievementprogress',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'earned_at'], name='achievement_user_id_f54b28_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['achievement', 'earned_at'], name='achievement_achieve_06fdd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
