# Generated by Django 5.0.14 on 2025-11-26 01:19

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PointActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='Points amount awarded')),
                (
                    'activity_type',
                    models.CharField(
                        choices=[
                            ('quiz_complete', 'Quiz Completed'),
                            ('project_create', 'Project Created'),
                            ('project_update', 'Project Updated'),
                            ('comment', 'Comment Posted'),
                            ('reaction', 'Reaction Given'),
                            ('daily_login', 'Daily Login'),
                            ('streak_bonus', 'Streak Bonus'),
                            ('weekly_goal', 'Weekly Goal Completed'),
                            ('side_quest', 'Side Quest Completed'),
                            ('special_event', 'Special Event'),
                            ('referral', 'Referral Bonus'),
                        ],
                        help_text='Type of activity that earned points',
                        max_length=30,
                    ),
                ),
                ('description', models.CharField(blank=True, help_text='Human-readable description', max_length=255)),
                ('tier_at_time', models.CharField(help_text='User tier when points were earned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Point Activity',
                'verbose_name_plural': 'Point Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SideQuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Quest title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the quest')),
                (
                    'quest_type',
                    models.CharField(
                        choices=[
                            ('quiz_mastery', 'Quiz Mastery'),
                            ('project_showcase', 'Project Showcase'),
                            ('community_helper', 'Community Helper'),
                            ('learning_streak', 'Learning Streak'),
                            ('topic_explorer', 'Topic Explorer'),
                            ('tool_master', 'Tool Master'),
                            ('early_bird', 'Early Bird'),
                            ('night_owl', 'Night Owl'),
                            ('social_butterfly', 'Social Butterfly'),
                            ('content_creator', 'Content Creator'),
                        ],
                        help_text='Type of quest',
                        max_length=50,
                    ),
                ),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('epic', 'Epic')],
                        default='medium',
                        max_length=20,
                    ),
                ),
                (
                    'topic',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('chatbots-conversation', 'Chatbots & Conversation'),
                            ('websites-apps', 'Websites & Apps'),
                            ('images-design-branding', 'Images, Design & Branding'),
                            ('video-creative-media', 'Video & Multimodal Media'),
                            ('podcasts-education', 'Podcasts & Educational Series'),
                            ('games-interactive', 'Games & Interactive Experiences'),
                            ('workflows-automation', 'Workflows & Automation'),
                            ('productivity', 'Productivity'),
                            ('developer-coding', 'Developer & Coding Projects'),
                            ('prompts-templates', 'Prompt Collections & Templates'),
                            ('thought-experiments', 'Thought Experiments & Concept Pieces'),
                            ('wellness-growth', 'Wellness & Personal Growth'),
                            ('ai-agents-multitool', 'AI Agents & Multi-Tool Systems'),
                            ('ai-models-research', 'AI Models & Research'),
                            ('data-analytics', 'Data & Analytics'),
                        ],
                        default='',
                        help_text='Specific topic this quest belongs to (empty = universal quest)',
                        max_length=50,
                    ),
                ),
                (
                    'skill_level',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('beginner', 'Beginner'),
                            ('intermediate', 'Intermediate'),
                            ('advanced', 'Advanced'),
                            ('master', 'Master'),
                        ],
                        default='',
                        help_text='Required skill level for this quest (empty = any level)',
                        max_length=20,
                    ),
                ),
                ('requirements', models.JSONField(default=dict, help_text='JSON object defining quest requirements')),
                (
                    'points_reward',
                    models.IntegerField(
                        help_text='Points awarded on completion',
                        validators=[django.core.validators.MinValueValidator(10)],
                    ),
                ),
                ('is_active', models.BooleanField(default=True, help_text='Whether quest is currently available')),
                ('starts_at', models.DateTimeField(blank=True, help_text='When quest becomes available', null=True)),
                (
                    'expires_at',
                    models.DateTimeField(blank=True, help_text='When quest expires (null = permanent)', null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Side Quest',
                'verbose_name_plural': 'Side Quests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSideQuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('not_started', 'Not Started'),
                            ('in_progress', 'In Progress'),
                            ('completed', 'Completed'),
                            ('expired', 'Expired'),
                        ],
                        default='not_started',
                        max_length=20,
                    ),
                ),
                (
                    'current_progress',
                    models.IntegerField(
                        default=0,
                        help_text='Current progress value',
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'target_progress',
                    models.IntegerField(
                        help_text='Target value to complete (cached from requirements)',
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('progress_data', models.JSONField(default=dict, help_text='Additional progress tracking data')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'points_awarded',
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Side Quest',
                'verbose_name_plural': 'User Side Quests',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'goal_type',
                    models.CharField(
                        choices=[
                            ('activities_3', 'Complete 3 Activities'),
                            ('streak_7', 'Maintain 7-Day Streak'),
                            ('help_5', 'Help 5 Community Members'),
                            ('topics_2', 'Try 2 New Topics'),
                        ],
                        max_length=30,
                    ),
                ),
                ('week_start', models.DateField(help_text='Monday of the week this goal is for')),
                ('week_end', models.DateField(help_text='Sunday of the week this goal is for')),
                (
                    'current_progress',
                    models.IntegerField(
                        default=0,
                        help_text='Current progress towards goal',
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'target_progress',
                    models.IntegerField(
                        help_text='Target to complete goal', validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'points_reward',
                    models.IntegerField(
                        default=30,
                        help_text='Points awarded on completion',
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weekly Goal',
                'verbose_name_plural': 'Weekly Goals',
                'ordering': ['-week_start', 'goal_type'],
            },
        ),
    ]
