# Generated by Django 5.0.14 on 2025-11-25

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='Points amount awarded')),
                (
                    'activity_type',
                    models.CharField(
                        choices=[
                            ('quiz_complete', 'Quiz Completed'),
                            ('project_create', 'Project Created'),
                            ('project_update', 'Project Updated'),
                            ('comment', 'Comment Posted'),
                            ('reaction', 'Reaction Given'),
                            ('daily_login', 'Daily Login'),
                            ('streak_bonus', 'Streak Bonus'),
                            ('weekly_goal', 'Weekly Goal Completed'),
                            ('side_quest', 'Side Quest Completed'),
                            ('special_event', 'Special Event'),
                            ('referral', 'Referral Bonus'),
                        ],
                        help_text='Type of activity that earned points',
                        max_length=30,
                    ),
                ),
                ('description', models.CharField(blank=True, help_text='Human-readable description', max_length=255)),
                ('tier_at_time', models.CharField(help_text='User tier when points were earned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='point_activities',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Point Activity',
                'verbose_name_plural': 'Point Activities',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', '-created_at'], name='thrive_circ_user_id_87eb71_idx'),
                    models.Index(fields=['activity_type', '-created_at'], name='thrive_circ_activit_556701_idx'),
                    models.Index(fields=['user', 'activity_type'], name='thrive_circ_user_act_idx'),
                ],
            },
        ),
    ]
