# Generated by Django 5.0.14 on 2025-11-25 00:50

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('thrive_circle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SideQuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Quest title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the quest')),
                (
                    'quest_type',
                    models.CharField(
                        choices=[
                            ('quiz_mastery', 'Quiz Mastery'),
                            ('project_showcase', 'Project Showcase'),
                            ('community_helper', 'Community Helper'),
                            ('learning_streak', 'Learning Streak'),
                            ('topic_explorer', 'Topic Explorer'),
                            ('tool_master', 'Tool Master'),
                            ('early_bird', 'Early Bird'),
                            ('night_owl', 'Night Owl'),
                            ('social_butterfly', 'Social Butterfly'),
                            ('content_creator', 'Content Creator'),
                        ],
                        help_text='Type of quest',
                        max_length=50,
                    ),
                ),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('epic', 'Epic')],
                        default='medium',
                        max_length=20,
                    ),
                ),
                (
                    'topic',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('chatbots-conversation', 'Chatbots & Conversation'),
                            ('websites-apps', 'Websites & Apps'),
                            ('images-design-branding', 'Images, Design & Branding'),
                            ('video-creative-media', 'Video & Multimodal Media'),
                            ('podcasts-education', 'Podcasts & Educational Series'),
                            ('games-interactive', 'Games & Interactive Experiences'),
                            ('workflows-automation', 'Workflows & Automation'),
                            ('productivity', 'Productivity'),
                            ('developer-coding', 'Developer & Coding Projects'),
                            ('prompts-templates', 'Prompt Collections & Templates'),
                            ('thought-experiments', 'Thought Experiments & Concept Pieces'),
                            ('wellness-growth', 'Wellness & Personal Growth'),
                            ('ai-agents-multitool', 'AI Agents & Multi-Tool Systems'),
                            ('ai-models-research', 'AI Models & Research'),
                            ('data-analytics', 'Data & Analytics'),
                        ],
                        help_text='Specific topic this quest belongs to (null = universal quest)',
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    'skill_level',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('beginner', 'Beginner'),
                            ('intermediate', 'Intermediate'),
                            ('advanced', 'Advanced'),
                            ('master', 'Master'),
                        ],
                        help_text='Required skill level for this quest (null = any level)',
                        max_length=20,
                        null=True,
                    ),
                ),
                ('requirements', models.JSONField(default=dict, help_text='JSON object defining quest requirements')),
                (
                    'points_reward',
                    models.IntegerField(
                        help_text='Points awarded on completion',
                        validators=[django.core.validators.MinValueValidator(10)],
                    ),
                ),
                ('is_active', models.BooleanField(default=True, help_text='Whether quest is currently available')),
                ('starts_at', models.DateTimeField(blank=True, help_text='When quest becomes available', null=True)),
                (
                    'expires_at',
                    models.DateTimeField(blank=True, help_text='When quest expires (null = permanent)', null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Side Quest',
                'verbose_name_plural': 'Side Quests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSideQuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('not_started', 'Not Started'),
                            ('in_progress', 'In Progress'),
                            ('completed', 'Completed'),
                            ('expired', 'Expired'),
                        ],
                        default='not_started',
                        max_length=20,
                    ),
                ),
                (
                    'current_progress',
                    models.IntegerField(
                        default=0,
                        help_text='Current progress value',
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'target_progress',
                    models.IntegerField(
                        help_text='Target value to complete (cached from requirements)',
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('progress_data', models.JSONField(default=dict, help_text='Additional progress tracking data')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'points_awarded',
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Side Quest',
                'verbose_name_plural': 'User Side Quests',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'goal_type',
                    models.CharField(
                        choices=[
                            ('activities_3', 'Complete 3 Activities'),
                            ('streak_7', 'Maintain 7-Day Streak'),
                            ('help_5', 'Help 5 Community Members'),
                            ('topics_2', 'Try 2 New Topics'),
                        ],
                        max_length=30,
                    ),
                ),
                ('week_start', models.DateField(help_text='Monday of the week this goal is for')),
                ('week_end', models.DateField(help_text='Sunday of the week this goal is for')),
                (
                    'current_progress',
                    models.IntegerField(
                        default=0,
                        help_text='Current progress towards goal',
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'target_progress',
                    models.IntegerField(
                        help_text='Target to complete goal', validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'points_reward',
                    models.IntegerField(
                        default=30,
                        help_text='Points awarded on completion',
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weekly Goal',
                'verbose_name_plural': 'Weekly Goals',
                'ordering': ['-week_start', 'goal_type'],
            },
        ),
        migrations.RenameIndex(
            model_name='pointactivity',
            new_name='thrive_circ_user_id_8b03fe_idx',
            old_name='thrive_circ_user_id_87eb71_idx',
        ),
        migrations.RenameIndex(
            model_name='pointactivity',
            new_name='thrive_circ_activit_5b07f1_idx',
            old_name='thrive_circ_activit_556701_idx',
        ),
        migrations.RenameIndex(
            model_name='pointactivity',
            new_name='thrive_circ_user_id_da7491_idx',
            old_name='thrive_circ_user_act_idx',
        ),
        migrations.AddIndex(
            model_name='sidequest',
            index=models.Index(fields=['is_active', '-created_at'], name='thrive_circ_is_acti_7a148e_idx'),
        ),
        migrations.AddIndex(
            model_name='sidequest',
            index=models.Index(fields=['quest_type', 'is_active'], name='thrive_circ_quest_t_edfe5b_idx'),
        ),
        migrations.AddIndex(
            model_name='sidequest',
            index=models.Index(fields=['difficulty', 'is_active'], name='thrive_circ_difficu_eab302_idx'),
        ),
        migrations.AddIndex(
            model_name='sidequest',
            index=models.Index(fields=['topic', 'skill_level', 'is_active'], name='thrive_circ_topic_1f5a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='sidequest',
            index=models.Index(fields=['topic', 'is_active'], name='thrive_circ_topic_68bb1e_idx'),
        ),
        migrations.AddField(
            model_name='usersidequest',
            name='side_quest',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_progresses',
                to='thrive_circle.sidequest',
            ),
        ),
        migrations.AddField(
            model_name='usersidequest',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='side_quests', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name='usersidequest',
            index=models.Index(fields=['user', 'status'], name='thrive_circ_user_id_31a756_idx'),
        ),
        migrations.AddIndex(
            model_name='usersidequest',
            index=models.Index(fields=['user', 'is_completed'], name='thrive_circ_user_id_547006_idx'),
        ),
        migrations.AddIndex(
            model_name='usersidequest',
            index=models.Index(fields=['side_quest', 'is_completed'], name='thrive_circ_side_qu_40a99f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersidequest',
            unique_together={('user', 'side_quest')},
        ),
        migrations.AddIndex(
            model_name='weeklygoal',
            index=models.Index(fields=['user', 'week_start', 'is_completed'], name='thrive_circ_user_id_4994c6_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklygoal',
            index=models.Index(fields=['week_start', '-created_at'], name='thrive_circ_week_st_a290cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklygoal',
            unique_together={('user', 'goal_type', 'week_start')},
        ),
    ]
