# Generated by Django 5.0.14 on 2025-11-26 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('thrive_circle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointactivity',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='point_activities',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='sidequest',
            index=models.Index(fields=['is_active', '-created_at'], name='thrive_circ_is_acti_7a148e_idx'),
        ),
        migrations.AddIndex(
            model_name='sidequest',
            index=models.Index(fields=['quest_type', 'is_active'], name='thrive_circ_quest_t_edfe5b_idx'),
        ),
        migrations.AddIndex(
            model_name='sidequest',
            index=models.Index(fields=['difficulty', 'is_active'], name='thrive_circ_difficu_eab302_idx'),
        ),
        migrations.AddIndex(
            model_name='sidequest',
            index=models.Index(fields=['topic', 'skill_level', 'is_active'], name='thrive_circ_topic_1f5a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='sidequest',
            index=models.Index(fields=['topic', 'is_active'], name='thrive_circ_topic_68bb1e_idx'),
        ),
        migrations.AddField(
            model_name='usersidequest',
            name='side_quest',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_progresses',
                to='thrive_circle.sidequest',
            ),
        ),
        migrations.AddField(
            model_name='usersidequest',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='side_quests', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name='pointactivity',
            index=models.Index(fields=['user', '-created_at'], name='thrive_circ_user_id_8b03fe_idx'),
        ),
        migrations.AddIndex(
            model_name='pointactivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='thrive_circ_activit_5b07f1_idx'),
        ),
        migrations.AddIndex(
            model_name='pointactivity',
            index=models.Index(fields=['user', 'activity_type'], name='thrive_circ_user_id_da7491_idx'),
        ),
        migrations.AddIndex(
            model_name='usersidequest',
            index=models.Index(fields=['user', 'status'], name='thrive_circ_user_id_31a756_idx'),
        ),
        migrations.AddIndex(
            model_name='usersidequest',
            index=models.Index(fields=['user', 'is_completed'], name='thrive_circ_user_id_547006_idx'),
        ),
        migrations.AddIndex(
            model_name='usersidequest',
            index=models.Index(fields=['side_quest', 'is_completed'], name='thrive_circ_side_qu_40a99f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersidequest',
            unique_together={('user', 'side_quest')},
        ),
        migrations.AddIndex(
            model_name='weeklygoal',
            index=models.Index(fields=['user', 'week_start', 'is_completed'], name='thrive_circ_user_id_4994c6_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklygoal',
            index=models.Index(fields=['week_start', '-created_at'], name='thrive_circ_week_st_a290cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklygoal',
            unique_together={('user', 'goal_type', 'week_start')},
        ),
    ]
