# Generated by Django 5.0.14 on 2025-11-24 00:14

from django.db import migrations


def create_user_tiers(apps, schema_editor):
    """Create UserTier records for all existing users who don't have one."""
    User = apps.get_model('core', 'User')
    UserTier = apps.get_model('thrive_circle', 'UserTier')

    # Get all users
    users = User.objects.all()

    # Create UserTier for users who don't have one
    user_tiers_to_create = []
    for user in users:
        if not UserTier.objects.filter(user=user).exists():
            user_tiers_to_create.append(UserTier(user=user, tier='ember', total_xp=0))

    # Bulk create for efficiency
    if user_tiers_to_create:
        UserTier.objects.bulk_create(user_tiers_to_create)
        print(f'Created {len(user_tiers_to_create)} UserTier records')


def reverse_migration(apps, schema_editor):
    """Remove all UserTier records created by this migration."""
    UserTier = apps.get_model('thrive_circle', 'UserTier')
    # Delete all UserTiers with 0 XP (initial state)
    UserTier.objects.filter(total_xp=0, tier='ember').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('thrive_circle', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_tiers, reverse_migration),
    ]
