# Generated by Django 5.0.14 on 2025-11-29 08:11

from django.db import migrations, models

TOPIC_CHOICES = [
    ('chatbots-conversation', 'Chatbots & Conversation'),
    ('websites-apps', 'Websites & Apps'),
    ('images-video', 'Images & Video'),
    ('design-ui', 'Design (Mockups & UI)'),
    ('video-creative-media', 'Video & Multimodal Media'),
    ('podcasts-education', 'Podcasts & Educational Series'),
    ('games-interactive', 'Games & Interactive Experiences'),
    ('workflows-automation', 'Workflows & Automation'),
    ('productivity', 'Productivity'),
    ('developer-coding', 'Developer & Coding Projects'),
    ('prompts-templates', 'Prompt Collections & Templates'),
    ('thought-experiments', 'Thought Experiments & Concept Pieces'),
    ('wellness-growth', 'Wellness & Personal Growth'),
    ('ai-agents-multitool', 'AI Agents & Multi-Tool Systems'),
    ('ai-models-research', 'AI Models & Research'),
    ('data-analytics', 'Data & Analytics'),
]


class Migration(migrations.Migration):
    dependencies = [
        ('thrive_circle', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidequest',
            name='topic',
            field=models.CharField(
                blank=True,
                choices=TOPIC_CHOICES,
                default='',
                help_text='Specific topic this quest belongs to (empty = universal quest)',
                max_length=50,
            ),
        ),
    ]
