# Generated by Django 5.0.14 on 2025-11-24 02:03

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('thrive_circle', '0002_create_user_tiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'goal_type',
                    models.CharField(
                        choices=[
                            ('activities_3', 'Complete 3 Activities'),
                            ('streak_7', 'Maintain 7-Day Streak'),
                            ('help_5', 'Help 5 Community Members'),
                            ('topics_2', 'Try 2 New Topics'),
                        ],
                        max_length=30,
                    ),
                ),
                ('week_start', models.DateField(help_text='Monday of the week this goal is for')),
                ('week_end', models.DateField(help_text='Sunday of the week this goal is for')),
                (
                    'current_progress',
                    models.IntegerField(
                        default=0,
                        help_text='Current progress towards goal',
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'target_progress',
                    models.IntegerField(
                        help_text='Target to complete goal',
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'xp_reward',
                    models.IntegerField(
                        default=30,
                        help_text='XP awarded on completion',
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weekly Goal',
                'verbose_name_plural': 'Weekly Goals',
                'ordering': ['-week_start', 'goal_type'],
            },
        ),
        migrations.AddField(
            model_name='usertier',
            name='current_streak_days',
            field=models.IntegerField(
                default=0,
                help_text='Current consecutive day streak',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name='usertier',
            name='last_activity_date',
            field=models.DateField(
                blank=True,
                help_text='Last date user earned XP (for streak tracking)',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='usertier',
            name='lifetime_comments_posted',
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name='usertier',
            name='lifetime_projects_created',
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name='usertier',
            name='lifetime_quizzes_completed',
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name='usertier',
            name='lifetime_side_quests_completed',
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name='usertier',
            name='longest_streak_days',
            field=models.IntegerField(
                default=0,
                help_text='Longest streak ever achieved',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='usertier',
            name='total_xp',
            field=models.IntegerField(
                default=0,
                help_text='Lifetime XP accumulated (cannot be negative)',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddIndex(
            model_name='xpactivity',
            index=models.Index(
                fields=['user', 'activity_type'],
                name='thrive_circ_user_id_79e1d8_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='usertier',
            constraint=models.CheckConstraint(
                check=models.Q(('total_xp__gte', 0)),
                name='total_xp_non_negative',
            ),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='weekly_goals',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='weeklygoal',
            index=models.Index(
                fields=['user', 'week_start', 'is_completed'],
                name='thrive_circ_user_id_4994c6_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='weeklygoal',
            index=models.Index(
                fields=['week_start', '-created_at'],
                name='thrive_circ_week_st_a290cb_idx',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='weeklygoal',
            unique_together={('user', 'goal_type', 'week_start')},
        ),
    ]
