# Generated by Django 5.0.14 on 2025-12-02 08:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('thrive_circle', '0003_alter_sidequest_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name (e.g., "Community Builder")', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField(help_text='What this category is about')),
                (
                    'category_type',
                    models.CharField(
                        choices=[
                            ('community', 'Community'),
                            ('learning', 'Learning'),
                            ('creative', 'Creative'),
                            ('exploration', 'Exploration'),
                            ('daily', 'Daily'),
                            ('special', 'Special'),
                        ],
                        max_length=20,
                    ),
                ),
                ('icon', models.CharField(default='faCompass', help_text='FontAwesome icon name', max_length=50)),
                ('color_from', models.CharField(default='blue-500', help_text='Gradient start color', max_length=20)),
                ('color_to', models.CharField(default='purple-500', help_text='Gradient end color', max_length=20)),
                (
                    'completion_bonus_points',
                    models.IntegerField(default=100, help_text='Bonus points for completing all quests in category'),
                ),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show prominently on the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quest Category',
                'verbose_name_plural': 'Quest Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='sidequest',
            options={
                'ordering': ['category__order', 'order', '-created_at'],
                'verbose_name': 'Side Quest',
                'verbose_name_plural': 'Side Quests',
            },
        ),
        migrations.AddField(
            model_name='sidequest',
            name='daily_reset_hour',
            field=models.IntegerField(default=0, help_text='Hour (0-23 UTC) when daily quest resets'),
        ),
        migrations.AddField(
            model_name='sidequest',
            name='is_daily',
            field=models.BooleanField(default=False, help_text='Is this a rotating daily quest?'),
        ),
        migrations.AddField(
            model_name='sidequest',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text='Can this quest be completed multiple times?'),
        ),
        migrations.AddField(
            model_name='sidequest',
            name='order',
            field=models.IntegerField(default=0, help_text='Order within category'),
        ),
        migrations.AddField(
            model_name='sidequest',
            name='repeat_cooldown_hours',
            field=models.IntegerField(default=24, help_text='Hours before quest can be repeated (if repeatable)'),
        ),
        migrations.AlterField(
            model_name='sidequest',
            name='quest_type',
            field=models.CharField(
                choices=[
                    ('comment_post', 'Comment on Posts'),
                    ('give_feedback', 'Give Feedback'),
                    ('react_to_projects', 'React to Projects'),
                    ('follow_users', 'Follow Users'),
                    ('complete_quiz', 'Complete Quiz'),
                    ('quiz_streak', 'Quiz Streak'),
                    ('perfect_quiz', 'Perfect Quiz'),
                    ('explore_topics', 'Explore Topics'),
                    ('create_project', 'Create Project'),
                    ('generate_image', 'Generate Image'),
                    ('import_github', 'Import GitHub'),
                    ('add_description', 'Add Description'),
                    ('visit_pages', 'Visit Pages'),
                    ('find_easter_egg', 'Find Easter Egg'),
                    ('explore_profiles', 'Explore Profiles'),
                    ('use_search', 'Use Search'),
                    ('daily_login', 'Daily Login'),
                    ('daily_activity', 'Daily Activity'),
                    ('daily_engagement', 'Daily Engagement'),
                    ('streak_milestone', 'Streak Milestone'),
                    ('level_up', 'Level Up'),
                    ('category_complete', 'Category Complete'),
                ],
                help_text='Type of quest',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='sidequest',
            name='category',
            field=models.ForeignKey(
                blank=True,
                help_text='Quest category/pathway',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='quests',
                to='thrive_circle.questcategory',
            ),
        ),
        migrations.AddIndex(
            model_name='sidequest',
            index=models.Index(fields=['category', 'is_active', 'order'], name='thrive_circ_categor_e55044_idx'),
        ),
        migrations.AddIndex(
            model_name='sidequest',
            index=models.Index(fields=['is_daily', 'is_active'], name='thrive_circ_is_dail_4ba770_idx'),
        ),
    ]
