# Generated by Django 5.0.14 on 2025-12-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('thrive_circle', '0004_add_quest_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidequest',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time to complete in minutes', null=True),
        ),
        migrations.AddField(
            model_name='sidequest',
            name='is_guided',
            field=models.BooleanField(default=False, help_text='True for multi-step guided quests'),
        ),
        migrations.AddField(
            model_name='sidequest',
            name='narrative_complete',
            field=models.TextField(blank=True, help_text='Celebration text shown when quest is completed'),
        ),
        migrations.AddField(
            model_name='sidequest',
            name='narrative_intro',
            field=models.TextField(
                blank=True,
                help_text='Welcome/intro text shown when quest starts (encouraging, educational tone)',
            ),
        ),
        migrations.AddField(
            model_name='sidequest',
            name='steps',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    'Ordered list of quest steps. '
                    'Example: [{"id": "step_1", "title": "Explore", '
                    '"description": "...", "destination_url": "/learn", '
                    '"action_trigger": "page_visit", "icon": "book"}]'
                ),
            ),
        ),
        migrations.AddField(
            model_name='usersidequest',
            name='completed_step_ids',
            field=models.JSONField(
                default=list,
                help_text='List of completed step IDs: ["step_1", "step_2"]',
            ),
        ),
        migrations.AddField(
            model_name='usersidequest',
            name='current_step_index',
            field=models.PositiveIntegerField(default=0, help_text='Index of current step in guided quest (0-based)'),
        ),
        migrations.AddField(
            model_name='usersidequest',
            name='step_completed_at',
            field=models.JSONField(
                default=dict,
                help_text='Timestamps when each step was completed: {"step_1": "2024-01-15T10:00:00Z"}',
            ),
        ),
    ]
