# Generated by Django 5.0.14 on 2025-12-02 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('thrive_circle', '0005_guided_quest_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='questcategory',
            index=models.Index(fields=['is_active', 'order'], name='thrive_circ_is_acti_74f11c_idx'),
        ),
        migrations.AddIndex(
            model_name='questcategory',
            index=models.Index(fields=['slug'], name='thrive_circ_slug_4a9ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='questcategory',
            index=models.Index(
                fields=['is_featured', 'is_active'],
                name='thrive_circ_is_feat_5757ba_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='questcategory',
            index=models.Index(
                fields=['category_type', 'is_active'],
                name='thrive_circ_categor_45acdc_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='usersidequest',
            index=models.Index(fields=['user', '-updated_at'], name='thrive_circ_user_id_179ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='usersidequest',
            index=models.Index(
                fields=['user', 'status', '-updated_at'],
                name='thrive_circ_user_id_d643fa_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='usersidequest',
            index=models.Index(
                fields=['is_completed', '-completed_at'],
                name='thrive_circ_is_comp_51cf4b_idx',
            ),
        ),
    ]
