# Generated by Django 5.0.14 on 2025-12-03 04:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0023_imagegenerationsession_imagegenerationiteration_and_more'),
        ('thrive_circle', '0007_update_quest_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Circle name (e.g., "Seedling Circle #472" or fun generated name)',
                        max_length=100,
                    ),
                ),
                (
                    'tier',
                    models.CharField(
                        choices=[
                            ('seedling', 'Seedling'),
                            ('sprout', 'Sprout'),
                            ('blossom', 'Blossom'),
                            ('bloom', 'Bloom'),
                            ('evergreen', 'Evergreen'),
                        ],
                        help_text='Which tier this circle belongs to',
                        max_length=20,
                    ),
                ),
                (
                    'week_start',
                    models.DateField(help_text='Monday of the week this circle is active'),
                ),
                (
                    'week_end',
                    models.DateField(help_text='Sunday of the week this circle is active'),
                ),
                (
                    'member_count',
                    models.PositiveIntegerField(default=0, help_text='Number of members in circle'),
                ),
                (
                    'active_member_count',
                    models.PositiveIntegerField(default=0, help_text='Members who were active this week'),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Whether this circle is currently active',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Circle',
                'verbose_name_plural': 'Circles',
                'ordering': ['-week_start', 'tier', 'name'],
                'indexes': [
                    models.Index(
                        fields=['tier', 'week_start', 'is_active'],
                        name='thrive_circ_tier_badc18_idx',
                    ),
                    models.Index(
                        fields=['week_start', 'week_end'],
                        name='thrive_circ_week_st_ed7218_idx',
                    ),
                    models.Index(
                        fields=['is_active', '-created_at'],
                        name='thrive_circ_is_acti_b33645_idx',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='CircleChallenge',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'challenge_type',
                    models.CharField(
                        choices=[
                            ('create_projects', 'Create Projects Together'),
                            ('give_feedback', 'Give Feedback to Each Other'),
                            ('complete_quests', 'Complete Side Quests'),
                            ('earn_points', 'Earn Points Together'),
                            ('maintain_streaks', 'Maintain Streaks'),
                        ],
                        help_text='Type of challenge',
                        max_length=30,
                    ),
                ),
                (
                    'title',
                    models.CharField(help_text='Human-readable challenge title', max_length=200),
                ),
                (
                    'description',
                    models.TextField(blank=True, help_text='Detailed description of the challenge'),
                ),
                (
                    'target',
                    models.PositiveIntegerField(help_text='Target value to complete challenge'),
                ),
                (
                    'current_progress',
                    models.PositiveIntegerField(default=0, help_text='Current collective progress'),
                ),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'bonus_points',
                    models.PositiveIntegerField(
                        default=50,
                        help_text='Points awarded to each member when challenge is completed',
                    ),
                ),
                (
                    'rewards_distributed',
                    models.BooleanField(
                        default=False,
                        help_text='Whether bonus points have been distributed to members',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'circle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='challenges',
                        to='thrive_circle.circle',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Circle Challenge',
                'verbose_name_plural': 'Circle Challenges',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['circle', 'is_completed'],
                        name='thrive_circ_circle__84f536_idx',
                    ),
                    models.Index(
                        fields=['challenge_type', 'is_completed'],
                        name='thrive_circ_challen_8d53a1_idx',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='CircleMembership',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                (
                    'points_earned_in_circle',
                    models.IntegerField(default=0, help_text='Points earned while in this circle'),
                ),
                (
                    'was_active',
                    models.BooleanField(
                        default=False,
                        help_text='Whether user was active during this circle period',
                    ),
                ),
                (
                    'circle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='memberships',
                        to='thrive_circle.circle',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='circle_memberships',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Circle Membership',
                'verbose_name_plural': 'Circle Memberships',
                'ordering': ['-joined_at'],
                'indexes': [
                    models.Index(
                        fields=['user', 'is_active'],
                        name='thrive_circ_user_id_2069ce_idx',
                    ),
                    models.Index(
                        fields=['circle', 'is_active'],
                        name='thrive_circ_circle__333e7c_idx',
                    ),
                    models.Index(
                        fields=['user', '-joined_at'],
                        name='thrive_circ_user_id_949671_idx',
                    ),
                ],
                'unique_together': {('user', 'circle')},
            },
        ),
        migrations.CreateModel(
            name='Kudos',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'kudos_type',
                    models.CharField(
                        choices=[
                            ('great_project', '🎨 Great Project'),
                            ('helpful', '🤝 Helpful'),
                            ('inspiring', '✨ Inspiring'),
                            ('creative', '💡 Creative'),
                            ('supportive', '💪 Supportive'),
                            ('welcome', '👋 Welcome'),
                        ],
                        default='helpful',
                        max_length=20,
                    ),
                ),
                (
                    'message',
                    models.CharField(
                        blank=True,
                        help_text='Optional short message (like a tweet)',
                        max_length=280,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'circle',
                    models.ForeignKey(
                        help_text='The circle context where kudos was given',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='kudos',
                        to='thrive_circle.circle',
                    ),
                ),
                (
                    'from_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='kudos_given',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        blank=True,
                        help_text='Optional: kudos for a specific project',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='kudos',
                        to='core.project',
                    ),
                ),
                (
                    'to_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='kudos_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Kudos',
                'verbose_name_plural': 'Kudos',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['to_user', '-created_at'],
                        name='thrive_circ_to_user_62ee02_idx',
                    ),
                    models.Index(
                        fields=['from_user', '-created_at'],
                        name='thrive_circ_from_us_9ef572_idx',
                    ),
                    models.Index(
                        fields=['circle', '-created_at'],
                        name='thrive_circ_circle__59d6a0_idx',
                    ),
                ],
                'unique_together': {('from_user', 'to_user', 'circle', 'kudos_type')},
            },
        ),
    ]
