# Generated by Django 5.1.15 on 2025-12-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('thrive_circle', '0008_add_circle_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointactivity',
            name='activity_type',
            field=models.CharField(
                choices=[
                    ('quiz_complete', 'Quiz Completed'),
                    ('project_create', 'Project Created'),
                    ('project_update', 'Project Updated'),
                    ('comment', 'Comment Posted'),
                    ('reaction', 'Reaction Given'),
                    ('daily_login', 'Daily Login'),
                    ('streak_bonus', 'Streak Bonus'),
                    ('weekly_goal', 'Weekly Goal Completed'),
                    ('side_quest', 'Side Quest Completed'),
                    ('special_event', 'Special Event'),
                    ('referral', 'Referral Bonus'),
                    ('prompt_battle', 'Battle Participation'),
                    ('prompt_battle_win', 'Battle Won'),
                ],
                help_text='Type of activity that earned points',
                max_length=30,
            ),
        ),
    ]
