# Generated by Django 5.1.15 on 2025-12-19 18:28
# Consolidated migration: Cleans up SideQuest topic fields, renames topic_taxonomy to topic

import django.db.models.deletion
from django.db import migrations, models


def cleanup_sidequest_fields(apps, schema_editor):
    """Clean up deprecated topic fields on SideQuest - rename topic_taxonomy_id to topic_id."""
    connection = schema_editor.connection
    quote_name = connection.ops.quote_name

    with connection.cursor() as cursor:
        # Helper to check column existence
        def column_exists(table_name, column_name):
            cursor.execute(
                'SELECT 1 FROM information_schema.columns WHERE table_name = %s AND column_name = %s',
                [table_name, column_name],
            )
            return cursor.fetchone() is not None

        # Helper to check index existence
        def index_exists(index_name):
            cursor.execute('SELECT 1 FROM pg_indexes WHERE indexname = %s', [index_name])
            return cursor.fetchone() is not None

        # Rename indexes if they exist (old names -> new names)
        index_renames = [
            ('thrive_circ_topic_1f5a4d_idx', 'thrive_circ_topic_i_c6dcb3_idx'),
            ('thrive_circ_topic_68bb1e_idx', 'thrive_circ_topic_i_d955a4_idx'),
        ]
        for old_name, new_name in index_renames:
            if index_exists(old_name):
                cursor.execute(f'ALTER INDEX IF EXISTS {quote_name(old_name)} RENAME TO {quote_name(new_name)}')

        # Check current column state
        has_topic = column_exists('thrive_circle_sidequest', 'topic')
        has_topic_taxonomy_id = column_exists('thrive_circle_sidequest', 'topic_taxonomy_id')
        has_topic_id = column_exists('thrive_circle_sidequest', 'topic_id')

        # If topic is a varchar column (old text field), drop it
        if has_topic:
            cursor.execute(
                'SELECT data_type FROM information_schema.columns WHERE table_name = %s AND column_name = %s',
                ['thrive_circle_sidequest', 'topic'],
            )
            result = cursor.fetchone()
            if result and result[0] == 'character varying':
                cursor.execute(
                    f'ALTER TABLE {quote_name("thrive_circle_sidequest")} '
                    f'DROP COLUMN IF EXISTS {quote_name("topic")}'
                )
                has_topic = False

        # Rename topic_taxonomy_id to topic_id if needed
        if has_topic_taxonomy_id and not has_topic_id:
            cursor.execute(
                f'ALTER TABLE {quote_name("thrive_circle_sidequest")} '
                f'RENAME COLUMN {quote_name("topic_taxonomy_id")} TO {quote_name("topic_id")}'
            )

            # Also rename the FK constraint if it exists
            cursor.execute("""
                SELECT constraint_name FROM information_schema.table_constraints
                WHERE table_name = 'thrive_circle_sidequest'
                AND constraint_type = 'FOREIGN KEY'
                AND constraint_name LIKE '%topic_taxonomy%'
            """)
            fk_result = cursor.fetchone()
            if fk_result:
                old_fk_name = fk_result[0]
                new_fk_name = old_fk_name.replace('topic_taxonomy', 'topic')
                cursor.execute(
                    f'ALTER TABLE {quote_name("thrive_circle_sidequest")} '
                    f'RENAME CONSTRAINT {quote_name(old_fk_name)} TO {quote_name(new_fk_name)}'
                )


def reverse_sidequest_fields(apps, schema_editor):
    """Reverse migration - renames topic_id back to topic_taxonomy_id."""
    connection = schema_editor.connection
    quote_name = connection.ops.quote_name

    with connection.cursor() as cursor:
        # Helper to check column existence
        def column_exists(table_name, column_name):
            cursor.execute(
                'SELECT 1 FROM information_schema.columns WHERE table_name = %s AND column_name = %s',
                [table_name, column_name],
            )
            return cursor.fetchone() is not None

        # Helper to check index existence
        def index_exists(index_name):
            cursor.execute('SELECT 1 FROM pg_indexes WHERE indexname = %s', [index_name])
            return cursor.fetchone() is not None

        has_topic_id = column_exists('thrive_circle_sidequest', 'topic_id')
        has_topic_taxonomy_id = column_exists('thrive_circle_sidequest', 'topic_taxonomy_id')

        # Rename topic_id back to topic_taxonomy_id
        if has_topic_id and not has_topic_taxonomy_id:
            cursor.execute(
                f'ALTER TABLE {quote_name("thrive_circle_sidequest")} '
                f'RENAME COLUMN {quote_name("topic_id")} TO {quote_name("topic_taxonomy_id")}'
            )

            # Rename FK constraint back
            cursor.execute("""
                SELECT constraint_name FROM information_schema.table_constraints
                WHERE table_name = 'thrive_circle_sidequest'
                AND constraint_type = 'FOREIGN KEY'
                AND constraint_name LIKE '%_topic_%'
                AND constraint_name NOT LIKE '%topic_taxonomy%'
            """)
            fk_result = cursor.fetchone()
            if fk_result:
                new_fk_name = fk_result[0]
                old_fk_name = new_fk_name.replace('_topic_', '_topic_taxonomy_')
                cursor.execute(
                    f'ALTER TABLE {quote_name("thrive_circle_sidequest")} '
                    f'RENAME CONSTRAINT {quote_name(new_fk_name)} TO {quote_name(old_fk_name)}'
                )

        # Recreate the old text topic column
        if not column_exists('thrive_circle_sidequest', 'topic'):
            cursor.execute(
                f'ALTER TABLE {quote_name("thrive_circle_sidequest")} '
                f'ADD COLUMN {quote_name("topic")} varchar(50) DEFAULT %s',
                [''],
            )

        # Rename indexes back (new names -> old names)
        index_renames = [
            ('thrive_circ_topic_i_c6dcb3_idx', 'thrive_circ_topic_1f5a4d_idx'),
            ('thrive_circ_topic_i_d955a4_idx', 'thrive_circ_topic_68bb1e_idx'),
        ]
        for new_name, old_name in index_renames:
            if index_exists(new_name):
                cursor.execute(f'ALTER INDEX IF EXISTS {quote_name(new_name)} RENAME TO {quote_name(old_name)}')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0056_cleanup_deprecated_topic_fields'),
        ('thrive_circle', '0011_migrate_topics_to_taxonomy'),
    ]

    operations = [
        # Run custom cleanup with proper reverse function
        migrations.RunPython(cleanup_sidequest_fields, reverse_sidequest_fields),
        # Update Django's model state to match database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Remove the old topic CharField from state
                migrations.RemoveField(
                    model_name='sidequest',
                    name='topic',
                ),
                # Remove topic_taxonomy FK from state
                migrations.RemoveField(
                    model_name='sidequest',
                    name='topic_taxonomy',
                ),
                # Add the new topic FK field to state
                # (column already exists as renamed topic_taxonomy_id -> topic_id)
                migrations.AddField(
                    model_name='sidequest',
                    name='topic',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Topic taxonomy this quest belongs to (null = universal quest)',
                        limit_choices_to={'is_active': True, 'taxonomy_type': 'topic'},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='side_quests',
                        to='core.taxonomy',
                    ),
                ),
                # Rename indexes in state
                migrations.RenameIndex(
                    model_name='sidequest',
                    new_name='thrive_circ_topic_i_c6dcb3_idx',
                    old_name='thrive_circ_topic_1f5a4d_idx',
                ),
                migrations.RenameIndex(
                    model_name='sidequest',
                    new_name='thrive_circ_topic_i_d955a4_idx',
                    old_name='thrive_circ_topic_68bb1e_idx',
                ),
            ],
            database_operations=[],
        ),
    ]
