# Generated by Django 5.1.15 on 2025-12-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('thrive_circle', '0012_cleanup_deprecated_topic_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointactivity',
            name='activity_type',
            field=models.CharField(
                choices=[
                    ('quiz_complete', 'Quiz Completed'),
                    ('project_create', 'Project Created'),
                    ('project_update', 'Project Updated'),
                    ('comment', 'Comment Posted'),
                    ('reaction', 'Reaction Given'),
                    ('daily_login', 'Daily Login'),
                    ('streak_bonus', 'Streak Bonus'),
                    ('weekly_goal', 'Weekly Goal Completed'),
                    ('side_quest', 'Side Quest Completed'),
                    ('special_event', 'Special Event'),
                    ('referral', 'Referral Bonus'),
                    ('prompt_battle', 'Battle Participation'),
                    ('prompt_battle_win', 'Battle Won'),
                    ('lesson_complete', 'Lesson Completed'),
                    ('exercise_complete', 'Exercise Completed'),
                    ('learning_path_complete', 'Learning Path Completed'),
                ],
                help_text='Type of activity that earned points',
                max_length=30,
            ),
        ),
    ]
