# Generated by Django 5.1.15 on 2025-12-05 00:04

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0027_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'stripe_connect_account_id',
                    models.CharField(
                        blank=True,
                        help_text='Stripe Express Connect account ID',
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    'onboarding_status',
                    models.CharField(
                        choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('complete', 'Complete')],
                        db_index=True,
                        default='not_started',
                        max_length=20,
                    ),
                ),
                (
                    'charges_enabled',
                    models.BooleanField(default=False, help_text='Whether the account can accept charges'),
                ),
                (
                    'payouts_enabled',
                    models.BooleanField(default=False, help_text='Whether the account can receive payouts'),
                ),
                (
                    'total_earnings',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='Total earnings after platform fees',
                        max_digits=12,
                    ),
                ),
                (
                    'pending_balance',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), help_text='Balance pending payout', max_digits=12
                    ),
                ),
                (
                    'default_currency',
                    models.CharField(default='usd', help_text='Default currency for payouts', max_length=3),
                ),
                ('is_active', models.BooleanField(default=True, help_text='Whether the creator account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='creator_account',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Creator Account',
                'verbose_name_plural': 'Creator Accounts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'product_type',
                    models.CharField(
                        choices=[
                            ('course', 'Course'),
                            ('prompt_pack', 'Prompt Pack'),
                            ('template', 'Template'),
                            ('ebook', 'E-Book'),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')],
                        db_index=True,
                        default='draft',
                        max_length=20,
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='Price in the specified currency',
                        max_digits=10,
                    ),
                ),
                ('currency', models.CharField(default='usd', max_length=3)),
                (
                    'stripe_product_id',
                    models.CharField(blank=True, default='', help_text='Stripe Product ID', max_length=255),
                ),
                (
                    'stripe_price_id',
                    models.CharField(blank=True, default='', help_text='Stripe Price ID', max_length=255),
                ),
                (
                    'source_type',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Import source type (youtube, pdf, notion, etc.)',
                        max_length=50,
                    ),
                ),
                (
                    'source_url',
                    models.URLField(
                        blank=True, default='', help_text='Original source URL if imported', max_length=500
                    ),
                ),
                (
                    'source_metadata',
                    models.JSONField(blank=True, default=dict, help_text='Additional metadata from import source'),
                ),
                ('total_sales', models.PositiveIntegerField(default=0, help_text='Total number of sales')),
                (
                    'total_revenue',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), help_text='Total revenue generated', max_digits=12
                    ),
                ),
                (
                    'is_featured',
                    models.BooleanField(db_index=True, default=False, help_text='Featured on marketplace homepage'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'published_at',
                    models.DateTimeField(blank=True, help_text='When the product was first published', null=True),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='products',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'project',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='product', to='core.project'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'amount_paid',
                    models.DecimalField(decimal_places=2, help_text='Total amount paid by buyer', max_digits=10),
                ),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Platform fee (5%)', max_digits=10)),
                (
                    'stripe_fee',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), help_text='Stripe processing fee', max_digits=10
                    ),
                ),
                (
                    'creator_payout',
                    models.DecimalField(decimal_places=2, help_text='Amount paid to creator after fees', max_digits=10),
                ),
                ('currency', models.CharField(default='usd', max_length=3)),
                (
                    'stripe_payment_intent_id',
                    models.CharField(help_text='Stripe PaymentIntent ID', max_length=255, unique=True),
                ),
                (
                    'stripe_transfer_id',
                    models.CharField(
                        blank=True, default='', help_text='Stripe Transfer ID for creator payout', max_length=255
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('paid', 'Paid'),
                            ('failed', 'Failed'),
                            ('refunded', 'Refunded'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'access_granted_at',
                    models.DateTimeField(blank=True, help_text='When product access was granted to buyer', null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'buyer',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='orders',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sales',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='orders',
                        to='marketplace.product',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                (
                    'expires_at',
                    models.DateTimeField(
                        blank=True, help_text='Access expiration (null for lifetime access)', null=True
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                (
                    'order',
                    models.ForeignKey(
                        blank=True,
                        help_text='Order that granted this access (null for promotional/gifted)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='access_grants',
                        to='marketplace.order',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='access_grants',
                        to='marketplace.product',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='product_access',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Product Access',
                'verbose_name_plural': 'Product Access',
            },
        ),
        migrations.CreateModel(
            name='ProductAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                (
                    'asset_type',
                    models.CharField(
                        choices=[
                            ('download', 'Downloadable File'),
                            ('video', 'Video File'),
                            ('audio', 'Audio File'),
                            ('document', 'Document'),
                        ],
                        default='download',
                        max_length=20,
                    ),
                ),
                ('file_path', models.CharField(help_text='Storage path (MinIO/S3)', max_length=500)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='File size in bytes')),
                ('content_type', models.CharField(blank=True, default='', help_text='MIME type', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_preview', models.BooleanField(default=False, help_text='Available for free preview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='marketplace.product'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Product Asset',
                'verbose_name_plural': 'Product Assets',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['creator', 'status', '-created_at'], name='marketplace_creator_739084_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'status', '-created_at'], name='marketplace_product_635073_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_featured', '-created_at'], name='marketplace_status_f65994_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status', '-created_at'], name='marketplace_buyer_i_8b3529_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['creator', 'status', '-created_at'], name='marketplace_creator_9c258e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product', 'status', '-created_at'], name='marketplace_product_7b2ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='productaccess',
            index=models.Index(fields=['user', 'is_active'], name='marketplace_user_id_33a620_idx'),
        ),
        migrations.AddIndex(
            model_name='productaccess',
            index=models.Index(fields=['product', 'is_active'], name='marketplace_product_d14078_idx'),
        ),
        migrations.AddConstraint(
            model_name='productaccess',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_product_access_per_user'),
        ),
    ]
