# Generated by Django 5.1.15 on 2025-12-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, help_text='Platform fee (8%)', max_digits=10),
        ),
    ]
