# Generated by Django 5.1.15 on 2025-12-17 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                (
                    'view_mode',
                    models.CharField(
                        choices=[('kanban', 'Kanban'), ('table', 'Table')], default='kanban', max_length=20
                    ),
                ),
                (
                    'filters',
                    models.JSONField(
                        default=dict,
                        help_text='Saved filters: {status_ids, type_ids, priority_ids, assignee_ids, search, due_filter}',
                    ),
                ),
                ('sort_by', models.CharField(default='order_in_status', max_length=50)),
                (
                    'sort_direction',
                    models.CharField(choices=[('asc', 'Asc'), ('desc', 'Desc')], default='asc', max_length=4),
                ),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_shared', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_task_dashboards',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'option_type',
                    models.CharField(
                        choices=[('status', 'Status'), ('type', 'Type'), ('priority', 'Priority')],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('color', models.CharField(default='slate', help_text='Tailwind color name or hex', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Heroicon name', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_closed_status', models.BooleanField(default=False, help_text='For status: marks task as done')),
            ],
            options={
                'ordering': ['option_type', 'order', 'name'],
                'indexes': [
                    models.Index(fields=['option_type', 'is_active', 'order'], name='tasks_tasko_option__96ddf9_idx')
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('is_default', True)),
                        fields=('option_type',),
                        name='unique_default_per_option_type',
                    )
                ],
                'unique_together': {('option_type', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order_in_status', models.PositiveIntegerField(db_index=True, default=0)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                (
                    'assignee',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='assigned_tasks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_tasks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='updated_tasks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'priority',
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={'is_active': True, 'option_type': 'priority'},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='tasks_by_priority',
                        to='tasks.taskoption',
                    ),
                ),
                (
                    'status',
                    models.ForeignKey(
                        limit_choices_to={'is_active': True, 'option_type': 'status'},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='tasks_by_status',
                        to='tasks.taskoption',
                    ),
                ),
                (
                    'task_type',
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={'is_active': True, 'option_type': 'type'},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='tasks_by_type',
                        to='tasks.taskoption',
                    ),
                ),
            ],
            options={
                'ordering': ['order_in_status', '-created_at'],
                'indexes': [
                    models.Index(fields=['status', 'order_in_status'], name='tasks_task_status__a4f656_idx'),
                    models.Index(fields=['assignee', 'status'], name='tasks_task_assigne_21077c_idx'),
                    models.Index(fields=['due_date'], name='tasks_task_due_dat_bce847_idx'),
                    models.Index(fields=['is_archived', '-created_at'], name='tasks_task_is_arch_e19e51_idx'),
                ],
            },
        ),
    ]
