# Generated by Django 5.1.15 on 2025-12-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0002_seed_default_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskoption',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name if not provided', max_length=120),
        ),
    ]
