# Generated by Django 5.1.15 on 2025-12-18 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0003_alter_taskoption_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                (
                    'author',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='task_comments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task'
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(fields=['task', 'created_at'], name='tasks_taskc_task_id_3f97e8_idx'),
                    models.Index(fields=['author', '-created_at'], name='tasks_taskc_author__226d21_idx'),
                ],
            },
        ),
    ]
