# Generated by Django 5.1.15 on 2025-12-18 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0004_add_task_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=1000)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='MIME type', max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                (
                    'attachment_type',
                    models.CharField(
                        choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')],
                        default='document',
                        max_length=20,
                    ),
                ),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task'
                    ),
                ),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='task_attachments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [
                    models.Index(fields=['task', 'order'], name='tasks_taska_task_id_611a11_idx'),
                    models.Index(fields=['attachment_type'], name='tasks_taska_attachm_3bc820_idx'),
                ],
            },
        ),
    ]
