openapi: 3.0.3
info:
  title: AllThrive AI Authentication API
  description: Authentication endpoints for React frontend
  version: 1.0.0
  contact:
    name: AllThrive AI Team

servers:
  - url: http://localhost:8000/api
    description: Development server
  - url: https://api.allthriveai.com/api
    description: Production server

paths:
  /auth/login/:
    post:
      summary: User login
      description: Authenticate user with email and password, returns httpOnly cookie with JWT
      operationId: login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          headers:
            Set-Cookie:
              description: JWT token in httpOnly cookie
              schema:
                type: string
                example: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...; HttpOnly; Secure; SameSite=Lax; Path=/
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/logout/:
    post:
      summary: User logout
      description: Invalidate current session and clear authentication cookie
      operationId: logout
      tags:
        - Authentication
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Logout successful
          headers:
            Set-Cookie:
              description: Clear JWT cookie
              schema:
                type: string
                example: jwt=; Max-Age=0; Path=/
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/me/:
    get:
      summary: Get current user
      description: Return information about the currently authenticated user
      operationId: getCurrentUser
      tags:
        - Authentication
      security:
        - cookieAuth: []
      responses:
        '200':
          description: User information retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/refresh/:
    post:
      summary: Refresh authentication token
      description: Refresh the JWT token to extend session
      operationId: refreshToken
      tags:
        - Authentication
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Token refreshed successfully
          headers:
            Set-Cookie:
              description: New JWT token in httpOnly cookie
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '401':
          description: Token invalid or expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt
      description: JWT token stored in httpOnly cookie

  schemas:
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
          description: User's email address
        password:
          type: string
          format: password
          minLength: 8
          example: SecurePassword123!
          description: User's password (minimum 8 characters)
        rememberMe:
          type: boolean
          default: false
          description: Extend session duration if true

    LoginResponse:
      type: object
      required:
        - success
        - data
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: '#/components/schemas/User'
        message:
          type: string
          example: Login successful

    UserResponse:
      type: object
      required:
        - success
        - data
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: '#/components/schemas/User'

    User:
      type: object
      required:
        - id
        - email
        - firstName
        - lastName
        - fullName
        - createdAt
      properties:
        id:
          type: integer
          example: 123
          description: Unique user identifier
        email:
          type: string
          format: email
          example: user@example.com
          description: User's email address
        firstName:
          type: string
          example: John
          minLength: 1
          maxLength: 50
          description: User's first name
        lastName:
          type: string
          example: Doe
          minLength: 1
          maxLength: 50
          description: User's last name
        fullName:
          type: string
          example: John Doe
          description: Computed full name (firstName + lastName)
        createdAt:
          type: string
          format: date-time
          example: '2025-11-10T14:30:00Z'
          description: Account creation timestamp (ISO 8601)

    MessageResponse:
      type: object
      required:
        - success
        - message
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Operation completed successfully

    ErrorResponse:
      type: object
      required:
        - success
        - error
        - statusCode
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: Invalid credentials
          description: Human-readable error message
        details:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          example:
            email: ['Invalid email format']
            password: ['Password is too short']
          description: Field-specific validation errors
        statusCode:
          type: integer
          example: 400
          description: HTTP status code

tags:
  - name: Authentication
    description: User authentication and session management

externalDocs:
  description: AllThrive AI Constitution
  url: file://.specify/memory/constitution.md
