# Generated by Django 5.1.15 on 2025-12-04 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'email_billing',
                    models.BooleanField(
                        default=True, help_text='Receive billing and account-related emails (transactional)'
                    ),
                ),
                ('email_welcome', models.BooleanField(default=True, help_text='Receive welcome and onboarding emails')),
                (
                    'email_battles',
                    models.BooleanField(default=True, help_text='Receive prompt battle invitations and results'),
                ),
                (
                    'email_achievements',
                    models.BooleanField(default=True, help_text='Receive achievement unlock notifications'),
                ),
                (
                    'email_social',
                    models.BooleanField(default=True, help_text='Receive social notifications (followers, comments)'),
                ),
                (
                    'email_quests',
                    models.BooleanField(default=True, help_text='Receive quest assignments and streak reminders'),
                ),
                (
                    'email_marketing',
                    models.BooleanField(
                        default=False, help_text='Receive marketing and promotional emails (opt-in only)'
                    ),
                ),
                (
                    'unsubscribe_token',
                    models.CharField(
                        editable=False, help_text='Secure token for one-click unsubscribe', max_length=64, unique=True
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='email_preferences',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Email Preferences',
                'verbose_name_plural': 'Email Preferences',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(help_text='Type of email (e.g., billing/low_balance)', max_length=50)),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                (
                    'recipient_email',
                    models.EmailField(help_text='Email address the message was sent to', max_length=254),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('sent', 'Sent'),
                            ('failed', 'Failed'),
                            ('bounced', 'Bounced'),
                            ('complained', 'Complained'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('error_message', models.TextField(blank=True, help_text='Error details if send failed')),
                (
                    'ses_message_id',
                    models.CharField(
                        blank=True, help_text='AWS SES Message ID for tracking bounces/complaints', max_length=100
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User who received the email',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='email_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', '-created_at'], name='notificatio_user_id_82d37f_idx'),
                    models.Index(fields=['status', '-created_at'], name='notificatio_status_d84ea4_idx'),
                    models.Index(fields=['ses_message_id'], name='notificatio_ses_mes_acc96c_idx'),
                    models.Index(fields=['created_at'], name='notificatio_created_eaa7a4_idx'),
                ],
            },
        ),
    ]
