# Generated by Django 5.1.15 on 2026-01-02 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'sms_battle_invitations',
                    models.BooleanField(default=True, help_text='Receive battle invitation SMS'),
                ),
                (
                    'sms_battle_results',
                    models.BooleanField(default=True, help_text='Receive battle result notifications'),
                ),
                ('sms_battle_reminders', models.BooleanField(default=True, help_text='Receive battle reminder SMS')),
                ('sms_streak_alerts', models.BooleanField(default=True, help_text='Receive streak at risk alerts')),
                (
                    'consent_given_at',
                    models.DateTimeField(blank=True, help_text='When user explicitly consented to SMS', null=True),
                ),
                (
                    'consent_method',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('opt_in_modal', 'Opt-in Modal'),
                            ('settings_page', 'Settings Page'),
                            ('phone_verification', 'Phone Verification'),
                            ('api', 'API'),
                        ],
                        help_text='How consent was provided',
                        max_length=30,
                    ),
                ),
                (
                    'consent_ip_address',
                    models.GenericIPAddressField(blank=True, help_text='IP address when consent was given', null=True),
                ),
                (
                    'consent_revoked_at',
                    models.DateTimeField(blank=True, help_text='When user revoked SMS consent', null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sms_preferences',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'SMS Preferences',
                'verbose_name_plural': 'SMS Preferences',
                'indexes': [models.Index(fields=['consent_given_at'], name='notificatio_consent_657dc3_idx')],
            },
        ),
    ]
