# Generated by Django 5.1.15 on 2025-12-24 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'feedback_type',
                    models.CharField(choices=[('feature', 'Feature Request'), ('bug', 'Bug Report')], max_length=20),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('open', 'Open'),
                            ('in_progress', 'In Progress'),
                            ('completed', 'Completed'),
                            ('declined', 'Declined'),
                        ],
                        default='open',
                        max_length=20,
                    ),
                ),
                ('vote_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedback_items',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-vote_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedback_comments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'feedback_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedbackitem'
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'feedback_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feedback.feedbackitem'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedback_votes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='feedbackitem',
            index=models.Index(
                fields=['feedback_type', 'status', '-vote_count'], name='feedback_fe_feedbac_cc1cf7_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='feedbackitem',
            index=models.Index(fields=['-created_at'], name='feedback_fe_created_35d17a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcomment',
            index=models.Index(fields=['feedback_item', 'created_at'], name='feedback_fe_feedbac_534052_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackvote',
            index=models.Index(fields=['user', 'feedback_item'], name='feedback_fe_user_id_4b9a5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbackvote',
            constraint=models.UniqueConstraint(fields=('user', 'feedback_item'), name='unique_feedback_vote_per_user'),
        ),
    ]
