# Generated by Django 5.1.15 on 2025-12-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackitem',
            name='category',
            field=models.CharField(
                choices=[
                    ('ui_ux', 'UI/UX'),
                    ('performance', 'Performance'),
                    ('learning', 'Learning & Courses'),
                    ('community', 'Community & Social'),
                    ('tools', 'Tools & Integrations'),
                    ('account', 'Account & Settings'),
                    ('mobile', 'Mobile Experience'),
                    ('accessibility', 'Accessibility'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=20,
            ),
        ),
    ]
