# Generated by Django 5.1.15 on 2025-12-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0003_update_category_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackitem',
            name='category',
            field=models.CharField(
                choices=[
                    ('explore', 'Explore'),
                    ('games', 'Games'),
                    ('prompt_battles', 'Prompt Battles'),
                    ('lounge', 'Lounge'),
                    ('learn', 'Learn'),
                    ('ember', 'Ember'),
                    ('sage', 'Sage'),
                    ('haven', 'Haven'),
                    ('guide', 'Guide'),
                    ('ui_ux', 'UI/UX'),
                    ('responsive', 'Responsive Design'),
                    ('accessibility', 'Accessibility'),
                    ('account', 'Account & Settings'),
                    ('other', 'Other'),
                ],
                default='explore',
                max_length=20,
            ),
        ),
    ]
