# Generated by Django 5.1.15 on 2025-12-04 19:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0025_alter_battlesubmission_submission_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company name (e.g., OpenAI, Anthropic)', max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL to sponsor logo')),
                ('website_url', models.URLField(blank=True, help_text='Sponsor website')),
                ('description', models.TextField(blank=True, help_text='Brief description of the sponsor')),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether sponsor is currently active')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified partner status')),
                ('total_challenges_sponsored', models.IntegerField(default=0)),
                ('total_prize_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'is_verified'], name='challenges__is_acti_74267b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'title',
                    models.CharField(help_text='Challenge title (e.g., "AI Art Week: Dreamscapes")', max_length=200),
                ),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(help_text='Full challenge description and rules')),
                ('prompt', models.TextField(help_text='The actual creative prompt for participants')),
                ('week_number', models.IntegerField(help_text='Week of year (1-52)')),
                ('year', models.IntegerField(help_text='Year')),
                ('starts_at', models.DateTimeField(help_text='When the challenge starts')),
                ('submission_deadline', models.DateTimeField(help_text='Deadline for submissions')),
                (
                    'voting_deadline',
                    models.DateTimeField(
                        blank=True, help_text='Deadline for voting (null if no voting period)', null=True
                    ),
                ),
                ('ends_at', models.DateTimeField(help_text='When the challenge fully ends')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('upcoming', 'Upcoming'),
                            ('active', 'Active'),
                            ('voting', 'Voting Period'),
                            ('completed', 'Completed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('is_featured', models.BooleanField(default=True, help_text='Show on homepage')),
                ('max_submissions_per_user', models.IntegerField(default=3, help_text='Max submissions per user')),
                ('allow_voting', models.BooleanField(default=True, help_text='Enable community voting')),
                ('require_project_link', models.BooleanField(default=False, help_text='Require link to a project')),
                (
                    'allow_external_submissions',
                    models.BooleanField(
                        default=True, help_text='Allow submissions with external URLs (not just projects)'
                    ),
                ),
                ('hero_image_url', models.URLField(blank=True, help_text='Hero image for the challenge page')),
                (
                    'theme_color',
                    models.CharField(default='purple', help_text='Theme color for UI styling', max_length=20),
                ),
                (
                    'prizes',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Prize configuration: {"1st": {"type": "cash", "amount": 100}, ...}',
                    ),
                ),
                (
                    'points_config',
                    models.JSONField(
                        blank=True, default=dict, help_text='Points config: {"submit": 50, "vote": 5, "early_bird": 25}'
                    ),
                ),
                ('submission_count', models.IntegerField(default=0)),
                ('participant_count', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='challenges_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'sponsor',
                    models.ForeignKey(
                        blank=True,
                        help_text='Optional sponsor for this challenge',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='challenges',
                        to='challenges.challengesponsor',
                    ),
                ),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Submission title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('image_url', models.URLField(blank=True, help_text='Direct image URL (if no project)')),
                ('external_url', models.URLField(blank=True, help_text='External link (portfolio, etc.)')),
                (
                    'ai_tool_used',
                    models.CharField(blank=True, help_text='AI tool used (e.g., Midjourney, DALL-E)', max_length=100),
                ),
                ('vote_count', models.IntegerField(db_index=True, default=0)),
                ('judge_score', models.FloatField(blank=True, help_text='Optional judge/AI score (0-100)', null=True)),
                (
                    'final_rank',
                    models.IntegerField(
                        blank=True, db_index=True, help_text='Final rank when challenge ends', null=True
                    ),
                ),
                ('participation_points', models.IntegerField(default=0)),
                ('bonus_points', models.IntegerField(default=0)),
                ('prize_points', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text="Editor's pick")),
                ('is_disqualified', models.BooleanField(default=False)),
                ('disqualification_reason', models.TextField(blank=True)),
                ('is_early_bird', models.BooleanField(default=False, help_text='Submitted within first 24 hours')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'project',
                    models.ForeignKey(
                        blank=True,
                        help_text='Link to an existing project (optional)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='challenge_submissions',
                        to='core.project',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='challenge_submissions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'challenge',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='submissions',
                        to='challenges.weeklychallenge',
                    ),
                ),
            ],
            options={
                'ordering': ['-vote_count', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_count', models.IntegerField(default=0)),
                ('votes_cast', models.IntegerField(default=0)),
                ('votes_received', models.IntegerField(default=0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('best_rank', models.IntegerField(blank=True, null=True)),
                ('prize_awarded', models.JSONField(blank=True, default=dict)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='challenge_participations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'challenge',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='participants',
                        to='challenges.weeklychallenge',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'submission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='votes',
                        to='challenges.challengesubmission',
                    ),
                ),
                (
                    'voter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='challenge_votes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(fields=['submission', '-created_at'], name='challenges__submiss_347349_idx'),
                    models.Index(fields=['voter', '-created_at'], name='challenges__voter_i_a4d1f0_idx'),
                ],
                'unique_together': {('submission', 'voter')},
            },
        ),
        migrations.AddIndex(
            model_name='weeklychallenge',
            index=models.Index(fields=['status', '-starts_at'], name='challenges__status_6e9f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklychallenge',
            index=models.Index(fields=['year', 'week_number'], name='challenges__year_694e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklychallenge',
            index=models.Index(fields=['-starts_at'], name='challenges__starts__f81618_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklychallenge',
            index=models.Index(fields=['is_featured', 'status'], name='challenges__is_feat_1d10c6_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesubmission',
            index=models.Index(fields=['challenge', '-vote_count'], name='challenges__challen_0db819_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesubmission',
            index=models.Index(fields=['challenge', 'user'], name='challenges__challen_43c1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesubmission',
            index=models.Index(fields=['user', '-submitted_at'], name='challenges__user_id_645989_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesubmission',
            index=models.Index(fields=['challenge', 'final_rank'], name='challenges__challen_998f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesubmission',
            index=models.Index(fields=['is_featured', '-vote_count'], name='challenges__is_feat_76136f_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeparticipant',
            index=models.Index(fields=['challenge', 'total_points_earned'], name='challenges__challen_28acc4_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeparticipant',
            index=models.Index(fields=['user', '-joined_at'], name='challenges__user_id_faf2ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeparticipant',
            unique_together={('challenge', 'user')},
        ),
    ]
