# Generated by Django 5.1.15 on 2025-12-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklychallenge',
            name='suggested_tools',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of suggested AI tools: [{"name": "Midjourney", "url": "https://...", "icon": "..."}, ...]',
            ),
        ),
    ]
