# Generated by Django 5.1.15 on 2025-12-07 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'provider',
                    models.CharField(
                        choices=[
                            ('google', 'Google'),
                            ('github', 'GitHub'),
                            ('gitlab', 'GitLab'),
                            ('linkedin', 'LinkedIn'),
                            ('figma', 'Figma'),
                            ('huggingface', 'Hugging Face'),
                            ('midjourney', 'Midjourney'),
                        ],
                        help_text='OAuth provider name',
                        max_length=20,
                    ),
                ),
                ('provider_user_id', models.CharField(help_text='Unique user ID from the provider', max_length=255)),
                (
                    'provider_username',
                    models.CharField(blank=True, help_text='Username on the provider platform', max_length=255),
                ),
                (
                    'provider_email',
                    models.EmailField(
                        blank=True, help_text='Email from provider (if available)', max_length=254, null=True
                    ),
                ),
                ('access_token_encrypted', models.BinaryField(help_text='Encrypted OAuth access token')),
                (
                    'refresh_token_encrypted',
                    models.BinaryField(blank=True, help_text='Encrypted OAuth refresh token', null=True),
                ),
                (
                    'token_expires_at',
                    models.DateTimeField(blank=True, help_text='When the access token expires', null=True),
                ),
                ('scopes', models.TextField(blank=True, help_text='Comma-separated list of granted OAuth scopes')),
                ('profile_url', models.URLField(blank=True, help_text='Link to user profile on provider')),
                ('avatar_url', models.URLField(blank=True, help_text='Profile picture from provider')),
                (
                    'extra_data',
                    models.JSONField(blank=True, default=dict, help_text='Additional provider-specific data'),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, help_text='Whether this connection is currently active'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='social_connections',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'provider'], name='social_soci_user_id_2dc07e_idx'),
                    models.Index(fields=['provider', 'provider_user_id'], name='social_soci_provide_21cd51_idx'),
                ],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
