# Generated by Django 5.1.15 on 2025-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialconnection',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Profile picture from provider', max_length=500),
        ),
        migrations.AlterField(
            model_name='socialconnection',
            name='profile_url',
            field=models.URLField(blank=True, help_text='Link to user profile on provider', max_length=500),
        ),
    ]
