# Generated by Django 5.1.15 on 2026-01-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social', '0002_alter_socialconnection_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialconnection',
            name='provider',
            field=models.CharField(
                choices=[
                    ('google', 'Google'),
                    ('github', 'GitHub'),
                    ('gitlab', 'GitLab'),
                    ('linkedin', 'LinkedIn'),
                    ('figma', 'Figma'),
                    ('huggingface', 'Hugging Face'),
                    ('midjourney', 'Midjourney'),
                    ('instagram', 'Instagram'),
                ],
                help_text='OAuth provider name',
                max_length=20,
            ),
        ),
    ]
