# Generated by Django 5.0.14 on 2025-11-28 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'platform',
                    models.CharField(
                        choices=[('youtube', 'YouTube')],
                        help_text='Platform type (YouTube, RSS, etc.)',
                        max_length=20,
                    ),
                ),
                (
                    'source_identifier',
                    models.CharField(
                        help_text='Platform-specific ID (channel ID for YouTube, feed hash for RSS)',
                        max_length=255,
                    ),
                ),
                (
                    'source_url',
                    models.URLField(help_text='Original URL (e.g., https://youtube.com/channel/UC...)'),
                ),
                (
                    'display_name',
                    models.CharField(
                        help_text='User-friendly name for this source (e.g., channel name)',
                        max_length=255,
                    ),
                ),
                (
                    'sync_enabled',
                    models.BooleanField(default=True, help_text='Enable automatic syncing'),
                ),
                (
                    'sync_frequency',
                    models.CharField(
                        choices=[
                            ('every_2_hours', 'Every 2 Hours'),
                            ('every_4_hours', 'Every 4 Hours'),
                            ('daily', 'Once Daily'),
                            ('manual', 'Manual Only'),
                        ],
                        default='every_2_hours',
                        help_text='How often to check for new content',
                        max_length=20,
                    ),
                ),
                (
                    'last_synced_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='When this source was last synced',
                        null=True,
                    ),
                ),
                (
                    'last_sync_status',
                    models.CharField(
                        default='pending',
                        help_text='Status of last sync (success, error, quota_exceeded, etc.)',
                        max_length=20,
                    ),
                ),
                (
                    'last_sync_error',
                    models.TextField(blank=True, help_text='Error message from last failed sync'),
                ),
                (
                    'metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Platform-specific metadata (ETags, video counts, etc.)',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User who owns this content source',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='content_sources',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Content Source',
                'verbose_name_plural': 'Content Sources',
                'db_table': 'content_sources',
                'indexes': [
                    models.Index(
                        fields=['sync_enabled', 'last_synced_at'],
                        name='content_sou_sync_en_050dd1_idx',
                    ),
                    models.Index(
                        fields=['user', 'platform'],
                        name='content_sou_user_id_5f4ca7_idx',
                    ),
                ],
                'unique_together': {('user', 'platform', 'source_identifier')},
            },
        ),
    ]
