# Generated by Django 5.0.14 on 2025-11-30 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_alter_project_type'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditCommunityBot',
            fields=[
                (
                    'id',
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                (
                    'name',
                    models.CharField(help_text='Display name (e.g., "ClaudeCode Reddit Bot")', max_length=255),
                ),
                (
                    'subreddit',
                    models.CharField(
                        db_index=True,
                        help_text='Target subreddit name (e.g., "ClaudeCode")',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')],
                        db_index=True,
                        default='active',
                        help_text='Bot status (active/paused/error)',
                        max_length=20,
                    ),
                ),
                (
                    'settings',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=('Bot configuration: min_score, min_comments, sync_interval_minutes, etc.'),
                    ),
                ),
                (
                    'last_synced_at',
                    models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True),
                ),
                (
                    'last_sync_status',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Status message from last sync',
                        max_length=50,
                    ),
                ),
                (
                    'last_sync_error',
                    models.TextField(blank=True, default='', help_text='Error message from last failed sync'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'bot_user',
                    models.OneToOneField(
                        help_text='Bot user account (role=BOT) that owns the projects',
                        limit_choices_to={'role': 'bot'},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reddit_bot_config',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Reddit Community Bot',
                'verbose_name_plural': 'Reddit Community Bots',
                'db_table': 'reddit_community_bots',
            },
        ),
        migrations.CreateModel(
            name='RedditThread',
            fields=[
                (
                    'id',
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                (
                    'reddit_post_id',
                    models.CharField(
                        db_index=True,
                        help_text='Reddit post ID (e.g., "t3_1pa4e7t")',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    'subreddit',
                    models.CharField(
                        db_index=True,
                        help_text='Subreddit name (denormalized for queries)',
                        max_length=100,
                    ),
                ),
                (
                    'author',
                    models.CharField(help_text='Reddit username of post author', max_length=100),
                ),
                (
                    'permalink',
                    models.URLField(help_text='Full Reddit URL to the thread', max_length=500),
                ),
                (
                    'score',
                    models.IntegerField(default=0, help_text='Reddit upvote score (at last sync)'),
                ),
                (
                    'num_comments',
                    models.IntegerField(default=0, help_text='Number of comments (at last sync)'),
                ),
                (
                    'thumbnail_url',
                    models.URLField(
                        blank=True,
                        default='',
                        help_text='Reddit thumbnail URL from RSS feed',
                        max_length=500,
                    ),
                ),
                (
                    'created_utc',
                    models.DateTimeField(help_text='When the post was created on Reddit'),
                ),
                (
                    'last_synced_at',
                    models.DateTimeField(auto_now=True, help_text='When we last fetched updates for this thread'),
                ),
                (
                    'reddit_metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional metadata from Reddit RSS feed',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'bot',
                    models.ForeignKey(
                        help_text='Bot that created this thread',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='threads',
                        to='integrations.redditcommunitybot',
                    ),
                ),
                (
                    'project',
                    models.OneToOneField(
                        help_text='Associated Project (type=reddit_thread)',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reddit_thread',
                        to='core.project',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Reddit Thread',
                'verbose_name_plural': 'Reddit Threads',
                'db_table': 'reddit_threads',
                'ordering': ['-created_utc'],
            },
        ),
        migrations.AddIndex(
            model_name='redditcommunitybot',
            index=models.Index(fields=['status', 'last_synced_at'], name='reddit_comm_status_e87cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='redditcommunitybot',
            index=models.Index(fields=['subreddit'], name='reddit_comm_subredd_e4dce5_idx'),
        ),
        migrations.AddIndex(
            model_name='redditthread',
            index=models.Index(fields=['subreddit', '-created_utc'], name='reddit_thre_subredd_d428ef_idx'),
        ),
        migrations.AddIndex(
            model_name='redditthread',
            index=models.Index(fields=['bot', '-created_utc'], name='reddit_thre_bot_id_00efc4_idx'),
        ),
        migrations.AddIndex(
            model_name='redditthread',
            index=models.Index(fields=['-score'], name='reddit_thre_score_5c6118_idx'),
        ),
        migrations.AddIndex(
            model_name='redditthread',
            index=models.Index(fields=['-num_comments'], name='reddit_thre_num_com_a009cb_idx'),
        ),
        migrations.AddIndex(
            model_name='redditthread',
            index=models.Index(fields=['reddit_post_id'], name='reddit_thre_reddit__43dc35_idx'),
        ),
    ]
