# Generated by Django 5.0.14 on 2025-12-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0002_redditcommunitybot_redditthread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditthread',
            name='moderation_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                    ('skipped', 'Skipped'),
                ],
                default='approved',
                db_index=True,
                help_text='Content moderation status',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='redditthread',
            name='moderation_reason',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Reason for moderation decision',
            ),
        ),
        migrations.AddField(
            model_name='redditthread',
            name='moderation_data',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Full moderation results from text and image checks',
            ),
        ),
        migrations.AddField(
            model_name='redditthread',
            name='moderated_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='When content was moderated',
            ),
        ),
    ]
