# Generated by Django 5.0.14 on 2025-12-02 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_add_tags_manually_edited'),
        ('integrations', '0006_add_deletion_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redditcommunityagent',
            options={'verbose_name': 'Reddit Community Agent', 'verbose_name_plural': 'Reddit Community Agents'},
        ),
        migrations.RemoveIndex(
            model_name='redditthread',
            name='reddit_thre_bot_id_00efc4_idx',
        ),
        migrations.RenameIndex(
            model_name='deletedredditthread',
            new_name='deleted_red_reddit__4eb72a_idx',
            old_name='deleted_red_reddit__7f3e2e_idx',
        ),
        migrations.RenameIndex(
            model_name='deletedredditthread',
            new_name='deleted_red_agent_i_1a6a5d_idx',
            old_name='deleted_red_agent_i_5a8c9f_idx',
        ),
        migrations.RenameIndex(
            model_name='redditcommunityagent',
            new_name='reddit_comm_status_0b7f04_idx',
            old_name='reddit_comm_status_e87cb8_idx',
        ),
        migrations.RenameIndex(
            model_name='redditcommunityagent',
            new_name='reddit_comm_subredd_a7ade1_idx',
            old_name='reddit_comm_subredd_e4dce5_idx',
        ),
        migrations.AlterField(
            model_name='redditcommunityagent',
            name='name',
            field=models.CharField(help_text='Display name (e.g., "ClaudeCode Reddit Agent")', max_length=255),
        ),
        migrations.AlterField(
            model_name='redditcommunityagent',
            name='settings',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Agent configuration: min_score, min_comments, sync_interval_minutes, etc.',
            ),
        ),
        migrations.AlterField(
            model_name='redditcommunityagent',
            name='status',
            field=models.CharField(
                choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')],
                db_index=True,
                default='active',
                help_text='Agent status (active/paused/error)',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='redditthread',
            name='agent',
            field=models.ForeignKey(
                help_text='Agent that created this thread',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='threads',
                to='integrations.redditcommunityagent',
            ),
        ),
        migrations.AddIndex(
            model_name='redditthread',
            index=models.Index(fields=['agent', '-created_utc'], name='reddit_thre_agent_i_9b1113_idx'),
        ),
    ]
