# Generated by Django 5.0.14 on 2025-12-02 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_alter_project_type'),
        ('integrations', '0007_alter_redditcommunityagent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeedAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'name',
                    models.CharField(help_text='Display name (e.g., "Google Research Blog Agent")', max_length=255),
                ),
                (
                    'feed_url',
                    models.URLField(db_index=True, help_text='RSS/Atom feed URL', max_length=500, unique=True),
                ),
                (
                    'source_name',
                    models.CharField(
                        help_text='Human-readable source name (e.g., "Google Research Blog")',
                        max_length=200,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')],
                        db_index=True,
                        default='active',
                        help_text='Agent status (active/paused/error)',
                        max_length=20,
                    ),
                ),
                (
                    'settings',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Agent configuration: sync_interval_minutes, max_items, etc.',
                    ),
                ),
                (
                    'last_synced_at',
                    models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True),
                ),
                (
                    'last_sync_status',
                    models.CharField(blank=True, default='', help_text='Status message from last sync', max_length=50),
                ),
                (
                    'last_sync_error',
                    models.TextField(blank=True, default='', help_text='Error message from last failed sync'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'agent_user',
                    models.OneToOneField(
                        help_text='Agent user account (role=AGENT) that owns the projects',
                        limit_choices_to={'role': 'agent'},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rss_agent_config',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'RSS Feed Agent',
                'verbose_name_plural': 'RSS Feed Agents',
                'db_table': 'rss_feed_agents',
            },
        ),
        migrations.CreateModel(
            name='RSSFeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'feed_item_id',
                    models.CharField(
                        db_index=True,
                        help_text='Unique identifier from RSS feed (guid or link)',
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    'source_name',
                    models.CharField(db_index=True, help_text='Source name (denormalized for queries)', max_length=200),
                ),
                (
                    'author',
                    models.CharField(blank=True, default='', help_text='Article author (if available)', max_length=200),
                ),
                ('permalink', models.URLField(help_text='Full URL to the article', max_length=500)),
                (
                    'thumbnail_url',
                    models.URLField(
                        blank=True,
                        default='',
                        help_text='Thumbnail/featured image URL from RSS feed',
                        max_length=500,
                    ),
                ),
                ('categories', models.JSONField(blank=True, default=list, help_text='Categories/tags from RSS feed')),
                ('published_at', models.DateTimeField(help_text='When the article was published')),
                (
                    'last_synced_at',
                    models.DateTimeField(auto_now=True, help_text='When we last fetched updates for this item'),
                ),
                (
                    'rss_metadata',
                    models.JSONField(blank=True, default=dict, help_text='Additional metadata from RSS feed'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'agent',
                    models.ForeignKey(
                        help_text='Agent that created this feed item',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feed_items',
                        to='integrations.rssfeedagent',
                    ),
                ),
                (
                    'project',
                    models.OneToOneField(
                        help_text='Associated Project (type=rss_article)',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rss_feed_item',
                        to='core.project',
                    ),
                ),
            ],
            options={
                'verbose_name': 'RSS Feed Item',
                'verbose_name_plural': 'RSS Feed Items',
                'db_table': 'rss_feed_items',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rssfeedagent',
            index=models.Index(fields=['status', 'last_synced_at'], name='rss_feed_ag_status_cec6b0_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeedagent',
            index=models.Index(fields=['feed_url'], name='rss_feed_ag_feed_ur_0298ef_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeeditem',
            index=models.Index(fields=['source_name', '-published_at'], name='rss_feed_it_source__6a5e90_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeeditem',
            index=models.Index(fields=['agent', '-published_at'], name='rss_feed_it_agent_i_4a7bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeeditem',
            index=models.Index(fields=['feed_item_id'], name='rss_feed_it_feed_it_c4e22a_idx'),
        ),
    ]
