# Generated by Django 5.1.15 on 2025-12-04 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0009_add_youtube_feed_agent_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='youtubefeedagent',
            new_name='youtube_fee_status_3f045e_idx',
            old_name='youtube_fee_status_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='youtubefeedagent',
            new_name='youtube_fee_channel_15cff4_idx',
            old_name='youtube_fee_channel_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='youtubefeedvideo',
            new_name='youtube_fee_channel_cd0208_idx',
            old_name='youtube_fee_channel_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='youtubefeedvideo',
            new_name='youtube_fee_agent_i_ef8ff0_idx',
            old_name='youtube_fee_agent_i_j0k1l2_idx',
        ),
        migrations.RenameIndex(
            model_name='youtubefeedvideo',
            new_name='youtube_fee_video_i_4117ba_idx',
            old_name='youtube_fee_video_i_m3n4o5_idx',
        ),
    ]
