# Generated by Django 5.1.15 on 2025-12-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0010_rename_youtube_fee_status_a1b2c3_idx_youtube_fee_status_3f045e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeedagent',
            name='visual_style',
            field=models.CharField(
                choices=[
                    ('neo_brutalism', 'Neo-Brutalism'),
                    ('dark_academia', 'Dark Academia'),
                    ('cyberpunk', 'Cyberpunk'),
                    ('organic_nature', 'Organic / Nature-Inspired'),
                    ('scandinavian_calm', 'Scandinavian Calm'),
                    ('editorial_magazine', 'Editorial Magazine'),
                    ('corporate_clean', 'Corporate Clean'),
                    ('constructivist_bauhaus', 'Constructivist / Bauhaus'),
                    ('zen_monochrome', 'Zen Monochrome'),
                    ('glass_neon', 'Glass Neon'),
                ],
                default='cyberpunk',
                help_text='Visual style for AI-generated hero images',
                max_length=30,
            ),
        ),
    ]
