# Generated by Django 5.1.15 on 2025-12-17 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0011_add_visual_style_to_rss_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedYouTubeFeedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'video_id',
                    models.CharField(
                        db_index=True,
                        help_text='YouTube video ID that was deleted or rejected',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    'deletion_type',
                    models.CharField(
                        choices=[('admin_deleted', 'Admin Deleted'), ('moderation_failed', 'Moderation Failed')],
                        db_index=True,
                        default='admin_deleted',
                        help_text='Type of deletion: admin or moderation failure',
                        max_length=20,
                    ),
                ),
                (
                    'channel_id',
                    models.CharField(db_index=True, help_text='YouTube channel ID for reference', max_length=100),
                ),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='When the video was deleted')),
                ('deletion_reason', models.TextField(blank=True, default='', help_text='Optional reason for deletion')),
                (
                    'agent',
                    models.ForeignKey(
                        help_text='Agent that originally created this video project',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='deleted_videos',
                        to='integrations.youtubefeedagent',
                    ),
                ),
                (
                    'deleted_by',
                    models.ForeignKey(
                        blank=True,
                        help_text='Admin user who deleted the video',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Deleted YouTube Feed Video',
                'verbose_name_plural': 'Deleted YouTube Feed Videos',
                'db_table': 'deleted_youtube_feed_videos',
                'ordering': ['-deleted_at'],
                'indexes': [
                    models.Index(fields=['video_id'], name='deleted_you_video_i_89ee0f_idx'),
                    models.Index(fields=['agent', '-deleted_at'], name='deleted_you_agent_i_11816c_idx'),
                ],
            },
        ),
    ]
