# Generated by Django 5.1.15 on 2025-12-18 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0011_add_visual_style_to_rss_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.BigIntegerField(help_text='GitHub App installation ID', unique=True)),
                (
                    'account_login',
                    models.CharField(
                        blank=True, help_text='GitHub account login (username or org name)', max_length=255
                    ),
                ),
                (
                    'account_type',
                    models.CharField(blank=True, help_text='Account type (User or Organization)', max_length=20),
                ),
                (
                    'repository_selection',
                    models.CharField(default='all', help_text='Repository selection (all or selected)', max_length=20),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User who installed the app',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='github_app_installations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'GitHub App Installation',
                'verbose_name_plural': 'GitHub App Installations',
                'db_table': 'github_app_installations',
                'indexes': [
                    models.Index(fields=['user'], name='github_app__user_id_59b871_idx'),
                    models.Index(fields=['installation_id'], name='github_app__install_f5a187_idx'),
                ],
            },
        ),
    ]
