# Generated by Django 5.0.14 on 2025-12-01 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'topic',
                    models.CharField(
                        choices=[
                            ('chatbots-conversation', 'Chatbots & Conversation'),
                            ('websites-apps', 'Websites & Apps'),
                            ('images-video', 'Images & Video'),
                            ('design-ui', 'Design (Mockups & UI)'),
                            ('video-creative-media', 'Video & Multimodal Media'),
                            ('podcasts-education', 'Podcasts & Educational Series'),
                            ('games-interactive', 'Games & Interactive Experiences'),
                            ('workflows-automation', 'Workflows & Automation'),
                            ('productivity', 'Productivity'),
                            ('developer-coding', 'Developer & Coding Projects'),
                            ('prompts-templates', 'Prompt Collections & Templates'),
                            ('thought-experiments', 'Thought Experiments & Concept Pieces'),
                            ('wellness-growth', 'Wellness & Personal Growth'),
                            ('ai-agents-multitool', 'AI Agents & Multi-Tool Systems'),
                            ('ai-models-research', 'AI Models & Research'),
                            ('data-analytics', 'Data & Analytics'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'current_skill_level',
                    models.CharField(
                        choices=[
                            ('beginner', 'Beginner'),
                            ('intermediate', 'Intermediate'),
                            ('advanced', 'Advanced'),
                            ('master', 'Master'),
                        ],
                        default='beginner',
                        max_length=20,
                    ),
                ),
                ('quizzes_completed', models.IntegerField(default=0)),
                ('quizzes_total', models.IntegerField(default=0)),
                ('side_quests_completed', models.IntegerField(default=0)),
                ('side_quests_total', models.IntegerField(default=0)),
                ('topic_points', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='learning_paths',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'User Learning Path',
                'verbose_name_plural': 'User Learning Paths',
                'ordering': ['-last_activity_at'],
                'indexes': [
                    models.Index(fields=['user', 'topic'], name='learning_pa_user_id_267930_idx'),
                    models.Index(fields=['user', '-last_activity_at'], name='learning_pa_user_id_93b67c_idx'),
                    models.Index(fields=['topic', 'current_skill_level'], name='learning_pa_topic_34b3e2_idx'),
                ],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
