# Generated by Django 5.1.15 on 2025-12-19 03:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0048_change_is_private_default_to_true'),
        ('learning_paths', '0001_initial'),
        ('tools', '0002_tool_game_stats_tool_rarity_tool_superpowers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                (
                    'topic',
                    models.CharField(
                        db_index=True, help_text='Learning path topic this concept belongs to', max_length=50
                    ),
                ),
                (
                    'base_difficulty',
                    models.CharField(
                        choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')],
                        default='beginner',
                        max_length=20,
                    ),
                ),
                ('estimated_minutes', models.IntegerField(default=5, help_text='Estimated time to learn this concept')),
                (
                    'keywords',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text='Keywords for search and matching',
                        size=None,
                    ),
                ),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'prerequisites',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Concepts that should be learned before this one',
                        related_name='unlocks',
                        to='learning_paths.concept',
                    ),
                ),
                (
                    'tool',
                    models.ForeignKey(
                        blank=True,
                        help_text='Tool this concept is primarily about',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='concepts',
                        to='tools.tool',
                    ),
                ),
            ],
            options={
                'ordering': ['topic', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'preferred_learning_style',
                    models.CharField(
                        choices=[
                            ('visual', 'Visual'),
                            ('hands_on', 'Hands-On'),
                            ('conceptual', 'Conceptual'),
                            ('mixed', 'Mixed'),
                        ],
                        default='mixed',
                        help_text='Preferred learning style (inferred from behavior)',
                        max_length=20,
                    ),
                ),
                (
                    'current_difficulty_level',
                    models.CharField(
                        choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')],
                        default='beginner',
                        help_text='Current adaptive difficulty level',
                        max_length=20,
                    ),
                ),
                (
                    'preferred_session_length',
                    models.IntegerField(default=5, help_text='Preferred learning session length in minutes'),
                ),
                (
                    'allow_proactive_suggestions',
                    models.BooleanField(default=True, help_text='Allow Ember to proactively suggest learning'),
                ),
                (
                    'proactive_cooldown_minutes',
                    models.IntegerField(default=10, help_text='Minimum minutes between proactive nudges'),
                ),
                (
                    'learning_streak_days',
                    models.IntegerField(default=0, help_text='Current consecutive days of learning activity'),
                ),
                ('longest_streak_days', models.IntegerField(default=0, help_text='Longest streak ever achieved')),
                (
                    'last_learning_activity',
                    models.DateTimeField(
                        blank=True, help_text='When user last completed a learning activity', null=True
                    ),
                ),
                (
                    'last_proactive_nudge',
                    models.DateTimeField(blank=True, help_text='When Ember last sent a proactive nudge', null=True),
                ),
                ('total_lessons_completed', models.IntegerField(default=0)),
                ('total_concepts_mastered', models.IntegerField(default=0)),
                ('total_learning_minutes', models.IntegerField(default=0)),
                ('total_quizzes_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='learner_profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Learner Profile',
                'verbose_name_plural': 'Learner Profiles',
            },
        ),
        migrations.CreateModel(
            name='MicroLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                (
                    'lesson_type',
                    models.CharField(
                        choices=[
                            ('explanation', 'Explanation'),
                            ('example', 'Example'),
                            ('practice', 'Practice'),
                            ('tip', 'Quick Tip'),
                        ],
                        default='explanation',
                        max_length=20,
                    ),
                ),
                ('content_template', models.TextField(help_text='Lesson content with markdown support')),
                (
                    'follow_up_prompts',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        blank=True,
                        default=list,
                        help_text='Suggested follow-up questions/prompts',
                        size=None,
                    ),
                ),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')],
                        default='beginner',
                        max_length=20,
                    ),
                ),
                ('estimated_minutes', models.IntegerField(default=3, help_text='Estimated reading/completion time')),
                (
                    'is_ai_generated',
                    models.BooleanField(default=False, help_text='Whether this was AI-generated (vs curated)'),
                ),
                ('times_delivered', models.IntegerField(default=0)),
                ('positive_feedback_count', models.IntegerField(default=0)),
                ('negative_feedback_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'concept',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning_paths.concept'
                    ),
                ),
            ],
            options={
                'ordering': ['concept', 'lesson_type', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('quiz_attempt', 'Quiz Attempt'),
                            ('quiz_completed', 'Quiz Completed'),
                            ('micro_lesson', 'Micro Lesson Viewed'),
                            ('concept_practiced', 'Concept Practiced'),
                            ('concept_mastered', 'Concept Mastered'),
                            ('skill_level_up', 'Skill Level Up'),
                            ('streak_milestone', 'Streak Milestone'),
                            ('project_learned_from', 'Learned from Project'),
                            ('tool_explored', 'Tool Explored'),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    'was_successful',
                    models.BooleanField(
                        blank=True, help_text='Whether the activity was successful (e.g., correct answer)', null=True
                    ),
                ),
                (
                    'payload',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Event-specific data (e.g., quiz_id, score, old_level, new_level)',
                    ),
                ),
                ('xp_earned', models.IntegerField(default=0, help_text='XP points earned from this event')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'concept',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='events',
                        to='learning_paths.concept',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='learning_events',
                        to='core.project',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='learning_events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'lesson',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='events',
                        to='learning_paths.microlesson',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLearningMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'is_learning_eligible',
                    models.BooleanField(
                        db_index=True, default=False, help_text='Meets quality threshold for learning content'
                    ),
                ),
                (
                    'learning_quality_score',
                    models.FloatField(db_index=True, default=0.0, help_text='Quality score for ranking (0.0-1.0)'),
                ),
                (
                    'key_techniques',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text='Key techniques demonstrated (e.g., "RAG", "Streaming")',
                        size=None,
                    ),
                ),
                (
                    'complexity_level',
                    models.CharField(
                        choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')],
                        default='intermediate',
                        max_length=20,
                    ),
                ),
                (
                    'learning_summary',
                    models.TextField(blank=True, help_text='AI-generated summary of what users can learn'),
                ),
                (
                    'times_used_for_learning',
                    models.IntegerField(default=0, help_text='How many times this project was used for learning'),
                ),
                ('last_used_for_learning', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'concepts',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Concepts demonstrated by this project',
                        related_name='example_projects',
                        to='learning_paths.concept',
                    ),
                ),
                (
                    'project',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='learning_metadata', to='core.project'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project Learning Metadata',
                'verbose_name_plural': 'Project Learning Metadata',
                'ordering': ['-learning_quality_score'],
            },
        ),
        migrations.CreateModel(
            name='UserConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'mastery_level',
                    models.CharField(
                        choices=[
                            ('unknown', 'Unknown'),
                            ('aware', 'Aware'),
                            ('learning', 'Learning'),
                            ('practicing', 'Practicing'),
                            ('proficient', 'Proficient'),
                            ('mastered', 'Mastered'),
                        ],
                        db_index=True,
                        default='unknown',
                        max_length=20,
                    ),
                ),
                ('mastery_score', models.FloatField(default=0.0, help_text='Mastery score 0.0-1.0')),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                (
                    'next_review_at',
                    models.DateTimeField(blank=True, help_text='When to review for spaced repetition', null=True),
                ),
                (
                    'consecutive_correct',
                    models.IntegerField(default=0, help_text='Consecutive correct answers (for SR interval)'),
                ),
                ('consecutive_incorrect', models.IntegerField(default=0, help_text='Consecutive incorrect answers')),
                ('times_practiced', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'concept',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_masteries',
                        to='learning_paths.concept',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='concept_masteries',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'User Concept Mastery',
                'verbose_name_plural': 'User Concept Masteries',
            },
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['topic', 'is_active'], name='learning_pa_topic_18edb9_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['base_difficulty', 'is_active'], name='learning_pa_base_di_ab1bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='microlesson',
            index=models.Index(fields=['concept', 'is_active'], name='learning_pa_concept_74a7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='microlesson',
            index=models.Index(fields=['is_ai_generated', 'is_active'], name='learning_pa_is_ai_g_1af5ab_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['user', '-created_at'], name='learning_pa_user_id_c24277_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['user', 'event_type', '-created_at'], name='learning_pa_user_id_3fd1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['event_type', '-created_at'], name='learning_pa_event_t_473a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectlearningmetadata',
            index=models.Index(
                fields=['is_learning_eligible', '-learning_quality_score'], name='learning_pa_is_lear_ad2bb6_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='userconceptmastery',
            index=models.Index(fields=['user', 'mastery_level'], name='learning_pa_user_id_43006c_idx'),
        ),
        migrations.AddIndex(
            model_name='userconceptmastery',
            index=models.Index(fields=['user', 'next_review_at'], name='learning_pa_user_id_42bd61_idx'),
        ),
        migrations.AddIndex(
            model_name='userconceptmastery',
            index=models.Index(fields=['concept', 'mastery_level'], name='learning_pa_concept_73755b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userconceptmastery',
            unique_together={('user', 'concept')},
        ),
    ]
