# Generated by Django 5.1.15 on 2025-12-19 04:50
# Modified to use RenameField and RunSQL for data migration

from django.db import migrations, models


def update_skill_levels(apps, schema_editor):
    """Update 'master' to 'expert' in existing data."""
    UserLearningPath = apps.get_model('learning_paths', 'UserLearningPath')
    UserLearningPath.objects.filter(current_skill_level='master').update(current_skill_level='expert')


def update_mastery_levels(apps, schema_editor):
    """Update 'mastered' to 'expert' in existing data."""
    UserConceptMastery = apps.get_model('learning_paths', 'UserConceptMastery')
    UserConceptMastery.objects.filter(mastery_level='mastered').update(mastery_level='expert')


def update_event_types(apps, schema_editor):
    """Update 'concept_mastered' to 'concept_completed' in existing data."""
    LearningEvent = apps.get_model('learning_paths', 'LearningEvent')
    LearningEvent.objects.filter(event_type='concept_mastered').update(event_type='concept_completed')


def reverse_skill_levels(apps, schema_editor):
    """Reverse: update 'expert' back to 'master'."""
    UserLearningPath = apps.get_model('learning_paths', 'UserLearningPath')
    UserLearningPath.objects.filter(current_skill_level='expert').update(current_skill_level='master')


def reverse_mastery_levels(apps, schema_editor):
    """Reverse: update 'expert' back to 'mastered'."""
    UserConceptMastery = apps.get_model('learning_paths', 'UserConceptMastery')
    UserConceptMastery.objects.filter(mastery_level='expert').update(mastery_level='mastered')


def reverse_event_types(apps, schema_editor):
    """Reverse: update 'concept_completed' back to 'concept_mastered'."""
    LearningEvent = apps.get_model('learning_paths', 'LearningEvent')
    LearningEvent.objects.filter(event_type='concept_completed').update(event_type='concept_mastered')


class Migration(migrations.Migration):
    dependencies = [
        ('learning_paths', '0002_concept_learnerprofile_microlesson_learningevent_and_more'),
    ]

    operations = [
        # Step 1: Rename the field (preserves data)
        migrations.RenameField(
            model_name='learnerprofile',
            old_name='total_concepts_mastered',
            new_name='total_concepts_completed',
        ),
        # Step 2: Update existing data for skill levels (before changing choices)
        migrations.RunPython(update_skill_levels, reverse_skill_levels),
        # Step 3: Update existing data for mastery levels (before changing choices)
        migrations.RunPython(update_mastery_levels, reverse_mastery_levels),
        # Step 4: Update existing data for event types (before changing choices)
        migrations.RunPython(update_event_types, reverse_event_types),
        # Step 5: Update the choices for event_type
        migrations.AlterField(
            model_name='learningevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('quiz_attempt', 'Quiz Attempt'),
                    ('quiz_completed', 'Quiz Completed'),
                    ('micro_lesson', 'Micro Lesson Viewed'),
                    ('concept_practiced', 'Concept Practiced'),
                    ('concept_completed', 'Concept Completed'),
                    ('skill_level_up', 'Skill Level Up'),
                    ('streak_milestone', 'Streak Milestone'),
                    ('project_learned_from', 'Learned from Project'),
                    ('tool_explored', 'Tool Explored'),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        # Step 6: Update the choices for mastery_level
        migrations.AlterField(
            model_name='userconceptmastery',
            name='mastery_level',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unknown'),
                    ('aware', 'Aware'),
                    ('learning', 'Learning'),
                    ('practicing', 'Practicing'),
                    ('proficient', 'Proficient'),
                    ('expert', 'Expert'),
                ],
                db_index=True,
                default='unknown',
                max_length=20,
            ),
        ),
        # Step 7: Update the choices for current_skill_level
        migrations.AlterField(
            model_name='userlearningpath',
            name='current_skill_level',
            field=models.CharField(
                choices=[
                    ('beginner', 'Beginner'),
                    ('intermediate', 'Intermediate'),
                    ('advanced', 'Advanced'),
                    ('expert', 'Expert'),
                ],
                default='beginner',
                max_length=20,
            ),
        ),
    ]
