# Generated by Django 5.1.15 on 2025-12-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning_paths', '0003_remove_learnerprofile_total_concepts_mastered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='celebration_enabled',
            field=models.BooleanField(default=True, help_text='Whether to show milestone celebrations'),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='current_focus_topic',
            field=models.CharField(blank=True, help_text='Current topic the user is focusing on', max_length=50),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='generated_path',
            field=models.JSONField(
                blank=True, help_text='AI-generated personalized learning path structure', null=True
            ),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='has_completed_path_setup',
            field=models.BooleanField(
                default=False, help_text='Whether user completed the cold-start learning path setup'
            ),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='learning_goal',
            field=models.CharField(
                blank=True,
                choices=[
                    ('build_projects', 'Build AI Projects'),
                    ('understand_concepts', 'Understand AI Concepts'),
                    ('career', 'Career Exploration'),
                    ('exploring', 'Just Exploring'),
                ],
                help_text='User-selected learning goal from cold-start',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='path_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the learning path was generated', null=True),
        ),
    ]
