# Generated by Django 5.1.15 on 2025-12-19 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0049_taxonomy_parent_alter_taxonomy_taxonomy_type'),
        ('learning_paths', '0004_learnerprofile_celebration_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'verb',
                    models.CharField(help_text='Action verb (e.g., "build", "explain", "analyze")', max_length=50),
                ),
                (
                    'description',
                    models.TextField(help_text='Full outcome statement (e.g., "Build a RAG pipeline using LangChain")'),
                ),
                (
                    'bloom_level',
                    models.CharField(
                        choices=[
                            ('remember', 'Remember'),
                            ('understand', 'Understand'),
                            ('apply', 'Apply'),
                            ('analyze', 'Analyze'),
                            ('evaluate', 'Evaluate'),
                            ('create', 'Create'),
                        ],
                        db_index=True,
                        default='apply',
                        max_length=20,
                    ),
                ),
                (
                    'proficiency_gained',
                    models.CharField(
                        choices=[
                            ('beginner', 'Beginner'),
                            ('intermediate', 'Intermediate'),
                            ('advanced', 'Advanced'),
                            ('expert', 'Expert'),
                        ],
                        default='beginner',
                        help_text='Proficiency level achieved when mastering this outcome',
                        max_length=20,
                    ),
                ),
                (
                    'assessment_criteria',
                    models.JSONField(
                        blank=True, default=list, help_text='How to verify mastery: [{criterion, evidence_type}, ...]'
                    ),
                ),
                (
                    'estimated_hours',
                    models.FloatField(default=1.0, help_text='Estimated hours to achieve this outcome'),
                ),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'prerequisites',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Outcomes that should be achieved first',
                        related_name='unlocks',
                        to='learning_paths.learningoutcome',
                    ),
                ),
                (
                    'skill',
                    models.ForeignKey(
                        help_text='The skill this outcome develops',
                        limit_choices_to={'taxonomy_type': 'skill'},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='learning_outcomes',
                        to='core.taxonomy',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Learning Outcome',
                'verbose_name_plural': 'Learning Outcomes',
                'ordering': ['skill', 'bloom_level', 'verb'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'proficiency_level',
                    models.CharField(
                        choices=[
                            ('none', 'None'),
                            ('beginner', 'Beginner'),
                            ('intermediate', 'Intermediate'),
                            ('advanced', 'Advanced'),
                            ('expert', 'Expert'),
                        ],
                        db_index=True,
                        default='none',
                        max_length=20,
                    ),
                ),
                (
                    'is_self_assessed',
                    models.BooleanField(default=True, help_text='Whether this was self-assessed vs system-calculated'),
                ),
                ('first_assessed_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                (
                    'outcomes_achieved',
                    models.ManyToManyField(
                        blank=True, related_name='users_achieved', to='learning_paths.learningoutcome'
                    ),
                ),
                (
                    'skill',
                    models.ForeignKey(
                        limit_choices_to={'taxonomy_type': 'skill'},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_proficiencies',
                        to='core.taxonomy',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='skill_proficiencies',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'User Skill Proficiency',
                'verbose_name_plural': 'User Skill Proficiencies',
            },
        ),
        migrations.CreateModel(
            name='ContentGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'topic',
                    models.CharField(db_index=True, help_text='Original topic text requested by user', max_length=200),
                ),
                (
                    'topic_normalized',
                    models.CharField(
                        db_index=True, help_text='Normalized/slugified version for deduplication', max_length=200
                    ),
                ),
                (
                    'modality',
                    models.CharField(
                        db_index=True, help_text='Learning modality requested (video, quiz, etc.)', max_length=30
                    ),
                ),
                (
                    'gap_type',
                    models.CharField(
                        choices=[
                            ('missing_topic', 'Missing Topic'),
                            ('modality_gap', 'Modality Gap'),
                            ('depth_gap', 'Depth Gap'),
                        ],
                        db_index=True,
                        default='missing_topic',
                        max_length=20,
                    ),
                ),
                (
                    'request_count',
                    models.PositiveIntegerField(
                        db_index=True, default=1, help_text='Number of times this has been requested'
                    ),
                ),
                (
                    'unique_user_count',
                    models.PositiveIntegerField(default=1, help_text='Number of unique users who requested this'),
                ),
                (
                    'results_returned',
                    models.PositiveIntegerField(
                        default=0, help_text='Number of results returned when gap was detected'
                    ),
                ),
                ('first_requested_at', models.DateTimeField(auto_now_add=True)),
                ('last_requested_at', models.DateTimeField(auto_now=True, db_index=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending Review'),
                            ('acknowledged', 'Acknowledged'),
                            ('in_progress', 'Content In Progress'),
                            ('resolved', 'Resolved'),
                            ('declined', 'Declined'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                (
                    'context',
                    models.JSONField(
                        blank=True, default=dict, help_text='Additional context: {conversation_id, user_level, etc.}'
                    ),
                ),
                (
                    'first_requested_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='content_gap_requests',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'matched_taxonomy',
                    models.ForeignKey(
                        blank=True,
                        help_text='Closest matching taxonomy item (if partial match)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='gap_requests',
                        to='core.taxonomy',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Content Gap',
                'verbose_name_plural': 'Content Gaps',
                'ordering': ['-request_count', '-last_requested_at'],
                'indexes': [
                    models.Index(fields=['status', '-request_count'], name='learning_pa_status_a75c97_idx'),
                    models.Index(fields=['gap_type', '-request_count'], name='learning_pa_gap_typ_3a168e_idx'),
                    models.Index(fields=['modality', '-request_count'], name='learning_pa_modalit_c8cfa9_idx'),
                ],
                'unique_together': {('topic_normalized', 'modality')},
            },
        ),
        migrations.AddIndex(
            model_name='learningoutcome',
            index=models.Index(fields=['skill', 'is_active'], name='learning_pa_skill_i_149b81_idx'),
        ),
        migrations.AddIndex(
            model_name='learningoutcome',
            index=models.Index(fields=['bloom_level', 'proficiency_gained'], name='learning_pa_bloom_l_5cbc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillproficiency',
            index=models.Index(fields=['user', 'proficiency_level'], name='learning_pa_user_id_bf4c23_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillproficiency',
            index=models.Index(fields=['skill', 'proficiency_level'], name='learning_pa_skill_i_d7584f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userskillproficiency',
            unique_together={('user', 'skill')},
        ),
    ]
