# Generated by Django 5.1.15 on 2025-12-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning_paths', '0008_is_learning_eligible_default_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='topic',
            field=models.CharField(db_index=True, help_text='DEPRECATED: Use topic_taxonomy instead.', max_length=50),
        ),
        migrations.AlterField(
            model_name='contentgap',
            name='topic',
            field=models.CharField(
                db_index=True, help_text='DEPRECATED: Original topic text requested by user.', max_length=200
            ),
        ),
        migrations.AlterField(
            model_name='contentgap',
            name='topic_normalized',
            field=models.CharField(
                db_index=True, help_text='DEPRECATED: Normalized/slugified version for deduplication.', max_length=200
            ),
        ),
    ]
