# Generated by Django 5.1.15 on 2025-12-21 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning_paths', '0010_add_weaviate_sync_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentHelpfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_type',
                    models.CharField(
                        choices=[
                            ('micro_lesson', 'Micro Lesson'),
                            ('quiz_explanation', 'Quiz Explanation'),
                            ('concept_explanation', 'Concept Explanation'),
                            ('project_learning', 'Project as Learning Resource'),
                            ('tool_info', 'Tool Information'),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    'content_id',
                    models.CharField(help_text='ID of the content (lesson ID, quiz ID, etc.)', max_length=255),
                ),
                (
                    'helpfulness',
                    models.CharField(
                        choices=[
                            ('very_helpful', 'Very Helpful'),
                            ('helpful', 'Helpful'),
                            ('neutral', 'Neutral'),
                            ('not_helpful', 'Not Helpful'),
                            ('confusing', 'Confusing'),
                        ],
                        max_length=20,
                    ),
                ),
                ('comment', models.TextField(blank=True, help_text='Optional feedback on how to improve')),
                (
                    'learning_goal',
                    models.CharField(blank=True, help_text='What the user was trying to learn', max_length=255),
                ),
                (
                    'prior_knowledge',
                    models.CharField(blank=True, help_text='User-stated prior knowledge level', max_length=50),
                ),
                (
                    'topic_slug',
                    models.CharField(
                        blank=True, db_index=True, help_text='Topic slug for grouping feedback', max_length=100
                    ),
                ),
                (
                    'concept_slug',
                    models.CharField(
                        blank=True, db_index=True, help_text='Concept slug for grouping feedback', max_length=100
                    ),
                ),
                (
                    'difficulty_perception',
                    models.CharField(
                        blank=True,
                        choices=[('too_easy', 'Too Easy'), ('just_right', 'Just Right'), ('too_hard', 'Too Hard')],
                        help_text='How the user perceived the difficulty',
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    'time_spent_seconds',
                    models.IntegerField(blank=True, help_text='Approximate time spent on the content', null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'concept',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='helpfulness_feedback',
                        to='learning_paths.concept',
                    ),
                ),
                (
                    'micro_lesson',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='helpfulness_feedback',
                        to='learning_paths.microlesson',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='content_helpfulness_feedback',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['content_type', 'helpfulness'], name='learning_pa_content_b49cc0_idx'),
                    models.Index(fields=['micro_lesson', 'helpfulness'], name='learning_pa_micro_l_75aa3d_idx'),
                    models.Index(fields=['topic_slug', 'helpfulness'], name='learning_pa_topic_s_921a1b_idx'),
                ],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='ConversationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'session_id',
                    models.CharField(db_index=True, help_text='Conversation session ID for grouping', max_length=255),
                ),
                (
                    'message_id',
                    models.CharField(db_index=True, help_text='Specific message this feedback is for', max_length=255),
                ),
                (
                    'feedback',
                    models.CharField(
                        choices=[
                            ('helpful', 'Helpful'),
                            ('not_helpful', 'Not Helpful'),
                            ('confusing', 'Confusing'),
                            ('too_basic', 'Too Basic'),
                            ('too_advanced', 'Too Advanced'),
                            ('incorrect', 'Incorrect Information'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'context_type',
                    models.CharField(
                        choices=[
                            ('explanation', 'Concept Explanation'),
                            ('recommendation', 'Content Recommendation'),
                            ('answer', 'Question Answer'),
                            ('proactive', 'Proactive Suggestion'),
                            ('game', 'Game/Quiz'),
                            ('general', 'General Response'),
                        ],
                        default='general',
                        max_length=20,
                    ),
                ),
                (
                    'topic_slug',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Topic being discussed when feedback was given',
                        max_length=100,
                    ),
                ),
                ('comment', models.TextField(blank=True, help_text='Optional user comment explaining the feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'concept',
                    models.ForeignKey(
                        blank=True,
                        help_text='Concept being explained when feedback was given',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='conversation_feedback',
                        to='learning_paths.concept',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='conversation_feedback',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'feedback'], name='learning_pa_user_id_54d6f1_idx'),
                    models.Index(fields=['topic_slug', 'feedback'], name='learning_pa_topic_s_c44547_idx'),
                    models.Index(fields=['context_type', 'feedback'], name='learning_pa_context_caca28_idx'),
                    models.Index(fields=['session_id', 'created_at'], name='learning_pa_session_9ae5c6_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='GoalCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'goal_description',
                    models.CharField(help_text="User's stated learning goal at check-in time", max_length=500),
                ),
                (
                    'progress',
                    models.CharField(
                        choices=[
                            ('on_track', 'On Track'),
                            ('ahead', 'Ahead of Schedule'),
                            ('behind', 'Behind Schedule'),
                            ('stuck', 'Stuck'),
                            ('goal_changed', 'Goal Has Changed'),
                            ('goal_achieved', 'Goal Achieved'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'satisfaction',
                    models.CharField(
                        choices=[
                            ('very_satisfied', 'Very Satisfied'),
                            ('satisfied', 'Satisfied'),
                            ('neutral', 'Neutral'),
                            ('unsatisfied', 'Unsatisfied'),
                            ('very_unsatisfied', 'Very Unsatisfied'),
                        ],
                        max_length=20,
                    ),
                ),
                ('whats_working', models.TextField(blank=True, help_text='What aspects of learning are working well')),
                ('whats_not_working', models.TextField(blank=True, help_text='What aspects need improvement')),
                ('blockers', models.TextField(blank=True, help_text='Any blockers preventing progress')),
                (
                    'new_goal',
                    models.CharField(blank=True, help_text='New goal if user changed their goal', max_length=500),
                ),
                ('xp_at_checkin', models.IntegerField(default=0)),
                ('concepts_mastered_at_checkin', models.IntegerField(default=0)),
                ('streak_days_at_checkin', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'learning_path',
                    models.ForeignKey(
                        blank=True,
                        help_text='Specific learning path being checked (optional)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='check_ins',
                        to='learning_paths.userlearningpath',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='goal_check_ins',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'created_at'], name='learning_pa_user_id_8b6adf_idx'),
                    models.Index(fields=['progress', 'satisfaction'], name='learning_pa_progres_d96b8c_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ProactiveOfferResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                (
                    'intervention_type',
                    models.CharField(
                        choices=[
                            ('simplify_explanation', 'Simplify Explanation'),
                            ('suggest_prerequisite', 'Suggest Prerequisite'),
                            ('offer_example', 'Offer Example'),
                            ('offer_break', 'Offer Break'),
                            ('offer_help', 'General Help Offer'),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    'response',
                    models.CharField(
                        choices=[
                            ('accepted', 'Accepted'),
                            ('declined', 'Declined'),
                            ('ignored', 'Ignored'),
                            ('helpful_after', 'Accepted and Found Helpful'),
                            ('not_helpful_after', 'Accepted but Not Helpful'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'struggle_confidence',
                    models.FloatField(help_text='Confidence score of the struggle detection (0.0-1.0)'),
                ),
                ('struggle_type', models.CharField(blank=True, help_text='Type of struggle detected', max_length=50)),
                ('topic_slug', models.CharField(blank=True, db_index=True, max_length=100)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                (
                    'responded_at',
                    models.DateTimeField(blank=True, help_text='When the user responded (null if ignored)', null=True),
                ),
                (
                    'concept',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='proactive_offer_responses',
                        to='learning_paths.concept',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='proactive_offer_responses',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-offered_at'],
                'indexes': [
                    models.Index(fields=['user', 'intervention_type'], name='learning_pa_user_id_1dd8c4_idx'),
                    models.Index(fields=['intervention_type', 'response'], name='learning_pa_interve_030aa3_idx'),
                    models.Index(fields=['struggle_confidence'], name='learning_pa_struggl_3e0078_idx'),
                ],
            },
        ),
    ]
