# Generated by Django 5.1.15 on 2025-12-23 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning_paths', '0013_saved_learning_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'lesson_order',
                    models.PositiveIntegerField(help_text='Order number of the curriculum item this image belongs to'),
                ),
                (
                    'content_hash',
                    models.CharField(
                        db_index=True, help_text='Hash of lesson content for cache invalidation', max_length=64
                    ),
                ),
                ('image_url', models.URLField(help_text='URL to the generated image in storage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'saved_path',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lesson_images',
                        to='learning_paths.savedlearningpath',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Lesson Image',
                'verbose_name_plural': 'Lesson Images',
                'indexes': [models.Index(fields=['saved_path', 'lesson_order'], name='learning_pa_saved_p_fb0f02_idx')],
                'unique_together': {('saved_path', 'lesson_order')},
            },
        ),
    ]
