# Generated by Django 5.1.15 on 2025-12-23 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0068_add_project_dismissal'),
        ('learning_paths', '0014_add_lesson_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlearningmetadata',
            name='is_lesson',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Whether this project is curated educational content for learning paths',
            ),
        ),
        migrations.AddField(
            model_name='projectlearningmetadata',
            name='negative_ratings',
            field=models.PositiveIntegerField(default=0, help_text='Number of not helpful ratings from users'),
        ),
        migrations.AddField(
            model_name='projectlearningmetadata',
            name='positive_ratings',
            field=models.PositiveIntegerField(default=0, help_text='Number of helpful ratings from users'),
        ),
        migrations.CreateModel(
            name='LessonRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'rating',
                    models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], max_length=20),
                ),
                ('feedback', models.TextField(blank=True, help_text='Optional written feedback from user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='lesson_ratings', to='core.project'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lesson_ratings',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Lesson Rating',
                'verbose_name_plural': 'Lesson Ratings',
                'indexes': [
                    models.Index(fields=['project', 'rating'], name='learning_pa_project_1beebc_idx'),
                    models.Index(fields=['created_at'], name='learning_pa_created_469ca5_idx'),
                ],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
