# Generated by Django 5.1.15 on 2025-12-23 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning_paths', '0015_add_is_lesson_and_ratings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlearningpath',
            name='is_published',
            field=models.BooleanField(
                db_index=True, default=True, help_text='Whether this path is published to the explore feed'
            ),
        ),
        migrations.AddField(
            model_name='savedlearningpath',
            name='published_at',
            field=models.DateTimeField(
                blank=True, db_index=True, help_text='When this path was published to explore feed', null=True
            ),
        ),
        migrations.AddIndex(
            model_name='savedlearningpath',
            index=models.Index(
                fields=['is_published', 'is_archived', '-published_at'], name='learning_pa_is_publ_7c1010_idx'
            ),
        ),
    ]
