# Generated by Django 5.1.15 on 2025-12-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning_paths', '0016_add_publish_fields_to_savedlearningpath'),
        ('tools', '0003_add_weaviate_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlearningpath',
            name='tools',
            field=models.ManyToManyField(
                blank=True,
                help_text='Tools featured or taught in this learning path',
                related_name='learning_paths',
                to='tools.tool',
            ),
        ),
    ]
