# Generated by Django 5.1.15 on 2025-12-24 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning_paths', '0017_add_tools_to_savedlearningpath'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'lesson_order',
                    models.PositiveIntegerField(
                        help_text='Order number of the lesson in the learning path (1-indexed)'
                    ),
                ),
                (
                    'is_completed',
                    models.BooleanField(
                        db_index=True, default=False, help_text='Whether the user has completed this lesson'
                    ),
                ),
                (
                    'completed_at',
                    models.DateTimeField(blank=True, help_text='When the lesson was completed', null=True),
                ),
                (
                    'exercise_completed',
                    models.BooleanField(default=False, help_text='Whether the exercise/practice was completed'),
                ),
                ('exercise_completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz_completed', models.BooleanField(default=False, help_text='Whether the quiz was completed')),
                ('quiz_completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'quiz_score',
                    models.FloatField(blank=True, help_text='Quiz score as percentage (0.0-1.0)', null=True),
                ),
                (
                    'started_at',
                    models.DateTimeField(auto_now_add=True, help_text='When the user first viewed this lesson'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'saved_path',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lesson_progress',
                        to='learning_paths.savedlearningpath',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lesson_progress',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress',
                'ordering': ['saved_path', 'lesson_order'],
                'indexes': [
                    models.Index(fields=['user', 'saved_path'], name='learning_pa_user_id_7e9b3f_idx'),
                    models.Index(fields=['saved_path', 'is_completed'], name='learning_pa_saved_p_dbabf2_idx'),
                    models.Index(fields=['user', 'is_completed'], name='learning_pa_user_id_8f60dc_idx'),
                ],
                'unique_together': {('user', 'saved_path', 'lesson_order')},
            },
        ),
    ]
