# Generated by Django 5.1.15 on 2025-12-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning_paths', '0018_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='sections_organization',
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='User-customized section organization for learning path topics',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='savedlearningpath',
            name='sections_organization',
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='User-customized section organization for learning path topics',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='allow_proactive_suggestions',
            field=models.BooleanField(default=True, help_text='Allow Ava to proactively suggest learning'),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='last_proactive_nudge',
            field=models.DateTimeField(blank=True, help_text='When Ava last sent a proactive nudge', null=True),
        ),
    ]
