# Generated by Django 5.1.15 on 2025-12-07 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0039_remove_battlematchmakingqueue_challenge_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(help_text='The prompt created by the user')),
                (
                    'submission_type',
                    models.CharField(
                        choices=[('text', 'Text Generation'), ('image', 'Image Generation')],
                        default='image',
                        help_text='Type of submission (text or image prompt)',
                        max_length=20,
                    ),
                ),
                (
                    'generated_output_url',
                    models.URLField(blank=True, help_text='URL to the generated output (if applicable)', null=True),
                ),
                (
                    'generated_output_text',
                    models.TextField(blank=True, help_text='Generated text output (if text submission)'),
                ),
                ('score', models.FloatField(blank=True, help_text='AI-evaluated score (0-100)', null=True)),
                (
                    'criteria_scores',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Breakdown by judging criteria: {"creativity": 85, "relevance": 90}',
                    ),
                ),
                ('evaluation_feedback', models.TextField(blank=True, help_text='AI feedback on the prompt quality')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'evaluated_at',
                    models.DateTimeField(blank=True, help_text='When the submission was evaluated', null=True),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User who made this submission',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='battle_submissions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'core_battlesubmission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'key',
                    models.CharField(
                        help_text="Unique identifier (e.g., 'dreamscape', 'movie_poster')", max_length=50, unique=True
                    ),
                ),
                ('name', models.CharField(help_text='Display name for the challenge type', max_length=100)),
                ('description', models.TextField(help_text='Description of what this challenge type is about')),
                (
                    'templates',
                    models.JSONField(
                        default=list, help_text='List of challenge templates with {variable} placeholders'
                    ),
                ),
                (
                    'variables',
                    models.JSONField(
                        default=dict,
                        help_text='Variable options for template substitution: {"style": ["surreal", "cosmic"]}',
                    ),
                ),
                (
                    'judging_criteria',
                    models.JSONField(
                        default=list,
                        help_text='List of criteria: [{"name": "creativity", "weight": 30, "description": "..."}]',
                    ),
                ),
                (
                    'ai_judge_prompt',
                    models.TextField(blank=True, help_text='Custom AI judging prompt (uses default if empty)'),
                ),
                (
                    'default_duration_minutes',
                    models.IntegerField(default=3, help_text='Default battle duration in minutes'),
                ),
                (
                    'min_submission_length',
                    models.IntegerField(default=10, help_text='Minimum prompt length in characters'),
                ),
                (
                    'max_submission_length',
                    models.IntegerField(default=2000, help_text='Maximum prompt length in characters'),
                ),
                ('winner_points', models.IntegerField(default=50, help_text='Points awarded to winner')),
                ('participation_points', models.IntegerField(default=10, help_text='Points for participation')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this challenge type is available')),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')],
                        default='medium',
                        max_length=20,
                    ),
                ),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        help_text='Category this challenge type belongs to',
                        limit_choices_to={'taxonomy_type': 'category'},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='challenge_types',
                        to='core.taxonomy',
                    ),
                ),
            ],
            options={
                'db_table': 'core_challengetype',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BattleMatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'match_type',
                    models.CharField(
                        choices=[('random', 'Random Match'), ('ai', 'AI Opponent (Pip)')],
                        default='random',
                        help_text='Type of match requested',
                        max_length=20,
                    ),
                ),
                ('queued_at', models.DateTimeField(auto_now_add=True, help_text='When user joined queue')),
                ('expires_at', models.DateTimeField(help_text='When queue entry expires')),
                (
                    'user',
                    models.OneToOneField(
                        help_text='User waiting in queue',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='matchmaking_queue',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'challenge_type',
                    models.ForeignKey(
                        blank=True,
                        help_text='Preferred challenge type (null = any)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='battles.challengetype',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Battle matchmaking queue entries',
                'db_table': 'core_battlematchmakingqueue',
            },
        ),
        migrations.CreateModel(
            name='PromptBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_text', models.TextField(help_text='The AI-generated challenge prompt for this battle')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('active', 'Active'),
                            ('completed', 'Completed'),
                            ('expired', 'Expired'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='pending',
                        help_text='Current status of the battle',
                        max_length=20,
                    ),
                ),
                (
                    'battle_type',
                    models.CharField(
                        choices=[
                            ('text_prompt', 'Text Prompt Generation'),
                            ('image_prompt', 'Image Generation Prompt'),
                            ('mixed', 'Mixed Challenge'),
                        ],
                        default='text_prompt',
                        help_text='Type of prompt battle',
                        max_length=20,
                    ),
                ),
                (
                    'duration_minutes',
                    models.IntegerField(default=10, help_text='Duration of battle in minutes (default 10)'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'started_at',
                    models.DateTimeField(
                        blank=True, help_text='When the battle officially started (after acceptance)', null=True
                    ),
                ),
                (
                    'expires_at',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text='When the battle expires (started_at + duration)',
                        null=True,
                    ),
                ),
                (
                    'completed_at',
                    models.DateTimeField(blank=True, help_text='When the battle was completed', null=True),
                ),
                (
                    'phase',
                    models.CharField(
                        choices=[
                            ('waiting', 'Waiting for Opponent'),
                            ('countdown', 'Countdown'),
                            ('active', 'Active'),
                            ('generating', 'AI Generating'),
                            ('judging', 'AI Judging'),
                            ('reveal', 'Results Reveal'),
                            ('complete', 'Complete'),
                        ],
                        db_index=True,
                        default='waiting',
                        help_text='Current phase of the real-time battle',
                        max_length=20,
                    ),
                ),
                (
                    'challenger_connected',
                    models.BooleanField(default=False, help_text='Is challenger connected via WebSocket'),
                ),
                (
                    'opponent_connected',
                    models.BooleanField(default=False, help_text='Is opponent connected via WebSocket'),
                ),
                (
                    'match_source',
                    models.CharField(
                        choices=[
                            ('direct', 'Direct Challenge'),
                            ('random', 'Random Match'),
                            ('ai_opponent', 'AI Opponent'),
                            ('invitation', 'SMS Invitation'),
                        ],
                        default='direct',
                        help_text='How this battle match was created',
                        max_length=20,
                    ),
                ),
                (
                    'challenge_type',
                    models.ForeignKey(
                        blank=True,
                        help_text='The challenge type configuration used for this battle',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='battles',
                        to='battles.challengetype',
                    ),
                ),
                (
                    'challenger',
                    models.ForeignKey(
                        help_text='User who initiated the battle',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='battles_initiated',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'opponent',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who was challenged (null for SMS invitations until accepted)',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='battles_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'winner',
                    models.ForeignKey(
                        blank=True,
                        help_text='Winner of the battle (determined by AI scoring)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='battles_won',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'core_promptbattle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'vote_source',
                    models.CharField(
                        choices=[('ai', 'AI Judge'), ('community', 'Community Vote'), ('panel', 'Judge Panel')],
                        default='ai',
                        help_text='Source of this vote',
                        max_length=20,
                    ),
                ),
                ('score', models.FloatField(help_text='Score given (0-100)')),
                (
                    'criteria_scores',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Per-criteria breakdown: {"creativity": 85, "relevance": 90}',
                    ),
                ),
                ('feedback', models.TextField(blank=True, help_text='Feedback explaining the vote')),
                ('weight', models.FloatField(default=1.0, help_text='Vote weight for aggregation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'submission',
                    models.ForeignKey(
                        help_text='The submission being voted on',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='votes',
                        to='battles.battlesubmission',
                    ),
                ),
                (
                    'voter',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who voted (null for AI judge)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='battle_votes_cast',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'battle',
                    models.ForeignKey(
                        help_text='The battle being voted on',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='votes',
                        to='battles.promptbattle',
                    ),
                ),
            ],
            options={
                'db_table': 'core_battlevote',
            },
        ),
        migrations.AddField(
            model_name='battlesubmission',
            name='battle',
            field=models.ForeignKey(
                help_text='The battle this submission belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='submissions',
                to='battles.promptbattle',
            ),
        ),
        migrations.CreateModel(
            name='BattleInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'recipient_phone',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Phone number for SMS invitations (E.164 format)',
                        max_length=20,
                    ),
                ),
                (
                    'recipient_name',
                    models.CharField(
                        blank=True, help_text='Name of SMS recipient (for display purposes)', max_length=100
                    ),
                ),
                (
                    'invitation_type',
                    models.CharField(
                        choices=[('platform', 'Platform User'), ('sms', 'SMS'), ('random', 'Random Match')],
                        db_index=True,
                        default='platform',
                        max_length=20,
                    ),
                ),
                (
                    'invite_token',
                    models.CharField(
                        blank=True,
                        help_text='Unique token for SMS invitation links',
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ('message', models.TextField(blank=True, help_text='Optional message from the challenger')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('accepted', 'Accepted'),
                            ('declined', 'Declined'),
                            ('expired', 'Expired'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'responded_at',
                    models.DateTimeField(blank=True, help_text='When the invitation was responded to', null=True),
                ),
                (
                    'expires_at',
                    models.DateTimeField(
                        db_index=True, help_text='When the invitation expires (24 hours from creation)'
                    ),
                ),
                ('sms_sent_at', models.DateTimeField(blank=True, help_text='When SMS was sent', null=True)),
                ('sms_log_id', models.IntegerField(blank=True, help_text='ID of SMSLog record', null=True)),
                (
                    'recipient',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who received the invitation (for platform invitations)',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='battle_invitations_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'sender',
                    models.ForeignKey(
                        help_text='User who sent the invitation',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='battle_invitations_sent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'battle',
                    models.OneToOneField(
                        help_text='The battle associated with this invitation',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invitation',
                        to='battles.promptbattle',
                    ),
                ),
            ],
            options={
                'db_table': 'core_battleinvitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='challengetype',
            index=models.Index(fields=['is_active', 'order'], name='core_challe_is_acti_7e6d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='challengetype',
            index=models.Index(fields=['category', 'is_active'], name='core_challe_categor_928afc_idx'),
        ),
        migrations.AddIndex(
            model_name='battlematchmakingqueue',
            index=models.Index(fields=['match_type', 'queued_at'], name='core_battle_match_t_ef4726_idx'),
        ),
        migrations.AddIndex(
            model_name='battlematchmakingqueue',
            index=models.Index(fields=['expires_at'], name='core_battle_expires_deb467_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['challenger', '-created_at'], name='core_prompt_challen_803316_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['opponent', '-created_at'], name='core_prompt_opponen_d60241_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['status', '-created_at'], name='core_prompt_status_e060b7_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['expires_at'], name='core_prompt_expires_faab10_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['phase', 'status'], name='core_prompt_phase_0b61ac_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['phase', '-created_at'], name='core_prompt_phase_6ae267_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['winner', '-completed_at'], name='core_prompt_winner__069661_idx'),
        ),
        migrations.AddIndex(
            model_name='battlevote',
            index=models.Index(fields=['battle', 'vote_source'], name='core_battle_battle__290016_idx'),
        ),
        migrations.AddIndex(
            model_name='battlevote',
            index=models.Index(fields=['submission', '-created_at'], name='core_battle_submiss_d01f9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='battlevote',
            unique_together={('submission', 'voter', 'vote_source')},
        ),
        migrations.AddIndex(
            model_name='battlesubmission',
            index=models.Index(fields=['battle', 'user'], name='core_battle_battle__9c153a_idx'),
        ),
        migrations.AddIndex(
            model_name='battlesubmission',
            index=models.Index(fields=['user', '-submitted_at'], name='core_battle_user_id_ad63b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='battlesubmission',
            unique_together={('battle', 'user')},
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['recipient', 'status', '-created_at'], name='core_battle_recipie_b6c75a_idx'),
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['sender', '-created_at'], name='core_battle_sender__68f92f_idx'),
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['expires_at'], name='core_battle_expires_8e6706_idx'),
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['recipient_phone', 'status'], name='core_battle_recipie_019643_idx'),
        ),
        migrations.AddIndex(
            model_name='battleinvitation',
            index=models.Index(fields=['invitation_type', 'status'], name='core_battle_invitat_2b60a1_idx'),
        ),
    ]
