# Generated by Django 5.1.15 on 2025-12-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleinvitation',
            name='invitation_type',
            field=models.CharField(
                choices=[
                    ('platform', 'Platform User'),
                    ('sms', 'SMS'),
                    ('random', 'Random Match'),
                    ('link', 'Shareable Link'),
                ],
                db_index=True,
                default='platform',
                max_length=20,
            ),
        ),
    ]
