# Generated by Django 5.1.15 on 2025-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0002_alter_battleinvitation_invitation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptbattle',
            name='judging_retry_count',
            field=models.PositiveSmallIntegerField(
                default=0, help_text='Number of times judging has been retried (force-complete after 3)'
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='phase_changed_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text='When the battle phase last changed (used for stuck battle detection)',
                null=True,
            ),
        ),
    ]
