# Generated by Django 5.1.15 on 2025-12-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0003_promptbattle_judging_retry_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptbattle',
            name='og_image_url',
            field=models.URLField(
                blank=True,
                help_text='URL to the pre-generated OG image for social media sharing',
                max_length=500,
                null=True,
            ),
        ),
    ]
