# Generated by Django 5.1.15 on 2025-12-12 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0004_add_og_image_url_to_promptbattle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promptbattle',
            name='async_deadline',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text=('Deadline for opponent to respond in async mode (3 days from invite accept)'),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='battle_mode',
            field=models.CharField(
                choices=[
                    ('sync', 'Synchronous (Real-time)'),
                    ('async', 'Asynchronous (Turn-based)'),
                    ('hybrid', 'Hybrid (Auto-detect)'),
                ],
                default='hybrid',
                help_text=('Battle mode: sync (real-time), async (turn-based), or hybrid (auto-detect)'),
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='current_turn_expires_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text='When the current 3-minute turn expires',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='current_turn_started_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the current turn started (for 3-min timer)',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='current_turn_user',
            field=models.ForeignKey(
                blank=True,
                help_text='User whose turn it is in async mode',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='battles_current_turn',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='deadline_extended_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who last extended the deadline',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='battles_extended',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='extension_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of deadline extensions used (max 2)'),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='last_reminder_sent_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the last reminder was sent for async battle',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='reminder_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of reminders sent for this battle'),
        ),
        migrations.AlterField(
            model_name='promptbattle',
            name='phase',
            field=models.CharField(
                choices=[
                    ('waiting', 'Waiting for Opponent'),
                    ('countdown', 'Countdown'),
                    ('active', 'Active'),
                    ('generating', 'AI Generating'),
                    ('judging', 'AI Judging'),
                    ('reveal', 'Results Reveal'),
                    ('complete', 'Complete'),
                    ('challenger_turn', "Challenger's Turn"),
                    ('opponent_turn', "Opponent's Turn"),
                ],
                db_index=True,
                default='waiting',
                help_text='Current phase of the real-time battle',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['battle_mode', 'status'], name='core_prompt_battle__37b76f_idx'),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(
                fields=['current_turn_user', 'phase'],
                name='core_prompt_current_158ccc_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['async_deadline'], name='core_prompt_async_d_1c2de9_idx'),
        ),
    ]
