# Generated by Django 5.1.15 on 2025-12-12 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0005_add_async_battle_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='promptbattle',
            index=models.Index(fields=['current_turn_expires_at', 'status'], name='core_prompt_current_dcb4b5_idx'),
        ),
    ]
