# Generated by Django 5.1.15 on 2025-12-13 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0006_add_turn_expires_status_index'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptbattle',
            name='tool',
            field=models.ForeignKey(
                blank=True,
                help_text='The AI tool used for this battle (e.g., Nano Banana)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='battles',
                to='tools.tool',
            ),
        ),
    ]
