# Generated by Django 5.1.15 on 2025-12-13 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0007_add_tool_to_battle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promptbattle',
            name='hidden_by',
            field=models.ManyToManyField(
                blank=True,
                help_text='Users who have hidden this battle from their view',
                related_name='hidden_battles',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
