# Generated by Django 5.1.15 on 2025-12-16 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0008_add_hidden_by_field'),
        ('core', '0044_add_decay_factor_to_usertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptbattle',
            name='challenge_type',
            field=models.ForeignKey(
                blank=True,
                help_text='The challenge type configuration used for this battle (legacy)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='battles',
                to='battles.challengetype',
            ),
        ),
        migrations.CreateModel(
            name='PromptChallengePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(help_text='The full prompt text shown to battle participants')),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')],
                        default='medium',
                        max_length=20,
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, help_text='Whether this prompt is available for selection'),
                ),
                (
                    'weight',
                    models.FloatField(default=1.0, help_text='Selection weight (higher = more likely to be selected)'),
                ),
                (
                    'times_used',
                    models.IntegerField(default=0, help_text='How many times this prompt has been used in battles'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        help_text='Category for organization (e.g., Dreamscape, Movie Poster)',
                        limit_choices_to={'taxonomy_type': 'category'},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='prompt_challenges',
                        to='core.taxonomy',
                    ),
                ),
            ],
            options={
                'db_table': 'core_promptchallengeprompt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='prompt',
            field=models.ForeignKey(
                blank=True,
                help_text='The curated prompt used for this battle',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='battles',
                to='battles.promptchallengeprompt',
            ),
        ),
        migrations.AddIndex(
            model_name='promptchallengeprompt',
            index=models.Index(fields=['is_active', 'category'], name='core_prompt_is_acti_1469d2_idx'),
        ),
        migrations.AddIndex(
            model_name='promptchallengeprompt',
            index=models.Index(fields=['is_active', 'difficulty'], name='core_prompt_is_acti_d4c4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='promptchallengeprompt',
            index=models.Index(fields=['times_used'], name='core_prompt_times_u_58924c_idx'),
        ),
    ]
