# Generated by Django 5.1.15 on 2025-12-16 22:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0009_alter_promptbattle_challenge_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlematchmakingqueue',
            name='challenge_type',
        ),
        migrations.RemoveField(
            model_name='promptbattle',
            name='challenge_type',
        ),
        migrations.DeleteModel(
            name='ChallengeType',
        ),
    ]
