# Generated by Django 5.1.15 on 2026-01-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0010_remove_challenge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptbattle',
            name='instagram_post_id',
            field=models.CharField(
                blank=True, help_text='Instagram post ID if battle was shared to Instagram', max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='instagram_post_url',
            field=models.URLField(blank=True, help_text='URL to the Instagram post', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promptbattle',
            name='instagram_posted_at',
            field=models.DateTimeField(blank=True, help_text='When the battle was posted to Instagram', null=True),
        ),
    ]
